<?php
$t = array();
$t[1] = 'Vy, kteř&iacute; věř&iacute;te! Nesnažte se předej&iacute;t Boha a posla jeho! Buďte bohabojn&iacute;, vždyť Bůh věru je sly&scaron;&iacute;c&iacute;, v&scaron;evědouc&iacute;!';
$t[2] = 'Vy, kteř&iacute; věř&iacute;te! Nezvedejte hlas svůj nad hlas prorokův a neobracejte se k němu s řeč&iacute; hlučnou, tak jak to děl&aacute;te mezi sebou, aby se skutky va&scaron;e nestaly marn&yacute;mi, aniž o tom budete m&iacute;t tu&scaron;en&iacute;.';
$t[3] = 'Věru ti, kdož snižuj&iacute; hlasy sv&eacute; před poslem Bož&iacute;m jsou ti, jejichž srdce Bůh podrobil zkou&scaron;ce bohabojnosti a těm n&aacute;lež&iacute; odměna nesm&iacute;rn&aacute; a odpu&scaron;těn&iacute;.';
$t[4] = 'Av&scaron;ak vět&scaron;ina z těch, kdož tě hlasitě vyvol&aacute;vaj&iacute; z komnat tv&yacute;ch, jsou lid&eacute; nerozumn&iacute;.';
$t[5] = 'Kdyby trpělivě vyčkali, dokud k nim nevyjde&scaron;, bylo by to pro ně lep&scaron;&iacute;; a Bůh je odpou&scaron;těj&iacute;c&iacute;, slitovn&yacute;.';
$t[6] = 'Vy, kteř&iacute; věř&iacute;te! Přijde-li k v&aacute;m hanebn&iacute;k s nějakou zvěst&iacute;, snažte se ji objasnit tak, abyste z nevědomosti sv&eacute; nepo&scaron;kodili lidi a abyste nemusili litovat toho, co jste učinili.';
$t[7] = 'Vězte, že kdyby posel Bož&iacute;, kter&yacute; mezi v&aacute;mi dl&iacute;, v&aacute;s uposlechl ve vět&scaron;ině z&aacute;ležitost&iacute;, věru byste &scaron;kodu utrpěli! Av&scaron;ak Bůh způsobil, že milujete v&iacute;ru, a učinil ji kr&aacute;snou v srdc&iacute;ch va&scaron;ich, zat&iacute;mco v&aacute;m zo&scaron;klivil nevěrectv&iacute;, hanebnosti a neposlu&scaron;nost. A to jsou ti, kdož ř&iacute;d&iacute; se cestou spr&aacute;vnou';
$t[8] = 'd&iacute;ky laskavosti a dobrodin&iacute; Bož&iacute;mu. A Bůh je v&scaron;evědouc&iacute;, moudr&yacute;.';
$t[9] = 'Bojuj&iacute;-li mezi sebou dvě skupiny věř&iacute;c&iacute;ch, usmiřte je! A čin&iacute;-li jedna skupina z těch dvou bezpr&aacute;v&iacute; druh&eacute;, bojujte proti těm, kdo čin&iacute; bezpr&aacute;v&iacute;, dokud se před rozkazem Bož&iacute;m nesklon&iacute;! A když se sklon&iacute;, usmiřte obě strany spravedlivě a buďte nestrann&iacute;, neboť Bůh věru miluje ty, kdož jsou nestrann&iacute;!';
$t[10] = 'Věř&iacute;c&iacute; jsou si přece bratry; usmiřujte tedy oba bratry sv&eacute; a buďte bohabojn&iacute; - snad dostane se v&aacute;m smilov&aacute;n&iacute;!';
$t[11] = 'Vy, kteř&iacute; věř&iacute;te! Nechť neposm&iacute;vaj&iacute; se jedni lid&eacute; druh&yacute;m, možn&aacute; že tito jsou lep&scaron;&iacute; než oni! A nechť jedny ženy se neposm&iacute;vaj&iacute; druh&yacute;m, možn&aacute; že tyto jsou lep&scaron;&iacute; než ony! Neur&aacute;žejte se vz&aacute;jemně a nenaz&yacute;vejte se přezd&iacute;vkami! A jak hnusn&yacute; je n&aacute;zev &quot;hanebn&iacute;k&quot; pot&eacute;, co byla přijata v&iacute;ra! A ti, kdož se nebudou k&aacute;t, jsou věru nespravedliv&iacute;!';
$t[12] = 'Vy, kteř&iacute; věř&iacute;te! Střezte se př&iacute;li&scaron;n&eacute;ho podezř&iacute;v&aacute;n&iacute; druh&yacute;ch, vždyť někter&aacute; podezřen&iacute; jsou hř&iacute;chem! Nevyzv&iacute;dejte a nepomlouvejte se vz&aacute;jemně! Což si někdo z v&aacute;s přeje j&iacute;st maso bratra sv&eacute;ho mrtv&eacute;ho - vždyť by v&aacute;m to bylo odporn&eacute;! Buďte bohabojn&iacute;, neboť Bůh věru je blahovoln&yacute; ke kaj&iacute;cn&iacute;ku a slitovn&yacute;.';
$t[13] = 'Lid&eacute;, věru jsme v&aacute;s stvořili z muže a ženy a učinili jsme z v&aacute;s n&aacute;rody a kmeny, abyste se vz&aacute;jemně poznali. Av&scaron;ak nejvzne&scaron;eněj&scaron;&iacute; z v&aacute;s před Bohem je ten, kdo je nejbohabojněj&scaron;&iacute; - a Bůh je v&scaron;evědouc&iacute; a dobře zpraven&yacute;.';
$t[14] = 'A ř&iacute;kaj&iacute; kočovn&iacute; Arabov&eacute;: &quot;Uvěřili jsme!&quot; Rci: &quot;Neuvěřili jste! Sp&iacute;&scaron;e řekněte:, Přistoupili jsme k isl&aacute;mu!?, neboť v&iacute;ra je&scaron;tě neve&scaron;la do srdc&iacute; va&scaron;ich. Budete-li poslouchat Boha a posla Jeho, On věru nedopust&iacute;, aby ztratilo se něco ze skutků va&scaron;ich, vždyť Bůh je odpou&scaron;těj&iacute;c&iacute;, slitovn&yacute;!&quot;';
$t[15] = 'Věř&iacute;c&iacute;mi jsou pouze ti, kdož uvěřili v Boha a posla Jeho a pot&eacute; nepodlehli pochybnostem, n&yacute;brž bojovali majetky i osobami sv&yacute;mi na cestě Bož&iacute; - a tito jsou věru upř&iacute;mn&iacute;.';
$t[16] = 'Rci: &quot;Chcete snad poučovat Boha o n&aacute;boženstv&iacute; sv&eacute;m, když Bůh dobře zn&aacute; v&scaron;e, co na nebes&iacute;ch je i na zemi? Bůh o každ&eacute; věci je v&scaron;evědouc&iacute;.&quot;';
$t[17] = 'A domn&iacute;vaj&iacute; se, že tobě udělali milost, když přistoupili k isl&aacute;mu. Rci: &quot;Netvrďte mi, že va&scaron;e přistoupen&iacute; k isl&aacute;mu je nějakou milost&iacute; vůči mně! Naopak Bůh v&aacute;m učinil milost t&iacute;m, že v&aacute;s přivedl k v&iacute;ře - jste-li pravdomluvn&iacute;!&quot;';
$t[18] = 'A Bůh vskutku zn&aacute; nepoznateln&eacute; na nebes&iacute;ch i na zemi a Bůh v&scaron;e, co děl&aacute;te, jasně zř&iacute;.';
?>