<?php
$t = array();
$t[1] = 'Bůh již sly&scaron;el řeč on&eacute;, kter&aacute; se s tebou h&aacute;dala ohledně manžela sv&eacute;ho a stěžovala si u Boha. Bůh sly&scaron;el v&aacute;&scaron; rozhovor, vždyť Bůh je věru sly&scaron;&iacute;c&iacute;, jasnozřiv&yacute;.';
$t[2] = 'Ti z v&aacute;s, kteř&iacute; naz&yacute;vaj&iacute; manželky sv&eacute; z&aacute;dami sv&yacute;ch matek, věd&iacute;, že ony nejsou jejich matkami; matkami jejich jsou jedině ty, kter&eacute; je porodily. A ř&iacute;kaj&iacute; t&iacute;m věru slova zavržen&iacute;hodn&aacute; a fale&scaron;n&aacute;. A Bůh zajist&eacute; je prom&iacute;jej&iacute;c&iacute;, odpou&scaron;těj&iacute;c&iacute;!';
$t[3] = 'Ti, kdož ř&iacute;kaj&iacute; žen&aacute;m sv&yacute;m &quot;Jsi pro mne jak z&aacute;da m&eacute; matky&quot; a potom chtěj&iacute; odvolat to, co řekli, mohou se vykoupit propu&scaron;těn&iacute;m otroka, dř&iacute;ve než se opět vz&aacute;jemně dotknou. A k tomu jste napom&iacute;n&aacute;ni a Bůh je dobře zpraven o v&scaron;em, co děl&aacute;te.';
$t[4] = 'A nechť se ten, kdo nenalezne k tomu možnost, post&iacute; dva měs&iacute;ce po sobě n&aacute;sleduj&iacute;c&iacute;, dř&iacute;ve než se opět vz&aacute;jemně dotknou. A nechť ten, kdo nebude toho schopen, nakrm&iacute; &scaron;edes&aacute;t chud&aacute;ků. A toto je stanoveno, abyste věřili v Boha a posla Jeho, a toto jsou omezen&iacute; Bož&iacute;. Nevěř&iacute;c&iacute;m se pak dostane trestu bolestn&eacute;ho!';
$t[5] = 'Ti, kdož se protiv&iacute; Bohu a poslu Jeho, budou povaleni, tak jako byli povaleni ti, kdož byli před nimi. A nyn&iacute; jsme již seslali znamen&iacute; jasn&aacute;. A nevěř&iacute;c&iacute;m se dostane trestu zahanbuj&iacute;c&iacute;ho';
$t[6] = 'v den, kdy Bůh je v&scaron;echny vzkř&iacute;s&iacute; a ozn&aacute;m&iacute; jim, co vlastně dělali. Bůh dobře to spoč&iacute;tal, zat&iacute;mco oni na to zapomněli - a Bůh svědkem je v&scaron;ech věc&iacute;.';
$t[7] = 'Což jsi neviděl, že Bůh zn&aacute; v&scaron;e, co na nebes&iacute;ch je i na zemi? A nen&iacute; rozmluvy tajn&eacute; ve třech, aby tam nebyl čtvrt&yacute;, a v pěti, aby tam nebyl &scaron;est&yacute;, nebo v men&scaron;&iacute;m či vět&scaron;&iacute;m počtu, aby On nebyl s nimi, ať již jsou kdekoliv. A Bůh jim pak v den zmrtv&yacute;chvst&aacute;n&iacute; ozn&aacute;m&iacute;, co vlastně dělali, neboť Bůh o každ&eacute; věci je v&scaron;evědouc&iacute;.';
$t[8] = 'Což jsi neviděl ty, jimž zak&aacute;z&aacute;ny byly tajn&eacute; rozmluvy, jak se potom vrac&iacute; k tomu, co bylo jim zak&aacute;z&aacute;no, a domlouvaj&iacute; se tajně v hř&iacute;chu, nepř&aacute;telstv&iacute; a neposlu&scaron;nosti vůči poslu? A když k tobě přijdou, zdrav&iacute; tě tak, jak tě nezdrav&iacute; Bůh, a ř&iacute;kaj&iacute; si v duchu: &quot;Pročpak n&aacute;s Bůh nepotrest&aacute; za to, co ř&iacute;k&aacute;me?&quot; V&scaron;ak stačit jim bude peklo, v němž hořet budou - a jak hnusn&yacute; je to c&iacute;l konečn&yacute;!';
$t[9] = 'Vy, kteř&iacute; věř&iacute;te! Když spolu tajně hovoř&iacute;te, nedomlouvejte se o hř&iacute;chu, nepř&aacute;telstv&iacute; a neposlu&scaron;nosti vůči poslu, ale domlouvejte se o zbožnosti a bohabojnosti! Bojte se Boha, k němuž budete shrom&aacute;žděni!';
$t[10] = 'Tajn&eacute; rozmluvy poch&aacute;zej&iacute; jen od satana, aby způsobil z&aacute;rmutek těm, kdož uvěřili. Av&scaron;ak on nemůže jim v ničem u&scaron;kodit, leda z dovolen&iacute; Bož&iacute;ho. A na Boha nechť věř&iacute;c&iacute; se spol&eacute;haj&iacute;!';
$t[11] = 'Vy, kteř&iacute; věř&iacute;te! Když je v&aacute;m řečeno &quot;Uvolněte m&iacute;sto ve shrom&aacute;žděn&iacute;!&quot;, tedy je uvolněte! A Bůh pro v&aacute;s tak&eacute; uvoln&iacute; m&iacute;sto (v r&aacute;ji). A když je v&aacute;m řečeno &quot;Vzdalte se!&quot;, tedy se vzdalte. A Bůh pak pov&yacute;&scaron;&iacute; ty z v&aacute;s, kdož uvěřili, a ty, jimž dostalo se věděn&iacute;, na stupně různ&eacute;. A Bůh dobře je zpraven o v&scaron;em, co děl&aacute;te.';
$t[12] = 'Vy, kteř&iacute; věř&iacute;te! Jestliže chcete mluvit soukromě s poslem, dejte napřed dobrovoln&yacute; dar! Toto bude pro v&aacute;s lep&scaron;&iacute; a čist&scaron;&iacute;. V&scaron;ak nenajdete-li prostředky... vždyť Bůh je odpou&scaron;těj&iacute;c&iacute;, slitovn&yacute;.';
$t[13] = 'Styd&iacute;te se snad d&aacute;t dobrovoln&yacute; dar před soukrom&yacute;m rozhovorem? Jestliže tak neučin&iacute;te a Bůh se nad v&aacute;mi smiluje - pak vykonejte modlitbu, dejte almužnu a poslouchejte Boha a posla Jeho! A Bůh dobře je zpraven o v&scaron;em, co děl&aacute;te.';
$t[14] = 'Což jsi neviděl ty, kteř&iacute; se sdružuj&iacute; s lidmi, na něž se Bůh rozhněval? Ti nepatř&iacute; ani k v&aacute;m, ani k nim a př&iacute;sahaj&iacute; křivě, ačkoliv dobře jsou si toho vědomi.';
$t[15] = 'Bůh pro ně připravil trest stra&scaron;n&yacute; - a věru jak hnusn&eacute; je to, co dělaj&iacute;.';
$t[16] = 'Za&scaron;t&iacute;tili se př&iacute;sahami sv&yacute;mi a odvracej&iacute; od cesty Bož&iacute; - a pro ně připraven je trest zahanbuj&iacute;c&iacute;.';
$t[17] = 'A nijak jim proti Bohu neprospěj&iacute; majetky jejich ani děti jejich; jsou obyvateli ohně pekeln&eacute;ho a budou v něm nesmrteln&iacute;.';
$t[18] = 'V onen den je Bůh v&scaron;echny vzkř&iacute;s&iacute; a budou Mu př&iacute;sahat tak, jako přisahali v&aacute;m, a budou se domn&iacute;vat, že jednaj&iacute; spr&aacute;vně. Což v&scaron;ak nejsou vskutku lh&aacute;ři?';
$t[19] = 'Satan je ovl&aacute;dl a dal jim zapomenout na připomenut&iacute; Bož&iacute;; a oni patř&iacute; ke straně satanově. Což v&scaron;ak strana satanova ztr&aacute;tu neutrp&iacute;?';
$t[20] = 'Ti, kdož se protiv&iacute; Bohu a poslu Jeho, ti budou věru patřit k nejopovrhovaněj&scaron;&iacute;m!';
$t[21] = 'A Bůh napsal: &quot;Věru že zv&iacute;těz&iacute;m J&aacute; i poslov&eacute; Moji!&quot;, vždyť Bůh vskutku je siln&yacute; a mocn&yacute;.';
$t[22] = 'Nenalezne&scaron; ž&aacute;dn&eacute; lidi, věř&iacute;c&iacute; v Boha a v den posledn&iacute;, př&aacute;telit se s těmi, kdož se protiv&iacute; Bohu a poslu Jeho, byť to byli otcov&eacute; jejich či synov&eacute; jejich anebo bratři jejich či rod jejich. Do srdc&iacute; těchto vepsal Bůh v&iacute;ru a podpořil je duchem od Něho poch&aacute;zej&iacute;c&iacute;m. A uvede je do zahrad, pod nimiž řeky tekou a v nichž nesmrteln&iacute; budou. Bůh nalezl v nich zal&iacute;ben&iacute; a oni nalezli zal&iacute;beni v Něm - a tito tvoř&iacute; stranu Bož&iacute;! A což nebudou ti, kdož ke straně Bož&iacute; patř&iacute;, blažen&iacute;?';
?>