<?php
$t = array();
$t[1] = 'Slav&iacute; Boha v&scaron;e, co na nebes&iacute;ch je i na zemi, a On mocn&yacute; je i moudr&yacute;.';
$t[2] = 'On je ten, jenž vyhnal ty z vlastn&iacute;ků P&iacute;sma, kteř&iacute; neuvěřili, z př&iacute;bytků jejich k prvn&iacute;mu shrom&aacute;žděn&iacute;. Nevěřili jste, že odejdou, zat&iacute;mco oni si myslili, že pevnosti jejich je proti Bohu ochr&aacute;n&iacute;. V&scaron;ak Bůh k nim při&scaron;el z m&iacute;sta, odkud se nenad&aacute;li, a vrhl v srdce jejich děs, takže zbořili domy sv&eacute; vlastn&iacute;ma rukama i rukama věř&iacute;c&iacute;ch. A vezměte si z toho poučen&iacute;, vy, kdož nad&aacute;ni jste proz&iacute;ravost&iacute;!';
$t[3] = 'Kdyby byl Bůh pro ně nepředepsal vyhnanstv&iacute;, byl by je věru potrestal v životě pozemsk&eacute;m jin&yacute;m způsobem; v životě budouc&iacute;m pak je oček&aacute;v&aacute; trest ohniv&yacute;.';
$t[4] = 'A to proto, že se vzepřeli Bohu a poslu Jeho. A kdokoliv se vzepře Bohu... vždyť Bůh věru je stra&scaron;n&yacute; ve Sv&eacute;m trest&aacute;ni.';
$t[5] = 'V&scaron;e, co jste porazili z palem datlov&yacute;ch či nechali st&aacute;t na kořenech jejich, to učinili jste z dovolen&iacute; Bož&iacute;ho, a aby pon&iacute;ženi byli hanebn&iacute;ci.';
$t[6] = 'To, co Bůh poskytl jako kořist poslu Sv&eacute;mu z majetku jejich, k tomu jste vy nemusili popoh&aacute;nět ani koně, ani velbloudy. Av&scaron;ak Bůh d&aacute;v&aacute; Sv&eacute; zplnomocněn&iacute; poslům Sv&yacute;m, nad k&yacute;m chce, a Bůh je nad každou věc&iacute; v&scaron;emocn&yacute;.';
$t[7] = 'To, co Bůh poskytl poslu Sv&eacute;mu jako kořist z obyvatelů měst, to patř&iacute; Bohu a poslu Jeho, př&iacute;buzn&yacute;m, sirotkům, chud&aacute;kům a tomu, kdo po cestě Bož&iacute; kr&aacute;č&iacute;, aby se to nedostalo do oběhu mezi bohat&yacute;mi z v&aacute;s. To, co v&aacute;m d&aacute;v&aacute; posel, to si vezměte! Ale toho, co v&aacute;m odepřel, toho se zdržujte! A bojte se Boha, neboť Bůh je věru stra&scaron;n&yacute; v trest&aacute;n&iacute; Sv&eacute;m.';
$t[8] = 'A č&aacute;st kořisti n&aacute;lež&iacute; chud&yacute;m vystěhovalcům, kteř&iacute; byli vyhn&aacute;ni z př&iacute;bytků sv&yacute;ch a od majetků sv&yacute;ch a kteř&iacute; usiluj&iacute; dos&aacute;hnout př&iacute;zně Bož&iacute; a zal&iacute;ben&iacute; a pom&aacute;haj&iacute; Bohu a poslu Jeho. A toto jsou vskutku lid&eacute; spravedliv&iacute;.';
$t[9] = 'Ti, kdož pevně s&iacute;dl&iacute; v tomto obvodu a utvrdili se ve v&iacute;ře je&scaron;tě před nimi, ti miluj&iacute; ty, kdož se k nim vystěhovali, a nenal&eacute;zaj&iacute; v hrud&iacute;ch sv&yacute;ch ž&aacute;dnou z&aacute;vist kvůli tomu, co d&aacute;no bylo vystěhovalcům. A d&aacute;vaj&iacute; jim přednost před sebou, i kdyby sami měli nedostatek. A ti, kdož ochr&aacute;n&iacute; du&scaron;e sv&eacute; před lakotou, ti budou blažen&iacute;.';
$t[10] = 'A ti, kdož při&scaron;li po nich, hovoř&iacute;: &quot;Pane n&aacute;&scaron;, odpusť n&aacute;m i bratř&iacute;m na&scaron;im, kteř&iacute; n&aacute;s přede&scaron;li ve v&iacute;ře; a nevkl&aacute;dej do srdc&iacute; na&scaron;ich zlobu proti těm, kdož před n&aacute;mi uvěřili, Pane n&aacute;&scaron;, vždyť Tys věru shov&iacute;vav&yacute;, slitovn&yacute;!&quot;';
$t[11] = 'Což jsi neviděl pokrytce, jak ř&iacute;kaj&iacute; bratř&iacute;m sv&yacute;m nevěř&iacute;c&iacute;m z vlastn&iacute;ků P&iacute;sma: &quot;Budete-li vyhn&aacute;ni, my věru odejdeme s v&aacute;mi a nikdy neuposlechneme nikoho proti v&aacute;m. A bude-li proti v&aacute;m bojov&aacute;no, my v&aacute;m určitě pomůžeme.&quot; A Bůh je věru svědkem toho, že jsou lh&aacute;ři.';
$t[12] = 'A budou-li tito vskutku vyhn&aacute;ni, oni s nimi neodejdou, a bude-li proti nim bojov&aacute;no, oni jim nepomohou, anebo poskytnou-li jim pomoc, obr&aacute;t&iacute; se potom z&aacute;dy a nakonec jim sam&yacute;m nebude pomoci.';
$t[13] = 'Vy nah&aacute;n&iacute;te srdc&iacute;m jejich vět&scaron;&iacute; hrůzu než Bůh, a to je proto, že to jsou lid&eacute;, kteř&iacute; nic nech&aacute;pou.';
$t[14] = 'Nebudou bojovat proti v&aacute;m společně, n&yacute;brž jednotlivě v s&iacute;dli&scaron;t&iacute;ch opevněn&yacute;ch či za hradbami. Jsou-li mezi sebou, je statečnost jejich velk&aacute; a ty je pokl&aacute;d&aacute;&scaron; za sjednocen&eacute;, av&scaron;ak srdce jejich jsou rozdělena. A to proto, že jsou to lid&eacute;, kteř&iacute; rozumně neuvažuj&iacute;,';
$t[15] = 'podobn&iacute; těm, kdož byli nedlouho před nimi: okusili již &scaron;patn&yacute;ch n&aacute;sledků sv&eacute;ho poč&iacute;n&aacute;n&iacute; a oček&aacute;v&aacute; je je&scaron;tě trest bolestn&yacute;.';
$t[16] = 'A podobaj&iacute; se satanovi, jenž ř&iacute;k&aacute; člověku: &quot;Buď nevěř&iacute;c&iacute;!&quot; A když se stane nevěř&iacute;c&iacute;m, tu mu řekne: &quot;J&aacute; nejsem za tebe zodpovědn&yacute;, neboť se věru ob&aacute;v&aacute;m Boha, P&aacute;na lidstva ve&scaron;ker&eacute;ho!&quot;';
$t[17] = 'A konec jich obou bude jedině v ohni pekeln&eacute;m a budou tam nesmrteln&iacute;. A takov&aacute; je odměna nespravedliv&yacute;ch.';
$t[18] = 'Vy, kteř&iacute; věř&iacute;te, bojte se Boha! Nechť du&scaron;e každ&aacute; popatř&iacute; na to, co si již dř&iacute;ve připravila pro z&iacute;třek. Bojte se Boha, vždyť Bůh je dobře zpraven o v&scaron;em, co děl&aacute;te.';
$t[19] = 'Nebuďte jako ti, kdož zapomněli na Boha a jimž On dal zapomenout na sebe sam&eacute; - a toto jsou věru hanebn&iacute;ci.';
$t[20] = 'A nebudou si rovni obyvatel&eacute; ohně a obyvatel&eacute; r&aacute;je; a obyvatel&eacute; r&aacute;je jsou ti, kdož velk&eacute;ho &uacute;spěchu dos&aacute;hli.';
$t[21] = 'Kdybychom byli seslali tento Kor&aacute;n na horu, byl bys ji viděl pokornou a pukaj&iacute;c&iacute; ze strachu před Bohem. A tato podobenstv&iacute; uv&aacute;d&iacute;me lidem, snad budou o tom přem&yacute;&scaron;let.';
$t[22] = 'On je Bůh - a nen&iacute; božstva kromě Něho - jenž zn&aacute; nepoznateln&eacute; i v&scaron;eobecně zn&aacute;m&eacute;. On milosrdn&yacute; je i slitovn&yacute;.';
$t[23] = 'On je Bůh - a nen&iacute; božstva kromě Něho - vl&aacute;dce, přesvat&yacute;, m&iacute;r, věrn&yacute;, ochr&aacute;nce bezpečn&yacute;, mocn&yacute;, samovl&aacute;dn&yacute;, velmožn&yacute;; oč slavněj&scaron;&iacute; je Bůh než v&scaron;e to, co k Němu přidružuj&iacute;.';
$t[24] = 'On je Bůh, stvořitel, tvůrce i utv&aacute;řej&iacute;c&iacute;. Jemu př&iacute;slu&scaron;&iacute; jm&eacute;na překr&aacute;sn&aacute; a Jeho slav&iacute; v&scaron;e, co na nebes&iacute;ch je i na zemi - On mocn&yacute; je i moudr&yacute;!';
?>