<?php
$t = array();
$t[1] = 'Vy, kteř&iacute; věř&iacute;te! Neberte si nepř&aacute;tele M&eacute; i svoje za př&aacute;tele, obracej&iacute;ce se k nim s l&aacute;skou, zat&iacute;mco oni nevěř&iacute; v to, co k v&aacute;m při&scaron;lo z pravdy. Vždyť vyhnali posla i v&aacute;s za to, že věř&iacute;te v Boha, P&aacute;na sv&eacute;ho. Jestliže jste se vydali do boje na M&eacute; cestě a snaž&iacute;te se z&iacute;skat M&eacute; zal&iacute;ben&iacute;, jak můžete jim projevovat tajně svou l&aacute;sku? Vždyť J&aacute; zn&aacute;m, co skr&yacute;v&aacute;te i co najevo d&aacute;v&aacute;te. A kdo z v&aacute;s tak učin&iacute;, ten zbloudil z cesty př&iacute;m&eacute;.';
$t[2] = 'Střetnou-li se s v&aacute;mi, budou pro v&aacute;s nepř&aacute;teli a vzt&aacute;hnou po v&aacute;s ruce sv&eacute; i jazyky sv&eacute; jen ve zl&eacute;m a př&aacute;li by si, abyste byli nevěř&iacute;c&iacute;mi.';
$t[3] = 'Nebudou v&aacute;m k užitku ani va&scaron;i pokrevn&iacute; př&iacute;buzn&iacute;, ani va&scaron;e děti a v den zmrtv&yacute;chvst&aacute;n&iacute; Bůh mezi v&aacute;mi rozhodne; Bůh přece jasně zř&iacute; v&scaron;e, co děl&aacute;te.';
$t[4] = 'Vždyť m&aacute;te nyn&iacute; př&iacute;klad překr&aacute;sn&yacute; v Abrahamovi a v těch, kdož byli s n&iacute;m, když pravili lidu sv&eacute;mu: &quot;My nem&aacute;me odpovědnost za v&aacute;s a za to, co m&iacute;sto Boha ct&iacute;te; my se v&aacute;s zř&iacute;k&aacute;me a propuklo mezi n&aacute;mi a v&aacute;mi nepř&aacute;telstv&iacute; a nen&aacute;vist až navěky, dokud neuvěř&iacute;te v Boha jedin&eacute;ho!&quot; V&yacute;jimkou jsou slova Abrahamova otci jeho: &quot;Budu zajist&eacute; prosit za tebe o odpu&scaron;těn&iacute;, ačkoliv nevl&aacute;dnu pro tebe ž&aacute;dnou moc&iacute; u Boha. Pane n&aacute;&scaron;, na Tebe spol&eacute;h&aacute;me a k Tobě se kaj&iacute;cně obrac&iacute;me a u Tebe je c&iacute;l konečn&yacute;.';
$t[5] = 'Pane n&aacute;&scaron;, neuveď n&aacute;s v poku&scaron;en&iacute; před těmi, kdož jsou nevěř&iacute;c&iacute;, ale odpusť n&aacute;m, Pane n&aacute;&scaron;, vždyť Tys mocn&yacute;, moudr&yacute;!&quot;';
$t[6] = 'Věru m&aacute;te v nich př&iacute;klad překr&aacute;sn&yacute; pro každ&eacute;ho, kdo douf&aacute; dos&aacute;hnout Boha a dne soudn&eacute;ho. Ten v&scaron;ak, kdo obr&aacute;t&iacute; se z&aacute;dy... tedy Bůh je soběstačn&yacute;, chv&aacute;lyhodn&yacute;!';
$t[7] = 'Možn&aacute; že Bůh způsob&iacute;, že mezi v&aacute;mi a těmi, s nimiž jste v nepř&aacute;telstv&iacute;, zavl&aacute;dne l&aacute;ska, neboť Bůh je v&scaron;emohouc&iacute; a Bůh je nejv&yacute;&scaron; odpou&scaron;těj&iacute;c&iacute; a slitovn&yacute;.';
$t[8] = 'Bůh v&aacute;m nezakazuje, abyste byli dobř&iacute; a spravedliv&iacute; vůči těm, kdož nebojovali proti v&aacute;m kvůli n&aacute;boženstv&iacute; a nevyhnali v&aacute;s z př&iacute;bytků va&scaron;ich, neboť Bůh věru miluje poctiv&eacute;.';
$t[9] = 'Av&scaron;ak Bůh v&aacute;m zakazuje br&aacute;t si za př&aacute;tele ty, kteř&iacute; proti v&aacute;m bojovali kvůli n&aacute;boženstv&iacute;, a ty, kteř&iacute; v&aacute;s vyhnali z př&iacute;bytků va&scaron;ich, a ty, kteř&iacute; pom&aacute;hali při va&scaron;em vyh&aacute;něn&iacute;. A ti, kdož se s nimi budou př&aacute;telit, jsou nespravedliv&iacute;!';
$t[10] = 'Vy, kteř&iacute; věř&iacute;te! Když k v&aacute;m přich&aacute;zej&iacute; věř&iacute;c&iacute; ženy, jež se vystěhovaly, podrobte je zkou&scaron;ce! Bůh nejl&eacute;pe pak zn&aacute; v&iacute;ru jejich; a když zjist&iacute;te, že jsou věř&iacute;c&iacute;, nepos&iacute;lejte je nazpět k nevěř&iacute;c&iacute;m, neboť jim nejsou dovoleny a ani oni nejsou dovoleni jim, ale dejte nevěř&iacute;c&iacute;m to, co vydali jako jejich obvěněn&iacute;! A nebude pro v&aacute;s hř&iacute;chem, jestliže se s nimi ožen&iacute;te pot&eacute;, co d&aacute;te jim obvěněn&iacute; jejich, av&scaron;ak nedržte nevěř&iacute;c&iacute; ženy ve svazku manželsk&eacute;m a ž&aacute;dejte nazpět to, co jste dali jako obvěněn&iacute; a nevěř&iacute;c&iacute; ať požaduj&iacute; to, co dali žen&aacute;m sv&yacute;m. Takov&eacute; je rozhodnut&iacute; Bož&iacute;, j&iacute;mž mezi v&aacute;mi rozhoduje - a Bůh v&scaron;evědouc&iacute; je i moudr&yacute;.';
$t[11] = 'A jestliže někter&aacute; z va&scaron;ich manželek odejde od v&aacute;s k nevěř&iacute;c&iacute;m a vy jste dos&aacute;hli sv&eacute; pomsty, dejte těm, jejichž manželky ode&scaron;ly, tot&eacute;ž, co oni vydali jako obvěněn&iacute;. A bojte se Boha, v něhož věř&iacute;te!';
$t[12] = 'Proroku, přijdou-li k tobě věř&iacute;c&iacute; ženy, př&iacute;sahaj&iacute;ce ti věrnost, a že nebudou nic přidružovat k Bohu, že nebudou kr&aacute;st, nebudou cizoložit, že nebudou zab&iacute;jet sv&eacute; děti, že se nedopust&iacute; hanebnosti vymy&scaron;len&eacute; mezi sv&yacute;ma rukama a nohama a že nebudou neposlu&scaron;n&eacute; tebe v tom, co bylo uzn&aacute;no za vhodn&eacute; - přijmi př&iacute;sahu jejich a popros Boha za ně o odpu&scaron;těn&iacute;, vždyť Bůh odpou&scaron;těj&iacute;c&iacute; je, slitovn&yacute;.';
$t[13] = 'Vy, kteř&iacute; věř&iacute;te! Neberte si za př&aacute;tele lid, na nějž se Bůh rozhněval; ti ztratili naději na život budouc&iacute;, tak jako ji ztratili nevěř&iacute;c&iacute; ohledně obyvatel hrobů.';
?>