<?php
$t = array();
$t[1] = 'Proroku! Rozv&aacute;d&iacute;te-li se sv&yacute;mi ženami, tedy se s nimi rozveďte v ustanoven&eacute; pro ně lhůtě a poč&iacute;tejte přesně dny čekac&iacute; lhůty a bojte se Boha, P&aacute;na sv&eacute;ho! Nevyh&aacute;nějte je z jejich domů a nechť z nich neodch&aacute;zej&iacute;, leda kdyby se dopustily hanebnosti zjevn&eacute;. A toto jsou omezen&iacute; Bož&iacute; a kdo přestupuje omezen&iacute; Bož&iacute;, ten s&aacute;m sobě křivd&iacute;. Ty nev&iacute;&scaron;, ale možn&aacute; že Bůh později způsob&iacute; nějakou věc jinou.';
$t[2] = 'A když ženy dos&aacute;hnou lhůty sv&eacute;, pak je buď podržte podle zvyklosti vhodn&eacute;, anebo se od nich odlučte tak&eacute; podle zvyklosti vhodn&eacute;. A vyž&aacute;dejte si svědectv&iacute; dvou osob spravedliv&yacute;ch mezi v&aacute;mi a přistupte k svědectv&iacute; při Bohu. A toto je napomenut&iacute; tomu, kdo věř&iacute; v Boha a v den soudn&yacute;. A kdo je bohabojn&yacute;, tomu On připrav&iacute; v&yacute;chodisko';
$t[3] = 'a u&scaron;tědř&iacute; mu obživu z m&iacute;sta, odkud s t&iacute;m ani nepoč&iacute;tal. A tomu, kdo spol&eacute;h&aacute; se na Boha, tomu On postač&iacute;, vždyť Bůh uskutečňuje rozkaz Svůj a Bůh ustanovil pro věc každou rozměr jej&iacute;.';
$t[4] = 'Pro ty z va&scaron;ich žen, jež již nemaj&iacute; naději na menstruaci, ale jste-li přesto na pochyb&aacute;ch, nechť jsou čekac&iacute; lhůtou tři měs&iacute;ce; a stejně plat&iacute; i pro ty, kter&eacute; je&scaron;tě menstruaci neměly. Pro ty, jež jsou těhotn&eacute;, skonč&iacute; čekac&iacute; lhůta tehdy, když porod&iacute;. A kdo je bohabojn&yacute;, tomu Bůh věc jeho ulehč&iacute;.';
$t[5] = 'Toto je nař&iacute;zen&iacute; Bož&iacute;, kter&eacute; v&aacute;m ses&iacute;l&aacute;. A kdo je bohabojn&yacute;, tomu Bůh vymaže &scaron;patn&eacute; skutky jeho a rozmnož&iacute; mu odměnu.';
$t[6] = 'Ubytujte ženy sv&eacute; po rozvodu tam, kde sami bydl&iacute;te, podle možnost&iacute; sv&yacute;ch. Nečiňte jim ž&aacute;dnou &uacute;jmu s &uacute;myslem je utiskovat. Jsou-li těhotn&eacute;, přisp&iacute;vejte jim, pokud neporod&iacute;! A jestliže koj&iacute; pro v&aacute;s d&iacute;tě va&scaron;e, d&aacute;vejte jim jejich odměnu a dohodněte se vz&aacute;jemně podle zvyklosti uznan&eacute;, v&scaron;ak naraz&iacute;te-li na obt&iacute;že, dejte je kojit ženě jin&eacute;!';
$t[7] = 'Nechť ten, kdo je blahobytn&yacute;, d&aacute;v&aacute; &uacute;měrně k blahobytu sv&eacute;mu a nechť ten, jehož obživa je odměřena, d&aacute;v&aacute; z toho, co Bůh mu u&scaron;tědřil. A Bůh neukl&aacute;d&aacute; du&scaron;i ž&aacute;dn&eacute; v&iacute;ce než to, co s&aacute;m j&iacute; dal. A Bůh po těžkostech přinese ulehčen&iacute;.';
$t[8] = 'Ať se již kolik chtělo z měst vzepřelo rozkazu P&aacute;na sv&eacute;ho a posla Jeho, z&uacute;čtovali jsme s nimi &uacute;čtem př&iacute;sn&yacute;m a potrestali jsme je trestem odporn&yacute;m!';
$t[9] = 'A okusila n&aacute;sledky poč&iacute;n&aacute;n&iacute; sv&eacute;ho a konec poč&iacute;n&aacute;n&iacute; jejich byla ztr&aacute;ta jejich.';
$t[10] = 'A Bůh připravil pro obyvatele jejich trest stra&scaron;n&yacute;, bojte se tedy Boha vy, kdož nad&aacute;ni jste rozmyslem a kteř&iacute; jste uvěřili! Bůh seslal v&aacute;m již připomenut&iacute;';
$t[11] = 'posla, kter&yacute; v&aacute;m předn&aacute;&scaron;&iacute; zřeteln&aacute; znamen&iacute; Bož&iacute;, aby vyvedl ty, kdož uvěřili a zbožn&eacute; skutky konali, z temnot k světlu. Kdo v Boha věř&iacute; a zbožn&eacute; skutky kon&aacute;, toho Bůh uvede do zahrad, pod nimiž tekou řeky, a tam bude nesmrteln&yacute; navěky. A pro takov&eacute;ho Bůh připravil obživu překr&aacute;snou.';
$t[12] = 'Bůh je ten, jenž stvořil sedm nebes a podobn&yacute; počet zem&iacute;. A zjeven&iacute; Jeho sestupuje mezi nimi, abyste zvěděli, že Bůh je nad každou věc&iacute; v&scaron;emocn&yacute; a že Bůh obj&iacute;m&aacute; věděn&iacute;m Sv&yacute;m věci v&scaron;echny.';
?>