<?php
$t = array();
$t[1] = 'Proroku, proč ve snaze uspokojit sv&eacute; ženy zakazuje&scaron; to, co Bůh ti dovolil? Vždyť Bůh je odpou&scaron;těj&iacute;c&iacute;, slitovn&yacute;.';
$t[2] = 'Bůh v&aacute;m uložil, abyste se vyv&aacute;zali z př&iacute;sah sv&yacute;ch; Bůh ochr&aacute;ncem je va&scaron;&iacute;m a On v&scaron;evědouc&iacute; je i moudr&yacute;.';
$t[3] = 'Hle, prorok svěřil v tajnosti jedn&eacute; ze sv&yacute;ch žen novinku; když v&scaron;ak to ozn&aacute;mila jin&eacute; a Bůh mu to odkryl, č&aacute;st z toho sdělil a č&aacute;st si ponechal pro sebe. A když j&iacute; to ozn&aacute;mil, zeptala se: &quot;Kdo ti to sdělil?&quot; I odpověděl: &quot;Sdělil mi to v&scaron;evědouc&iacute;, dobře zpraven&yacute;.&quot;';
$t[4] = 'Jestliže se obě kaj&iacute;cně obr&aacute;t&iacute;te k Bohu... a srdce va&scaron;e se již odch&yacute;lila, av&scaron;ak budete-li se mu společně protivit, tedy Bůh věru je ochr&aacute;ncem jeho, i Gabriel a každ&yacute; spravedliv&yacute; z věř&iacute;c&iacute;ch a anděl&eacute; jsou nadto pomocn&iacute;ky jeho.';
$t[5] = 'Jestliže se s v&aacute;mi rozvede, možn&aacute; že mu Bůh pak d&aacute; v n&aacute;hradu manželky lep&scaron;&iacute;, než jste vy, odevzdan&eacute; do vůle Jeho, věř&iacute;c&iacute;, pokorně oddan&eacute;, kaj&iacute;cn&eacute;, Boha uct&iacute;vaj&iacute;c&iacute; a slav&iacute;c&iacute;, ať již předt&iacute;m vdan&eacute; či panny.';
$t[6] = 'Vy, kteř&iacute; věř&iacute;te! Střezte sebe i rodiny sv&eacute; před ohněm, jehož palivem budou lid&eacute; a kamen&iacute;. Na něj dohl&iacute;žej&iacute; anděl&eacute; př&iacute;sn&iacute; a siln&iacute;, kteř&iacute; se neodv&aacute;ž&iacute; neuposlechnout Boha v ničem, co jim přik&aacute;zal, a vykonaj&iacute; v&scaron;e, co jim bylo poručeno.';
$t[7] = '&quot;Vy, kteř&iacute; jste neuvěřili, nevymlouvejte se dnes! Dost&aacute;v&aacute; se v&aacute;m jen odměny za to, co jste dělali.&quot;';
$t[8] = 'Vy, kteř&iacute; věř&iacute;te! Obraťte se k Bohu s upř&iacute;mn&yacute;m pok&aacute;n&iacute;m! Snad P&aacute;n v&aacute;&scaron; v&aacute;m vymaže &scaron;patn&eacute; skutky va&scaron;e a uvede v&aacute;s do zahrad, pod nimiž řeky tekou, v den, kdy nezahanb&iacute; Bůh ani proroka, ani ty, kdož s n&iacute;m věřili. A světlo jejich poběž&iacute; před nimi a po pravici jejich a budou volat: &quot;Pane n&aacute;&scaron;, učiň dokonal&yacute;m světlo na&scaron;e a odpusť n&aacute;m, vždyť Tys v&scaron;ech věc&iacute; mocen!&quot;';
$t[9] = 'Proroku, bojuj usilovně proti nevěř&iacute;c&iacute;m a pokrytcům a buď k nim př&iacute;sn&yacute;! Jejich &uacute;toči&scaron;těm bude peklo - jak hnusn&yacute; je to c&iacute;l konečn&yacute;!';
$t[10] = 'Bůh uv&aacute;d&iacute; těm, kdož neuvěřili, podobenstv&iacute; o ženě Noema a o ženě Lota: obě byly pod moc&iacute; Na&scaron;ich dvou služebn&iacute;ků bez&uacute;honn&yacute;ch a obě je zradily. Av&scaron;ak nic jim nepomohli manžel&eacute; jejich proti Bohu a bylo jim řečeno: &quot;Vstupte do ohně s těmi, kdož tam vstupuj&iacute;!&quot;';
$t[11] = 'A Bůh uv&aacute;d&iacute; těm, kdož uvěřili, př&iacute;klad ženy Fara&oacute;novy, když zvolala: &quot;Pane můj, postav pro mne u Sebe v r&aacute;ji př&iacute;bytek a zachraň mne před Fara&oacute;nem a jeho skutky a zachraň mne před lidem nespravedliv&yacute;m!&quot;';
$t[12] = 'A uv&aacute;d&iacute; i Marii, dceru &acute;Imr&aacute;novu, jež panenstv&iacute; sv&eacute; střežila a do n&iacute;ž jsme vdechli ducha Sv&eacute;ho. A za pravdiv&aacute; prohl&aacute;sila slova P&aacute;na sv&eacute;ho i P&iacute;sma Jeho a patřila mezi Bohu pokorně oddan&eacute;.';
?>