<?php
$t = array();
$t[1] = 'Al&aacute; ha o&iacute;do lo que dec&iacute;a la que discut&iacute;a contigo a prop&oacute;sito de su esposo y que se quejaba a Al&aacute;. Al&aacute; oye vuestro di&aacute;logo. Al&aacute; todo lo oye, todo lo ve.';
$t[2] = 'Aqu&eacute;llos de vosotros que repudian a sus mujeres mediante la f&oacute;rmula: &laquo;&iexcl;Eres para m&iacute; como la espalda de mi madre!&raquo;... Ellas no son sus madres. S&oacute;lo son sus madres las que les han dado a luz. Dicen, ciertamente, algo reprobable y err&oacute;neo. Pero Al&aacute; es, s&iacute;, perdonador, indulgente.';
$t[3] = 'Quienes repudian a sus mujeres mediante la f&oacute;rmula: &laquo;&iexcl;Eres para m&iacute; como la espalda de mi madre!&raquo; y la repiten, deben, antes de cohabitar de nuevo, manumitir a un esclavo. Se os exhorta a ello. Al&aacute; est&aacute; bien informado de lo que hac&eacute;is.';
$t[4] = 'Quien no pueda hacerlo, deber&aacute; ayunar durante dos meses consecutivos antes de cohabitar de nuevo. Quien no pueda, deber&aacute; alimentar a sesenta pobres. Para que cre&aacute;is en Al&aacute; y en Su Enviado. &Eacute;stas son las leyes de Al&aacute;. Los infieles tendr&aacute;n un castigo doloroso.';
$t[5] = 'Quienes se oponen a Al&aacute; y a su Enviado ser&aacute;n derribados como lo fueron quienes les precedieron. Hemos revelado signos claros. Los infieles tendr&aacute;n un castigo humillante.';
$t[6] = 'El d&iacute;a que Al&aacute; les resucite a todos, ya les informar&aacute; de lo que hicieron. Al&aacute; lo habr&aacute; tenido en cuenta, mientras que ellos lo habr&aacute;n olvidado. Al&aacute; es testigo de todo.';
$t[7] = '&iquest;No ves que Al&aacute; conoce lo que est&aacute; en los cielos y en la tierra? No hay concili&aacute;bulo de tres personas en que no sea &Eacute;l el cuarto, ni de cinco personas en que no sea &Eacute;l el sexto. Lo mismo si son menos que si son m&aacute;s, &Eacute;l siempre est&aacute; presente, dondequiera que se encuentren. Luego, el d&iacute;a de la Resurrecci&oacute;n, ya les informar&aacute; de lo que hicieron. Al&aacute; es omnisciente.';
$t[8] = '&iquest;No ves a aqu&eacute;llos a quienes se ha prohibido celebrar concili&aacute;bulos, que se obstinan en lo prohibido y los celebran, haci&eacute;ndose culpables de pecado, de violaci&oacute;n de la ley y de desobediencia al Enviado? Cuando vienen a ti, te saludan de manera distinta a como Al&aacute; te saluda y dicen para s&iacute;: &laquo;&iquest;C&oacute;mo es que Al&aacute; no nos castiga por lo que decimos?&raquo; Les bastar&aacute; con la gehena, en la que arder&aacute;n. &iexcl;Qu&eacute; mal fin...!';
$t[9] = '&iexcl;Creyentes! Cuando celebr&eacute;is un concili&aacute;bulo, no lo hag&aacute;is con &aacute;nimo de pecar, de violar la ley y de desobedecer al Enviado, sino con el &aacute;nimo de ser buenos y temerosos de Al&aacute;. &iexcl;Y temed a Al&aacute;, hacia Quien ser&eacute;is congregados!';
$t[10] = 'El concili&aacute;bulo es s&oacute;lo cosa del Demonio, para entristecer a los que creen, pero que no puede hacerles ning&uacute;n da&ntilde;o, a menos que Al&aacute; lo permita. &iexcl;Que los creyentes conf&iacute;en en Al&aacute;!';
$t[11] = '&iexcl;Creyentes! Cuando se os dice: &laquo;&iexcl;Haced sitio en las asambleas!&raquo; hacedlo as&iacute; para que Al&aacute; os haga tambi&eacute;n sitio. Y si se os dice: &laquo;&iexcl;Levantaos!&raquo;, hacedlo as&iacute; para que Al&aacute; tambi&eacute;n eleve la categor&iacute;a de aqu&eacute;llos de vosotros que crean y reciban la Ciencia. Al&aacute; est&aacute; informado de lo que hac&eacute;is.';
$t[12] = '&iexcl;Creyentes! Cuando quer&aacute;is tener una conversaci&oacute;n a solas con el Enviado, hacedla preceder de una limosna. Es mejor para vosotros y m&aacute;s puro. Si no pod&eacute;is, Al&aacute; es indulgente, misericordioso';
$t[13] = '&iquest;Os arredra hacer preceder vuestra conversaci&oacute;n a solas de limosnas? Si no lo hac&eacute;is y Al&aacute; se aplaca con vosotros, &iexcl;haced la azal&aacute;, dad el azaque y obedeced a Al&aacute; y a su Enviado! Al&aacute; est&aacute; bien informado de lo que hac&eacute;is.';
$t[14] = '&iquest;No has visto a quienes han tomado como protectores a gente que ha incurrido en la ira de Al&aacute;? No son ni de los vuestros ni de los suyos y juran en falso deliberadamente.';
$t[15] = 'Al&aacute; ha preparado para ellos un castigo severo. Lo que han hecho est&aacute; mal.';
$t[16] = 'Se han escudado en sus juramentos y han desviado a otros del camino de Al&aacute;. Tendr&aacute;n un castigo humillante.';
$t[17] = 'Ni su hacienda ni sus hijos le servir&aacute;n de nada frente a Al&aacute;. Esos tales morar&aacute;n en el Fuego eternamente.';
$t[18] = 'El d&iacute;a que Al&aacute; les resucite a todos, Le jurar&aacute;n a &Eacute;l como os juran a vosotros, creyendo apoyarse en algo s&oacute;lido. &iquest;No son ellos los que mienten?';
$t[19] = 'El Demonio se ha apoderado de ellos y les ha hecho olvidarse del recuerdo de Al&aacute;. Esos tales son los partidarios del Demonio. Y &iquest;no son los partidarios del Demonio los que pierden?';
$t[20] = 'Los que se oponen a Al&aacute; y a Su Enviado estar&aacute;n entre los m&aacute;s viles.';
$t[21] = 'Al&aacute; ha escrito: &laquo;&iexcl;Vencer&eacute;, en verdad! &iexcl;Yo y Mis enviados!&raquo; Al&aacute; es fuerte, poderoso.';
$t[22] = 'No encontrar&aacute;s a gente que crea en Al&aacute; y en el &uacute;ltimo D&iacute;a y que tenga cari&ntilde;o a quienes se oponen a Al&aacute; y a Su Enviado, aunque &eacute;stos sean sus padres, sus hijos varones, sus hermanos o los miembros de su misma tribu. He inscrito la fe en sus corazones, les ha fortalecido con un esp&iacute;ritu de &Eacute;l y les introducir&aacute; en jardines por cuyos bajos fluyen arroyos, en los que estar&aacute;n eternamente. Al&aacute; est&aacute; satisfecho de ellos y ellos lo est&aacute;n de &Eacute;l. &Eacute;sos constituyen el partido de Al&aacute;. Y &iquest;no son los partidarios de Al&aacute; los que prosperan?';
?>