<?php
$t = array();
$t[1] = '&iexcl;Creyentes! &iexcl;No tom&eacute;is como amigos a los enemigos M&iacute;os y vuestros, d&aacute;ndoles muestras de afecto, siendo as&iacute; que no creen en la Verdad venida a vosotros! Expulsan al Enviado y os expulsan a vosotros porque cre&eacute;is en Al&aacute; vuestro Se&ntilde;or. Si sal&iacute;s para luchar por Mi causa y por deseo de agradarme, &iquest;les tendr&eacute;is un afecto secreto? Yo s&eacute; bien lo que ocult&aacute;is y lo que manifest&aacute;is. Quien de vosotros obra as&iacute;, se extrav&iacute;a del camino recto.';
$t[2] = 'Si dan con vosotros, son para vosotros enemigos y os maltratan de obra y de palabra. Querr&iacute;an que no creyerais...';
$t[3] = 'El d&iacute;a de la Resurrecci&oacute;n no os aprovechar&aacute;n ni vuestros parientes ni vuestros hijos. &Eacute;l fallar&aacute; acerca de vosotros. Al&aacute; ve bien lo que hac&eacute;is.';
$t[4] = 'Ten&eacute;is un bello modelo en Abraham y en los que con &eacute;l estaban. Cuando dijeron a su pueblo: &laquo;No somos responsables de vosotros ni de lo que serv&iacute;s en lugar de servir a Al&aacute;. &iexcl;Renegamos de vosotros! &iexcl;Ha aparecido, entre nosotros y vosotros, hostilidad y odio para siempre mientras no cre&aacute;is en Al&aacute; Solo!&raquo; No es de imitar, en cambio, Abraham cuando dijo a su padre: &laquo;He de pedir perd&oacute;n para ti, aunque no pueda hacer nada por ti contra Al&aacute;. &iexcl;Se&ntilde;or! Confiamos en Ti y a Ti nos volvemos arrepentidos. &iexcl;Eres T&uacute; el fin de todo!';
$t[5] = '&iexcl;Se&ntilde;or! &iexcl;No hagas de nosotros instrumento de tentaci&oacute;n para los infieles! &iexcl;Perd&oacute;nanos, Se&ntilde;or! Eres T&uacute; el Poderoso, el Sabio&raquo;.';
$t[6] = 'Ten&eacute;is en ellos un bello modelo para quien cuenta con Al&aacute; y con el &uacute;ltimo D&iacute;a. Pero quien vuelve la espalda,... Al&aacute; es Quien Se basta a S&iacute; mismo, el Digno de Alabanza.';
$t[7] = 'Quiz&aacute; establezca Al&aacute; la amistad entre vosotros y los que de ellos ten&eacute;is por enemigos. Al&aacute; es capaz, Al&aacute; es indulgente, misericordioso.';
$t[8] = 'Al&aacute; no os proh&iacute;be que se&aacute;is buenos y equitativos con quienes no han combatido contra vosotros por causa de la religi&oacute;n, ni os han expulsado de vuestros hogares. Al&aacute; ama a los que son equitativos.';
$t[9] = 'Lo que s&iacute; os proh&iacute;be Al&aacute; es que tom&eacute;is como amigos a los que han combatido contra vosotros por causa de la religi&oacute;n y os han expulsado de vuestros hogares o han contribu&iacute;do a vuestra expulsi&oacute;n. Quienes les tomen como amigos, &eacute;sos son los imp&iacute;os.';
$t[10] = '&iexcl;Creyentes! Cuando vengan a vosotros mujeres creyentes que hayan emigrado, &iexcl;examinadlas! Al&aacute; conoce bien su fe. Si comprob&aacute;is que de verdad son creyentes, no las devolv&aacute;is a los infieles: ni ellas son l&iacute;citas para ellos ni ellos lo son para ellas. &iexcl;Reembolsadles lo que hayan gastado! No ten&eacute;is nada que reprocharos si os cas&aacute;is con ellas, con tal que les entregu&eacute;is su dote. Pero no reteng&aacute;is a las infieles. Pedid lo que hay&aacute;is gastado, y que ellos tambi&eacute;n pidan lo que hayan gastado. &Eacute;sa es la decisi&oacute;n de Al&aacute;. &Eacute;l decide entre vosotros. Al&aacute; es omnisciente, sabio.';
$t[11] = 'Si alguna de vuestras esposas se pasa a los infieles y, luego, os toca a vosotros vencer, dad a aqu&eacute;llos cuyas esposas hayan huido otro tanto de lo que hab&iacute;an gastado. &iexcl;Temed a Al&aacute;, en Quien cre&eacute;is!';
$t[12] = '&iexcl;Profeta! Cuando las creyentes vengan a ti a prestarte juramento de fidelidad, de que no asociar&aacute;n nada a Al&aacute;, que no robar&aacute;n, que no fornicar&aacute;n, que no matar&aacute;n a sus hijos, que no dir&aacute;n calumnia forjada entre sus manos y pies, que no te desobedecer&aacute;n en lo que se juzgue razonable, acepta su juramento y pide a Al&aacute; que les perdone. Al&aacute; es indulgente, misericordioso.';
$t[13] = '&iexcl;Creyentes! &iexcl;No tom&eacute;is como amigos a gente que ha incurrido en la ira de Al&aacute;! Desesperan de la otra vida, como los infieles desesperan de los sepultados.';
?>