<?php
$t = array();
$t[1] = '&iexcl;Profeta! Cuando repudi&aacute;is a las mujeres, &iexcl;hacedlo al terminar su per&iacute;odo de espera! &iexcl;Contad bien los d&iacute;as de ese per&iacute;odo y temed a Al&aacute;, vuestro Se&ntilde;or! &iexcl;No las expuls&eacute;is de sus casas ni ellas salgan, a menos que sean culpables de deshonestidad manifiesta! &Eacute;sas son las leyes de Al&aacute;. Y quien viola las leyes de Al&aacute; es injusto consigo mismo. T&uacute; no sabes... Quiz&aacute; Al&aacute;, entre tanto, suscite alg&uacute;n imprevisto...';
$t[2] = 'Cuando lleguen a su t&eacute;rmino, retenedlas decorosamente o separaos de ellas decorosamente. Y requerid el testimonio de dos personas justas de los vuestros y atestiguad ante Al&aacute;. A esto se exhorta a quien cree en Al&aacute; y en el &uacute;ltimo D&iacute;a. A quien teme a Al&aacute;, &Eacute;l le da una salida';
$t[3] = 'y le provee de un modo insospechado por &eacute;l. A quien conf&iacute;a en Al&aacute;, &Eacute;l le basta. Al&aacute; consigue lo que se propone. Al&aacute; ha establecido una medida para cada cosa.';
$t[4] = 'Para aqu&eacute;llas de vuestras mujeres que ya no esperan tener la menstruaci&oacute;n, si ten&eacute;is dudas, su per&iacute;odo de espera ser&aacute; de tres meses; lo mismo para las imp&uacute;beres. Para las embarazadas, su per&iacute;odo de espera terminar&aacute; cuando den a luz. A quien teme a Al&aacute;, &Eacute;l le facilita sus cosas.';
$t[5] = '&Eacute;sta es la orden que Al&aacute; os ha revelado. Al&aacute; borra las malas obras de quien Le teme y le da una magn&iacute;fica recompensa.';
$t[6] = '&iexcl;Alojadlas, seg&uacute;n vuestros medios, en vuestra misma vivienda! &iexcl;No les hag&aacute;is da&ntilde;o con &aacute;nimo de molestarlas! Si est&aacute;n embarazadas, proveedles de lo necesario hasta que den a luz. Si la criatura que cr&iacute;an es vuestra, retribuidles como es debido y llegad a un acuerdo decoroso. Si encontr&aacute;is alguna dificultad, entonces, tomad un ama a cuenta vuestra.';
$t[7] = '&iexcl;Que el acomodado gaste seg&uacute;n sus medios! Quien disponga de medios limitados &iexcl;que gaste seg&uacute;n lo que Al&aacute; le haya dado! Al&aacute; no pide a nadie sino lo que le ha dado. Al&aacute; har&aacute; que a la adversidad suceda la felicidad.';
$t[8] = '&iexcl;A cu&aacute;ntas ciudades, que desde&ntilde;aron la orden de su Se&ntilde;or y de Sus enviados, pedimos cuenta rigurosa e infligimos un castigo horroroso!';
$t[9] = 'Gustaron la gravedad de su conducta, que acab&oacute; por perderles.';
$t[10] = 'Al&aacute; ha preparado para ellos un castigo severo. &iexcl;Temed, pues, a Al&aacute;, creyentes dotados de intelecto! Al&aacute; os ha enviado de lo alto una Amonestaci&oacute;n,';
$t[11] = 'un Enviado que os recita aleyas aclaratorias de Al&aacute;, para sacar de las tinieblas a la luz a quienes creen y obran bien. A quien cree en Al&aacute; y obra bien, &Eacute;l le introducir&aacute; en jardines por cuyos bajos fluyen arroyos, en los que estar&aacute;n eternamente, para siempre. Al&aacute; le ha reservado un bello sustento.';
$t[12] = 'Al&aacute; es Quien ha creado siete cielos y otras tantas tierras. La orden desciende gradualmente entre ellos para que sep&aacute;is&sbquo; que Al&aacute; es omnipotente y que Al&aacute; todo lo abarca en Su ciencia.';
?>