<?php
$t = array();
$t[1] = '&iexcl;Profeta! &iquest;Por qu&eacute;, para agradar a tus esposas, declaras prohibido lo que Al&aacute; ha declarado l&iacute;cito para ti? Pero Al&aacute; es indulgente, misericordioso.';
$t[2] = 'Al&aacute; os ha prescrito la anulaci&oacute;n de vuestros juramentos. Al&aacute; es vuestro Protector. &Eacute;l es el Omnisciente, el Sabio.';
$t[3] = 'Y cuando el Profeta dijo un secreto a una de sus esposas. Cuando, no obstante, ella lo revel&oacute; y Al&aacute; se lo descubri&oacute;, dio &eacute;l a conocer parte y ocult&oacute; el resto. Y, cuando se lo revel&oacute;, dijo ella: &laquo;&iquest;Qui&eacute;n te ha informado de esto?&raquo; &Eacute;l dijo: &laquo;Me lo ha revelado el Omnisciente, el Bien Informado&raquo;.';
$t[4] = 'Si os volv&eacute;is ambas, arrepentidas, a Al&aacute;, es se&ntilde;al de que vuestros corazones han cedido. Si, al contrario, os prest&aacute;is ayuda en contra de &eacute;l, entonces, Al&aacute; es su Protector. Y le ayudar&aacute;n Gabriel, los buenos creyentes y, adem&aacute;s, los &aacute;ngeles.';
$t[5] = 'Si &eacute;l os repudia, quiz&aacute; su Se&ntilde;or le d&eacute;, a cambio, esposas mejores que vosotras, sometidas a &Eacute;, creyentes, devotas, arrepentidas, que sirven a Al&aacute;, que ayunan, casadas de antes o v&iacute;rgenes.';
$t[6] = '&iexcl;Creyentes! Guardaos, vosotros y vuestras familias, de un Fuego cuyo combustible lo forman hombres y piedras, y sobre el que habr&aacute; &aacute;ngeles gigantescos, poderosos, que no desobedecen a Al&aacute; en lo que les ordena, sino que hacen lo que se les ordena.';
$t[7] = '&iexcl;Infieles! &iexcl;No os disculp&eacute;is hoy! Se os retribuir&aacute; tan s&oacute;lo seg&uacute;n vuestras obras.';
$t[8] = '&iexcl;Creyentes! &iexcl;Volveos a Al&aacute; con sincero arrepentimiento! Quiz&aacute; vuestro Se&ntilde;or borre vuestras malas obras y os introduzca en jardines por cuyos bajos fluyen arroyos. El d&iacute;a que Al&aacute; libre de verg&uuml;enza al Profeta y a los que con &eacute;l creyeron... Su luz correr&aacute; ante ellos y a su derecha. Dir&aacute;n: &laquo;&iexcl;Se&ntilde;or! &iexcl;Perfecci&oacute;nanos nuestra luz y perd&oacute;nanos! Eres omnipotente&raquo;.';
$t[9] = '&iexcl;Profeta! &iexcl;Combate contra los infieles y los hip&oacute;critas! &iexcl;Mu&eacute;strate duro con ellos! Tendr&aacute;n la gehena por morada. &iexcl;Qu&eacute; mal fin...!';
$t[10] = 'Al&aacute; pone como ejemplo para los infieles a la mujer de No&eacute; y a la mujer de Lot. Ambas estaban sujetas a dos de Nuestros siervos justos, pero les traicionaron, aunque su traici&oacute;n no les sirvi&oacute; de nada frente a Al&aacute;. Y se dijo: &laquo;&iexcl;Entrad ambas en el Fuego, junto con los dem&aacute;s que entran!&raquo;';
$t[11] = 'Y Al&aacute; pone como ejemplo para los creyentes a la mujer de Fara&oacute;n. Cuando dijo: &laquo;&iexcl;Se&ntilde;or! &iexcl;Constr&uacute;yeme, junto a Ti, una casa en el Jard&iacute;n y s&aacute;lvame de Fara&oacute;n y de sus obras! &iexcl;S&aacute;lvame del pueblo imp&iacute;o!&raquo;';
$t[12] = 'Y a Mar&iacute;a, hija de Imran, que conserv&oacute; su virginidad y en la que infundimos de Nuestro Esp&iacute;ritu. Tuvo por aut&eacute;nticas las palabras y Escritura de su Se&ntilde;or y fue de las devotas.';
?>