<?php
$t = array();
$t[1] = 'God heeft de woorden gehoord van haar, die zich bij u over haren echtgenoot heeft beklaagd, en hare klachten tot God heeft gericht , God heeft uwe wederzijdsche gesprekken gehoord; want God hoort en ziet alles.';
$t[2] = 'Wat degenen onder u betreft, die van hunne vrouwen scheiden, met de verklaring, dat zij haar daarna als hunne moeders zullen beschouwen, laat hen weten, dat zij hunne moeders niet zijn. Hunne moeders zijn slechts zij, die hen baarden, en zij spreken waarlijk onrechtvaardig en logentaal; Maar God is barmhartig en vergevensgezind.';
$t[3] = 'Zij die van hunne vrouwen scheiden, met de verklaring, dat zij haar in de toekomst als hunne moeders zullen beschouwen, en daarna terugnemen willen wat zij hebben gezegd, zullen genoodzaakt zijn een slaaf te bevrijden, alvorens zij elkander zullen mogen aanraken. Dit wordt u gewaarschuwd in acht te nemen, en God is wel onderricht van hetgeen gij doet.';
$t[4] = 'En hij die geen slaaf vindt, om dien eed los te koopen, zal een vasten van twee achtereenvolgende maanden houden, alvorens zij elkander aanraken. En hij die niet in staat zal zijn dien tijd te vasten, zal zestig arme lieden voeden. Dit is u bevolen, opdat gij God en zijn gezant zoudt gelooven. Dit zijn de bevelen van God. Voor de ongeloovigen is eene pijnlijke marteling gereed gemaakt.';
$t[5] = 'Zij die God en zijn gezant wederstand bieden, zullen ten onder gebracht worden, zooals de ongeloovigen die hen voorafgingen, werden ten onder gebracht. En wij hebben duidelijke teekens nedergezonden, en eene schandelijke straf wacht de ongeloovigen.';
$t[6] = 'Op een zekeren dag zal God hen allen ten leven opwekken, en hij zal hun verklaren wat zij verricht hebben. God heeft eene nauwkeurige rekening daarvan opgemaakt; maar zij hebben die vergeten, en God is getuige van alle dingen.';
$t[7] = 'Bemerkt gij niet dat God alles kent, wat in den hemel en op aarde is? Er is geen geheim gesprek tusschen drie personen, of hij is er de vierde van, noch van vijf, of hij is er de zesde van, noch tusschen een kleiner, noch tusschen een grooter getal dan dit, of hij is met hen, waar zij ook mochten zijn: en hij zal hun op den dag der opstanding verklaren, wat zij hebben gedaan; want God kent alle dingen.';
$t[8] = 'Hebt gij degenen niet opgemerkt, aan wie het ontzegd werd, verboden gesprekken te voeren, maar die nochtans terugkeerden tot hetgeen hun was verboden, en heimelijk onder elkander van zonde spraken en van vijandschap en van ongehoorzaamheid nopens den gezant? En als zij tot u komen, begroeten zij u met een groet, waarmede God u niet begroet, en zij zeggen spottenderwijze tot elkander: Zou God ons niet straffen voor hetgeen wij zeggen, indien deze man een profeet ware? De hel zal eene toereikende straf voor hen zijn; zij zullen die binnengaan om verbrand te worden, en dat zal een ongelukkig verblijf wezen.';
$t[9] = 'O ware geloovigen! als gij in het geheim met elkander spreekt, spreekt dan niet van zonde en vijandschap en ongehoorzaamheid opzichtens den gezant; en vreest God, voor wien gij zult worden verzameld.';
$t[10] = 'Waarlijk, de verboden gesprekken der ongeloovigen gaan van Satan uit, ten einde de ware geloovigen te grieven; maar niemand zal hen in het minst kunnen deren, tenzij met verlof van God: laat dus de geloovige op God vertrouwen.';
$t[11] = 'O ware geloovigen! als men u zegt: Maakt ruimte in de vergadering, maakt ruimte: God zal u groote ruimte in het paradijs schenken. En als u gezegd wordt: staat op, staat op; God zal degenen van u die gelooven, en hen aan welke kennis werd geschonken, doen oprijzen in een hoogen graad. En God is volkomen onderricht van hetgeen gij doet.';
$t[12] = 'O ware geloovigen! indien gij gaat om met den gezant te spreken, geeft dan aalmoezen, eer gij met hem spreekt; dit zal beter voor u zijn en reiner; maar indien gij niet hebt waarvan te geven, waarlijk, dan zal God genadig en barmhartig omtrent u zijn.';
$t[13] = 'Vreest gij aalmoezen te geven v&oacute;&oacute;r uw gesprek met den profeet, duchtende u te verarmen? Indien gij het niet doet, hetgeen God u zal vergeven, verricht dan ten minste het gebed, geeft de voorgeschreven (wettige) aalmoezen (de schatting), en gehoorzaamt God en zijn gezant in alle andere zaken; want God weet wel wat gij doet.';
$t[14] = 'Hebt gij degenen niet opgemerkt, die een volk tot hunne vrienden hebben genomen, op hetwelk God vertoornd is? Zij zijn van hunne partij noch van de uwe, en zij zweren voorbedachtelijk bij eene leugen.';
$t[15] = 'God heeft eene gestrenge straf voor hen gereed gemaakt; want datgene wat zij doen is slecht.';
$t[16] = 'Zij bedienen zich van hunne eeden als van een kleed, en zij hebben de menschen van Gods weg afgeleid.';
$t[17] = 'Noch hunne welvaart, noch hunne kinderen zullen hun bij God van nut zijn. Zij zullen de bewoners van het hellevuur zijn, eeuwig zullen zij daarin verblijven.';
$t[18] = 'Op een zekeren dag zal God hen allen opwekken; dan zullen zij bij hen zweren, zooals zij het thans bij u doen, denkende dat dit hun van dienst zal wezen. Zijn zij geene leugenaars?';
$t[19] = 'Satan heeft hen overmeesterd, en heeft hen de herdenking van God doen vergeten. Dezen vormen de partij van den duivel; en zal de partij des duivels niet tot verderf worden gedoemd?';
$t[20] = 'Waarlijk, zij die God en zijn gezant wederstand bieden, zullen onder de laagsten worden geplaatst.';
$t[21] = 'God heeft geschreven: waarlijk, ik en mijn gezant zullen overwinnen; want God is sterk en machtig.';
$t[22] = 'Gij zult onder degenen die in God en in den jongsten dag gelooven, geene menschen vinden, welke de ongeloovigen beminnen die God en zijn gezant we&ecirc;rstand bieden, al waren zij hunne vaders, of hunne zonen, of hunne broeders of hunne naaste betrekkingen. In de harten van dezen heeft God het geloof geschreven, en hij heeft hen met zijn geest gesterkt. Hij zal hen in tuinen, doorsneden met rivieren, leiden, om er voor eeuwig te verblijven. God is over hen voldaan, en zij zijn wel voldaan over hem. Dit is de partij van God; en zal de partij van God geen voorspoed genieten?';
?>