<?php
$t = array();
$t[1] = 'Alles wat in den hemel of op aarde is, verkondigt den lof van God, en hij is de Machtige, de Wijze.';
$t[2] = 'Hij was het, die degenen van het volk dat de schrift ontving welke niet geloofden, bij de eerste landverhuizing uit hunne woningen deed vertrekken. Gij dacht niet, dat zij van daar zouden gaan, en zij dachten, dat hunne sterkte hen tegen God zoude bijstaan. Maar Gods kastijding kwam over hen, van waar zij die niet verwacht hadden, en hij wierp schrik in hunne harten. Zij verwoestten hunne huizing met eigen handen en met de handen der ware geloovigen. Neemt dus een voorbeeld aan hen, o gij die oogen hebt!';
$t[3] = 'En indien God hen niet tot verbanning had gedoemd, zou hij hen zeker hebben uitgeroeid; en in de volgende wereld zullen zij de marteling van het hellevuur ondergaan.';
$t[4] = 'Dit geschiedt, omdat zij God en zijn gezant wederstand hebben geboden; en wie God we&ecirc;rstand biedt, waarlijk, die zal door God streng gestraft worden.';
$t[5] = 'De palmboomen welke gij nederhouwt, of die gij met hunne wortelen laat staan, werden nedergehouwen of bleven staan door den wil van God om de zondaren gerust te stellen.';
$t[6] = 'En wat den buit betreft van het volk, dat God geheel aan zijn gezant heeft geschonken, gij hebt daartegen noch paarden, noch kameelen aangevoerd; maar God geeft de heerschappij aan zijne gezanten over wien hij wil; want God is almachtig.';
$t[7] = 'De buit der bewoners van de steden die God aan zijn gezant heeft geschonken is aan God en zijn gezant verschuldigd, en aan hem, die tot de nabestaanden van den gezant behoort, en aan de weezen en aan den arme en aan den reiziger, opdat die niet immer in een kring zoude verdeeld worden, van diegenen uwer, welke rijk zijn. Neemt aan wat de profeet u zal geven, en onthoudt u van hetgeen hij u verbiedt, en vreest God; want God is gestreng in het kastijden.';
$t[8] = 'Ook behoort een deel aan de arme Mohajerin die van hunne huizen en hunne bezittingen werden beroofd, terwijl zij naar Gods gunst en naar zijn welgevallen streefden en God en zijn gezant bijstonden. Dit zijn de lieden der waarachtigheid.';
$t[9] = 'En zij die, v&oacute;&oacute;r hen, de stad Medina geheel bezaten en het geloof zonder beletsel beleden, beminnen dengeen, die tot hen is gevlucht, en vinden in hunne borsten geene begeerte naar datgene wat den Mohajerin werd gegeven, maar verkiezen die boven zich zelven, hoewel zij mede door nooddruftigheid worden gekweld. En hij die zich voor de gierigheid zijner eigene ziel behoedt, zal zeker voorspoed genieten.';
$t[10] = 'En zij die na hen zijn gekomen zeggen: O Heer! vergeef ons en onze broederen, die ons in het geloof zijn voorgegaan, en werp geen kwaden wil in onze harten, omtrent hen, die geloofd hebben: O Heer! Waarlijk, gij zijt medelijdend en genadig.';
$t[11] = 'Hebt gij degenen niet gezien, welke huichelachtig zijn. Zij zeggen tot hunne broeders, van degenen welke de schriften hebben ontvangen, en die niet gelooven: Waarlijk, indien gij uit uwe woningen wordt verdreven, zullen wij zekerlijk met u vertrekken; wij zullen nimmer iemand gehoorzamen als er sprake van u zal zijn, en indien gij wordt aangevallen, zullen wij u zekerlijk bijstaan. Maar God is getuige, dat zij leugenaars zijn.';
$t[12] = 'Waarlijk, indien zij verdreven worden, zullen dezen niet met hen heengaan, en indien zij aangevallen worden, zullen deze hen niet bijstaan en indien zij hen al in \'t eerst bijstaan, zullen zij hun de ruggen toewenden, en zij zullen niet ondersteund worden.';
$t[13] = 'Waarlijk, gij zijt sterker dan zij, uithoofde van de vrees, die door God in hunne borsten is geworpen. Dit is omdat zij lieden zonder doorzicht zijn.';
$t[14] = 'Zij zullen niet vereenigd tegen u strijden, behalve in versterkte steden of van achter muren. Hunne hevigheid in den oorlog onder elkander is groot: gij denkt dat zij vereenigd zijn, maar hunne harten zijn verdeeld. Dit is, omdat zij lieden zijn, die niet begrijpen willen.';
$t[15] = 'Gelijk degenen, die hen voorafgingen hebben zij het booze gevolg van hunne daden geproefd, en eene pijnlijke straf is hiernamaals voor hen gereed gemaakt.';
$t[16] = 'Zoo hebben de huichelaars de Joden bedrogen; gelijk de duivel, toen hij tot een mensch zeide: Wees een ongeloovige! En toen hij een ongeloovige was geworden, riep hij: Waarlijk, ik ben onschuldig aan u; want ik vrees God, den Heer van alle schepselen.';
$t[17] = 'Daarom zal het einde van hen zijn, dat zij in het hellevuur zullen verblijven, en dit zal de vergelding der onrechtvaardigen wezen.';
$t[18] = 'O ware geloovigen! vreest God. Dat iedere ziel zie, wat zij zich voor morgen gereed maakt, en vreest God; want God is welbekend met hetgeen gij doet.';
$t[19] = 'En weest niet als zij, die God hebben vergeten, en welke hij hunne eigenen zielen heeft doen vergeten: dit zijn de zondaren.';
$t[20] = 'De bewoners van het hellevuur en de bewoners van het paradijs zullen niet gelijk gesteld worden. De bewoners van het paradijs zijn zij, die gelukzaligheid genieten.';
$t[21] = 'Indien wij dezen Koran op een berg hadden nedergezonden, zoudt gij zeker gezien hebben, hoe die zich verootmoedigd had, en uit vrees voor God gespleten ware. Dit zijn de voorbeelden welke wij den mensch geven, opdat hij zou mogen overwegen.';
$t[22] = 'Hij is de God, buiten wien geen god is. Hij kent het zichtbare en het onzichtbare. Hij is de Goedertierene, de Barmhartige.';
$t[23] = 'Hij is God, buiten wien geen god is: de Koning, de Heilige, de Verlosser, de Getrouwe, de Beschermer, de Sterke, de Vermogende, de Verhevenste. God is verre verheven boven de afgoden, welke zij met hem vereenigen.';
$t[24] = 'Hij is de eenige God, de Schepper, de Maker, de Vormer. Hij heeft de meest uitmuntende namen. Alles wat in den hemel of op aarde is, prijst hem. Hij is de Machtige, de Wijze.';
?>