<?php
$t = array();
$t[1] = 'O profeet! waarom verbiedt gij wat God heeft vergund, daardoor trachtende uwe vrouwen te behagen. God is vergevensgezind en barmhartig';
$t[2] = 'God heeft u veroorloofd, uwe eeden in te trekken; en God is uwe meester en hij is alwetend en wijs.';
$t[3] = 'Toen de profeet eens eene zekere gebeurtenis als een geheim aan eene zijner vrouwen verhaalde, en toen zij dat aan eene ander mededeelde, en God het hem bekend maakte, gaf hij haar kennis van een gedeelte van hetgeen zij had gedaan, en vermeed, haar het andere gedeelte daarvan te verwijten. En toen hij haar daarmede had bekend gemaakt, zeide zij: Wie heeft u dit ondekt? Hij zeide: de wijze, de alwetende God heeft het mij ontdekt.';
$t[4] = 'Indien gij beiden tot God zijt gewend (want uwe harten hebben gewankeld), is het wel, maar indien gij tegen hem (den profeet) samenspant, waarlijk, dan is God zijn beschermer, en Gabri&euml;l en de rechtvaardigen, onder de gelooven en de engelen zijn mede zijne helpers.';
$t[5] = 'Indien hij van u scheidt, kan zijn Heer hem gemakkelijk in uwe plaats andere vrouwen, beter dan gij, geven; vrouwen die aan God onderworpen zijn; ware geloovigen, vroom, boetvaardig, gehoorzaam, de vasten in acht nemende, en zoowel die gehuwd zijn geweest, als maagden.';
$t[6] = 'O ware geloovigen! redt uwe zielen en die uwer gezinnen, van het vuur, dat door menschen en steenen wordt gevoed, waarover onvermurwbare en vreeselijke engelen zijn geplaatst, die God niet ongehoorzaam zijn, in hetgeen hij hun heeft bevolen; maar die volvoeren, wat hun werd geboden.';
$t[7] = 'O ongeloovigen! verontschuldig u niet op dezen dag, U zal zekerlijk vergolden worden hetgeen gij hebt gedaan.';
$t[8] = 'O ware geloovigen! wendt u tot God met een oprecht berouw, misschien wil uw Heer uwe slechte daden van u afnemen, en wil hij u toelaten in tuinen, met rivieren doorsneden, op den dag waarop God den profeet niet zal beschamen, of degenen die met hem geloofd hebben; hun licht zal voor hen uitgaan en aan hunne rechterhanden , en zij zullen zeggen: Heer! maak ons licht volmaakt en vergeef ons; want gij zijt almachtig.';
$t[9] = 'O profeet! tast de ongeloovigen met wapens aan, en de huichelaars met woorden, en behandel hen met gestrengheid; de hel zal hun verblijf zijn, en dat is eene ellendige woning.';
$t[10] = 'God stelt den ongeloovigen, als een voorbeeld, de vrouw van Noach en de vrouw van Lot voor; zij waren onder de heerschappij van twee onzer rechtvaardige dienaren, welke beiden door haar bedrogen werden. Daarom waren hare echtgenooten haar volstrekt niet van voordeel, voor het aangezicht van God, en er zal op den jongsten dag tot haar gezegd worden: Treedt het hellevuur binnen met hen die daar ingaan.';
$t[11] = 'God stelde ook de vrouw van Pharao als een voorbeeld aan hen die gelooven, toen zij zeide: Heer, bouw mij een huis bij u in het paradijs, verlos mij van Pharao en zijne daden, en bevrijd mij van de onrechtvaardigen.';
$t[12] = 'En Maria, de dochter van Imram, die hare kuischheid bewaarde, en in wier boezem wij onzen geest bliezen, en die in de woorden van haren Heer en in zijne schriften geloofde, en vroom en gehoorzaam was.';
?>