<?php
$t = array();
$t[1] = 'TROENDE! Pocka inte p&aring; uppm&auml;rksamhet f&ouml;r egen del, n&auml;r ni st&aring;r inf&ouml;r Gud och Hans S&auml;ndebud, men frukta Gud! Gud h&ouml;r allt, vet allt!';
$t[2] = 'Troende! Dr&auml;nk inte med era r&ouml;ster Profetens ord och h&ouml;j inte r&ouml;sten n&auml;r ni talar till honom, som ni g&ouml;r sinsemellan; annars kan det [goda] ni g&ouml;r g&aring; om intet utan att ni f&ouml;rst&aring;r [vad som sker]!';
$t[3] = 'De som s&auml;nker r&ouml;sten i S&auml;ndebudets n&auml;rvaro &auml;r de vars hj&auml;rtan Gud har gjort redo f&ouml;r gudsfruktan; f&ouml;r dem finns f&ouml;rl&aring;telse och en rik bel&ouml;ning.';
$t[4] = 'De flesta av dem som h&ouml;gljutt kallar p&aring; dig, n&auml;r du [Muhammad] befinner dig i de inre rummen, &auml;r m&auml;nniskor som inte t&auml;nker sig f&ouml;r.';
$t[5] = 'Det vore b&auml;st f&ouml;r dem om de gav sig till t&aring;ls tills du kommer ut till dem, men Gud &auml;r st&auml;ndigt f&ouml;rl&aring;tande, barmh&auml;rtig.';
$t[6] = 'TROENDE! Om en m&auml;nniska som inte &aring;tnjuter stadgat rykte [f&ouml;r tillf&ouml;rlitlighet] kommer till er med en upplysning, f&ouml;rs&ouml;k d&aring; reda ut [vad som &auml;r sanning], s&aring; att ni inte utan att inse det tillfogar [andra] skada och sedan m&aring;ste &aring;ngra vad ni gjort.';
$t[7] = 'Och t&auml;nk p&aring; att det &auml;r Guds S&auml;ndebud ni har mitt ibland er; om han var g&aring;ng ni l&auml;gger fram ett problem lyssnade till era [&aring;sikter], kunde det v&aring;lla er sv&aring;righeter. Men Gud har gjort tron dyrbar f&ouml;r er och visat era hj&auml;rtan dess sk&ouml;nhet och Han har ingjutit i er avsky mot f&ouml;rnekandet av sanningen och mot all synd och olydnad. De [som beskrivs p&aring; detta s&auml;tt] &auml;r de som f&ouml;ljer den raka v&auml;gen';
$t[8] = 'tack vare Guds n&aring;d och Hans godhet; Gud &auml;r allvetande, vis.';
$t[9] = 'Om tv&aring; grupper av troende skulle r&aring;ka i delo med varandra, f&ouml;rs&ouml;k d&aring; m&auml;kla fred mellan dem, men om den ena [gruppen] grovt kr&auml;nker den andras r&auml;tt, ingrip d&aring; mot de skyldiga tills de fogar sig efter Guds bud; och, om de fogar sig, medla d&aring; mellan dem b&aring;da med r&auml;ttvisa och opartiskhet. Gud &auml;lskar de opartiska.';
$t[10] = 'De troende &auml;r br&ouml;der. F&ouml;rsona d&auml;rf&ouml;r tv&aring; br&ouml;der [som &auml;r oense] och frukta Gud - kanske skall ni erfara barmh&auml;rtighet.';
$t[11] = 'TROENDE! M&auml;n skall inte g&ouml;ra narr av andra m&auml;n - det kan h&auml;nda att de som de g&ouml;r narr av &auml;r b&auml;ttre &auml;n de sj&auml;lva. Och kvinnor skall inte g&ouml;ra narr av andra kvinnor - det kan h&auml;nda att de som de g&ouml;r narr av &auml;r b&auml;ttre &auml;n de sj&auml;lva. Och f&ouml;rtala inte varandra och ge inte varandra skamliga &ouml;knamn; det &auml;r gement, troende emellan, att anv&auml;nda &ouml;knamn som leder tanken till synd och lastbarhet, och de som [beter sig s&aring; och] inte &aring;ngrar det g&ouml;r sig skyldiga till en sv&aring;r or&auml;tt.';
$t[12] = 'Troende! Undvik i m&ouml;jligaste m&aring;n att g&ouml;ra l&ouml;sa antaganden [och f&ouml;rmoda det ena och det andra om varandra]; det kan ligga synd i s&aring;dana antaganden. Och spionera inte p&aring; varandra och tala inte illa om andra bakom deras rygg. [Eller] skulle n&aring;gon av er vilja &auml;ta sin d&ouml;de broders k&ouml;tt? Nej, den [tanken] skulle ni finna v&auml;mjelig! Och frukta Gud! I Sin barmh&auml;rtighet g&aring;r Gud den &aring;ngerfulle till m&ouml;tes!';
$t[13] = 'M&auml;nniskor! Vi har skapat er av en man och en kvinna, och Vi har samlat er i folk och stammar f&ouml;r att ni skall l&auml;ra k&auml;nna varandra. Inf&ouml;r Gud &auml;r den av er den b&auml;ste vars gudsfruktan &auml;r djupast. Gud vet allt, &auml;r underr&auml;ttad om allt.';
$t[14] = '&Ouml;KENARABERNA s&auml;ger: &rdquo;Vi har blivit troende.&rdquo; Svara [dem, Muhammad]: &rdquo;[&Auml;nnu] &auml;n ni inte troende &ndash; s&auml;g hellre: \'Vi har underkastat oss Guds vilja\'! &Auml;nnu har inte [sann] tro vunnit insteg i era hj&auml;rtan. Men om ni [med &auml;rligt upps&aring;t] lyder Gud och Hans S&auml;ndebud skall Han inte l&aring;ta er g&aring; miste om n&aring;gon del av [l&ouml;nen f&ouml;r] era handlingar; Gud &auml;r st&auml;ndigt f&ouml;rl&aring;tande, barmh&auml;rtig.&rdquo;';
$t[15] = 'Inga andra &auml;n de som tror p&aring; Gud och Hans S&auml;ndebud och som inte vacklar i tron och de som k&auml;mpar f&ouml;r Guds sak med sina &auml;godelar och med livet som insats &auml;r [verkliga] troende; det &auml;r de som &auml;r uppriktiga [i sin bek&auml;nnelse av tron].';
$t[16] = 'S&auml;g: &quot;Vill ni underr&auml;tta Gud om [beskaffenheten av] er tro, fast&auml;n det &auml;r Gud som k&auml;nner allt det som himlarna rymmer och det som jorden b&auml;r? Gud har vetskap om allt!&quot;';
$t[17] = 'De [tror att de] har gett dig n&aring;got [Muhammad] n&auml;r de underkastade sig Guds vilja. S&auml;g: &quot;Er underkastelse under Guds vilja &auml;r inte en g&aring;va till mig; nej, det &auml;r en Guds v&auml;lg&auml;rning mot er att Han har velat leda er till tron - om er bek&auml;nnelse &auml;r sann.&quot;';
$t[18] = 'Gud k&auml;nner himlarnas och jordens dolda verklighet - och Gud ser allt vad ni g&ouml;r.';
?>