<?php
$t = array();
$t[1] = 'GUD har helt visst h&ouml;rt hennes ord, hon som v&auml;djar till dig i [tvisten med] sin man och som b&ouml;nfaller Gud om hj&auml;lp. Och Gud h&ouml;r vad ni b&aring;da har haft att anf&ouml;ra - Gud &auml;r Den som h&ouml;r allt, ser allt.';
$t[2] = 'De av er som [h&auml;danefter vill] f&ouml;rskjuta sina hustrur [b&ouml;r inse att de] inte &auml;r deras m&ouml;drar; deras m&ouml;drar &auml;r de som f&ouml;dde dem och inga andra. Orden [som yttras enligt denna sed] strider mot rim och reson och &auml;r en klar l&ouml;gn. Men Gud utpl&aring;nar och f&ouml;rl&aring;ter mycken synd.';
$t[3] = 'De som p&aring; detta s&auml;tt f&ouml;rskjuter sin hustru men tar tillbaka sitt ord skall [som bot] sk&auml;nka en slav friheten, innan samlivet [med den f&ouml;rskjutna] f&aring;r &aring;terupptas. Detta &auml;r vad Gud f&ouml;reskriver f&ouml;r er. Gud &auml;r underr&auml;ttad om vad ni g&ouml;r.';
$t[4] = 'De som inte [&auml;r i st&aring;nd att lyda denna f&ouml;reskrift] skall fasta tv&aring; m&aring;nader i f&ouml;ljd, innan [man och hustru] f&aring;r &aring;teruppta samlivet; och de som inte f&ouml;rm&aring;r [fasta] skall ge mat &aring;t sextio n&ouml;dst&auml;llda; p&aring; s&aring; s&auml;tt f&aring;r ni [visa] er tro p&aring; Gud och Hans S&auml;ndebud. Detta &auml;r Guds f&ouml;reskrifter, och de som inte lyder [dem] har ett pl&aring;gsamt straff [att v&auml;nta].';
$t[5] = 'De som s&auml;tter sig upp mot Gud och Hans S&auml;ndebud skall f&ouml;r&ouml;dmjukas s&aring;som deras f&ouml;reg&aring;ngare blev f&ouml;r&ouml;dmjukade, eftersom V&aring;ra budskap &auml;r otvetydiga. De som f&ouml;rnekar sanningen har ett f&ouml;rnedrande straff [att v&auml;nta]';
$t[6] = 'den Dag d&aring; Gud skall uppv&auml;cka dem alla till nytt liv och l&aring;ta dem veta vad deras handlingar [var v&auml;rda]. Gud h&aring;ller r&auml;kning p&aring; det som de sj&auml;lva har gl&ouml;mt. Gud &auml;r vittne till allt som sker.';
$t[7] = 'HAR DU inte klart f&ouml;r dig att Gud k&auml;nner allt det som himlarna rymmer och det som jorden b&auml;r? N&auml;r tre samlas till en hemlig &ouml;verl&auml;ggning &auml;r Han den fj&auml;rde, och om fem samlas &auml;r Han den sj&auml;tte; och vare sig de &auml;r f&auml;rre eller flera &auml;r Han med dem, var de &auml;n befinner sig. Till sist, p&aring; Uppst&aring;ndelsens dag, skall Han l&aring;ta dem veta vad deras handlingar [var v&auml;rda]. Gud har k&auml;nnedom om allt.';
$t[8] = 'Har du inte lagt m&auml;rke till, hur de som &aring;lagts att avh&aring;lla sig fr&aring;n hemliga &ouml;verl&auml;ggningar, &aring;terg&aring;r till det f&ouml;rbjudna och &ouml;verl&auml;gger i hemlighet om syndiga handlingar och om att motarbeta och trotsa Profeten? N&auml;r de kommer till dig [Muhammad], h&auml;lsar de dig med ord som Gud inte har anbefallt, och s&auml;ger till sig sj&auml;lva: &quot;Varf&ouml;r straffar inte Gud oss f&ouml;r det vi s&auml;ger?&quot; Helvetet &auml;r straff nog f&ouml;r dem; i dess eld skall de brinna - ett fasansfullt slut!';
$t[9] = 'Troende! Om ni &ouml;verl&auml;gger i avskildhet om era angel&auml;genheter, undvik d&aring; allt som kan ligga synd, illvilja och trots mot S&auml;ndebudet n&auml;ra. Nej, &ouml;verl&auml;gg om hur ni skall verka f&ouml;r st&ouml;rre fromhet och lydnad f&ouml;r Gud - och frukta Gud! [En Dag] skall ni f&ouml;ras samman inf&ouml;r Honom.';
$t[10] = 'Hemliga &ouml;verl&auml;ggningar &auml;r n&aring;got som Dj&auml;vulen funnit p&aring; f&ouml;r att f&ouml;rarga och pl&aring;ga de troende; men han kan inte v&aring;lla dem skada utan Guds till&aring;telse; l&aring;t d&auml;rf&ouml;r de troende s&auml;tta sin lit till Gud!';
$t[11] = 'TROENDE! N&auml;r ni under era sammankomster uppmanas &quot;Ge plats!&quot; - ge plats; d&aring; skall Gud bereda plats &aring;t er [i Sin n&aring;d]. Och n&auml;r ni uppmanas &quot;Res er!&quot; - res er [utan att dr&ouml;ja]. D&aring; skall Gud upph&ouml;ja dem bland er som &auml;r [sanna] troende och dem som har f&aring;tt kunskap, till h&ouml;gre rang. Gud &auml;r underr&auml;ttad om vad ni g&ouml;r.';
$t[12] = 'TROENDE! Om ni vill f&aring; ett samtal i avskildhet med S&auml;ndebudet, ge d&aring; en offerg&aring;va till de beh&ouml;vande f&ouml;re ert samtal; det &auml;r f&ouml;r ert eget b&auml;sta och det leder till st&ouml;rre renhet [i ert upps&aring;t]. Men den som inte har [m&ouml;jlighet till detta, skall finna att] Gud &auml;r st&auml;ndigt f&ouml;rl&aring;tande, barmh&auml;rtig.';
$t[13] = 'Om f&ouml;reskriften att inf&ouml;r ert samtal ge en offerg&aring;va v&aring;llar er bekymmer och ni har underl&aring;tit att [f&ouml;lja den] och Gud i Sin n&aring;d f&ouml;rl&aring;ter er, [n&ouml;j er d&aring; med att samvetsgrant] f&ouml;rr&auml;tta b&ouml;nen och betala allmoseskatten; och lyd Gud och Hans S&auml;ndebud; Gud &auml;r underr&auml;ttad om vad ni g&ouml;r.';
$t[14] = 'HAR DU inte lagt m&auml;rke till de [hycklare] som s&ouml;ker st&ouml;d hos dem som har drabbats av Guds vrede [d&auml;rf&ouml;r att de f&ouml;rnekar sanningen]? De h&ouml;r inte samman med er och inte heller med dem och de sv&auml;r p&aring; det som de vet &auml;r en l&ouml;gn.';
$t[15] = 'Gud har ett str&auml;ngt straff i beredskap f&ouml;r dem; vad de g&ouml;r &auml;r ont.';
$t[16] = 'De sv&auml;r sina eder f&ouml;r att skydda sig och p&aring; s&aring; s&auml;tt leder de [andra] bort fr&aring;n Guds v&auml;g. De har [att v&auml;nta] ett f&ouml;rnedrande straff.';
$t[17] = 'Varken deras [betydande] jordiska &auml;godelar eller deras [m&aring;nga] s&ouml;ner kan ge dem skydd mot Gud; deras arvedel &auml;r Elden och d&auml;r skall de f&ouml;rbli till evig tid.';
$t[18] = 'Den Dag d&aring; Gud uppv&auml;cker dem alla fr&aring;n de d&ouml;da, kommer de att bedyra och sv&auml;ra inf&ouml;r Gud [att de hade underkastat sig Hans vilja] liksom de nu bedyrar och sv&auml;r inf&ouml;r er i tron att de uppn&aring;r n&aring;got [med sina eder]. Nej, de &auml;r l&ouml;gnens verkliga m&auml;stare!';
$t[19] = 'Dj&auml;vulen har helt tagit bef&auml;let &ouml;ver dem och kommit dem att gl&ouml;mma att &aring;kalla Gud. [De &auml;r Dj&auml;vulens trogna och] Dj&auml;vulens trogna &auml;r sannerligen f&ouml;rlorarna!';
$t[20] = 'De som trotsar Gud och Hans S&auml;ndebud kommer att h&ouml;ra till de el&auml;ndigaste [p&aring; Uppst&aring;ndelsens dag].';
$t[21] = 'Gud har slagit fast: &quot;Helt visst &auml;r det Jag, Jag och Mina s&auml;ndebud, som skall segra!&quot; - Hos Gud finns all styrka, all makt!';
$t[22] = 'Du kan inte finna [s&aring;dana] m&auml;nniskor som tror p&aring; Gud och den Yttersta dagen och som [samtidigt] s&ouml;ker v&auml;nskap med dem som trotsar Gud och Hans S&auml;ndebud - inte ens om det g&auml;ller deras egen fader eller son eller broder eller [andra] som st&aring;r dem n&auml;ra. Det &auml;r i deras hj&auml;rtan som Han har skrivit in tron och de som Han har st&auml;rkt med Sin ande, och dem skall Han f&ouml;ra till lustg&aring;rdar, vattnade av b&auml;ckar, d&auml;r de skall f&ouml;rbli till evig tid. Gud &auml;r n&ouml;jd med dem och de &auml;r n&ouml;jda [d&auml;r de njuter] Hans [g&aring;vor]. De &auml;r Guds trogna och Guds trogna skall det sannerligen g&aring; v&auml;l i h&auml;nder!';
?>