<?php
$t = array();
$t[1] = 'ALLT det som himlarna rymmer och det som jorden b&auml;r prisar Gud; Han &auml;r den Allsm&auml;ktige, den Vise.';
$t[2] = 'Det &auml;r Han som f&ouml;rm&aring;dde dem av efterf&ouml;ljarna av &auml;ldre tiders uppenbarelser som f&ouml;rnekade sanningen, att &ouml;verge sina hem vid den f&ouml;rsta [stora] m&ouml;nstringen. Ni [troende] tvivlade p&aring; att de skulle ge sig av [utan strid] och de trodde att de var v&auml;l skyddade mot Guds makt i sina f&auml;sten. Men Guds h&aring;rda slag drabbade dem fr&aring;n ett h&aring;ll som de inte hade r&auml;knat med, och Han injagade [s&aring;dan] skr&auml;ck i deras hj&auml;rtan att de raserade sina hem med egna h&auml;nder - och de troende [rev vad som &aring;terstod]. L&auml;r av detta, ni som ser klart!';
$t[3] = 'Om Gud inte hade beslutat att de skulle f&ouml;rvisas skulle Han ha l&aring;tit [ytterligare] lidande drabba dem i denna v&auml;rld. Men i det kommande livet [v&auml;ntar dem] Eldens straff';
$t[4] = 'eftersom de satte sig upp mot Gud och Hans S&auml;ndebud och den som s&auml;tter sig upp emot Gud [skall f&aring; erfara att] Gud straffar med str&auml;nghet.';
$t[5] = 'N&auml;r ni [troende] h&ouml;gg ned deras palmer eller l&auml;t dem st&aring;, [skedde allt] enligt Guds vilja, och f&ouml;r att f&ouml;rnedra dem som hade f&ouml;rh&auml;rdat sig i olydnad och trots.';
$t[6] = '[Gl&ouml;m inte att] ni varken har beh&ouml;vt sporra h&auml;st eller kamel f&ouml;r att vinna det byte [som ni tog fr&aring;n fienden och] som Gud har &ouml;verl&auml;mnat till Sitt S&auml;ndebud. Gud l&auml;gger makten &ouml;ver dem Han vill i Sina s&auml;ndebuds h&auml;nder; Gud &auml;r allsm&auml;ktig.';
$t[7] = 'Det som Gud anvisar Sitt S&auml;ndebud av [det byte som tagits utan krig] av st&auml;dernas folk tillh&ouml;r Gud och S&auml;ndebudet, [hans] n&auml;rmaste, de faderl&ouml;sa och de beh&ouml;vande och vandringsmannen. Det f&aring;r inte bli [en handelsvara], som cirkulerar mellan dem av er som lever i v&auml;lst&aring;nd. Tag allts&aring; emot vad [Hans] S&auml;ndebud ger er [av detta] och avst&aring; [villigt] fr&aring;n det som han nekar er; och frukta Gud; Gud straffar med str&auml;nghet.';
$t[8] = 'Bland dem [som skall f&aring; del av bytet &auml;r] de fattiga och utvandrarna som tvingats att l&auml;mna sina hem och sin egendom och &ouml;verge ondskans rike f&ouml;r att s&ouml;ka Guds n&aring;d och Hans v&auml;lbehag och som ger sina bidrag [i kampen] f&ouml;r Guds och Hans S&auml;ndebuds sak. De &auml;r de som har en sann och uppriktig [tro].';
$t[9] = '[Till dem h&ouml;r ocks&aring;] de som var bofasta i staden och antog tron f&ouml;re [utvandrarnas ankomst, och som] med k&auml;rlek bem&ouml;tte alla som s&ouml;kte tillflykt hos dem och inte missunnade dem vad de fick ta emot, utan tv&auml;rtom gav dem f&ouml;retr&auml;de, trots att de sj&auml;lva m&aring;ste g&ouml;ra uppoffringar. De som v&auml;rjer sig f&ouml;r girighetens [frestelser] - dem skall det g&aring; v&auml;l i h&auml;nder.';
$t[10] = 'De som kommer efter dem ber: &quot;Herre, ge oss Din f&ouml;rl&aring;telse och f&ouml;rl&aring;t v&aring;ra br&ouml;der som g&aring;tt f&ouml;re oss i tron, och l&aring;t inte ovilja mot [n&aring;gon] troende bli kvar i v&aring;ra hj&auml;rtan! Herre! Du &ouml;mmar, full av barmh&auml;rtighet, [f&ouml;r Dina tj&auml;nare]!&quot;';
$t[11] = 'HAR DU inte insett [vad] hycklarna s&auml;ger till sina br&ouml;der, dem bland efterf&ouml;ljarna av &auml;ldre tiders uppenbarelser som f&ouml;rnekar sanningen? &quot;Om ni blir bortdrivna lovar vi att l&auml;mna [staden] med er och vi kommer aldrig att f&ouml;lja n&aring;gon [som vill g&aring; h&aring;rt fram] mot er; och om ni blir angripna skall vi helt s&auml;kert st&aring; p&aring; er sida.&quot; Men Gud vittnar att de ljuger.';
$t[12] = 'Om [f&ouml;rnekarna] drivs bort kommer [hycklarna] med s&auml;kerhet inte att g&aring; med dem, och om de angrips kommer [hycklarna] inte att sluta upp vid deras sida; men kommer de [&auml;nd&aring;] till deras hj&auml;lp, g&ouml;r de [snart] helt om och flyr och s&aring; blir [f&ouml;rnekarna] till sist ensamma.';
$t[13] = 'Ja, de hyser l&aring;ngt st&ouml;rre fruktan f&ouml;r er [troende] &auml;n f&ouml;r Gud; de &auml;r n&auml;mligen m&auml;nniskor som alls ingenting f&ouml;rst&aring;r.';
$t[14] = 'De kommer aldrig att k&auml;mpa i samlad trupp mot er om det inte sker fr&aring;n [st&auml;llningar i] bef&auml;sta st&auml;der eller bakom murar. Inb&ouml;rdes &auml;r de h&auml;tska fiender. Det &auml;r l&auml;tt att tro att de h&aring;ller samman, men i sitt inre &auml;r de splittrade [utom i sitt hat mot de troende]; de &auml;r m&auml;nniskor som inte anv&auml;nder sitt f&ouml;rst&aring;nd.';
$t[15] = 'Liksom de som en kort tid f&ouml;re dem fick k&auml;nna p&aring; [de onda] f&ouml;ljderna av sina handlingar, m&aring;ste de utst&aring; sv&aring;ra lidanden [ocks&aring; i n&auml;sta liv].';
$t[16] = 'Se hur Dj&auml;vulen [beter sig]: f&ouml;rst s&auml;ger han till m&auml;nniskan: &quot;F&ouml;rneka sanningen!&quot; och n&auml;r hon f&ouml;rnekar sanningen, s&auml;ger han: &quot;Jag &auml;r inte ansvarig f&ouml;r dig; jag fruktar Gud, v&auml;rldarnas Herre!&quot;';
$t[17] = 'Och slutet f&ouml;r b&aring;da &auml;r Elden, d&auml;r de skall f&ouml;rbli till evig tid; s&aring;dan &auml;r syndarnas l&ouml;n.';
$t[18] = 'TROENDE! Frukta Gud, och t&auml;nk p&aring; vad ni s&auml;nder framf&ouml;r er, var och en, till morgondagen! Ja, frukta Gud! Han &auml;r v&auml;l underr&auml;ttad om vad ni g&ouml;r.';
$t[19] = 'Var inte som de som gl&ouml;mmer Gud och som Han l&aring;ter gl&ouml;mma sj&auml;lens [v&auml;lf&auml;rd]; det &auml;r de som har f&ouml;rh&auml;rdat sig i synd och trots.';
$t[20] = 'De som har Elden till arvedel kan inte j&auml;mf&ouml;ras med dem som &auml;rver paradiset; paradisets arvtagare &auml;r de som har vunnit den stora segern.';
$t[21] = 'OM VI hade uppenbarat denna Koran f&ouml;r ett berg, skulle du helt s&auml;kert ha sett det r&auml;mna av fruktan f&ouml;r Gud. S&aring;dana liknelser framst&auml;ller Vi f&ouml;r m&auml;nniskorna f&ouml;r att st&auml;mma dem till eftertanke.';
$t[22] = 'HAN &auml;r Gud; ingen gudom finns utom Han! Han k&auml;nner allt det som &auml;r dolt f&ouml;r m&auml;nniskor liksom det som de kan bevittna - Han, den N&aring;derike, den Barmh&auml;rtige.';
$t[23] = 'Han &auml;r Gud; ingen gudom finns utom Han, Konungen, den Helige, Han [som sk&auml;nker] fred, Han som [v&auml;cker och vidmakth&aring;ller] tron, Han som vakar [&ouml;ver uppenbarelsen], den M&auml;ktige, Han som betvingar och &aring;teruppr&auml;ttar, Han vars storhet [ingen kan fatta]! Stor &auml;r Gud i Sin h&auml;rlighet, fj&auml;rran fr&aring;n allt som [m&auml;nniskor] vill s&auml;tta vid Hans sida!';
$t[24] = 'Han &auml;r Gud, Skaparen, som &auml;r upphovet till allt och som ger allt dess slutliga form. Hans &auml;r fullkomlighetens sk&ouml;na namn; allt och alla i himlarna och p&aring; jorden prisar Honom - Han &auml;r den Allsm&auml;ktige, den Vise.';
?>