<?php
$t = array();
$t[1] = 'TROENDE! Tag inte Mina fiender - de &auml;r ocks&aring; era fiender - till bundsf&ouml;rvanter som ni sk&auml;nker v&auml;nskap och tillgivenhet, [m&auml;nniskor som] har avvisat den sanning som ni har f&aring;tt del av, och som har jagat bort S&auml;ndebudet och er [sj&auml;lva fr&aring;n era hem] p&aring; grund av er tro p&aring; Gud, er Herre! Om ni har valt att k&auml;mpa f&ouml;r Min sak och str&auml;var efter [att vinna] Mitt v&auml;lbehag, [tag dem d&aring; inte till v&auml;nner] som ni i hemlighet visar tillgivenhet. Jag har full k&auml;nnedom om det som ni vill d&ouml;lja liksom om det som ni g&ouml;r &ouml;ppet. De bland er som handlar s&aring; har avvikit fr&aring;n den raka v&auml;gen.';
$t[2] = 'Om de fick ta bef&auml;let &ouml;ver er skulle de &ouml;ppet visa er sin fiendskap och lyfta sina h&auml;nder mot er och l&aring;ta sina tungor l&ouml;pa i onda avsikter; ja, de skulle vilja att [ocks&aring;] ni f&ouml;rnekade sanningen.';
$t[3] = 'Varken era anf&ouml;rvanter eller era s&ouml;ner skall vara er till hj&auml;lp p&aring; Uppst&aring;ndelsens dag, d&aring; [Gud] skall d&ouml;ma mellan er. Gud ser vad ni g&ouml;r.';
$t[4] = 'Ett gott f&ouml;red&ouml;me har ni i Abraham och de som f&ouml;ljde honom, n&auml;r de sade till sina landsm&auml;n: &quot;Vi &auml;r inte ansvariga f&ouml;r er och f&ouml;r det som ni dyrkar i Guds st&auml;lle och vi tar avst&aring;nd fr&aring;n er. Fiendskap och hat skall r&aring;da mellan oss och er &auml;nda till dess ni tror p&aring; den Ende Guden.&quot; [Men tag] inte [exempel av] Abraham n&auml;r han sade till sin fader: &quot;Jag lovar att be [Gud] ge dig Sin f&ouml;rl&aring;telse; men jag kan inte av Gud utverka n&aring;gon [lindring i ditt straff].&quot; [Abraham och de som f&ouml;ljde honom bad:] &quot;Herre! Till Dig s&auml;tter vi v&aring;r lit, till Dig v&auml;nder vi oss i &aring;nger [&ouml;ver v&aring;ra synder] och Du &auml;r m&aring;let f&ouml;r v&aring;r f&auml;rd!';
$t[5] = 'Herre! G&ouml;r oss inte till [Ditt redskap n&auml;r] Du vill s&auml;tta f&ouml;rnekarna av sanningen p&aring; prov! Och Herre! F&ouml;rl&aring;t oss [v&aring;ra synder]! Du &auml;r den Allsm&auml;ktige, den Vise!&quot;';
$t[6] = 'I dem har ni ett gott f&ouml;red&ouml;me, [ett f&ouml;red&ouml;me] f&ouml;r den som ser fram mot [m&ouml;tet med] Gud och den Yttersta dagen med hopp [och fruktan]. Och den som v&auml;nder ryggen [&aring;t Gud b&ouml;r t&auml;nka p&aring; att] Gud &auml;r Den som &auml;r Sig sj&auml;lv nog, Den som allt lov och pris tillkommer.';
$t[7] = 'Kanske skall Gud i Sin allmakt l&aring;ta v&auml;nskap uppst&aring; mellan er och dem som ni nu ser som era fiender; Gud &auml;r st&auml;ndigt f&ouml;rl&aring;tande, barmh&auml;rtig.';
$t[8] = 'Gud f&ouml;rbjuder er inte att visa godhet mot dem som inte bek&auml;mpar er p&aring; grund av [er] tro och inte driver ut er ur era hem, och [Han f&ouml;rbjuder er inte] att bem&ouml;ta dem med r&auml;ttvisa och opartiskhet - Gud &auml;lskar de opartiska.';
$t[9] = 'Det &auml;r inga andra &auml;n de som bek&auml;mpar er p&aring; grund av [er] tro och som vill driva bort er fr&aring;n era hem eller hj&auml;lper [dem som vill] driva bort er, vilkas skydd och v&auml;nskap Gud f&ouml;rbjuder er att s&ouml;ka. De som s&ouml;ker deras v&auml;nskap och skydd har beg&aring;tt or&auml;tt mot sig sj&auml;lva!';
$t[10] = 'TROENDE! N&auml;r troende kvinnor som har utvandrat kommer till er, f&ouml;rh&ouml;r dem! Ingen utom Gud k&auml;nner deras tro, men om ni har &ouml;vertygat er om att de &auml;r troende, s&auml;nd d&aring; inte tillbaka dem till f&ouml;rnekarna av sanningen; deras m&auml;n har inte [l&auml;ngre] r&auml;tt att leva med dem och de har inte r&auml;tt att leva med sina m&auml;n. Men ge tillbaka till m&auml;nnen vad [brudg&aring;van] har kostat dem. Och ni beg&aring;r ingen synd om ni sedan tar dem till hustrur efter att ha gett dem deras brudg&aring;va. H&aring;ll inte fast vid det &auml;ktenskapliga bandet med kvinnor som f&ouml;rnekar sanningen; beg&auml;r att f&aring; tillbaka det som ni har gett [dem som brudg&aring;va], och l&aring;t dem [vars hustrur g&aring;r &ouml;ver till er] beg&auml;ra tillbaka det som de har gett ut [f&ouml;r sina hustrur]. Detta &auml;r Guds dom; Han d&ouml;mer [r&auml;ttvist] mellan er [och de icke-troende]. Gud &auml;r allvetande, vis.';
$t[11] = 'Och om [ni lider en f&ouml;rlust genom att] hustrun till n&aring;gon av de troende l&auml;mnar honom och &aring;terg&aring;r till f&ouml;rnekarna och ni kan g&ouml;ra en motsvarande vinst, ge d&aring; den vars hustru &ouml;vergett honom motv&auml;rdet till vad han gett [henne i brudg&aring;va] och frukta Gud, som ni tror p&aring;!';
$t[12] = 'Profet! N&auml;r troende kvinnor kommer till dig f&ouml;r att avl&auml;gga trohetsed - [och lovar] att inte s&auml;tta n&aring;got, vad det &auml;n &auml;r, vid Guds sida, att inte stj&auml;la, att inte beg&aring; &auml;ktenskapsbrott, att inte d&ouml;da sina egna barn, att inte sprida f&ouml;rtal som de sj&auml;lva diktat upp och att aldrig v&auml;gra dig lydnad i det som &auml;r r&auml;tt och rimligt - tag d&aring; emot deras trohetsed och be Gud f&ouml;rl&aring;ta dem deras synder; Gud &auml;r st&auml;ndigt f&ouml;rl&aring;tande, barmh&auml;rtig.';
$t[13] = 'TROENDE! S&ouml;k inte v&auml;nskap och skydd hos dem som har drabbats av Guds vrede! De hoppas inte p&aring; det eviga livet, liksom de som [helt] f&ouml;rnekar sanningen inte hoppas [f&aring; &aring;terse] dem som [de har f&ouml;ljt till graven].';
?>