<?php
$t = array();
$t[1] = 'PROFET! N&auml;r n&aring;gon av er har f&ouml;r avsikt att skilja sig fr&aring;n sin hustru, skall han [iaktta] den f&ouml;reskrivna v&auml;ntetiden och ber&auml;kna denna tid [med all noggrannhet]. Och frukta Gud, er Herre! Mannen f&aring;r inte tvinga [hustrun] att l&auml;mna hemmet och hon skall inte heller [sj&auml;lvmant] l&auml;mna det annat &auml;n om hon gjort sig skyldig till en grovt oanst&auml;ndig [eller annan f&ouml;rkastlig] handling. Dessa &auml;r de regler som Gud [har f&ouml;reskrivit], och den som &ouml;vertr&auml;der dessa av Gud [givna] regler har beg&aring;tt or&auml;tt mot sig sj&auml;lv; det &auml;r n&auml;mligen m&ouml;jligt - om det kan du ingenting veta - att Gud efter det [som varit] l&aring;ter ett nytt l&auml;ge uppst&aring;.';
$t[2] = '[N&auml;r n&aring;gon av er skilt sig fr&aring;n sin hustru] och hennes v&auml;ntetid n&auml;rmar sig sitt slut, skall han antingen h&aring;lla henne kvar eller ocks&aring; l&aring;ta henne g&aring;, allt i hedersamma former. Och tag tv&aring; r&auml;ttsinniga m&auml;nniskor ur er krets till vittnen, och avge sj&auml;lva vittnesm&aring;l inf&ouml;r Gud! Denna maning riktas till alla som tror p&aring; Gud och den Yttersta dagen. Gud visar var och en som fruktar Honom en utv&auml;g ur [alla sv&aring;righeter]';
$t[3] = 'och s&ouml;rjer f&ouml;r honom p&aring; ett s&auml;tt som han inte kan f&ouml;rutse; och den som litar till Gud beh&ouml;ver inget annat [st&ouml;d]. Gud n&aring;r alltid Sitt syfte [och] Gud har fastst&auml;llt ett m&aring;tt f&ouml;r allt.';
$t[4] = 'Om ni tvekar om [vad som g&auml;ller] dem av era kvinnor, vilkas m&aring;nadsbl&ouml;dningar helt har upph&ouml;rt, &auml;r deras v&auml;ntetid tre m&aring;nader, och samma tid g&auml;ller dem vars bl&ouml;dningar har uteblivit. Och de som &auml;r havande skall inv&auml;nta barnets f&ouml;delse. Och f&ouml;r var och en som fruktar Honom g&ouml;r Gud uppgiften l&auml;tt;';
$t[5] = 'detta &auml;r vad Gud befaller er genom Sin uppenbarelse. Och f&ouml;r den som fruktar Honom skall Gud utpl&aring;na hans d&aring;liga handlingar och &ouml;ka hans bel&ouml;ning.';
$t[6] = 'L&aring;t [den hustru som inv&auml;ntar skilsm&auml;ssa] leva under samma villkor som ni sj&auml;lva inom ramen f&ouml;r era m&ouml;jligheter, och g&ouml;r inte livet sv&aring;rt f&ouml;r henne med inskr&auml;nkningar [av olika slag]. Om hon &auml;r havande, s&ouml;rj d&aring; f&ouml;r hennes uppeh&auml;lle tills barnet har f&ouml;tts, och ge henne sk&auml;lig ers&auml;ttning om hon ammar ert [barn]; och samr&aring;d med henne i godo [om barnets b&auml;sta] p&aring; brukligt s&auml;tt. Men uppst&aring;r sv&aring;righeter, anst&auml;ll d&aring; n&aring;gon som ammar [barnet] &aring;t er.';
$t[7] = 'Den f&ouml;rm&ouml;gne skall s&ouml;rja [f&ouml;r det som nu har sagts] med sin rikedom, och den som lever under knappa f&ouml;rh&aring;llanden skall avst&aring; [vad han kan] av det som Gud har gett honom f&ouml;r hans f&ouml;rs&ouml;rjning. Gud fordrar inte av n&aring;gon mer &auml;n vad Han har l&aring;tit honom f&ouml;rfoga &ouml;ver. Efter sv&aring;righeterna skall Gud sk&auml;nka er l&auml;ttnad.';
$t[8] = 'HUR m&aring;nga folk, som i &ouml;vermod satte sig upp emot Guds och Hans s&auml;ndebuds befallningar, har Vi inte avkr&auml;vt str&auml;ng r&auml;kenskap och l&aring;tit dem utst&aring; sv&aring;ra straff.';
$t[9] = 'Och de m&aring;ste smaka de bittra frukterna av sina handlingar och resultatet var [deras] slutliga underg&aring;ng och f&ouml;rintelse;';
$t[10] = 'och Gud har i beredskap f&ouml;r dem ett str&auml;ngt straff [i det kommande livet]. Frukta d&auml;rf&ouml;r Gud, ni som tror och har f&ouml;rst&aring;nd! Gud har s&auml;nt er en p&aring;minnelse,';
$t[11] = 'ett S&auml;ndebud som framf&ouml;r till er Guds klara budskap f&ouml;r att leda dem som tror och lever r&auml;ttskaffens ut ur m&ouml;rkret till ljuset. Och Gud skall f&ouml;ra dem som tror p&aring; Honom och lever r&auml;ttskaffens till lustg&aring;rdar, vattnade av b&auml;ckar, d&auml;r de skall f&ouml;rbli till evig tid; ja, Gud har s&ouml;rjt f&ouml;r dem p&aring; b&auml;sta s&auml;tt!';
$t[12] = 'GUD &Auml;R Den som har skapat sju himlar och lika m&aring;nga jordar och genom dem alla str&ouml;mmar [oupph&ouml;rligt] Hans vilja. Detta f&ouml;r att ni skall veta att Gud har allt i Sin makt och att Gud omfattar allt med Sin kunskap.';
?>