<?php
$t = array();
$t[1] = 'PROFET! Varf&ouml;r p&aring;l&auml;gger du [dig sj&auml;lv] - i en &ouml;nskan att vara dina hustrur till lags - f&ouml;rbud mot det som Gud har f&ouml;rklarat till&aring;tet f&ouml;r dig? Gud &auml;r st&auml;ndigt f&ouml;rl&aring;tande, barmh&auml;rtig.';
$t[2] = 'Gud har till&aring;tit er att fr&aring;ng&aring; eder [vars inneh&aring;ll strider mot lag och r&auml;tt] och att plikta f&ouml;r detta. Gud &auml;r er Beskyddare och Han &auml;r den Allvetande, den Allvise.';
$t[3] = 'Det h&auml;nde att Profeten i f&ouml;rtroende ber&auml;ttade n&aring;got f&ouml;r en av sina hustrur och hon f&ouml;rde det vidare; n&auml;r Gud l&auml;t honom veta detta n&auml;mnde han n&aring;got om det [till andra] men undanh&ouml;ll [en del]. D&aring; han sade det till henne fr&aring;gade hon: &quot;Vem har l&aring;tit dig veta det?&quot; - och han svarade: &quot;Han som vet allt, &auml;r underr&auml;ttad om allt, har l&aring;tit mig veta det.&quot;';
$t[4] = '[Det &auml;r b&auml;st f&ouml;r er b&aring;da] att ni v&auml;nder &aring;ter till Gud i &aring;nger &ouml;ver [ert handlingss&auml;tt], eftersom era hj&auml;rtan har avvikit [fr&aring;n pliktens v&auml;g]! Om ni g&ouml;r gemensam sak mot honom [b&ouml;r ni veta att] Gud &auml;r hans Beskyddare och att d&auml;rf&ouml;r ocks&aring; Gabriel och de fr&auml;msta bland de troende och [alla] &auml;nglar st&aring;r vid hans sida.';
$t[5] = 'Om [Profeten] skulle f&ouml;rskjuta er sk&auml;nker honom kanske hans Herre b&auml;ttre hustrur &auml;n ni - kvinnor som underkastar sig Guds vilja, sanna troende, &ouml;dmjuka inf&ouml;r Gud, som &aring;ngrar [sina synder] och troget tillber sin Herre, och som st&auml;ndigt g&aring;r [Guds &auml;renden] - f&ouml;rut gifta eller ungm&ouml;r.';
$t[6] = 'TROENDE! F&ouml;r er egen skull och f&ouml;r deras som st&aring;r er n&auml;ra b&ouml;r ni frukta den Eld som har m&auml;nniskor och stenar till br&auml;nsle, och som m&auml;ktiga och str&auml;nga &auml;nglar [vakar &ouml;ver, &auml;nglar] som aldrig brister i lydnad f&ouml;r Gud, vad Han &auml;n befaller dem, och som utf&ouml;r allt som &aring;l&auml;ggs dem.';
$t[7] = '&quot;Urskulda er inte denna Dag, ni envisa f&ouml;rnekare av sanningen! Ni skall l&ouml;nas enbart f&ouml;r det som ni gjorde [i livet].&quot;';
$t[8] = 'Troende! V&auml;nd er i uppriktig &aring;nger [&ouml;ver era synder] till Gud! Kanske skall er Herre ur er [bok] utpl&aring;na era d&aring;liga handlingar och f&ouml;ra er till lustg&aring;rdar, vattnade av b&auml;ckar, den Dag d&aring; Gud inte l&aring;ter skam komma vid Profeten och dem som f&ouml;ljde honom i tron - ljuset [av deras tro och deras goda handlingar] skall lysa framf&ouml;r dem och till h&ouml;ger om dem [och] de ber: &quot;Herre, l&aring;t v&aring;rt ljus lysa allt klarare och f&ouml;rl&aring;t oss v&aring;ra synder! Du har allt i Din makt!&quot;';
$t[9] = 'PROFET! K&auml;mpa outtr&ouml;ttligt mot f&ouml;rnekarna av sanningen och mot hycklarna och visa dig omutligt str&auml;ng mot dem; Elden &auml;r deras slutliga hemvist - detta el&auml;ndiga m&aring;l!';
$t[10] = 'Gud har utpekat Noas hustru och Lots hustru som varnande exempel f&ouml;r dem som framh&auml;rdar i att f&ouml;rneka sanningen; deras m&auml;n var tv&aring; av V&aring;ra r&auml;ttf&auml;rdiga tj&auml;nare och de svek dem. Men [m&auml;nnen] kunde inte skydda dem mot Guds [straff] och [p&aring; Domens dag] skall de f&aring; h&ouml;ra dessa ord: &quot;G&aring; in i Elden med de [&ouml;vriga f&ouml;rd&ouml;mda]!&quot;';
$t[11] = 'Och som ett [efterf&ouml;ljansv&auml;rt] exempel f&ouml;r de troende har Gud framh&aring;llit Faraos hustru, som bad: &quot;Herre! Bygg en boning &aring;t mig i paradiset i Din n&auml;rhet och skydda mig mot Farao och allt [det onda] han har gjort och skydda mig mot alla dem som st&auml;ndigt beg&aring;r or&auml;tt!&quot;';
$t[12] = '&Auml;nnu ett exempel har de i Maria, `Imrans dotter; Hon bevarade sin oskuld och Vi andades in i [hennes kropp] n&aring;got av V&aring;r ande. Hon trodde p&aring; sin Herres ord och p&aring; Hans uppenbarelser och hon var en av dem som &ouml;dmjukt b&ouml;jer sig under Hans vilja.';
?>