<?php
$t = array();
$t[1] = '&Oacute; fi&eacute;is, n&atilde;o vos antecipeis a Deus e ao Seu Mensageiro, e temei a Deus, porque Deus &eacute; Oniouvinte, Sapient&iacute;ssimo.';
$t[2] = '&Oacute; fi&eacute;is, n&atilde;o altereis as vossas vozes acima da voz do Profeta, nem lhe faleis em voz alta, como fazeis entre v&oacute;s, para n&atilde;otornardes sem efeito as vossas obras, involuntariamente.';
$t[3] = 'Sabei que os que baixam as suas vozes na presen&ccedil;a do Mensageiro de Deus, s&atilde;o aqueles cujos cora&ccedil;&otilde;es Deus testou paraa piedade; obter&atilde;o o perd&atilde;o e uma magn&iacute;fica recompensa.';
$t[4] = 'Em verdade, a maioria daqueles que gritam (o teu nome), do lado de fora dos (teus) aposentos, &eacute; insensata.';
$t[5] = 'Mas, se aguardassem pacientemente, at&eacute; que tu sa&iacute;sses ao seu encontro, seria muito melhor para eles. Deus &eacute; Ingulgente, Misericordios&iacute;ssimo.';
$t[6] = '&Oacute; fi&eacute;is, quando um &iacute;mpio vos trouxer uma not&iacute;cia, examinai-a prudentemente, para n&atilde;o prejudicardes ningu&eacute;m, porignor&acirc;ncia, e n&atilde;o vos arrependerdes depois.';
$t[7] = 'E sabei que o Mensageiro de Deus est&aacute; entre v&oacute;s e que se ele vos obedecesse em muitos assuntos, cair&iacute;eis em desgra&ccedil;a. Por&eacute;m, Deus vos inspirou o amor pela f&eacute; e adornou com ela vossos cora&ccedil;&otilde;es e vos fez repudiar a incredulidade, aimpiedade e a rebeldia. Tais s&atilde;o os sensatos.';
$t[8] = 'Isso, pela gra&ccedil;a e favor de Deus; e Deus &eacute; Prudente, Sapient&iacute;ssimo.';
$t[9] = 'E quando dois grupos de fi&eacute;is combaterem entre si, reconciliai-os, ent&atilde;o. E se um grupo provocar outro, combatei oprovocador, at&eacute; que se cumpram os des&iacute;gnios de Deus. Se por&eacute;m, se cumprirem (os des&iacute;gnios), ent&atilde;o reconciliai-oseq&uuml;itativamente e sede equ&acirc;nimes, porque Deus aprecia os equ&acirc;nimes.';
$t[10] = 'Sabe que os fi&eacute;is s&atilde;o irm&atilde;os uns dos outros; reconciliai, pois, os vossos irm&atilde;os, e temei a Deus, para vos mostrarmiseric&oacute;rdia.';
$t[11] = '&Oacute; fi&eacute;is, que nenhum povo zombe do outro; &eacute; poss&iacute;vel que (os escarnecidos) sejam melhores do que eles (osescarnecedores). Que tampouco nenhuma mulher zombe de outra, porque &eacute; poss&iacute;vel que esta seja melhor do que aquela. N&atilde;ovos difameis, nem vos motejeis com apelidos mutuamente. Muito vil &eacute; o nome que detona maldade (para ser usado poralgu&eacute;m), depois de Ter recebido a f&eacute;! E aqueles que n&atilde;o se arrependem ser&atilde;o os in&iacute;quos.';
$t[12] = '&Oacute; fi&eacute;is, evitai tanto quanto poss&iacute;vel a suspeita, porque algumas suspeitas implicam em pecado. N&atilde;o vos espreiteis, nemvos calunieis mutuamente. Quem de v&oacute;s seria capaz de comer a carne do seu irm&atilde;o morto? Tal atitude vos causa repulsa! Temei a Deus, porque Ele &eacute; Remiss&oacute;rio, Misericordios&iacute;ssimo.';
$t[13] = '&Oacute; humanos, em verdade, N&oacute;s vos criamos de macho e f&ecirc;mea e vos dividimos em povos e tribos, para reconhecerdes unsaos outros. Sabei que o mais honrado, dentre v&oacute;s, ante Deus, &eacute; o mais temente. Sabei que Deus &eacute; Sapient&iacute;ssimo e est&aacute; beminteirado.';
$t[14] = 'Os bedu&iacute;nos dizem: Cremos! Dize-lhes: Qual! Ainda n&atilde;o credes; deveis dizer: Tornamo-nos mu&ccedil;ulmanos, pois que a f&eacute;ainda n&atilde;o penetrou vossos cora&ccedil;&otilde;es. Por&eacute;m, se obedecerdes a Deus e ao Seu Mensageiro, em nada ser&atilde;o diminu&iacute;das asvossas obras, porque Deus &eacute; Indulgente, Misericordios&iacute;ssimo.';
$t[15] = 'Somente s&atilde;o fi&eacute;is aqueles que cr&ecirc;em em Deus e em Seu Mensageiro e n&atilde;o duvidam, mas sacrificam os seus bens e assuas pessoas pela causa de Deus. Estes s&atilde;o os verazes!';
$t[16] = 'Dize-lhes: Pretendeis, acaso, ensinar a Deus a vossa religi&atilde;o, quando Deus bem conhece tudo quanto existe nos c&eacute;us e naterra? Sabei que Deus &eacute; Onisciente.';
$t[17] = 'Dizem que te fizeram um favor por se terem tornado mu&ccedil;ulmanos. Dize-lhes: n&atilde;o considereis a vossa convers&atilde;o um favorpara mim; outrossim, &eacute; a Deus que deveis o m&eacute;rito de vos Ter encaminhado &agrave; f&eacute;, se sois verazes.';
$t[18] = 'Sabei que Deus conhece o mist&eacute;rio dos c&eacute;us e da terra, e Deus bem v&ecirc; tudo o quanto fazeis!';
?>