<?php
$t = array();
$t[1] = 'Em verdade, Deus escutou a declara&ccedil;&atilde;o daquela que discutia contigo, acerca do marido, e se queixava (em ora&ccedil;&atilde;o) aDeus. Deus ouviu vossa palestra, porque &eacute; Oniouvinte, Onividente.';
$t[2] = 'Aqueles, dentre v&oacute;s, que repudiam as suas mulheres atrav&eacute;s do zihar, saibam que elas n&atilde;o s&atilde;o suas m&atilde;es. Estas s&atilde;o as queos geraram; certamente, com tal juramento, eles proferiram algo in&iacute;quo e falso; por&eacute;m, Deus &eacute; Absolvedor, Indulgent&iacute;ssimo.';
$t[3] = 'Quanto &agrave;queles que repudiarem as suas mulheres pelo zihar e logo se retratarem disso, dever&atilde;o manumitir um escravo, antes de as tocarem. Isso &eacute; uma exorta&ccedil;&atilde;o para v&oacute;s, porque Deus est&aacute; inteirado de tudo quanto fazeis.';
$t[4] = 'Mas, quem n&atilde;o o encontrar (escravo), dever&aacute; jejuar&aacute; dois meses consecutivos antes de a tocar. Por&eacute;m, quem n&atilde;o pudersuportar o jejum, dementar sessenta necessitados. Isso, para que creiais em Deus e em Seu Mensageiro. Tais s&atilde;o as leis deDeus, e aqueles que as profanarem sofrer&atilde;o um doloroso castigo.';
$t[5] = 'Sabei que aqueles que contrariam Deus e Seu Mensageiro ser&atilde;o exterminados, como o foram os seus antepassados; porisso N&oacute;s lhes enviamos l&uacute;cidos vers&iacute;culos e, aqueles que os negarem, sofrer&atilde;o um afrontoso castigo.';
$t[6] = 'Ser&aacute; o dia em que Deus os ressuscitar&aacute; a todos e os inteirar&aacute; de tudo quanto tiverem feito. Deus o memoriza, enquantoeles o esquecem, porque Deus &eacute; Testemunha de tudo.';
$t[7] = 'N&atilde;o reparas em que Deus conhece tudo quanto existe nos c&eacute;us e na terra? N&atilde;o h&aacute; confid&ecirc;ncia entre tr&ecirc;s pessoas, sem queEle seja a Quarta delas; nem entre cinco, sem que Ele seja a sexta; nem que haja menos ou mais do que isso, sem que Eleesteja com elas, onde quer que se achem. Logo, no Dia da Ressurrei&ccedil;&atilde;o, os inteirar&aacute; de tudo quanto fizerem, porque Deus &eacute;Onisciente.';
$t[8] = 'Acaso, n&atilde;o reparaste naqueles a quem foi proibida a confid&ecirc;ncia? N&atilde;o obstante, reincidem no que lhes foi vedado e falamclandestinamente de iniq&uuml;idades, de hostilidades e de desobedi&ecirc;ncias ao Mensageiro! E quando se apresentam a ti, sa&uacute;dam-te, em termos com os quais Deus jamais te saudaram, e dizem para si: Por que Deus n&atilde;o nos castiga pelo quefazemos? Bastar-lhes-&aacute; o inferno, no qual entrar&atilde;o! E que funesto destino!';
$t[9] = '&Oacute; fi&eacute;is, quando falardes na intimidade, n&atilde;o discorrais sobre iniq&uuml;idades, sobre hostilidades, nem sobre a desobedi&ecirc;nciaao Mensageiro; antes, falai da virtude e da piedade, e temei a Deus, ante Quem sereis congregados.';
$t[10] = 'Sabei que a confabula&ccedil;&atilde;o emana de Sat&atilde;, para atribular os fi&eacute;is. Por&eacute;m, ele em nada poder&aacute; prejudic&aacute;-los sem obenepl&aacute;cito de Deus. Que os fi&eacute;is se encomendem a Deus!';
$t[11] = '&Oacute; fi&eacute;is, quando vos for dito para que vos aperteis, (dando) nas assembl&eacute;ias (lugar aos demais), fazei-o; e sabei que Deusvos dar&aacute; lugar no Para&iacute;so! E quando vos for dito que vos levanteis, fazei-o, pois Deus dignificar&aacute; os fi&eacute;is, dentre v&oacute;s, assimcomo os s&aacute;bios, porque est&aacute; inteirado de tudo quanto fazeis.';
$t[12] = '&Oacute; fi&eacute;is, quando fordes consultar privativamente o Mensageiro, fazei antes uma caridade; isso ser&aacute; melhor para v&oacute;s; eser&aacute; mais puro; por&eacute;m, se carecerdes de meios, sabei que Deus &eacute; Indulgente, Misericordios&iacute;ssimo.';
$t[13] = 'Temeis, acaso, fazer caridade, antes da vossa consulta privativa (a ele)? Mas, se n&atilde;o o fizerdes - e que Deus vos perdoe-, observai, a ora&ccedil;&atilde;o, pagai o zakat e obedecei a Deus e ao Seu Mensageiro, porque Deus est&aacute; inteirado de tudo quantofazeis.';
$t[14] = 'Acaso, n&atilde;o reparaste naqueles que entraram (em privacidade) com um povo, o qual Deus abominou? N&atilde;o s&atilde;o dosvossos, nem tampouco sois dos deles, e perjuram conscientemente!';
$t[15] = 'Deus lhes tem preparado um severo castigo. Qu&atilde;o p&eacute;ssimo &eacute; o que fizeram!';
$t[16] = 'Fizeram dos seus juramentos uma coberta (para as suas m&aacute;s a&ccedil;&otilde;es), e desencaminharam-se da senda de Deus; por&eacute;m, sofrer&atilde;o um castigo afrontoso.';
$t[17] = 'Perante Deus, de nada lhes valer&atilde;o os seus bens, nem os seus filhos e ser&atilde;o os condenados ao inferno, no qualpermanecer&atilde;o eternamente.';
$t[18] = 'No dia em que Deus os ressuscitar a todos, jurar-Lhe-&atilde;o, ent&atilde;o, como juraram a v&oacute;s, e crer&atilde;o que possuem algo. N&atilde;os&atilde;o, na verdade, uns mentirosos?';
$t[19] = 'Satan&aacute;s os conquistou e os fez esquecer da recorda&ccedil;&atilde;o de Deus. Estes s&atilde;o os seguidores de Satan&aacute;s. N&atilde;o &eacute;, acaso, certo, que os seguidores de Satan&aacute;s ser&atilde;o os desventurados?';
$t[20] = 'Sabei que aqueles que contrariam Deus e o Seu Mensageiro contar-se-&atilde;o entre os mais humilhados.';
$t[21] = 'Deus decretou: Venceremos, Eu e os Meus mensageiros! Em verdade, Deus &eacute; Poderoso, Fort&iacute;ssimo.';
$t[22] = 'N&atilde;o encontrar&aacute;s povo algum que creia em Deus e no Dia do Ju&iacute;zo final, que tenha rela&ccedil;&otilde;es com aqueles que contrariamDeus e o Seu Mensageiro, ainda que sejam seus pais ou seus filhos, seus irm&atilde;os ou parentes. Para aqueles, Deus lhes firmoua f&eacute; nos cora&ccedil;&otilde;es e os confortou com o Seu Esp&iacute;rito, e os introduzir&aacute; em jardins, abaixo dos quais correm os rios, ondemorar&atilde;o eternamente. Deus se comprazer&aacute; com eles e eles se comprazer&atilde;o n\'Ele. Estes formam o partido de Deus. Acaso, n&atilde;o &eacute; certo que os que formam o partido de Deus ser&atilde;o os bem-aventurados?';
?>