<?php
$t = array();
$t[1] = 'Tudo quando existe nos c&eacute;us e na terra glorifica Deus. Ele &eacute; o Poderoso, o Prudent&iacute;ssimo.';
$t[2] = 'Foi ele Quem expatriou os incr&eacute;dulos, dentre os adeptos do Livro, quando do primeiro desterro. Pouco cr&iacute;eis (&oacute;mu&ccedil;ulmanos) que eles sa&iacute;ssem dos seus lares, porquanto supunham que as suas fortalezas os preservariam de Deus; por&eacute;m, Deus os a&ccedil;oitou, por onde menos esperavam, e infundiu o terror em seus cora&ccedil;&otilde;es; destru&iacute;ram as suas casas com suaspr&oacute;prias m&atilde;os, e com as m&atilde;os dos fi&eacute;is. Aprendei a li&ccedil;&atilde;o, &oacute; sensatos!';
$t[3] = 'E se Deus n&atilde;o lhes tivesse decretado o seu banimento, t&ecirc;-los-ia castigado nesse mundo, e no outro, sofreriam o tormentoinfernal.';
$t[4] = 'Isso, por terem contrariado Deus e Seu Mensageiro; e, quem contraria Deus (saiba que), certamente Deus &eacute; sever&iacute;ssimono castigo.';
$t[5] = '(&Oacute; mu&ccedil;ulmanos), ficai sabendo que, se cortardes as tamareiras tenras ou se as deixardes de p&eacute;, f&aacute;-lo-eis com obenepl&aacute;cito de Deus, e para que Ele avilte os depravados.';
$t[6] = 'Tudo quanto Deus concedeu ao Seu Mensageiro, (tirado) dos bens deles (dos Bani Annadhir), n&atilde;o tivestes de fazergalopar cavalo ou camelo algum para conseguir (para transportar). Deus concede aos Seus mensageiros o predom&iacute;nio sobrequem Lhe apraz, porque Deus &eacute; Onipotente.';
$t[7] = 'Tudo quanto Deus concedeu ao Seu Mensageiro, (tomado) dos moradores das cidades, corresponde a Deus, ao SeuMensageiro e aos seus parentes, aos &oacute;rf&atilde;os, aos necessitados e aos viajantes; isso, para que (as riquezas) n&atilde;o sejammonopolizadas pelos opulentos, dentre v&oacute;s. Aceitai, pois, o que vos der o Mensageiro, e abstende-vos de tudo quanto elevos pro&iacute;ba. E temei a Deus, porque Deus &eacute; Sever&iacute;ssimo no castigo.';
$t[8] = '(E tamb&eacute;m corresponde uma parte) aos pobres migrantes (maquenses), que foram expatriados e despojados dos seus bens, que procuram a gra&ccedil;a de Deus e a Sua complac&ecirc;ncia, e secundam Deus e Seu Mensageiro; estes s&atilde;o os verazes.';
$t[9] = 'Os que antes deles residiam (em Madina) e haviam adotado a f&eacute;, mostram afei&ccedil;&atilde;o por aqueles que migraram para juntodeles e n&atilde;o nutrem inveja alguma em seus cora&ccedil;&otilde;es, pelo que (tais migrantes) receberam (de despojos); por outra, preferem-nos, em detrimento de si mesmos. Sabei que eles que se preservarem da avareza ser&atilde;o os bem-aventurados.';
$t[10] = 'E aqueles que os seguiram dizem: &Oacute; Senhor nosso, perdoa-nos, assim como tamb&eacute;m aos nosso irm&atilde;os, que nosprecederam na f&eacute;, e n&atilde;o infundas em nossos cora&ccedil;&otilde;es rancor algum pelos fi&eacute;is. &Oacute; Senhor nosso, certamente Tu &eacute;sCompassivo, Misericordios&iacute;ssimo.';
$t[11] = 'N&atilde;o reparas, acaso, nos hip&oacute;critas, que dizem aos seus irm&atilde;os incr&eacute;dulos, dentre os adeptos do Livro: Juramos que sefordes expulsos, sairemos convosco e jamais obedeceremos a ningu&eacute;m, contra v&oacute;s; e, se fordes combatidos, socorrer-vos-emos. Por&eacute;m, Deus atesta que s&atilde;o uns mentirosos.';
$t[12] = 'Porque, na verdade, se fossem expulsos, n&atilde;o sairiam com eles, se fossem combatidos, n&atilde;o os socorreriam; e, mesmo queos socorressem, empreenderiam a fuga; e, ainda, eles mesmos n&atilde;o seriam socorridos.';
$t[13] = 'Seguramente, v&oacute;s, &oacute; fi&eacute;is, infundis em seus cora&ccedil;&otilde;es mais terror ainda do que Deus; isso, porque s&atilde;o uns insensatos.';
$t[14] = 'Eles n&atilde;o vos combater&atilde;o (mesmo) em conjunto, sen&atilde;o em cidades fortificadas, ou por detr&aacute;s das muralhas. A hostilidadeentre eles &eacute; intensa. V&oacute;s os credes unidos, quando os seus cora&ccedil;&otilde;es est&atilde;o divididos; isso, porque s&atilde;o uns insensatos.';
$t[15] = 'Parecem-se com os seus predecessores imediatos, ao auferirem e rev&eacute;s da sua conduta; ter&atilde;o um doloroso castigo.';
$t[16] = 'S&atilde;o como Satan&aacute;s, quando diz ao humano: Renega! Por&eacute;m, quando este renega a Deus, diz-lhe: Sabe que n&atilde;o sourespons&aacute;vel pelo que te acontecer, porque temo a Deus, Senhor do Universo!';
$t[17] = 'Por&eacute;m, o destino deles &eacute; serem condenados ao fogo, onde permanecer&atilde;o eternamente. Tal ser&aacute; o castigo dos in&iacute;quos!';
$t[18] = '&Oacute; fi&eacute;is, temei a Deus! E que cada alma considere o que tiver oferecido, para o dia de amanh&atilde;; temei, pois, a Deus, porque Deus est&aacute; bem inteirado de tudo quanto fazeis.';
$t[19] = 'E n&atilde;o sejais como aqueles que se esqueceram de Deus e, por isso mesmo, Ele os fez esquecerem-se de si pr&oacute;prios. Estess&atilde;o os depravados!';
$t[20] = 'Jamais poder&atilde;o equiparar-se os condenados ao inferno com os diletos do Para&iacute;so, porque os diletos do Para&iacute;so ser&atilde;o osganhadores.';
$t[21] = 'Se tiv&eacute;ssemos feito descer este Alcor&atilde;o sobre uma montanha, t&ecirc;-las-ias visto humilhar-se e fender-se, por temor a Deus, Tais exemplos propomos aos humanos, para que raciocinem.';
$t[22] = 'Ele &eacute; Deus; n&atilde;o h&aacute; mais divindade al&eacute;m d\'Ele, conhecedor do cognosc&iacute;vel e do incognosc&iacute;vel. Ele &eacute; o Clemente, oMisericordios&iacute;ssimo.';
$t[23] = 'Ele &eacute; Deus; n&atilde;o h&aacute; mais divindade al&eacute;m d\'Ele, Soberano, Augusto, Pac&iacute;fico, Salvador, Zeloso, Poderoso, Compulsor, Supremo! Glorificado seja Deus, de tudo quanto (Lhe) associam!';
$t[24] = 'Ele &eacute; Deus, Criador, Onifeitor, Formador. Seus s&atilde;o os mais sublimes atributos. Tudo quanto existe nos c&eacute;us e na terraglorifica-O, porque &eacute; o Poderoso, o Prudent&iacute;ssimo.';
?>