<?php
$t = array();
$t[1] = '&Oacute; fi&eacute;is, n&atilde;o tomeis por confidentes os Meus e os vossos inimigos, demonstrando-lhes afeto, posto que renegam tudoquanto vos chegou da verdade, e expulsam (de Makka) tanto o Mensageiro, como v&oacute;s mesmos, porque credes em Deus, vosso Senhor! Quando sairdes para combater pela Minha causa, procurando a Minha complac&ecirc;ncia (n&atilde;o os tomeis porconfidentes), confiando-lhes as vossas intimidades, porque Eu, melhor do que ningu&eacute;m, sei tudo quanto ocultais, e tudoquanto manifestais. Em verdade, quem de v&oacute;s assim proceder, desviar-se-&aacute; da verdadeira senda.';
$t[2] = 'Se lograssem tirar o melhor de v&oacute;s, mostrar-se-iam vossos inimigos, estenderiam as m&atilde;os e as l&iacute;nguas contra v&oacute;s, desejando fazer-vos rejeitar a f&eacute;.';
$t[3] = 'De nada vos valer&atilde;o os vossos parentes ou os vossos filhos, no Dia da Ressurrei&ccedil;&atilde;o. Ele vos separar&aacute;; sabei que Deusbem v&ecirc; tudo quanto fazeis.';
$t[4] = 'Tivestes um excelente exemplo em Abra&atilde;o e naqueles que o seguiram, quando disseram ao seu povo: Em verdade, n&atilde;osomos respons&aacute;veis por vossos atos e por tudo quando adorais, em lugar de Deus, Renegamos-vos e iniciar-se-&aacute; inimizade eum &oacute;dio duradouros entre n&oacute;s e v&oacute;s, a menos que creiais unicamente em Deus! Todavia, as palavras de Abra&atilde;o para o pai: -Implorai o perd&atilde;o para ti, embora nada venha a obter de Deus em teu favor - foram uma exce&ccedil;&atilde;o. (Dizei, &oacute; crentes): &Oacute;Senhor nosso, a Ti nos encomendamos e a Ti nos voltamos contritos, porque para Ti ser&aacute; o retorno;';
$t[5] = '&Oacute; Senhor nosso, n&atilde;o fa&ccedil;as de n&oacute;s um escarmento para os incr&eacute;dulos e perdoa-nos, &oacute; Senhor nosso, porque &eacute;s o Poderoso, o Prudent&iacute;ssimo.';
$t[6] = 'Tivestes neles um excelente exemplo, de quem confia em Deus e no Dia do Ju&iacute;zo Final. Mas, quem desdenhar, que fiquesabendo que Deus &eacute;, por Si, o Opulento, o Laudabil&iacute;ssimo!';
$t[7] = '&Eacute; poss&iacute;vel que Deus restabele&ccedil;a a cordialidade entre v&oacute;s e os vossos inimigos, porque Deus &eacute; Poderoso, e porque Deus &eacute;Indulgente, Misericordios&iacute;ssimo.';
$t[8] = 'Deus nada vos pro&iacute;be, quanto &agrave;quelas que n&atilde;o nos combateram pela causa da religi&atilde;o e n&atilde;o vos expulsaram dos vossoslares, nem que lideis com eles com gentileza e eq&uuml;idade, porque Deus aprecia os eq&uuml;itativos.';
$t[9] = 'Deus vos pro&iacute;be t&atilde;o-somente entrar em privacidade com aqueles que vos combateram na religi&atilde;o, vos expulsaram devossos lares ou que cooperaram na vossa expuls&atilde;o. Em verdade, aqueles que entrarem em privacidade com eles ser&atilde;oin&iacute;quos.';
$t[10] = '&Oacute; fi&eacute;is, quando se vos apresentarem as fugitivas fi&eacute;is, examinai-as, muito embora Deus conhe&ccedil;a a sua f&eacute; melhor do queningu&eacute;m; por&eacute;m, se as julgardes fi&eacute;is, n&atilde;o as restituais aos incr&eacute;dulos, porquanto elas n&atilde;o lhes cabem por direito, nem eles aelas; por&eacute;m, restitu&iacute; o que eles gastaram (com os seus dotes). N&atilde;o sereis recriminados se as desposardes, contanto que asdoteis; por&eacute;m, n&atilde;o vos apegueis &agrave; tutela das incr&eacute;dulas, mas exigi a restitui&ccedil;&atilde;o do que gastastes no seu dote; e que (osincr&eacute;dulos), por sua vez, exijam o que gastaram. Tal &eacute; o Ju&iacute;zo de Deus, com que vos julga, porque Deus &eacute; Sapiente, Prudent&iacute;ssimo.';
$t[11] = 'E se alguma de vossas esposas fugir para os incr&eacute;dulos, e depois tiverdes acesso (a uma mulher deles), restitu&iacute; &agrave;quelescujas esposas houverem fugido o equivalente ao que haviam gasto (com os seus dotes). E temei a Deus, em Quem credes.';
$t[12] = '&Oacute; Profeta, quando as fi&eacute;is se apresentarem a ti, jurando-te fidelidade, afirmando-te que n&atilde;o atribuir&atilde;o parceiros a Deus, n&atilde;o roubar&atilde;o, n&atilde;o fornicar&atilde;o, n&atilde;o ser&atilde;o filicidas, n&atilde;o se apresentar&atilde;o com cal&uacute;nias que forjarem intencionalmente, nem tedesobedecer&atilde;o em causa justa, aceita, ent&atilde;o, o seu compromisso e implora, para elas, o perd&atilde;o de Deus, porque Deus &eacute;Indulgente, Misericordios&iacute;ssimo.';
$t[13] = '&Oacute; fi&eacute;is, n&atilde;o tenhais v&iacute;nculos com o povo que Deus abominou, por ter-se tornado c&eacute;tico quanto &agrave; outra vida, como osincr&eacute;dulos se tornaram c&eacute;ticos quanto aos donos das sepulturas.';
?>