<?php
$t = array();
$t[1] = '&Oacute; Profeta, quando vos divorciardes das vossas mulheres, divorciai-vos delas em seus per&iacute;odos prescritos e contaiexatamente tais per&iacute;odos e temei a Deus, vosso Senhor. N&atilde;o as expulseis dos seus lares, nem elas dever&atilde;o sair, a n&atilde;o serque tenham cometido obscenidade comprovada. Tais s&atilde;o as leis de Deus; e quem profanar as leis de Deus, condenar-se-&aacute;. Tu o ignoras, mas &eacute; poss&iacute;vel que Deus, depois disto, modifique a situa&ccedil;&atilde;o para melhor.';
$t[2] = 'Todavia, quando tiverem cumprido o seu t&eacute;rmino prefixado, tomai-as em termos eq&uuml;itativos ou separai-vos delas, emtermos eq&uuml;itativos. (Em ambos os casos) fazei-o ante testemunhas eq&uuml;itativas, dentre v&oacute;s, e justificai o testemunho anteDeus, com o qual se exorta quem cr&ecirc; em Deus e no Dia do Ju&iacute;zo Final. Mas, a quem temer a Deus, Ele lhe apontar&aacute; umasa&iacute;da.';
$t[3] = 'E o agraciar&aacute;, de onde menos esperar. Quanto &agrave;quele que se encomendar a Deus, saiba que Ele ser&aacute; Suficiente, porqueDeus cumpre o que promete. Certamente Deus predestinou uma propor&ccedil;&atilde;o para cada coisa.';
$t[4] = 'Quanto &agrave;quelas, das vossas mulheres, que tiverem chegado &agrave; menopausa, se tiverdes d&uacute;vida quanto a isso, o seu per&iacute;odoprescrito ser&aacute; de tr&ecirc;s meses; o mesmo se diga, com respeito &agrave;quelas que ainda n&atilde;o tiverem chegado a tal condi&ccedil;&atilde;o; e, quanto&agrave;s gr&aacute;vidas, o seu per&iacute;odo estar&aacute; terminado quando derem &agrave; luz. Mas, a quem temer a Deus, Ele lhe aplainar&aacute; o assunto.';
$t[5] = 'Tal &eacute; o mandamento que Deus vos revelou. E quem temer a Deus, (saiba que) Ele lhe absolver&aacute; os pecados e lheaumentar&aacute; a recompensa.';
$t[6] = 'Instalai-as (as divorciadas) onde habitais, segundo os vossos recursos, e n&atilde;o as molesteis, para criar-lhes dificuldades. Se estiverem gr&aacute;vidas, mantende-as, at&eacute; que tenham dado &agrave; luz. Se amamentam os vossos filhos, pagai-lhes a suarecompensa e consultai-vos cordialmente. Por&eacute;m, se encontrardes constrangimento nisso, que os amamente outra mulher.';
$t[7] = 'Que o abastado retribua isso, segundo as suas posses; quanto &agrave;quele, cujos recursos forem parcos, que retribua comaquilo com que Deus lhe agraciou. Deus n&atilde;o imp&otilde;e a ningu&eacute;m obriga&ccedil;&atilde;o superior ao que lhe concedeu; Deus trocar&aacute; adificuldade pela facilidade.';
$t[8] = 'Quantas cidades descartaram a autoridade do seu Senhor e dos Seus mensageiros! Saldamo-lhes as contas rigorosamente elhes infligimos um castigo exemplar.';
$t[9] = 'Sofreram, ent&atilde;o, a dura conseq&uuml;&ecirc;ncia da sua conduta, e o resultado da sua conduta foi a perdi&ccedil;&atilde;o.';
$t[10] = 'Deus lhes preparou um severo castigo. Temei, pois, a Deus, &oacute; fi&eacute;is sensatos, pois Deus vos enviou uma Mensagem.';
$t[11] = 'Por um Mensageiro, que vos recita os l&uacute;cidos vers&iacute;culos de Deus, para tirar os que cr&ecirc;em e praticam o bem, das trevas, para os levar &agrave; luz. E os que cr&ecirc;em em Deus e praticam o bem, Ele os introduzir&aacute; em jardins, abaixo dos quais correm osrios, onde morar&atilde;o eternamente. Deus lhes reservou uma excelente provis&atilde;o.';
$t[12] = 'Deus foi Quem criou sete firmamentos e outro tanto de terras; e Seus des&iacute;gnios se cumprem, entre eles, para que saibaisque Deus &eacute; Onipotente e que Deus tudo abrange, com a Sua onisci&ecirc;ncia.';
?>