<?php
$t = array();
$t[1] = '&Oacute; profeta, por que te abst&eacute;ns daquilo que Deus te concedeu, procurando, com isso, agradar as tuas esposas, quando sabesque Deus &eacute; Indulgente, Misericordios&iacute;ssimo?';
$t[2] = 'Deus vos permitiu a expia&ccedil;&atilde;o dos vossos juramentos, porque &eacute; vosso Protetor e &eacute; o Sapiente, o Prudent&iacute;ssimo.';
$t[3] = 'Quando o Profeta confidenciou um segredo a uma das suas esposas (Hafsa), ela o revelou (a outra), e Deus informou-odisso; ele, ent&atilde;o, confirmou uma parte disso, escondendo a outra. Mais, quando ele contou, ela perguntou: Quem te anunciouisso? Disse: Anunciou-mo o Onisciente, o Sapient&iacute;ssimo.';
$t[4] = 'Se v&oacute;s, ambas, voltardes arrependidas a Deus, os vossos cora&ccedil;&otilde;es inclinar-se-&atilde;o para isso; por&eacute;m, se confabulardescontra ele, sabei que Deus &eacute; o seu Protetor, bem como Gabriel, os virtuosos, dentre os fi&eacute;is e os anjos ser&atilde;o os (seus) socorredores.';
$t[5] = 'Se ele se divorciar de v&oacute;s, pode ser que o seu Senhor lhe conceda esposas mu&ccedil;ulmanas prefer&iacute;veis a v&oacute;s, fi&eacute;is, devotas, arrependidas, adoradoras, jejuadoras, anteriormente casadas ou donzelas.';
$t[6] = '&Oacute; fi&eacute;is, precavei-vos, juntamente com as vossas fam&iacute;lias, do fogo, cujo alimento ser&atilde;o os homens e as pedras, o qual &eacute; guardado por anjos inflex&iacute;veis e severos, que jamais desobedecem &agrave;s ordens que recebem de Deus, mas executam tudo quanto lhes &eacute; imposto.';
$t[7] = '&Oacute; incr&eacute;dulos, n&atilde;o apresenteis escusas hoje, porque s&oacute; sereis recompensados pelo que houverdes feito!';
$t[8] = '&Oacute; fi&eacute;is, voltai, sinceramente arrependidos, a Deus; &eacute; poss&iacute;vel que o vosso Senhor absolva as vossas faltas e vos introduza em jardins, abaixo dos quais correm os rios, no dia em que Deus n&atilde;o aviltar&aacute; o Profeta e aqueles que com ele crerem. Uma luz fulgurar&aacute; diante deles e, com a sua cren&ccedil;a, dir&atilde;o: &Oacute; Senhor nosso, completa-nos a nossa luz e perdoa-nos, porque Tu &eacute;s Onipotente!';
$t[9] = '&Oacute; Profeta, combate com denodo os incr&eacute;dulos e os hip&oacute;critas, e s&ecirc; inflex&iacute;vel para com eles, pois a sua morada ser&aacute; o inferno. E que funesto destino!';
$t[10] = 'Deus exemplifica, assim, aos incr&eacute;dulos, com as mulheres de No&eacute; e a de Lot: ambas achavam-se submetidas a dois dos Nossos servos virtuosos; por&eacute;m, ambas os atrai&ccedil;oaram e ningu&eacute;m p&ocirc;de defend&ecirc;-las de Deus. Ser-lhes-&aacute; dito: Entrai no fogo, juntamente com os que ali entrarem!';
$t[11] = 'E Deus d&aacute;, como exemplo aos fi&eacute;is, o da mulher do Fara&oacute;, a qual disse: &Oacute; Senhor meu, constr&oacute;i-me, junto a Ti, uma morada no Para&iacute;so, e livra-me do Fara&oacute; e das suas a&ccedil;&otilde;es, e salva-me dos in&iacute;quos!';
$t[12] = 'E com Maria, filha de Imran, que conservou o seu pudor, e a qual alentamos com o Nosso Esp&iacute;rito, por te acreditado nas palavras do seu Senhor e nos Seus Livros, e por se Ter contado entre os consagrados.';
?>