<?php
$t = array();
$t[1] = 'Ey iman gətirənlər! (S&ouml;zləriniz, iş və hərəkətlərinizdə) Allahdan və Peyğəmbərindən &ouml;nə ke&ccedil;məyin. Allahdan qorxun. Həqiqətən, Allah (hər şeyi) eşidəndir, (hər şeyi) biləndir!';
$t[2] = 'Ey iman gətirənlər! Səsinizi Peyğəmbərin səsindən artıq qaldırmayın və bir-birinizlə ucadan danışdığınız kimi onunla ucadan danışmayın! Yoxsa, &ouml;z&uuml;n&uuml;z də bilmədən, əməlləriniz pu&ccedil; olar.';
$t[3] = 'Həqiqətən, Allahın Peyğəmbəri yanında astadan danışanlar (səslərini asta &ccedil;ıxardanlar) o kimsələrdir ki, Allah onların &uuml;rəklərini təqva &uuml;&ccedil;&uuml;n imtahana &ccedil;əkmişdir (m&ouml;&rsquo;minliyə layiq etmişdir). Onları (g&uuml;nahlardan) bağışlanma və b&ouml;y&uuml;k m&uuml;kafat (Cənnət) g&ouml;zləyir!';
$t[4] = '(Ya Peyğəmbər!) Ş&uuml;bhəsiz ki, səni otaqların arxasından &ccedil;ağıranların &ccedil;oxusunun ağlı kəsmir!';
$t[5] = 'Əgər onlar sən qarşılarına &ccedil;ıxancaya qədər səbr etsəydilər, (bu, Allahın yanında) onlar &uuml;&ccedil;&uuml;n, əlbəttə, daha yaxşı olardı. Allah (t&ouml;vbə edənləri) bağışlayandır, rəhm edəndir!';
$t[6] = 'Ey iman gətirənlər! Əgər bir fasiq sizə (pis) bir xəbər gətirsə, dərhal (onun doğruluğunu) yoxlayın, yoxsa bilmədən bir q&ouml;vmə pislik edər, sonra da etdiyinizə peşman olarsınız!';
$t[7] = '(Ey iman gətirənlər!) Bilin ki, aranızda Allahın Peyğəmbəri vardır. Əgər o, bir &ccedil;ox işlərdə sizə uysaydı, siz (&ccedil;ətinliyə d&uuml;şər) əziyyət &ccedil;əkərdiniz. Lakin Allah sizə imanı sevdirmiş, onu &uuml;rəklərinizdə s&uuml;sləmiş, k&uuml;frə, itaətdən &ccedil;ıxmağa və (Allaha) asi olmağa qarşı sizdə nifrət oyatmışdır. Məhz belələri (bu xislət sahibləri) doğru yolda olanlardır!';
$t[8] = 'Bu isə Allah dərgahından olan l&uuml;tf və ne&rsquo;mət sayəsindədir. Allah (hər şeyi) biləndir, hikmət sahibidir!';
$t[9] = 'Əgər m&ouml;&rsquo;minlərdən iki dəstə bir-biri ilə vuruşsa, onları dərhal barışdırın. Əgər onlardan biri təcav&uuml;zkarlıq etsə, təcav&uuml;zkarlıq edənlə Allahın əmrinə (itaətinə) qayıdana qədər vuruşun. (Təcav&uuml;zkarlıq edən Allahın əmrinə) qayıtsa, hər iki dəstənin arasını ədalətlə d&uuml;zəldin və insafla hərəkət edin. Ş&uuml;bhəsiz ki, Allah insaflıları sevər!';
$t[10] = 'Həqiqətən, m&ouml;&rsquo;minlər (dində) qardaşdırlar. Buna g&ouml;rə də (aralarında bir m&uuml;bahisə d&uuml;şsə) iki qardaşınızın arasını d&uuml;zəldin və Allahdan qorxun ki, bəlkə, (əvvəlki g&uuml;nahlarınız bağışlanıb) rəhm olunasınız!';
$t[11] = 'Ey iman gətirənlər! Bir q&ouml;vm digərini lağa qoymasın. Ola bilsin ki, onlar (lağa qoyulanlar) o birilərindən (lağa qoyanlardan Allah yanında) daha yaxşı olsunlar. Qadınlar da bir-birinə (rişxənd eləməsinlər). Bəlkə, onlar (rişxənd olunanlar) o birilərindən (rişxənd edənlərdən) daha yaxşıdırlar. Bir-birinizə tə&rsquo;nə etməyin (ayıb tutmayın) və bir-birinizi pis ləqəblərlə (ey kafir, ey fasiq, ey m&uuml;nafiq və i. a.) &ccedil;ağırmayın. İman gətirdikdən sonra fasiq adını qazanmaq necə də pisdir. Məhz t&ouml;vbə etməyənlər zalımlardır! (&Ouml;zlərinə z&uuml;lm edənlərdir!)';
$t[12] = 'Ey iman gətirənlər! &Ccedil;ox zənnə-g&uuml;mana qapılmaqdan &ccedil;əkinin. Ş&uuml;bhəsiz ki, zənnin bə&rsquo;zisi (he&ccedil; bir əsası olmayan zənn) g&uuml;nahdır. (Bir-birinizin eyibini, sirrini) arayıb axtarmayın, bir-birinizin qeybətini qırmayın! Sizdən biriniz &ouml;lm&uuml;ş qardaşının ətini yeməyə razı olarmı?! Bu sizdə ikrah hissi oyadar (qeybət də belədir). Allahdan qorxun. Həqiqətən, Allah t&ouml;vbələri qəbul edəndir, rəhmlidir!';
$t[13] = 'Ey insanlar! Biz sizi bir kişi və bir qadından (Adəm və Həvvadan) yaratdıq. Sonra bir-birinizi tanıyasınız (kimliyinizi biləsiniz) deyə, sizi xalqlara və qəbilələrə ayırdıq. Allah yanında ən h&ouml;rmətli olanınız Allahdan ən &ccedil;ox qorxanınızdır (pis əməllərdən ən &ccedil;ox &ccedil;əkinəninizdir). Həqiqətən, Allah (hər şeyi) biləndir, (hər şeydən) xəbərdardır.';
$t[14] = '(Qənimət əldə etmək iştahası ilə islama daxil olan) bədəvi ərəblər: &ldquo;Biz iman gətirdik!&rdquo; &ndash; dedilər. (Ya Peyğəmbər! Onlara) de: &ldquo;Siz (qəlbən) iman gətirmədiniz! Ancaq: &ldquo;Biz islamı (m&uuml;əyyən şəxsi məqsəd, mənfəət naminə) qəbul etdik!&rdquo; &ndash; deyin. Hələ iman sizin qəlblərinizə daxil olmamışdır (&ccedil;&uuml;nki iman əməllə e&rsquo;tiqadın vəhdəti, islamı qəbul etmək isə yalnız zahiri əməl deməkdir). Əgər Allaha və Peyğəmbərinə itaət etsəniz, O sizin əməllərinizdən he&ccedil; bir şey əskiltməz (m&uuml;kafatınızı layiqincə verər). Həqiqətən, Allah bağışlayandır, rəhm edəndir!';
$t[15] = 'M&ouml;&rsquo;minlər yalnız Allaha və Peyğəmbərinə iman gətirən, (iman gətirdikdən) sonra he&ccedil; bir şəkk-ş&uuml;bhəyə d&uuml;şməyən, Allah yolunda malları və canları ilə vuruşanlardır! Məhz belələri (imanlarında) sadiq olanlardır!';
$t[16] = '(Ya Peyğəmbər! Bu bədəvilərə) de: &ldquo;Siz dininizi (həqiqi m&uuml;səlman olduğunuzu) Allahamı &ouml;yrədirsiniz?&rdquo; Halbuki Allah g&ouml;ylərdə və yerdə nə varsa, (hamısını) bilir. Allah hər şeyi biləndir!';
$t[17] = 'Onlar islamı qəbul etdiklərinə g&ouml;rə sənə minnət qoyurlar. De: &ldquo;M&uuml;səlman olduğunuzla mənə minnət qoymayın! Xeyr, əgər (iman gətirdiyinizi) doğru deyirsinizsə, (bilin ki) sizi imana m&uuml;vəffəq etməklə, əslində Allah sizin boynunuza minnət qoymuş olur!&rdquo;';
$t[18] = 'Ş&uuml;bhəsiz ki, Allah g&ouml;ylərin və yerin qeybini (g&ouml;zə g&ouml;r&uuml;nməyən sirlərini) bilir. Allah sizin nə etdiklərinizi g&ouml;rəndir!';
?>