<?php
$t = array();
$t[1] = '(Ya Peyğəmbər!) Əri barəsində səninlə m&uuml;bahisə edən və Allaha şikayət edən qadının s&ouml;z&uuml;n&uuml; Allah eşitdi. Allah sizin danışığınızı eşidir. Həqiqətən, Allah (hər şeyi) eşidəndir, (hər şeyi) g&ouml;rəndir!';
$t[2] = 'Sizdən &ouml;z qadınları ilə zihar edən kimsələrin z&ouml;vcələri (əslində) onların anaları deyillər. Onların anaları ancaq &ouml;zlərini doğan qadınlardır. Onlar, əlbəttə, pis və yalan s&ouml;z danışırlar. Ş&uuml;bhəsiz ki, Allah əfv edəndir, bağışlayandır.';
$t[3] = 'Qadınları ilə zihar (qanuni nikahlarını &ouml;zlərinə haram) edib, sonra s&ouml;zlərindən d&ouml;nənlər onlarla yaxınlıq etməzdən əvvəl (kəffarə vermək &uuml;&ccedil;&uuml;n) bir k&ouml;lə azad etməlidirlər. Bu sizə (zihar barəsində) verilən &ouml;y&uuml;dd&uuml;r. Allah nə etdiklərinizdən xəbərdardır!';
$t[4] = 'Kim (azad etməyə bir k&ouml;lə) tapmasa, qadını ilə yaxınlıq etməzdən əvvəl iki ay sərasər oruc tutmalı, buna da g&uuml;c&uuml; &ccedil;atmasa, altmış yoxsulu yedirdib doydurmalıdır. Bu sizin Allah və Onun Peyğəmbərinə iman gətirməniz &uuml;&ccedil;&uuml;nd&uuml;r. Bunlar Allahın hədləridir (onları aşmaq olmaz). Kafirləri şiddətli bir əzab g&ouml;zləyir!';
$t[5] = 'Allah və Onun Peyğəmbəri əleyhinə &ccedil;ıxanlar, &ouml;zlərindən əvvəlkilər nə c&uuml;r r&uuml;svay olmuşlarsa, o c&uuml;r r&uuml;svay olacaqlar. Biz artıq (Muhəmməd əleyhissəlamın haqlı olmasını s&uuml;but edən) a&ccedil;ıq-aşkar ayələr nazil etdik. Kafirləri al&ccedil;aldıcı bir əzab g&ouml;zləyir!';
$t[6] = 'Allah onların hamısını dirildəcəyi g&uuml;n etdikləri əməlləri onlara xəbər verəcəkdir. Allah (onların əməllərini bir-bir) sayıb yazmış, onlar isə (etdiklərini) unutmuşlar. Allah hər bir şeyə şahiddir!';
$t[7] = '(Ya Peyğəmbər!) Məgər g&ouml;rm&uuml;rsənmi ki, Allah g&ouml;ylərdə və yerdə nə varsa, (hamısını) bilir. Aralarında gizli s&ouml;hbət gedən &uuml;&ccedil; adamın d&ouml;rd&uuml;nc&uuml;s&uuml;, beş adamın altıncısı Odur. Onlar bundan az da, &ccedil;ox da olsalar və harada olsalar, (Allah) yenə də onların yanındadır. Sonra qiyamət g&uuml;n&uuml; (Allah) onlara etdikləri əməlləri (bir-bir) xəbər verəcəkdir. Allah hər şeyi biləndir!';
$t[8] = '(Ya Peyğəmbər!) Məgər məxfi danışmaq qadağan edildikdən sonra yenə də qadağan olunduqları əmələ qayıdıb g&uuml;nah, ədavət və Peyğəmbərin əleyhinə &ccedil;ıxmaq barədə &ouml;z aralarında pı&ccedil;ıldaşanları (m&uuml;nafiqlərlə yəhudiləri) g&ouml;rmədinmi? Onlar yanına gəldikləri zaman səni Allahın salamladığı kimi salamlamır (&ldquo;əssəlamu əleykə&rdquo; əvəzinə &ldquo;əsammu əleykə - sənə &ouml;l&uuml;m olsun!&rdquo; &ndash; deyərək guya salam verir) və &uuml;rəklərində: &ldquo;(Əgər Məhəmməd həqiqi peyğəmbərdirsə) bəs niyə Allah bizi dediklərimizə g&ouml;rə əzaba d&uuml;&ccedil;ar etmir?&rdquo; &ndash; deyirlər. Onlara girib yanacaqları Cəhənnəm kifayət edər. Ora necə də pis qayıdış yeridir!';
$t[9] = 'Ey iman gətirənlər! Bir-birinizlə xəlvət danışdığınız zaman g&uuml;nah, d&uuml;şmən&ccedil;ilik və Peyğəmbərin əleyhinə &ccedil;ıxmaq barədə danışmayın; yaxşı işlər, Allahdan qorxmaq barədə danışın və (qiyamət g&uuml;n&uuml;) h&uuml;zuruna toplanacağınız Allahdan qorxun!';
$t[10] = 'Ş&uuml;bhəsiz ki, (bir yerə yığışıb g&uuml;naha, d&uuml;şmən&ccedil;iliyə bais olan) məxfi danışma (pı&ccedil;ıldaşma) iman gətirənləri mə&rsquo;yus edib kədərləndirmək &uuml;&ccedil;&uuml;n olan Şeytan əməlindəndir. Halbuki Allahın izni olmadıqca (Şeytan) onlara he&ccedil; bir zərər yetirə bilməz. M&ouml;&rsquo;minlər yalnız Allaha təvəkk&uuml;l etsinlər!';
$t[11] = 'Ey iman gətirənlər! Sizə: &ldquo;Məclislərdə (m&ouml;&rsquo;min qardaşlarınıza) yer verin!&rdquo; &ndash; deyildiyi zaman (onlara) yer verin ki, Allah da sizə (Cənnətdə) geniş yer versin. Eləcə də sizə: &ldquo;Qalxın!&rdquo; deyildikdə qalxın ki, Allah da sizdən iman gətirənlərin və (x&uuml;susilə) elm bəxş edilmiş kimsələrin dərəcələrini ucaltsın. Allah etdiyiniz əməllərdən xəbərdardır!';
$t[12] = 'Ey iman gətirənlər! Peyğəmbərlə (hər hansı bir iş barəsində) məxfi danışacağınız zaman bu danışıqdan əvvəl (ona h&ouml;rmət əlaməti olaraq yoxsullara) sədəqə verin. Bu (əməl) sizin &uuml;&ccedil;&uuml;n (Allah yanında) daha xeyirli, daka pakdır. Əgər (sədəqə verməyə) bir şey tapmasanız (&uuml;rəyinizi qısmayın). &Ccedil;&uuml;nki Allah bağışlayandır, rəhm edəndir!';
$t[13] = 'Məgər siz (Peyğəmbərlə) məxfi danışmazdan əvvəl sədəqə verməkdən qorxdunuzmu? Madam ki, siz (bunu) etmədiniz (sədəqə vermədiniz) və Allah da t&ouml;vbənizi qəbul buyurdu, onda namaz qılıb zəkat verin, Allaha və Onun Peyğəmbərinə itaət edin. Allah nə etdiklərinizdən xəbərdardır!';
$t[14] = '(Ya Peyğəmbər!) Məgər onların (m&uuml;nafiqlərin) Allahın qəzəbləndiyi bir tayfanı (yəhudiləri) &ouml;zlərinə dost tutduqlarını (m&ouml;&rsquo;min m&uuml;səlmanların sirlərini onlara verdiklərini) g&ouml;rmədinmi? Onlar nə sizdəndirlər, nə də onlardan. Onlar (&ouml;zlərinin riyakar olduqlarını) bilə-bilə (Allaha və Muhəmməd əleyhissəlama iman gətirdikləri barədə) yalandan and i&ccedil;irlər.';
$t[15] = 'Allah onlar &uuml;&ccedil;&uuml;n şiddətli bir əzab hazırlamışdır. Onların etdiyi əməllər necə də pisdir!';
$t[16] = 'Onlar andlarını &ouml;zlərinə sipər etdilər və (xalqı) Allah yolundan d&ouml;ndərdilər. Onları al&ccedil;aldıcı bir əzab g&ouml;zləyir.';
$t[17] = 'Onları nə malları, nə də &ouml;vladları he&ccedil; bir vəchlə Allahdan (Allahın əzabından) qurtara bilməz. Onlar cəhənnəmlikdirlər və orada əbədi qalacaqlar.';
$t[18] = 'Allah onların hamısını dirildəcəyi g&uuml;n onlar sizə (yalandan) and i&ccedil;dikləri kimi, Allaha da and i&ccedil;əcək və (bununla axirətdə) bir şey qazanacaqlarını zənn edəcəklər. Bilin ki, onlar əsl yalan&ccedil;ıdırlar!';
$t[19] = 'Şeytan onlara hakim olmuş və Allahı zikr etməyi onlara unutdurmuşdur. Onlar Şeytanın firqəsidirlər (Şeytana uyanlardır). Bilin ki, Şeytanın firqəsi &ndash; məhz onlar ziyana uğrayanlardır!';
$t[20] = 'Allahın və Onun Peyğəmbərinin əleyhinə &ccedil;ıxanlar (Cəhənnəmdəki) ən zəlil kimsələr i&ccedil;ərisində olacaqlar!';
$t[21] = 'Allah (l&ouml;vhi-məhfuzda): &ldquo;And olsun ki, Mən və peyğəmbərlərim qalib gələcəyik!&rdquo; &ndash; deyə yazmışdır. Həqiqətən, Allah yenilməz q&uuml;vvət sahibi, q&uuml;drət sahibidir!';
$t[22] = '(Ya Peyğəmbər!) Allaha və axirət g&uuml;n&uuml;nə inanan he&ccedil; bir tayfanın Allah və Onun Peyğəmbəri əleyhinə &ccedil;ıxanlarla &ndash; &ouml;z ataları, oğulları, qardaşları, yaxın qohumları olsalar belə - dostluq etdiyini g&ouml;rməzsən. Onlar elə kimsələrdir ki, Allah onların qəlblərinə iman yazmış və &Ouml;z dərgahından onlara ruh (g&uuml;c) vermişdir (iman, hidayət nuru əta etmişdir). (Allah) onları (ağacları) altından &ccedil;aylar axan cənnətlərə daxil edəcəkdir. Onlar orada əbədi qalacaqlar. Allah onlardan, onlar da Allahdan razıdırlar. Onlar Allahın firqəsidirlər (Allahın dininə k&ouml;mək edən kimsələrdir). Bilin ki, Allahın firqəsi məhz onlar nicat tapıb (əbədi) səadətə qovuşanlardır.';
?>