<?php
$t = array();
$t[1] = 'G&ouml;ylərdə və yerdə nə varsa, (hamısı) Allahı təqdis edib şə&rsquo;ninə tə&rsquo;riflər deyər. O, yenilməz q&uuml;vvət sahibi, hikmət sahibidir!';
$t[2] = 'Kitab əhlindən kafir olanları (Mədinə ətrafında yaşayıb Muhəmməd əleyhissəlamın peyğəmbərliyini inkar edən Bəni Nəzir qəbiləsini) ilk dəfə (bir yerə) toplayıb &ouml;z yurdundan &ccedil;ıxardan (Şama s&uuml;rg&uuml;n edən) Odur. (Ey m&ouml;&rsquo;minlər!) Siz onların (&ouml;z yurdundan) &ccedil;ıxacaqlarını g&uuml;man etmirdiniz. Onlar isə &ouml;z qalalarının onları Allahdan (Allahın əzabından) qoruyacağını zənn edirdilər. Amma Allah (Allahın əzabı) onlara g&ouml;zləmədikləri yerdən gəlib &uuml;rəklərinə qorxu saldı. Belə ki, onlar evlərini həm &ouml;z əlləri, həm də m&ouml;&rsquo;minlərin əlləri ilə u&ccedil;urdub dağıdırdılar. Ey bəsirət sahibləri! (Bəni Nəzir qəbiləsinin başına gələnlərdən) ibrət alın!';
$t[3] = 'Əgər Allah onlara (yurdlarından &ccedil;ıxardılıb) s&uuml;rg&uuml;n olunmağı h&ouml;km etməsəydi, onları d&uuml;nyada m&uuml;tləq (başqa bir) əzaba d&uuml;&ccedil;ar edərdi. Axirətdə isə onları cəhənnəm əzabı g&ouml;zləyir!';
$t[4] = 'Bu onların Allaha və Onun Peyğəmbərinə asi olmalarına g&ouml;rədir. Kim Allaha asi olsa (bilsin ki), Allahın cəzası &ccedil;ox şiddətlidir!';
$t[5] = '(Ey m&ouml;&rsquo;minlər! Sizin kafirlərə məxsus olan) hər hansı bir xurma ağacını kəsməyiniz, yaxud (toxunmayıb) onu k&ouml;k&uuml; &uuml;st&uuml;ndə salamat qoymağınız Allahın iznilədir. Və bu (Allahın &ouml;z Rəbbinə asi olan) fasiqləri r&uuml;svay etməsi &uuml;&ccedil;&uuml;nd&uuml;r.';
$t[6] = '(Ey m&ouml;&rsquo;minlər!) Allahın onların (Bəni Nəzər qəbiləsinin) mallarından &Ouml;z Peyğəmbərinə verdiyi qənimət &uuml;&ccedil;&uuml;n siz onların &uuml;st&uuml;nə nə at, nə də dəvə s&uuml;rd&uuml;n&uuml;z. Lakin Allah &Ouml;z peyğəmbərini istədiyi kimsələr &uuml;zərində hakim edər. Allah hər şeyə qadirdir!';
$t[7] = 'Allah &Ouml;z Peyğəmbərinə (fəth olunmuş) məmləkətlərin əhalisindən (dinc yolla) verdiyi qənimət Allaha, Peyğəmbərə, (Muhəmməd əleyhissəlama yaxın olan) qohum-əqrabaya, yetimlərə, yoxsullara və (pulu qurtarıb yolda qalan) m&uuml;safirə (yol&ccedil;ulara) məxsusdur. Bu ona g&ouml;rədir ki, (həmin mal-d&ouml;vlət) i&ccedil;ərinizdəki zənginlər arasında əldən-ələ dolaşan bir sərvət olmasın (ondan yoxsullar da faydalansın). Peyğəmbər sizə nə verirsə, onu g&ouml;t&uuml;r&uuml;n; nəyi qadağan edirsə, ondan əl &ccedil;əkin. Allahdan qorxun. Həqiqətən, Allahın cəzası &ccedil;ox şiddətlidir.';
$t[8] = '(Bu qənimət) yurdlarından qovulub &ccedil;ıxardılmış, Allahdan mərhəmət və riza diləyən, Allaha və Onun Peyğəmbərinə k&ouml;mək edən yoxsul m&uuml;hacirlərə məxsusdur. Onlar (imanlarında, s&ouml;zlərində və işlərində) doğru olan kimsələrdir!';
$t[9] = 'Onlardan (m&uuml;hacirlərdən) əvvəl (Mədinədə) yurd salmış və (Muhəmməd əleyhissəlama qəlbən) iman gətirirmiş kimsələr (ənsar) &ouml;z yanlarına (şəhərlərinə) m&uuml;hacirət edənləri sevər, onlara verilən qənimətə g&ouml;rə &uuml;rəklərində həsəd (qəzəb) duymaz, &ouml;zləri ehtiyac i&ccedil;ində olsalar belə, onları &ouml;zlərindən &uuml;st&uuml;n tutarlar. (Allah tərəfindən) nəfsinin xəsisliyindən (tamahından) qorunub saxlanılan kimsələr &ndash; məhz onlar nicat tapıb səadətə (Cənnətə) qovuşanlardır!';
$t[10] = 'Onlardan (m&uuml;hacirlərdən və ənsarlardan) sonra gələnlər belə deyirlər: &ldquo;Ey Rəbbimiz! Bizi və bizdən əvvəlki iman gətirmiş (din) qardaşlarımızı bağışla. Bizim qəlblərimizdə iman gətirənlərə qarşı kinə (həsədə) yer vermə. Ey Rəbbimiz! Sən, həqiqətən, şəfqətlisən, mərhəmətlisən!&rdquo;';
$t[11] = '(Ya Peyğəmbər) Məgər kitab əhlindən kafir olan qardaşlarına: &ldquo;Əgər (siz &ouml;z yurdunuzdan) &ccedil;ıxarılsanız, biz də sizinlə birlikdə m&uuml;tləq (yurdumuzdan) &ccedil;ıxacaq, sizin əleyhinizə he&ccedil; vaxt he&ccedil; kəsə qoşulub tabe olmayacağıq. Əgər (m&ouml;&rsquo;minlər) sizinlə vuruşsalar, ş&uuml;bhəsiz ki, sizə yardım edəcəyik!&rdquo; &ndash; deyən m&uuml;nafiqləri g&ouml;rmədinmi? Allah onların xalis yalan&ccedil;ı olduğuna şahiddir!';
$t[12] = 'And olsun ki, əgər onlar (Bəni Nəzər qəbiləsi) yurdlarından &ccedil;ıxarılsalar, (m&uuml;nafiqlər) onlarla birlikdə (&ouml;z yurdlarından) &ccedil;ıxmazlar. Əgər (m&ouml;&rsquo;minlər) onlarla vuruşsalar, (m&uuml;nafiqlər) onlara (yəhudilərə) k&ouml;mək etməzlər. Yox, əgər (m&uuml;nafiqlər) onlara yardım etmiş olsalar, (&ouml;zləri məğlubiyyətə uğrayaraq) arxa &ccedil;evirib qa&ccedil;ar, sonra da onlara (Bəni Nəzir qəbiləsinə) he&ccedil; bir k&ouml;mək olunmaz!';
$t[13] = '(Ey m&ouml;&rsquo;minlər!) Onların (m&uuml;nafiqlərlə yəhudilərin) &uuml;rəklərinə qorxu salan Allahdan &ccedil;ox sizsiniz. Bu isə onların (Allahın əzəmət və heybətini) anlamaz bir q&ouml;vm olduqlarına g&ouml;rədir.';
$t[14] = 'Onlar (m&uuml;nafiqlərlə yəhudilər) hamılıqla sizə qarşı ancaq m&ouml;hkəm şəhərlərdə (kəndlərdə), yaxud divar arxasında (qala i&ccedil;ərisində) olarkən d&ouml;y&uuml;şərlər (başqa şəraitdə sizinlə vuruşmağa c&uuml;r&rsquo;ət etməzlər). Onların &ouml;z aralarındakı vuruşmaları (və d&uuml;şmən&ccedil;ilikləri) isə &ccedil;ox g&uuml;cl&uuml;d&uuml;r. (Ya Peyğəmbər!) Sən onların əlbir olduqlarını g&uuml;man edirsən, lakin onların qəlbləri dağınıqdır. Bunun səbəbi onların ağılsız bir q&ouml;vm olmalarıdır.';
$t[15] = 'Onlar &ouml;zlərindən bir az əvvəl əməllərinin cəzasını (d&uuml;nyada) dadmış kimsələrə (Bədrdə məğlub olmuş Məkkə m&uuml;şriklərinə) bənzəyirlər. Onları (axirətdə) şiddətli bir əzab g&ouml;zləyir.';
$t[16] = '(M&uuml;nafiqlər Bəni Nəzir yəhudilərini aldatması) Şeytana (Şeytanın insanı aldatmasına) bənzəyir. O, insana: &ldquo;Kafir ol!&rdquo; &ndash; deyər. (İnsan) kafir olan kimi (Şeytan onu qoyub qa&ccedil;araq): &ldquo;Mənim səninlə he&ccedil; bir əlaqəm yoxdur. Mən aləmlərin Rəbbi olan Allahdan qorxuram!&rdquo; &ndash; deyər.';
$t[17] = 'Onların hər ikisinin (Şeytanla onun aldatdığı adamın, eləcə də m&uuml;nafiqlərlə Bəni Nəzir qəbiləsinin) aqibəti cəhənnəm odu i&ccedil;ində həmişəlik qalmaqdır. Zalımların (kafirlərin) cəzası budur!';
$t[18] = 'Ey iman gətirənlər! Allahdan qorxun! Hər kəs sabah &uuml;&ccedil;&uuml;n nə etdiyinə (axirət &uuml;&ccedil;&uuml;n &ouml;z&uuml;nə nə hazırladığına) nəzər salsın. Allahdan qorxun. Həqiqətən, Allah etdiklərinizdən xəbərdardır!';
$t[19] = 'Allahı unutduları &uuml;&ccedil;&uuml;n Allahın da onları &ouml;zlərinə unutdurduğu (xeyirlərini başa d&uuml;şməyən) kimsələrə bənzəməyin! Onlar (Allahın itaətindən &ccedil;ıxmış) fasiqlərdir!';
$t[20] = 'Cəhənnəm əhli ilə cənnət əhli eyni ola bilməz. Cənnət əhli nicat tapıb (əbədi) səadətə qovuşanlardır!';
$t[21] = '(Ya Peyğəmbər!) Əgər Biz bu Qur&rsquo;anı bir dağa nazil etsəydik, sən onun Allahın qorxusundan (ki&ccedil;ildiyini) par&ccedil;a-par&ccedil;a olduğunu g&ouml;rərdin (halbuki ağıl və ruh sahibi olan insan onun &ouml;y&uuml;d-nəsihətlərindən ibrət almır). Biz bu misalları insanlar &uuml;&ccedil;&uuml;n &ccedil;əkirik ki, bəlkə, d&uuml;ş&uuml;nələr.';
$t[22] = 'O &Ouml;z&uuml;ndən başqa he&ccedil; bir tanrı olmayan, gizlini də, aşkarı da bilən Allahdır. O rəhmlidir, mərhəmətlidir! (Allah d&uuml;nyada b&uuml;t&uuml;n bəndələrinə rəhm edən Rəhman, axirətdə isə yalnız m&ouml;&rsquo;minləri bağışlayan Rəhimdir!)';
$t[23] = 'O &Ouml;z&uuml;ndən başqa he&ccedil; bir tanrı (mə&rsquo;bud) olmayan, (b&uuml;t&uuml;n məxluqatın) ixtiyar sahibi, m&uuml;qəddəs (pak) olan, (bəndələrinə) salamatlıq, əmin-amanlıq bəxş edən, (hər şeydən) g&ouml;z-qulaq olub (onu) qoruyan, yenilməz q&uuml;drət (q&uuml;vvət) sahibi, (hamını istədiyi hər hansı bir şeyə) məcbur etməyə qadir olan, (hər şeydən) b&ouml;y&uuml;k (hər şeyin f&ouml;vq&uuml;ndə) olan Allahdır. Allah (m&uuml;şriklərin) Ona qoşduqlarından (şəriklərdən) ucadır.';
$t[24] = 'O, (hər şeyi) yaradan, yoxdan var edən, (hər şeyə) surət verən Allahdır. Ən g&ouml;zəl adlar (əsmayi-h&uuml;sna) ancaq Ona məxsusdur. G&ouml;ylərdə və yerdə nə varsa (hamısı) Onu təqdis edib şə&rsquo;ninə tə&rsquo;riflər deyər. O, yenilməz q&uuml;vvət sahibi, hikmət sahibidir!';
?>