<?php
$t = array();
$t[1] = 'Ey iman gətirənlər! Nə mənim d&uuml;şmənimi, nə də &ouml;z&uuml;n&uuml;z&uuml;n d&uuml;şmənini dost (vəli) tutun! Onlar (kafirlər) sizə gələn haqqı (Qur&rsquo;anı, Muhəmməd əleyhissəlamı) inkar etdikləri halda, siz onlarla dostluq edirsiniz (mehribanlıq g&ouml;stərirsiniz). Siz Rəbbiniz olan Allaha iman gətirdiyiniz &uuml;&ccedil;&uuml;n onlar Peyğəmbəri və sizi (Məkkədən) &ccedil;ıxardırdılar. Əgər siz Mənim yolumda və Mənim rizamı qazanmaq uğrunda cihada &ccedil;ıxmısınızsa (Mənim d&uuml;şmənlərimi dost tutmayın). Siz onlarla gizlində dostluq edirsiniz (dostluq &uuml;z&uuml;ndən onlara sirr verirsiniz). Mən sizin gizli saxladığınız və aşkar etdiyiniz hər şeyi (b&uuml;t&uuml;n gizli və aşkar əməllərinizi) bilirəm. Sizdən kim (bir daha) bunu etsə (d&uuml;şmənlərlə dostluq edib onlara sirr versə), o, ş&uuml;bhəsiz ki, haqq yoldan azmışdır!';
$t[2] = 'Əgər onlar (m&uuml;şriklər) sizi ələ ke&ccedil;irsələr (sizə qələbə &ccedil;alsalar), sizə d&uuml;şmən olar, sizə pisliklə əl və dil uzadar, sizin kafir olmanızı istəyərlər.';
$t[3] = 'Nə (xatirinə Allaha və Peyğəmbərinə xəyanət etdiyiniz Məkkədəki) qohum-əqrabanız, nə də oğul-uşağınız sizə bir fayda verəcəkdir. Allah qiyamət g&uuml;n&uuml; sizi bir-birinizdən ayıracaqdır. Allah nə etdiklərinizi g&ouml;rəndir!';
$t[4] = 'İbrahim və onunla birlikdə olanlar (m&ouml;&rsquo;minlər) sizin &uuml;&ccedil;&uuml;n g&ouml;zəl &ouml;rnəkdir. O zaman onlar &ouml;z q&ouml;vm&uuml;nə belə demişdilər: &ldquo;Ş&uuml;bhəsiz ki, bizim sizinlə və sizin Allahdan başqa ibadət etdiklərinizlə (b&uuml;tlərlə) he&ccedil; bir əlaqəmiz yoxdur. Biz sizi (dininizi) inkar edirik. Siz bir olan Allaha iman gətirməyincə bizimlə sizin aranızda həmişə ədavət və nifrət olacaqdır!&rdquo; Ancaq İbrahim &ouml;z atasına: &ldquo;Mən (&ouml;z Rəbbimdən) m&uuml;tləq sənin bağışlanmağını diləyəcəm. Mən he&ccedil; vəchlə səni Allahdan (Allahın əzabından) qurtara bilmərəm (mənim bacardığım yalnız budur)!&rdquo; &ndash; deməsi istisnadır (bunda sizin &uuml;&ccedil;&uuml;n &ouml;rnək yoxdur). (Onlar həm&ccedil;inin belə demişdilər:) &ldquo;Ey Rəbbimiz! Biz ancaq Sənə təvəkk&uuml;l etdik, t&ouml;vbə edib ancaq Sənə tərəf qayıtdıq. Axır d&ouml;n&uuml;ş də ancaq Sənin h&uuml;zurunadır.';
$t[5] = 'Ey Rəbbimiz! Bizi kafirlər &uuml;&ccedil;&uuml;n sınaq vasitəsi etmə! (Bizi kafirlərin əli ilə sınağa &ccedil;əkmə, onları bizim &uuml;st&uuml;m&uuml;zdə hakim etmə!) Bizi bağışla. Ey Rəbbimiz! Həqiqətən, Sən yenilməz q&uuml;vvət sahibi, hikmət sahibisən!&rdquo;';
$t[6] = '(Ey m&ouml;&rsquo;minlər!) And olsun ki, onlar sizin &uuml;&ccedil;&uuml;n, Allaha və axirət g&uuml;n&uuml;nə &uuml;mid bəsləyənlər &uuml;&ccedil;&uuml;n g&ouml;zəl &ouml;rnəkdir. Kim (kafirlərlə dostluq edib Allahın buyurduğundan) &uuml;z d&ouml;ndərsə (bunun zərəri ancaq onun &ouml;z&uuml;nə olar). Allah (he&ccedil; nəyə) m&ouml;htac deyildir; O, tə&rsquo;rifə (ş&uuml;krə) layiqdir!';
$t[7] = '(Ey m&ouml;&rsquo;minlər!) Ola bilsin ki, Allah sizinlə d&uuml;şmən&ccedil;ilik etdiyiniz kimsələr (Məkkə m&uuml;şrikləri) arasında (onları islam dininə gətirməklə) dostluq (məhəbbət) yaratsın. Allah (hər şeyə) qadirdir. Allah bağışlayandır, rəhm edəndir!';
$t[8] = 'Allah din yolunda sizinlə vuruşmayan və sizi yurdunuzdan &ccedil;ıxartmayan kimsələrə yaxşılıq etməyi və onlarla ədalətlə rəftar etməyi sizə qadağan etməz. Allah ədalətli olanları sevər!';
$t[9] = 'Allah sizə ancaq sizinlə din yolunda vuruşan, sizi yurdunuzdan &ccedil;ıxardan və &ccedil;ıxartmağa k&ouml;mək edən kimsələrlə dostluq etmənizi qadağan edər. Onlarla dostluq edənlər əsl zalımlardır!';
$t[10] = 'Ey iman gətirənlər! M&ouml;&rsquo;min qadınlar sizin yanınıza m&uuml;hacir kimi gəldikləri zaman onları imtahana &ccedil;əkin. Allah onların imanını &ccedil;ox g&ouml;zəl bilir (onları yoxlayıb bilmək sizə lazımdır). Əgər bunların (bu qadınların həqiqi) m&ouml;&rsquo;min olduqlarını bilsəniz, artıq onları kafirlərin yanına qaytarmayın. Nə bunlar (bu qadınlar) onlara (kafirlərə), nə də onlar bunlara halaldır. Onların (kafirlərin həmin qadınlara) xərclədiklərini (mehri) &ouml;zlərinə qaytarıb verin. Bunların (bu qadınların) mehrlərini &ouml;zlərinə verdiyiniz təqdirdə onlarla evlənməyinizdən sizə he&ccedil; bir g&uuml;nah gəlməz. Kafir qadınları &ouml;z kəbininiz altında saxlamayın. (Həmin qadınlara) verdiyiniz mehri (onların ərə getdiyi kafirlərdən) istəyin. (Kafirlər də islamı qəbul edib m&ouml;&rsquo;minlərlə evlənən qadınlara) sərf etdikləri mehri (sizdən) istəsinlər. Allahın h&ouml;km&uuml; budur. O sizin aranızda (belə) h&ouml;km edər. Allah (hər şeyi) biləndir, hikmət sahibidir!';
$t[11] = 'Əgər z&ouml;vcələrinizdən biri sizdən qa&ccedil;ıb (mehrini geri qaytarmadan) kafirlərə qoşulsa və siz də (onlarla vuruşaraq) qənimət əldə etsəniz, z&ouml;vcələri (kafirlərin yanına) getmiş kimsələrə (həmin qənimətdən) onların (bu &ouml;vrətlərə) sərf etdikləri mehr qədər verin. İman gətirdiyiniz Allahdan qorxun!';
$t[12] = 'Ya Peyğəmbər! M&ouml;&rsquo;min qadınlar Allaha he&ccedil; bir şərik qoşmayacaqları, oğurluq və zina etməyəcəkləri, &ouml;vladlarını &ouml;ld&uuml;rməyəcəkləri (qız uşaqlarını diri-diri torpağa g&ouml;mməyəcəklərini), &ouml;zgə kişilərdən olan uşaqlarını yalandan ərlərinə isnad etməyəcəkləri və he&ccedil; bir yaxşı (bəyənilən) işdə sənin əleyhinə &ccedil;ıxmayacaqları barədə sənə bey&rsquo;ət etmək &uuml;&ccedil;&uuml;n yanına gəldikləri zaman onların bey&rsquo;ətini qəbul et və Allahdan onların bağışlanmasını dilə. Həqiqətən, Allah bağışlayandır, rəhm edəndir!';
$t[13] = 'Ey iman gətirənlər! Allahın qəzəbinə d&uuml;&ccedil;ar olmuş bir q&ouml;vmlə dostluq etməyin. Kafirlər qəbiristan əhlindən (&ouml;l&uuml;lərin qiyamət g&uuml;n&uuml; diriləcəyindən) &uuml;midlərini &uuml;zd&uuml;kləri kimi, onlar da axirətdən (axirətdə Allahın mərhəmətindən) &uuml;midlərini &uuml;zm&uuml;şlər!';
?>