<?php
$t = array();
$t[1] = 'G&ouml;ylərdə və yerdə nə varsa, (hamısı) m&uuml;lk&uuml;n (yer-g&ouml;y m&uuml;lk&uuml;n&uuml;n) h&ouml;kmdarı (sahibi), m&uuml;qəddəs (pak), yenilməz q&uuml;vvət, hikmət sahibi olan Allahı təqdis edib Onun şə&rsquo;ninə tə&rsquo;riflər deyər!';
$t[2] = '(Əksəriyyəti yazıb-oxumaq bilməyən) &uuml;mmi ərəblərə &ouml;zlərindən peyğəmbər g&ouml;ndərən Odur. (Bu Peyğəmbər) əvvəllər haqq yoldan a&ccedil;ıq-aşkar azsalar da, onlara (Allahın) ayələrini oxuyar, onları (g&uuml;nahlardan, şirk və k&uuml;fr &ccedil;irkabından) təmizləyər, onlara Kitabı və hikməti (Qur&rsquo;anı və şəriəti) &ouml;yrədər.';
$t[3] = '(Allah-təala Muhəmməd əleyhissəlamı) ərəblərdən savayı hələ onlara qoşulmamış başqalarına da (islamı qəbul etməmiş indiki &uuml;mmətlərə və qiyamət g&uuml;n&uuml;nə qədər d&uuml;nyaya gələcək b&uuml;t&uuml;n sonrakı tayfalara da peyğəmbər g&ouml;ndərmişdir) [Və ya: o Peyğəmbər Kitabı və hikməti ərəblərdən əlavə hələ onlara qoşulmamış başqalarına da (başqa &uuml;mmətlərə də) &ouml;yrədər]. O, yenilməz q&uuml;vvət sahibi, hikmət sahibidir!';
$t[4] = 'Bu, Allahın istədiyinə əta etdiyi mərhəmətdir (kərəmdir). Allah &ccedil;ox b&ouml;y&uuml;k mərhəmət (kərəm) sahibidir!';
$t[5] = 'T&ouml;vrata əməl etməyə m&uuml;kəlləf olduqdan sonra ona əməl etməyənlər (T&ouml;vrata y&uuml;kləndikdən sonra onu daşımayanlar, T&ouml;vrata iman gətirdikdən, onu oxuyub &ouml;yrəndikdən sonra h&ouml;kmlərini lazımınca yerinə yetirməyənlər) belində &ccedil;oxlu kitab daşıyan (lakin onların i&ccedil;ində nə yazıldığını bilməyən, onlardan faydalanmağı bacarmayan) ulağa bənzərlər. (Muhəmməd əleyhissəlamın həqiqi peyğəmbər olmasına dair) Allahın ayələrini yalan sayanlar barədə &ccedil;əkilən məsəl necə də pisdir! Allah zalım (kafir) q&ouml;vm&uuml; doğru yola y&ouml;nəltməz!';
$t[6] = '(Ya Peyğəmbər!) De: &ldquo;Ey yəhudilər! Əgər b&uuml;t&uuml;n insanlardan fərqli olaraq, &ouml;z&uuml;n&uuml;z&uuml;n Allahın dostları olduğunuzu iddia edirsinizsə, (və bunu) doğru deyirsinizsə, onda (Allahdan) &ouml;l&uuml;m diləyin! (&Ccedil;&uuml;nki Allah dərgahındakı ne&rsquo;mətlər, əbədi həyat &ouml;vliyalara ancaq &ouml;ləndən sonra qismət olar).';
$t[7] = 'Halbuki onlar (d&uuml;nyada) &ouml;z əlləri ilə etdikləri əməllərə (qazandıqları g&uuml;nahlara) g&ouml;rə he&ccedil; vaxt (&ouml;l&uuml;m&uuml;) diləməzlər. Allah zalımları (kafirləri) &ccedil;ox g&ouml;zəl tanıyandır!';
$t[8] = '(Ya Peyğəmbər!) De: &ldquo;(Qorxub) qa&ccedil;dığınız &ouml;l&uuml;m sizi m&uuml;tləq yaxalayacaqdır. Sonra siz gizlini də, aşkarı da bilənin (Allahın) h&uuml;zuruna qaytarılacaqsınız. O da sizə (d&uuml;nyada) nələr etdiyinizi (bir-bir) xəbər verəcəkdir!';
$t[9] = 'Ey iman gətirənlər! C&uuml;mə g&uuml;n&uuml; namaza &ccedil;ağırıldığınız zaman Allahı zikr etməyə tələsin və alış-verişi buraxın. Bilsəniz, bu sizin &uuml;&ccedil;&uuml;n nə qədər xeyirlidir!';
$t[10] = 'Namaz qılınıb qurtardıqdan sonra yer &uuml;z&uuml;nə dağılın və Allahın l&uuml;tf&uuml;ndən ruzi diləyib axtarın! (Yenə &ouml;z işinizə qayıdın!) Və Allahı &ccedil;ox zikr edin ki, nicat tapıb səadətə qovuşasınız! (Hər iki d&uuml;nyada muradınıza yetişəsiniz!)';
$t[11] = 'Onlar (m&ouml;&rsquo;minlər) bir alış-veriş, yaxud bir əyləncə g&ouml;rd&uuml;kləri zaman səni ayaq &uuml;stə (minbərdə x&uuml;tbə oxuduğun halda) qoyub ona tərəf cumdular. (Ya Peyğəmbər!) De: &ldquo;Allah dərgahında olan savab əyləncədən də, ticarətdən də xeyirlidir. Allah ruzi verənlərin ən yaxşısıdır!&rdquo; (Bir dəfə Muhəmməd əleyhissəlam minbərdə c&uuml;mə namazı x&uuml;tbəsi oxuduğu zaman Şamdan ərzaqla y&uuml;klənmiş bir karvanın gəldiyini xəbər verən təbil səsləri eşidilmişdi. O vaxt Mədinə əhalisi qıtlıqdan m&ouml;hkəm əziyyət &ccedil;əkirdi. Bunu eşidən camaat Peyğəmbəri tərk edərək karvanın qabağına qa&ccedil;mışdı. Məsciddə cəmi on iki adam qalmışdı. O zaman bu ayə nazil olub c&uuml;mə x&uuml;tbəsi və namazı bitməmiş məsciddən &ccedil;ıxıb getməyin məqbul hərəkət olmadığına işarə edilmişdir).';
?>