<?php
$t = array();
$t[1] = 'G&ouml;ylərdə və yerdə nə varsa, (hamısı) Allahı təqdis edib şə&rsquo;ninə tə&rsquo;riflər deyər. H&ouml;km Onundur, həmd-səna da Ona məxsusdur. O, hər şeyə qadirdir!';
$t[2] = 'Sizin yaradan Odur. Kiminiz kafirsiniz, kiminiz m&ouml;&rsquo;min. Allah nə etdiklərinizi g&ouml;rəndir!';
$t[3] = 'O, g&ouml;yləri və yeri haqq-ədalətlə (yerli-yerində) xəlq etdi, sizə surət verdi, surətlərinizi də g&ouml;zəl yaratdı. (İnsan b&uuml;t&uuml;n canlıların ən g&ouml;zəli və ən kamilidir). Axır d&ouml;n&uuml;ş də Onun h&uuml;zurunadır!';
$t[4] = 'O, g&ouml;ylərdə və yerdə olanları da, sizin gizlində və aşkar da nə etdiyinizi də bilir. Allah &uuml;rəklərdə olanları biləndir!';
$t[5] = '(Ey Məkkə m&uuml;şrikləri!) Məgər sizdən əvvəl kafir olanların (əzaba d&uuml;&ccedil;ar edilməsi) xəbəri sizə gəlib &ccedil;atmadımı? Onlar &ouml;z g&ouml;rd&uuml;kləri işlərin cəzasını d&uuml;nyada daddılar. Onları (axirətdə) şiddətli bir əzab g&ouml;zləyir!';
$t[6] = '&Ccedil;&uuml;nki peyğəmbərləri onlara a&ccedil;ıq-aşkar m&ouml;&rsquo;c&uuml;zələr gətirir, onlar isə: &ldquo;Məgər bizi doğu yola (&ouml;z&uuml;m&uuml;z kimi adi) bir insanmı salacaqdır?!&rdquo; &ndash; deyərək (o peyğəmbərləri) inkar edir və (haqdan) &uuml;z d&ouml;ndərirlər. Allahın (onların ibadətinə) ehtiyacı yoxdur. Allah he&ccedil; bir şeyə m&ouml;htac deyildir. O, (hər c&uuml;r) ş&uuml;krə (tə&rsquo;rifə) layiqdir!';
$t[7] = 'Kafir olanlar (&ouml;ld&uuml;kdən sonra) əsla dirildilməyəcəklərini iddia edirlər. (Ya Peyğəmbər!) De: &ldquo;Bəli, Rəbbimə and olsun ki, siz m&uuml;tləq dirildiləcəksiniz. Sonra da (d&uuml;nyada) etdiyiniz əməllər sizə (bir-bir) xəbər veriləcəkdir. Bu, Allah &uuml;&ccedil;&uuml;n &ccedil;ox asandır!';
$t[8] = 'Elə isə Allaha, Onun Peyğəmbərinə və nazil etdiyimiz nura (Qur&rsquo;ana) iman gətirin! Allah etdiyimiz əməllərdən agahdır!';
$t[9] = 'Allahın sizi (haqq-hesab &uuml;&ccedil;&uuml;n) toplanmış g&uuml;n&uuml;nə cəm edəcəyi g&uuml;n &ndash; məhz o g&uuml;n qarşılıqlı aldanma g&uuml;n&uuml;d&uuml;r! (Həmin g&uuml;n kafirlərin d&uuml;nyaya uyaraq axirəti əldən verdiklərinə g&ouml;rə, bə&rsquo;zi m&ouml;&rsquo;minlərin də d&uuml;nyada bacardıqlarından az yaxşı əməllər etdiklərinə g&ouml;rə aldanmaları bəlli olacaqdır). Kim Allaha iman gətirib yaxşı əməllər etsə, (Allah) onun g&uuml;nahlarının &uuml;st&uuml;n&uuml; &ouml;rtər və onu (ağacları) altından &ccedil;aylar axan cənnətlərə daxil edər. Belələri orada (Cənnətdə) əbədi qalacaqlar. Bu, b&ouml;y&uuml;k qurtuluşdur (uğurdur)!';
$t[10] = 'Kafir olub ayələrimizi yalan sayanlara gəldikdə isə, onlar cəhənnəmlikdirlər. Onlar orada həmişəlik qalacaqlar. Ora necə də pis məskəndir!';
$t[11] = 'Allahın izni olmadıqca (he&ccedil; kəsə) he&ccedil; bir m&uuml;sibət &uuml;z verməz. Kim Allaha iman gətirsə, (Allah) onun qəlbini haqqa doğru y&ouml;nəldər. (O, d&uuml;nyada baş verən hər şeyin Allahın əzəli h&ouml;km&uuml; və izni ilə olduğunu bilər). Allah hər şeyi (ke&ccedil;mişi, indini və gələcəyi) biləndir!';
$t[12] = 'Allaha itaət edin, Onun Peyğəmbərinə itaət edin; hər kəs (itaətdən) &uuml;z d&ouml;ndərsə, (bilsin ki) Peyğəmbərimizin &ouml;hdəsinə d&uuml;şən yalnız a&ccedil;ıq-aşkar təbliğdir! (O he&ccedil; kəsi zorla iman gətirməyə məcbur edən deyildir).';
$t[13] = 'Allahdan başqa he&ccedil; bir tanrı (mə&rsquo;bud) yoxdur. Buna g&ouml;rə də m&ouml;&rsquo;minlər ancaq Allaha təvəkk&uuml;l etsinlər!';
$t[14] = 'Ey iman gətirənlər! Ş&uuml;bhəsiz ki, z&ouml;vcələrinizdən və &ouml;vladınızdan sizə d&uuml;şmən olanlar vardır. (Onlar din və ya d&uuml;nya işlərində sizin əleyhinizə &ccedil;ıxar, sizi ibadətdən, yaxşı əməllərdən yayındırarlar. Hətta siz bir dəfə Məkkədən Mədinəyə hicrət etmək istədiyiniz zaman onlar m&uuml;xtəlif bəhanələrlə sizi bu fikrinizdən daşındırmışdılar). Onlardan &ouml;z&uuml;n&uuml;z&uuml; g&ouml;zləyin! Amma (t&ouml;vbə edəcəkləri təqdirdə) onları əfv etsəniz, (təqsirlərindən) ke&ccedil;səniz və bağışlasanız (daha yaxşı olar). &Ccedil;&uuml;nki Allah (g&uuml;nahları &ccedil;ox) bağışlayandır, rəhm edəndir!';
$t[15] = 'Həqiqətən, mal-d&ouml;vlətiniz və oğul-uşağınız (sizin &uuml;&ccedil;&uuml;n) ancaq bir imtahandır. Ən b&ouml;y&uuml;k m&uuml;kafat (Cənnət) isə Allah dərgahındadır!';
$t[16] = 'Allahdan (Allahın əzabından) bacardığınız qədər qorxun. (Sizə verilə &ouml;y&uuml;d-nəsihətə) qulaq asın; (Allaha və Peyğəmbərinə) itaət edin və (mal-d&ouml;vlətinizdən Allah yolunda) xərcləyin. Bu sizin &ouml;z&uuml;n&uuml;z &uuml;&ccedil;&uuml;n xeyirli olar. (Allah tərəfindən) nəfsinin xəsisliyindən (tamahından) qorunub saxlanılan kimsələr &ndash; məhz onlar nicat tapıb səadətə qovuşanlardır!';
$t[17] = 'Əgər Allaha (Allah yolunda) g&ouml;zəl (k&ouml;n&uuml;l xoşluğu ilə) bir borc versəniz, (Allah) sizin &uuml;&ccedil;&uuml;n onun əvəzini qat-qat artırar və sizi bağışlayar. Allah qədirbiləndir, həlimdir!';
$t[18] = '(Allah) gizlini də, aşkarı da biləndir, yenilməz q&uuml;drət sahibi, hikmət sahibidir!';
?>