<?php
$t = array();
$t[1] = '(Ya Peyğəmbər!) &Ouml;vrətləri boşadığınız zaman onları g&ouml;zləmə m&uuml;ddətlərində (heyzdən pak olduqdan sonra) boşayın. G&ouml;zləmə m&uuml;ddətini (iddəti) sayın. Rəbbiniz olan Allahdan qorxun. Onları &ndash; a&ccedil;ıq-aşkar bir pis iş (zina) etməyənə qədər &ndash; (g&ouml;zləmə m&uuml;ddəti qurtarmamış) yaşadıqları evlərdən &ccedil;ıxartmayın və onlar &ouml;zləri də &ccedil;ıxmasınlar. Bu, Allahın hədləridir (h&ouml;kmləridir). Allah m&uuml;əyyən etdiyi hədləri aşan kimsə &ouml;z&uuml;nə z&uuml;lm etmiş olar. Nə bilirsən, ola bilsin ki, Allah bundan sonra bir iş icad etsin (ərin &uuml;rəyinə yenidən z&ouml;vcəsinin məhəbbətini salsın və onlar barışsınlar).';
$t[2] = 'Bunların (bu qadınların) g&ouml;zləmə m&uuml;ddəti başa &ccedil;atdıqda (barışmaq istəsəniz) onları yaxşılıqla (mehrlərini verib) yola salın. (Sonradan aranızda ixtilaf olmasın deyə) i&ccedil;ərinizdən iki ədalətli şahid tutun. (Siz də ey şahidlər!) Allah &uuml;&ccedil;&uuml;n (doğru) şahidlik edin! Bununla Allaha və axirət g&uuml;n&uuml;nə iman gətirənlərə &ouml;y&uuml;d-nəsihət verilir. Kim Allahdan qorxsa, Allah ona (hər &ccedil;ətinlikdən) bir &ccedil;ıxış yolu əta edər.';
$t[3] = 'Və ona g&ouml;zləmədiyi yerdən ruzi verər. Kim Allaha təvəkk&uuml;l etsə, (Allah) ona kifayət edər. Allah &Ouml;z əmrini yerinə yetirəndir. Allah hər şey &uuml;&ccedil;&uuml;n bir &ouml;l&ccedil;&uuml; (hədd, m&uuml;ddət) tə&rsquo;yin etmişdir.';
$t[4] = '(Yaşa dolmaqla) heyzdən kəsilmiş qadınlarınız (onların g&ouml;zləmə m&uuml;ddəti) barədə ş&uuml;bhə etsəniz, (bilin ki) onların və həm&ccedil;inin (yaşları m&uuml;said olmadığı &uuml;&ccedil;&uuml;n) hələ heyz g&ouml;rməmiş olanların (heyz g&ouml;rməmiş gənc &ouml;vrətlərinizin) g&ouml;zləmə m&uuml;ddəti &uuml;&ccedil; aydır (bu m&uuml;ddət başa &ccedil;atdıqdan sonra başqası ilə evlənə bilərlər). Hamilə qadınların g&ouml;zləmə m&uuml;ddəti isə onlar bari-həmlini yerə qoyduqda başa &ccedil;atır. Kim Allahdan qorxsa, Allah onun işini (d&uuml;nya və axirətdə) asan edər.';
$t[5] = 'Bu, Allahın sizə nazil etdiyi buyuruğudur. Kim Allahdan qorxsa, Allah onun (g&uuml;nahlarının) &uuml;st&uuml;n&uuml; &ouml;rtər və (axirətdə) m&uuml;kafatını artırar.';
$t[6] = 'Onları (boşadığınız, lakin g&ouml;zləmə m&uuml;ddətləri sona yetməmiş qadınları) imkanınız &ccedil;atdığı qədər &ouml;z yaşadığınız yerdə sakin edin. (Bu qadınları) sıxışdırmaq (evdən &ccedil;ıxıb getməyə məcbur etmək) məqsədilə onlara zərər (əziyyət) verməyə cəhd g&ouml;stərməyin. Əgər onlar hamilədirlərsə, bari-həmləni yerə qoyana qədər xərclərini verin. (Həmin qadınlar g&ouml;zləmə m&uuml;ddətləri qurtarandan sonra) sizin &uuml;&ccedil;&uuml;n uşaq əmizdirirlərsə, onların (s&uuml;d) haqqını verin (&ccedil;&uuml;nki onlar artıq sizin uşaqlarınıza s&uuml;d verməyə borclu deyillər). &Ouml;z aranızda yaxşılıqla (şəriətə m&uuml;vafiq şəkildə) sazişə gəlin. Əgər (bu məsələdə) &ccedil;ətinliyə d&uuml;şsəniz (bir-birinizlə razılığa gələ bilməsəniz), onu (uşağı) başqa bir qadın əmizdirə bilər.';
$t[7] = 'Varlı-karlı olan &ouml;z varına g&ouml;rə (s&uuml;d haqqı) versin. İmkanı az olan isə Allahın ona verdiyindən versin. Allah he&ccedil; kəsi &Ouml;z&uuml;n&uuml;n ona verdiyindən artıq xərcləməyə məcbur etməz. Allah hər bir &ccedil;ətinlikdən sonra asanlıq (yoxsulluqdan sonra d&ouml;vlət) əta edər.';
$t[8] = 'Ne&ccedil;ə-ne&ccedil;ə məmləkət (əhli) &ouml;z Rəbbinin və Onun peyğəmbərinin əmrindən &ccedil;ıxdı. Biz də onlara şiddətli cəza verib g&ouml;r&uuml;nməmiş m&uuml;dhiş əzaba d&uuml;&ccedil;ar etdik.';
$t[9] = 'Onlar əməllərinin cəzasını aldılar və axırda işləri ziyana uğramaq oldu.';
$t[10] = 'Allah onlar &uuml;&ccedil;&uuml;n şiddətli əzab hazırladı. Ey iman gətirmiş ağıl sahibləri, Allahdan qorxun! Allah sizin &uuml;&ccedil;&uuml;n Qur&rsquo;an nazil etmiş,';
$t[11] = 'Və iman gətirib yaxşı işlər g&ouml;rənləri z&uuml;lmətdən nura (k&uuml;frdən imana) &ccedil;ıxartmaq &uuml;&ccedil;&uuml;n Allahın a&ccedil;ıq-aşkar (halal-haramı bəyan edən) ayələrini sizə oxuyan bir peyğəmbər g&ouml;ndərmişdir. Kim Allaha iman gətirib yaxşı iş g&ouml;rsə, (Allah) onu (m&ouml;&rsquo;minlərin) əbədi qalacaqları, (ağacları) altından &ccedil;aylar axan cənnətlərə daxil edər. Həqiqətən, Allah ona g&ouml;zəl ruzi əta etmişdir!';
$t[12] = 'Yeddi (qat) g&ouml;y&uuml; və bir o qədər də yeri yaradan Allahdır. Allahın hər şeyə qadir olduğunu, Allahın hər şeyi elm (&Ouml;z əzəli elmi) ilə ehtiva etdiyini biləsiniz deyə, (Allahın) əmri onların arasında (m&ouml;vcud olan b&uuml;t&uuml;n məxluqata) nazil olar.';
?>