<?php
$t = array();
$t[1] = 'Ya Peyğəmbər! Z&ouml;vcələrinin (səndən) razı qalmasını diləyərək Allahın sənə halal etdiyi şeyi (d&uuml;nya ləzzətini) niyə &ouml;z&uuml;nə haram (qadağan) edirsən? Allah bağışlayandır, rəhm edəndir!';
$t[2] = 'Həqiqətən, Allah (halal bir şeyi &ouml;z&uuml;n&uuml;zə haram etmək barəsində i&ccedil;diyiniz) andlarınızı (kəffarə verməklə) geri g&ouml;t&uuml;rməyi vacib (qanuni) etmişdir. Allah sizin ixtiyar sahibinizdir. O (hər şeyi) biləndir, hikmət sahibidir!';
$t[3] = 'Bir zaman Peyğəmbər &ouml;z z&ouml;vcələrindən birinə (Həfsəyə) gizli bir s&ouml;z (bir daha Zeynəb bint Cəhşin, yaxud Mariyeyi-Qibtiyyənin yanına getməyəcəyini) demişdi. (Həfsə) bu s&ouml;z&uuml; (digər z&ouml;vcələrdən biri olan Aişəyə) xəbər verdikdə və Allah bunu ona (Peyğəmbərə) əyan etdikdə (Peyğəmbər) bunun bir qismini (Həfsəyə) bildirmiş, (alicənablığı &uuml;z&uuml;ndən) bir qismini bildirməkdən isə vaz ke&ccedil;mişdi. (Peyğəmbər) əhvalatı (Həfsəyə) bildirdikdə o: &ldquo;Bunu sənə kim xəbər verdi?&rdquo; &ndash; deyə soruşmuş, o da: &ldquo;Bunu mənə (hər şeyi) bilən, (hər şeydən) agah olan (Allah) xəbər verdi!&rdquo; &ndash; deyə cavab vermişdi.';
$t[4] = '(Ey Həfsə, ey Aişə!) Əgər ikiniz də (bu hərəkətinizə g&ouml;rə) Allaha t&ouml;vbə etsəniz (&ccedil;ox yaxşı olar). &Ccedil;&uuml;nki (Peyğəmbərə əziyyət verməklə, ona xoş getməyən bir hərəkət etməklə) qəlbləriniz (onun barəsində bir qədər qeyri-səmimiliyə, g&uuml;naha) meyl etdi. Əgər ona (Peyğəmbərə) qarşı bir-birinizə k&ouml;mək etsəniz, (bilin ki, sizə qələbə &ccedil;almaqda) onun m&ouml;vlası (dostu, hamisi) Allah, yardım g&ouml;stərənləri isə Cəbrail, əməlisaleh m&ouml;&rsquo;minlər və bundan sonra da (b&uuml;t&uuml;n) mələklərdir. (Yaxud onun dostu və yardım&ccedil;ıları Allah, Cəbrail, əməlisaleh m&ouml;&rsquo;minlərdir. Bunlardan sonra da mələklər onun yardım&ccedil;ısıdır).';
$t[5] = 'Əgər o sizi boşasa, ola bilsin ki, Rəbbi sizin əvəzinizə ona sizdən daha yaxşı z&ouml;vcələr &ndash; m&uuml;səlman, m&ouml;&rsquo;min, itaətkar, t&ouml;vbəkar, ibadət edən, oruc tutan dul qadınlar və bakirə qızlar versin!';
$t[6] = 'Ey iman gətirənlər! &Ouml;z&uuml;n&uuml;z&uuml; və əhli-əyalınızı elə bir oddan qoruyun ki, onun yanacağı insanlar və daşlar (daşdan d&uuml;zəlmiş b&uuml;tlər), xidmət&ccedil;iləri isə Allahın onlara verdiyi əmrlərə asi olamayan, buyurduqlarını yerinə yetirən daş qəlbli (he&ccedil; kəsə zərrəcə rəhm etməyən) və &ccedil;ox sərt təbiətli mələklərdir (zəbanilərdir).';
$t[7] = '(Kafirlər cəhənnəm oduna atıldıqları zaman onlara belə deyiləcəkdir:) &ldquo;Ey kafir olanlar! Bu g&uuml;n he&ccedil; bir &uuml;zrxahlıq etməyin. Siz ancaq (d&uuml;nyada) t&ouml;rətdiyiniz əməllərin cəzasını &ccedil;əkəcəksiniz!&rdquo;';
$t[8] = 'Ey iman gətirənlər! Allaha səmimi-qəlbdən (bir daha g&uuml;naha qayıtmamaq şərtilə) t&ouml;vbə edin. Ola bilsin ki, Rəbbiniz g&uuml;nahlarınızın &uuml;st&uuml;n&uuml; &ouml;rts&uuml;n və sizi (ağacları) altından &ccedil;aylar axan cənnətlərə daxil etsin. O g&uuml;n Allah &Ouml;z Peyğəmbərini və onunla birlikdə iman gətirənləri xəcil etməz. Onların (iman) nuru (qıl k&ouml;rp&uuml;s&uuml; &uuml;st&uuml;ndə onlara yol g&ouml;stərmək &uuml;&ccedil;&uuml;n) &ouml;nlərindən və sağ tərəflərindən axıb ş&ouml;&rsquo;lə sa&ccedil;arkən onlar belə deyəcəklər: &ldquo;Ey Rəbbimiz! Bizim nurumuzu tamam-kamal elə və bizi bağışla. Həqiqətən, Sən hər şeyə qadirsən!&rdquo;';
$t[9] = 'Ya Peyğəmbər! Kafirlərə qarşı (qılıncla), m&uuml;nafiqlərə qarşı (s&ouml;zlə) vuruş. Onlarla sərt rəftar et. Onların məskəni Cəhənnəmdir. Ora necə də pis sığınacaqdır!';
$t[10] = 'Allah kafirlərə Nuhun &ouml;vrəti ilə Lutun &ouml;vrətini misal &ccedil;əkdi. Onlar Bizim qullarımızdan iki saleh bəndənin kəbini altında idilər. Onlar ərlərinə xəyanət etdilər və (Nuhla Lut) onları Allahdan (Allahın əzabından) he&ccedil; vəchlə qurtara bilmədilər. Onlara: &ldquo;(Başqa) girənlərlə birlikdə siz ikiniz də Cəhənnəmə girin!&rdquo; &ndash; deyildi.';
$t[11] = 'Allah iman gətirənlərə isə Fir&rsquo;onun z&ouml;vcəsini (Asiyə bint Məzahimi) misal &ccedil;əkdi. O zaman o: &ldquo;Ey Rəbbim! Mənim &uuml;&ccedil;&uuml;n &Ouml;z dərgahında &ndash; Cənnətdə bir ev tik. Məni Fir&rsquo;ondan və onun əməlindən qurtar. Məni zalım q&ouml;vmdən xilas et!&rdquo; &ndash; demişdi.';
$t[12] = '(Allah m&ouml;&rsquo;min qadınlara) həm&ccedil;inin namusunu (ismətini) m&ouml;hkəm qoruyub saxlamış İmranın qızı Məryəmi də misal &ccedil;əkdi. Biz (Cəbrail vasitəsilə) libasının yaxasından ona &Ouml;z ruhumuzdan (&Ouml;z yaratdığımız ruhdan) &uuml;f&uuml;rd&uuml;k. Məryəm Rəbbinin s&ouml;zlərini (şəriətini, dini h&ouml;kmlərini), kitablarını təsdiq etdi və (Allaha) itaət edənlərdən oldu.';
?>