<?php
$t = array();
$t[1] = 'Gud har h&oslash;rt hennes innlegg, som talte sin sak overfor deg vedr&oslash;rende sin ektemann, og klaget til Gud. Gud h&oslash;rte deres samtale. Gud h&oslash;rer, er observant.';
$t[2] = 'De blant dere som forst&oslash;ter sine hustruer ved &laquo;ryggformelen&raquo; &ndash; du er meg likegyldig som min mors rygg &ndash; s&aring; er de dog ikke &aring; anse som deres m&oslash;dre. Deres m&oslash;dre er kun de som har f&oslash;dt dem, og de f&oslash;rer forkastelig og falsk tale. Men Gud er visselig unnskyldende og tilgivende.';
$t[3] = 'De som forst&oslash;ter sine hustruer ved &laquo;ryggformelen&raquo;, og s&aring; &oslash;nsker &aring; g&aring; tilbake p&aring; det de sa, de skal sette fri en slave f&oslash;r de to gjenopptar samlivet. Dette formanes dere til. Gud er vel underrettet om det dere gj&oslash;r.';
$t[4] = 'Den som ikke finner &oslash;konomisk utvei, la ham faste i to p&aring;f&oslash;lgende m&aring;neder f&oslash;r de to gjenopptar samlivet. Den som ikke er i stand til dette, la ham bespise seksti fattige. Dette for at dere skal tro p&aring; Gud og Hans sendebud. Dette er grenser som Gud har satt. De vantro venter smertelig straff.';
$t[5] = 'De som setter seg opp mot Gud og Hans sendebud, vil bli kastet til jorden, som de f&oslash;r dem ble kastet over ende. Vi har n&aring; &aring;penbart klar beskjed, og de vantro har ydmykende straff i vente,';
$t[6] = 'den dag Gud gjenoppvekker dem alle og forteller dem hva de bedrev. Gud har notert det, men de har glemt det. Gud er vitne til alle ting.';
$t[7] = 'Ser du ikke at Gud kjenner til alt som er i himlene og p&aring; jord? Det er ingen hemmelig r&aring;dslagning mellom tre, uten at Han er den fjerde, eller fem, uten at Han er den sjette av dem. Heller ikke mellom f&aelig;rre eller flere enn dette, uten at Han er med dem, hvor de enn er. S&aring; vil Han fortelle dem hva de bedrev p&aring; oppstandelsens dag. Gud kjenner til alle ting.';
$t[8] = 'Du har vel sett dem som ble forbudt &aring; holde hemmelige r&aring;d, og s&aring; fortsetter med det som ble dem forbudt, og r&aring;dsl&aring;r med hverandre i synd og fiendskap, og i ulydighet mot Sendebudet? N&aring;r de kommer til deg, hilser de deg med en hilsen som Gud aldri har gitt deg, og sier til seg selv: &laquo;Hvorfor refser ikke Gud oss for det vi sier?&raquo; Helvete er til pass for dem, hvor de m&oslash;ter stekende ild. Hvilken s&oslash;rgelig skjebne!';
$t[9] = 'Dere som tror, n&aring;r dere holder hemmelig r&aring;d, s&aring; r&aring;dsl&aring; ikke i synd og fiendskap og ulydighet mot Sendebudet, men r&aring;dsl&aring; i fromhet og gudsfrykt. Frykt Gud, hos Ham vil dere bli samlet.';
$t[10] = 'Hemmelig r&aring;d er Satans verk, for &aring; gj&oslash;re de troende bedr&oslash;vet, men han kan ikke skade dem det ringeste, uten Guds tillatelse. P&aring; Gud skal de troende forlate seg!';
$t[11] = 'Dere som tror, n&aring;r det sies til dere &laquo;Gi plass&raquo; i forsamlingen, s&aring; gi plass, slik at Gud vil gi dere plass. N&aring;r det sies: &laquo;Reis opp,&raquo; s&aring; reis opp, slik at Gud vil heve opp i rang dem som tror og har f&aring;tt kunnskap. Gud er vel underrettet om hva dere gj&oslash;r.';
$t[12] = 'Dere som tror, n&aring;r dere vil r&aring;dsl&aring; med Sendebudet, s&aring; gi en god gave f&oslash;r deres samtale. Dette er godt og mest s&oslash;mmelig for dere. Men om dere ikke finner &oslash;konomisk utvei, s&aring; er Gud tilgivende, n&aring;derik.';
$t[13] = 'Er dere betenkt p&aring; &aring; gi en god gave f&oslash;r deres samtale? Om dere ikke gj&oslash;r det, og Gud viser overb&aelig;renhet mot dere, s&aring; forrett b&oslash;nnen, betal det rituelle bidrag, og adlyd Gud og Hans sendebud. Gud er vel underrettet om hva dere gj&oslash;r.';
$t[14] = 'Du har vel sett dem som slutter seg til folk som er under Guds vrede? De er ikke av dere og ikke av dem, og de sverger falskt og vet det!';
$t[15] = 'Gud har gjort klar en hard straff for dem. Ille er det de har gjort!';
$t[16] = 'De har gjort sine eder til et dekke, og har lagt hindringer p&aring; Guds vei. Dem venter en ydmykende straff.';
$t[17] = 'Deres rikdom og barn hjelper dem ikke det ringeste mot Gud. Disse er Ildens folk, og der skal de v&aelig;re og bli.';
$t[18] = 'Den dag n&aring;r Gud gjenoppvekker dem alle, s&aring; sverger de overfor Ham som de sverger over dere, og tror de har noe &aring; st&aring; p&aring;. De er visselig l&oslash;gnere!';
$t[19] = 'Satan har f&aring;tt dem i sin makt, og latt dem glemme Guds formaning. Disse utgj&oslash;r Satans parti, og Satans parti, de er visselig tapere!';
$t[20] = 'De som setter seg opp mot Gud og Hans sendebud, disse vil bli av de ynkeligste.';
$t[21] = 'Gud har skrevet: &laquo;Jeg vil visselig seire, Jeg og Mine sendebud.&raquo; Gud er sterk, mektig.';
$t[22] = 'Du vil ikke finne at folk som tror p&aring; Gud og dommens dag, har noe til overs for dem som setter seg opp mot Gud og Hans sendebud, om det s&aring; var deres fedre, deres s&oslash;nner, deres br&oslash;dre eller deres klan. Gud har skrevet troen i deres hjerter og styrket dem med sin &aring;nd. Og Han vil f&oslash;re dem inn i paradisets haver, hvor bekker sildrer, og her skal de v&aelig;re og bli. Gud har funnet velbehag i dem, og de i Ham. Disse utgj&oslash;r Guds parti. Og Guds parti, dem vil det g&aring; godt!';
?>