<?php
$t = array();
$t[1] = 'Slutt dere ikke til Mine og deres fiender, idet dere tilbyr dem sympati, skj&oslash;nt de fornekter det som er blitt dere til del av sannhet, og har fordrevet Sendebudet og dere fordi dere tror p&aring; Gud, deres Herre, om dere er dratt ut for &aring; kjempe for Min sak og &aring; s&oslash;ke Mitt velbehag. Dere betror dem hemmelig sympati, men Jeg vet hva dere skjuler og hva dere b&aelig;rer &aring;pent frem. Den av dere som gj&oslash;r dette, er kommet bort fra den strake vei.';
$t[2] = 'Hvis de kommer over dere, er de deres fiender og retter sine hender og tungens tale mot dere for &aring; gj&oslash;re dere vondt, og &oslash;nsker at dere skal falle fra.';
$t[3] = 'Verken blodsb&aring;nd eller barn skal v&aelig;re til nytte for dere p&aring; oppstandelsens dag. Han vil skille mellom dere. Gud er observant for det dere gj&oslash;r.';
$t[4] = 'I Abraham og de som var med ham, har dere et vakkert eksempel, da de sa til sitt folk: &laquo;Vi er ferdige med dere og det dere tilber utenom Gud! Vi tar avstand fra dere, og mellom dere og oss er oppst&aring;tt fiendskap og hat for alltid, inntil dere m&aring;tte tro p&aring; Gud alene.&raquo; Dog sa Abraham til sin far: &laquo;Jeg skal visselig be om tilgivelse for deg, men jeg har ikke makt til &aring; utrette noe som helst for deg overfor Gud,&raquo; Herre, vi forlater oss p&aring; Deg, og til Deg vender vi oss i bot. Til Deg er reisens m&aring;l!';
$t[5] = 'Herre gj&oslash;r oss ikke til anst&oslash;t for de vantro, men tilgi oss, Herre! Du er den Mektige, Vise.';
$t[6] = 'Det er et vakkert eksempel for dere i dem, for alle som setter sitt h&aring;p til Gud og dommens dag. Men om noen vender seg bort, s&aring; er Gud den Selvtilstrekkelige, den Lovpriste.';
$t[7] = 'Det kan hende at Gud skaper sympati mellom dere og dem dere levde i fiendskap med. Gud evner alt! Gud er tilgivende og n&aring;derik.';
$t[8] = 'Gud forbyr dere ikke &aring; vise respekt og rimelighet mot dem som ikke bekjemper dere for religionens sak, og ikke drev dere bort fra deres hjem. Gud liker dem som viser rimelighet.';
$t[9] = 'Gud forbyr dere bare at dere slutter dere til dem som bekjempet dere for religionens sak, og drev dere bort fra deres hjem eller hjalp til ved utdrivingen. De som sluttet seg til disse, de er urettferdige.';
$t[10] = 'Dere som tror, n&aring;r det kommer til dere troende kvinner som utvandrere, s&aring; sett dem p&aring; pr&oslash;ve. Gud kjenner best til deres tro. Hvis dere s&aring; vet at de er troende, s&aring; send dem ikke tilbake til de vantro. De er ikke tillatt for dem, og de vantro er ikke tillatt for disse. Men gi de vantro det de har lagt ut ved gifterm&aring;l. Dere rammes ikke av skyld om dere gifter dere med dem, s&aring; fremt dere gir dem det de har krav p&aring;. Men hold ikke fast ved b&aring;ndene til vantro kvinner. Krev det dere har lagt ut, og la dem kreve det de har lagt ut. Dette er Guds avgj&oslash;relse. Han treffer avgj&oslash;relse mellom dere. Gud vet, er vis.';
$t[11] = 'Og hvis noen av deres hustruer kommer bort fra dere og til de vantro, s&aring; st&aring; sammen om f&oslash;lgen, og gi dem hvis hustruer er blitt borte, tilsvarende det de har lagt ut. Og frykt Gud, Ham som dere tror p&aring;.';
$t[12] = 'Du profet! N&aring;r troende kvinner kommer til deg og gir deg troskapsed, at de ikke skal sette noen ved Guds side, ikke stjele, ikke beg&aring; utroskap, ikke drepe sine barn, og ikke fare med bakvaskelser som de har grepet ut av luften, og ikke vise deg ulydighet i det som er godt og rett, s&aring; ta imot deres troskapsed og be Gud om tilgivelse for dem. Gud er tilgivende, n&aring;derik.';
$t[13] = 'Dere som tror, slutt dere ikke til folk som er under Guds vrede, som har avskrevet det kommende liv, slik de vantro har avskrevet dem som er i gravene!';
?>