<?php
$t = array();
$t[1] = 'O ihr, die ihr glaubt, kommt nicht Gott und seinem Gesandten zuvor und f&uuml;rchtet Gott. Gott h&ouml;rt und wei&szlig; alles.';
$t[2] = 'O ihr, die ihr glaubt, erhebt nicht eure Stimme &uuml;ber die Stimme des Propheten, und sprecht nicht so laut zu ihm, wie ihr laut zueinander sprecht, damit nicht eure Werke wertlos werden, ohne da&szlig; ihr es merkt.';
$t[3] = 'Diejenigen, die ihre Stimme bei dem Gesandten Gottes d&auml;mpfen, das sind die, deren Herzen Gott auf die Gottesfurcht gepr&uuml;ft hat. Bestimmt ist f&uuml;r sie Vergebung und gro&szlig;artiger Lohn.';
$t[4] = 'Von denen, die dich rufen, w&auml;hrend du dich in den Gem&auml;chern aufh&auml;ltst, haben die meisten keinen Verstand.';
$t[5] = 'W&uuml;rden sie sich gedulden, bis du zu ihnen herauskommst, w&auml;re es besser f&uuml;r sie. Und Gott ist voller Vergebung und barmherzig.';
$t[6] = 'O ihr, die ihr glaubt, wenn ein Frevler mit einer Nachricht zu euch kommt, so stellt es eindeutig fest, damit ihr nicht (einigen) Leuten in Unwissenheit etwas antut und dann bereuen m&uuml;&szlig;t, was ihr getan habt.';
$t[7] = 'Und wi&szlig;t, da&szlig; der Gesandte Gottes unter euch weilt. W&uuml;rde er in vielen Angelegenheiten euch gehorchen, w&uuml;rdet ihr in Bedr&auml;ngnis geraten. Aber Gott hat euch den Glauben lieb und in euren Herzen anziehend gemacht, und Er hat euch den Unglauben, den Frevel und den Ungehorsam verabscheuen lassen. Das sind die, die den rechten Wandel zeigen.';
$t[8] = 'Dies als Huld und Gnade von Gott. Und Gott wei&szlig; Bescheid und ist weise.';
$t[9] = 'Und wenn zwei Gruppen von den Gl&auml;ubigen einander bek&auml;mpfen, so stiftet Frieden zwischen ihnen. Wenn die eine von ihnen gegen die andere in ungerechter Weise vorgeht, dann k&auml;mpft gegen diejenige, die in ungerechter Weise vorgeht, bis sie zum Befehl Gottes umkehrt. Wenn sie umkehrt, dann stiftet Frieden zwischen ihnen nach Gerechtigkeit und handelt dabei gerecht. Gott liebt die, die gerecht handeln.';
$t[10] = 'Die Gl&auml;ubigen sind ja Br&uuml;der. So stiftet Frieden zwischen euren beiden Br&uuml;dern und f&uuml;rchtet Gott, auf da&szlig; ihr Erbarmen findet.';
$t[11] = 'O ihr, die ihr glaubt, die einen sollen nicht die anderen verh&ouml;hnen, vielleicht sind diese eben besser als sie. Auch sollen nicht Frauen andere Frauen verh&ouml;hnen, vielleicht sind diese eben besser als sie. Und n&ouml;rgelt nicht untereinander und gebt einander keine Schimpfnamen. Welch schlimmer Name, der des Frevels, nach der Annahme des Glaubens! Diejenigen, die nicht umkehren, sind die, die Unrecht tun.';
$t[12] = 'O ihr, die ihr glaubt, meidet viel von den Mutma&szlig;ungen. Manche Mutma&szlig;ung ist S&uuml;nde. Spioniert nicht und f&uuml;hrt nicht &uuml;ble Nachrede &uuml;bereinander. M&ouml;chte denn einer von euch das Fleisch seines Bruders, wenn er tot ist, essen? Es w&auml;re euch doch zuwider. F&uuml;rchtet Gott. Gott wendet sich gn&auml;dig zu und ist barmherzig.';
$t[13] = 'O ihr Menschen, Wir haben euch von einem m&auml;nnlichen und einem weiblichen Wesen erschaffen, und Wir haben euch zu Verb&auml;nden und St&auml;mmen gemacht, damit ihr einander kennenlernt. Der Angesehenste von euch bei Gott, das ist der Gottesf&uuml;rchtigste von euch. Gott wei&szlig; Bescheid und hat Kenntnis von allem.';
$t[14] = 'Die arabischen Beduinen sagen: &laquo;Wir glauben.&raquo; Sprich: Ihr glaubt nicht (wirklich). Sagt vielmehr: Wir sind Muslime geworden. Der Glaube ist ja noch nicht in eure Herzen gedrungen. Wenn ihr aber Gott und seinem Gesandten gehorcht, verringert Er euch nichts von euren Werken. Gott ist voller Vergebung und barmherzig.';
$t[15] = 'Die Gl&auml;ubigen, das sind diejenigen, die an Gott und seinen Gesandten glauben und dann nicht zweifeln und sich mit ihrem Verm&ouml;gen und mit ihrer eigenen Person auf dem Weg Gottes einsetzen. Das sind die Wahrhaftigen.';
$t[16] = 'Sprich: Wollt ihr denn Gott &uuml;ber eure Religion belehren, wo Gott wei&szlig;, was in den Himmeln und was auf der Erde ist? Und Gott wei&szlig; &uuml;ber alle Dinge Bescheid.';
$t[17] = 'Sie halten es f&uuml;r eine Wohltat gegen dich, da&szlig; sie Muslime geworden sind. Sprich: Haltet nicht eure Annahme des Islams f&uuml;r eine Wohltat gegen mich. Nein, Gott hat euch eine Wohltat erwiesen dadurch, da&szlig; Er euch zum Glauben gef&uuml;hrt hat, wenn ihr wahrhaftig seid.';
$t[18] = 'Gott kennt das Unsichtbare der Himmel und der Erde. Und Gott sieht wohl, was ihr tut.';
?>