<?php
$t = array();
$t[1] = 'Geh&ouml;rt hat Gott die Aussage jener, die mit dir &uuml;ber ihren Gatten streitet und bei Gott Klage erhebt. Gott h&ouml;rt euren Wortwechsel. Gott h&ouml;rt und sieht alles.';
$t[2] = 'F&uuml;r diejenigen von euch, die sich von ihren Frauen durch den R&uuml;ckenspruch scheiden... Sie sind doch nicht ihre M&uuml;tter. Ihre M&uuml;tter sind die, die sie geboren haben. Sie sagen da ein verwerfliches Wort und etwas Falsches. Und Gott ist voller Verzeihung und Vergebung.';
$t[3] = 'Diejenigen, die sich von ihren Frauen durch den R&uuml;ckenspruch scheiden und dann doch zu dem zur&uuml;ckkehren, wovon sie reden, haben einen Sklaven freizulassen, bevor sie beide einander ber&uuml;hren. Damit werdet ihr ermahnt. Und Gott hat Kenntnis von dem, was ihr tut.';
$t[4] = 'Wer es nicht vermag, der hat zwei Monate hintereinander zu fasten, bevor sie beide einander ber&uuml;hren. Wer es nicht vermag, der hat sechzig Bed&uuml;rftige zu bek&ouml;stigen. Dies, damit ihr an Gott und seinen Gesandten glaubt. Das sind die Rechtsbestimmungen Gottes. F&uuml;r die Ungl&auml;ubigen ist eine schmerzhafte Pein bestimmt.';
$t[5] = 'Diejenigen, die sich Gott und seinem Gesandten widersetzen, werden niedergeworfen, wie die niedergeworfen wurden, die vor ihnen lebten. Wir haben doch deutliche Zeichen hinabgesandt. Und f&uuml;r die Ungl&auml;ubigen ist eine schm&auml;hliche Pein bestimmt.';
$t[6] = 'Am Tag, da Gott sie alle auferweckt und ihnen kundtut, was sie getan haben. Gott hat es erfa&szlig;t, w&auml;hrend sie es vergessen haben. Und Gott ist Zeuge &uuml;ber alle Dinge.';
$t[7] = 'Hast du nicht gesehen, da&szlig; Gott wei&szlig;, was in den Himmeln und was auf der Erde ist? Es gibt kein vertrauliches Gespr&auml;ch zwischen dreien, ohne da&szlig; Er der vierte in ihrer Runde w&auml;re, und keines zwischen f&uuml;nfen, ohne da&szlig; Er der Sechste in ihrer Runde w&auml;re, und auch nicht zwischen weniger oder mehr als dieser (Zahl), ohne da&szlig; Er mit ihnen w&auml;re, wo immer sie sein m&ouml;gen. Dann tut Er ihnen am Tag der Auferstehung kund, was sie getan haben. Gott wei&szlig; &uuml;ber alle Dinge Bescheid.';
$t[8] = 'Hast du nicht auf jene geschaut, denen verboten wurde, vertrauliche Gespr&auml;che zu f&uuml;hren, die aber dann zur&uuml;ckkehren zu dem, was ihnen verboten wurde und miteinander &uuml;ber S&uuml;nde, &Uuml;bertretung und Ungehorsam gegen den Gesandten vertraulich sprechen? Und wenn sie zu dir kommen, gr&uuml;&szlig;en sie dich, wie nicht einmal Gott dich gr&uuml;&szlig;t, und sagen bei sich: &laquo;K&ouml;nnte Gott uns nur peinigen f&uuml;r das, was wir sagen!&raquo; Ihnen gen&uuml;gt doch die H&ouml;lle, in der sie brennen worden - welch schlimmes Ende!';
$t[9] = 'O ihr, die ihr glaubt, wenn ihr vertraulich miteinander sprecht, dann sprecht nicht vertraulich miteinander &uuml;ber S&uuml;nde, &Uuml;bertretung und Ungehorsam gegen den Gesandten, sondern sprecht vertraulich miteinander &uuml;ber Fr&ouml;mmigkeit und Gottesfurcht. Und f&uuml;rchtet Gott, zu dem ihr versammelt werdet.';
$t[10] = 'Vertrauliche Gespr&auml;che sind vom Satan, der damit die betr&uuml;ben will, die gl&auml;ubig sind. Aber er kann ihnen keinen Schaden zuf&uuml;gen, au&szlig;er mit der Erlaubnis Gottes. Auf Gott sollen die Gl&auml;ubigen vertrauen.';
$t[11] = 'O ihr, die ihr glaubt, wenn zu euch gesagt wird: &laquo;Macht Platz in den Versammlungen.&raquo;, dann macht Platz, so macht auch Gott euch Platz. Und wenn gesagt wird: &laquo;Erhebt euch.&raquo;, dann erhebt euch eben, so erh&ouml;ht auch Gott diejenigen von euch, die glauben, und die, denen das Wissen zugekommen ist, um Rangstufen. Und Gott hat Kenntnis von dem, was ihr tut.';
$t[12] = 'O ihr, die ihr glaubt, wenn ihr mit dem Gesandten vertraulich sprechen wollt, dann gebt vor eurem vertraulichen Gespr&auml;ch im voraus ein Almosen. Das ist besser und reiner f&uuml;r euch. Wenn ihr es nicht verm&ouml;gt, dann ist Gott voller Vergebung und barmherzig.';
$t[13] = 'Seid ihr erschrocken davor, da&szlig; ihr vor eurem vertraulichen Gespr&auml;ch im voraus Almosen geben sollt? Nun, wenn ihr es nicht tut und Gott sich euch wieder gn&auml;dig zuwendet, dann verrichtet das Gebet und entrichtet die Abgabe, und gehorcht Gott und seinem Gesandten. Und Gott hat Kenntnis von dem, was ihr tut.';
$t[14] = 'Hast du nicht auf jene geschaut, die sich Leute zu Freunden nehmen, auf die Gott zornig ist? Sie geh&ouml;ren nicht zu euch, und auch nicht zu ihnen. Und sie leisten wissentlich falsche Eide.';
$t[15] = 'Gott hat f&uuml;r sie eine harte Pein bereitet. Schlimm ist das, was sie zu tun pflegen.';
$t[16] = 'Sie haben sich ihre Eide zu einem Schutzschild genommen und so (die Menschen) vom Weg Gottes abgewiesen. Bestimmt ist f&uuml;r sie eine schm&auml;hliche Pein.';
$t[17] = 'Ihr Verm&ouml;gen und ihre Kinder werden ihnen vor Gott nichts n&uuml;tzen. Das sind die Gef&auml;hrten des Feuers; darin werden sie ewig weilen.';
$t[18] = 'Am Tag, da Gott sie alle auferweckt. Da werden sie Ihm schw&ouml;ren, wie sie euch schw&ouml;ren, und meinen, sie h&auml;tten nun eine Grundlage. Siehe, sie sind ja doch L&uuml;gner.';
$t[19] = 'Der Satan hat von ihnen Besitz ergriffen und sie die Ermahnung Gottes vergessen lassen. Sie sind die Partei des Satans. Siehe, die Partei des Satans sind ja doch die Verlierer.';
$t[20] = 'Diejenigen, die sich Gott und seinem Gesandten widersetzen, die geh&ouml;ren zu den Niedrigsten.';
$t[21] = 'Gott hat vorgeschrieben: &laquo;Siegen werde Ich, Ich und meine Gesandten.&raquo; Gott ist stark und m&auml;chtig.';
$t[22] = 'Du wirst nicht feststellen, da&szlig; Leute, die an Gott und den J&uuml;ngsten Tag glauben, denen Liebe zeigen, die sich Gott und seinem Gesandten widersetzen, auch wenn sie ihre V&auml;ter w&auml;ren oder ihre S&ouml;hne, ihre Br&uuml;der oder ihre Sippenmitglieder. In deren Herzen hat Er den Glauben geschrieben und sie mit einem Geist von sich gest&auml;rkt. Er wird sie in G&auml;rten eingehen lassen, unter denen B&auml;che flie&szlig;en; darin werden sie ewig weilen. Gott hat Wohlgefallen an ihnen, und sie haben Wohlgefallen an Ihm. Sie sind die Partei Gottes. Siehe, die Partei Gottes sind die, denen es wohl ergeht.';
?>