<?php
$t = array();
$t[1] = 'Gott preist, was in den Himmeln und was auf der Erde ist. Und Er ist der M&auml;chtige, der Weise.';
$t[2] = 'Er ist es, der diejenigen von den Leuten des Buches, die ungl&auml;ubig sind, aus ihren Wohnst&auml;tten zur ersten Versammlung vertrieben hat. Ihr habt nicht geglaubt, da&szlig; sie fortziehen w&uuml;rden; auch sie meinten, ihre Festungen w&uuml;rden sie vor Gott sch&uuml;tzen. Da kam Gott &uuml;ber sie, von wo sie nicht damit rechneten, und jagte ihren Herzen Schrecken ein, so da&szlig; sie ihre H&auml;user mit ihren eigenen H&auml;nden und durch die H&auml;nde der Gl&auml;ubigen zerst&ouml;rten. Zieht nun die Lehre daraus, ihr Einsichtigen.';
$t[3] = 'Und h&auml;tte Gott ihnen nicht die Verbannung vorgeschrieben, Er h&auml;tte sie im Diesseits gepeinigt. Im Jenseits aber erhalten sie die Pein des Feuers.';
$t[4] = 'Dies daf&uuml;r, da&szlig; sie sich Gott und seinem Gesandten widersetzten. Und wenn jemand sich Gott widersetzt, so verh&auml;ngt Gott eine harte Strafe.';
$t[5] = 'Was ihr an Palmen umgehauen habt oder auf ihrem Stamm habt stehenlassen, es geschah mit der Erlaubnis Gottes, auch damit Er die Frevler zuschanden mache.';
$t[6] = 'Und f&uuml;r das, was Gott seinem Gesandten von ihnen als Beute zugeteilt hat, habt ihr weder Pferde noch Kamele anspornen m&uuml;ssen. Gott verleiht vielmehr seinen Gesandten Gewalt, &uuml;ber wen Er will. Und Gott hat Macht zu allen Dingen.';
$t[7] = 'Was Gott seinem Gesandten von den Bewohnern der St&auml;dte als Beute zugeteilt hat, geh&ouml;rt Gott und seinem Gesandten, und den Verwandten, den Waisen, den Bed&uuml;rftigen, dem Reisenden. Dies, damit es nicht eben unter den Reichen von euch die Runde macht. Und was der Gesandte euch zukommen l&auml;&szlig;t, das sollt ihr nehmen. Und was er euch verwehrt, davon sollt ihr euch fernhalten. Und f&uuml;rchtet Gott. Gott verh&auml;ngt eine harte Strafe.';
$t[8] = '(Das geh&ouml;rt) den armen Auswanderern, die aus ihren Wohnst&auml;tten und von ihrem Besitz vertrieben wurden, die nach Gottes Huld und Wohlgefallen streben und Gott und seinen Gesandten unterst&uuml;tzen. Das sind die Wahrhaftigen.';
$t[9] = 'Und diejenigen, die vor ihnen in der Wohnst&auml;tte und im Glauben zu Hause waren, lieben die, die zu ihnen ausgewandert sind; sie empfinden in ihrem Inneren kein Bed&uuml;rfnis f&uuml;r das, was diesen zugekommen ist, und sie bevorzugen sie vor sich selbst, auch wenn sie selbst Not leiden. Und diejenigen, die vor ihrer eigenen Habsucht bewahrt bleiben, sind die, denen es wohl ergeht.';
$t[10] = 'Und diejenigen, die nach ihnen gekommen sind, sagen: &laquo;Unser Herr, vergib uns und unseren Br&uuml;dern, die uns im Glauben vorangegangen sind. Und setze in unsere Herzen keinen Groll gegen die, die glauben. Unser Herr, du hast Mitleid und bist barmherzig.&raquo;';
$t[11] = 'Hast du nicht auf jene geschaut, die Heuchler sind? Sie sagen zu ihren Br&uuml;dern von den Leuten des Buches, welche ungl&auml;ubig sind: &laquo;Wenn ihr vertrieben werdet, werden wir mit euch fortziehen. Und wir werden niemals jemandem gegen euch gehorchen. Und wenn gegen euch gek&auml;mpft wird, dann werden wir euch bestimmt unterst&uuml;tzen.&raquo; Und Gott bezeugt, da&szlig; sie ja l&uuml;gen.';
$t[12] = 'Wenn sie vertrieben werden, werden sie nicht mit ihnen fortziehen. Und wenn gegen sie gek&auml;mpft wird, werden sie sie nicht unterst&uuml;tzen. Und sollten sie sie unterst&uuml;tzen, dann werden sie den R&uuml;cken kehren, und dann werden sie selbst keine Unterst&uuml;tzung erfahren.';
$t[13] = 'Ihr fl&ouml;&szlig;t ihnen mehr Angst ein als Gott. Dies, weil sie Leute sind, die nicht begreifen.';
$t[14] = 'Sie k&auml;mpfen nicht alle zusammen gegen euch, es sei denn in befestigten St&auml;dten oder hinter Mauern. Ihre Schlagkraft ist untereinander gewaltig. Du meinst, sie bilden eine Einheit, aber ihre Herzen sind geteilt. Dies, weil sie Leute sind, die keinen Verstand haben.';
$t[15] = 'Es ist wie mit denen, die es kurz vor ihnen erlebten. Sie erlitten die schweren Folgen ihres Verhaltens, und f&uuml;r sie ist eine schmerzhafte Pein bestimmt.';
$t[16] = 'Es ist wie mit dem Satan, als er zum Menschen sagte: &laquo;Sei ungl&auml;ubig.&raquo; Als er ungl&auml;ubig wurde, sagte er: &laquo;Ich bin unschuldig an dir. Ich f&uuml;rchte Gott, den Herrn der Welten.&raquo;';
$t[17] = 'Das Ende von beiden war, da&szlig; sie nun im Feuer sind; darin werden sie ewig weilen. Und das ist die Vergeltung f&uuml;r die, die Unrecht tun.';
$t[18] = 'O ihr, die ihr glaubt, f&uuml;rchtet Gott. Und jeder schaue, was er f&uuml;r morgen vorausschickt. Und f&uuml;rchtet Gott. Gott hat Kenntnis von dem, was ihr tut.';
$t[19] = 'Und seid nicht wie diejenigen, die Gott vergessen haben und die Er dann sich selbst vergessen lie&szlig;. Das sind die Frevler.';
$t[20] = 'Nicht gleich sind die Gef&auml;hrten des Feuers und die Gef&auml;hrten des Paradieses. Die Gef&auml;hrten des Paradieses sind es, die den Erfolg erzielen.';
$t[21] = 'H&auml;tten Wir diesen Koran auf einen Berg hinabgesandt, du h&auml;ttest gesehen, wie er aus Furcht vor Gott dem&uuml;tig inneh&auml;lt und sich spaltet. Diese Gleichnisse f&uuml;hren Wir den Menschen an, auf da&szlig; sie nachdenken.';
$t[22] = 'Er ist Gott, au&szlig;er dem es keinen Gott gibt, der &uuml;ber das Unsichtbare und das Offenbare Bescheid wei&szlig;. Er ist der Erbarmer, der Barmherzige.';
$t[23] = 'Er ist Gott, au&szlig;er dem es keinen Gott gibt, der K&ouml;nig, der Heilige, der Inbegriff des Friedens, der Stifter der Sicherheit, der alles fest in der Hand hat, der M&auml;chtige, der Gewaltige, der Stolze. Preis sei Gott! (Er ist erhaben) &uuml;ber das, was sie (Ihm) beigesellen.';
$t[24] = 'Er ist Gott, der Sch&ouml;pfer, der Erschaffer, der Bildner. Sein sind die sch&ouml;nsten Namen. Ihn preist, was in den Himmeln und auf der Erde ist. Und Er ist der M&auml;chtige, der Weise.';
?>