<?php
$t = array();
$t[1] = 'O ihr, die ihr glaubt, nehmt euch nicht meine Feinde und eure Feinde zu Freunden, indem ihr ihnen Liebe entgegenbringt, wo sie doch das verleugnen, was von der Wahrheit zu euch gekommen ist, und den Gesandten und euch selbst vertreiben, weil ihr an Gott, euren Herrn, glaubt. (Haltet euch daran), wenn ihr wirklich ausgezogen seid zum Einsatz auf meinem Weg und im Streben nach meinem Wohlgefallen. Ihr zeigt ihnen heimlich Liebe, wo Ich doch besser wei&szlig;, was ihr verbergt und was ihr offenlegt. Und wer von euch das tut, der ist vom rechten Weg abgeirrt.';
$t[2] = 'Wenn sie euch treffen, sind sie euch feind und strecken gegen euch ihre H&auml;nde und ihre Zungen zum B&ouml;sen aus. Sie w&uuml;nschten, ihr w&auml;ret ungl&auml;ubig.';
$t[3] = 'Weder eure Verwandtschaftsbande noch eure Kinder werden euch n&uuml;tzen. Am Tag der Auferstehung wird Gott zwischen euch entscheiden. Und Gott sieht wohl, was ihr tut.';
$t[4] = 'Ihr habt doch ein sch&ouml;nes Beispiel in Abraham und denen, die mit ihm waren, als sie zu ihrem Volk sagten: &laquo;Wir sind unschuldig an euch und an dem, was ihr anstelle Gottes verehrt. Wir verleugnen euch. Und zwischen uns und euch sind Feindschaft und Ha&szlig; auf immer sichtbar geworden, bis ihr an Gott allein glaubt.&raquo; Dies, bis auf das Wort Abrahams zu seinem Vater: &laquo;Ich werde f&uuml;r dich um Vergebung bitten. Und ich kann dir vor Gott keinen Nutzen bringen. Unser Herr, auf Dich vertrauen wir, und Dir wenden wir uns reum&uuml;tig zu. Und zu Dir f&uuml;hrt der Lebensweg.';
$t[5] = 'Unser Herr, mach uns nicht zu einer Versuchung f&uuml;r die, die ungl&auml;ubig sind. Und vergib uns, unser Herr. Du bist der M&auml;chtige, der Weise.&raquo;';
$t[6] = 'Ihr habt in ihnen ein sch&ouml;nes Beispiel, und zwar jeder, der auf Gott hofft und den J&uuml;ngsten Tag erwartet. Wenn einer sich abkehrt, so ist Gott der, der auf niemanden angewiesen und des Lobes w&uuml;rdig ist.';
$t[7] = 'M&ouml;ge Gott zwischen euch und die von ihnen, mit denen ihr verfeindet seid, Liebe setzen! Und Gott ist m&auml;chtig. Und Gott ist voller Vergebung und barmherzig.';
$t[8] = 'Gott verbietet euch nicht, denen, die nicht gegen euch der Religion wegen gek&auml;mpft und euch nicht aus euren Wohnst&auml;tten vertrieben haben, Piet&auml;t zu zeigen und Gerechtigkeit angedeihen zu lassen. Gott liebt ja die, die gerecht handeln.';
$t[9] = 'Gott verbietet Euch, die, die gegen euch der Religion wegen gek&auml;mpft und euch aus euren Wohnst&auml;tten vertrieben und zu eurer Vertreibung Beistand geleistet haben, zu Freunden zu nehmen. Diejenigen, die sie zu Freunden nehmen, das sind die, die Unrecht tun.';
$t[10] = 'O ihr, die ihr glaubt, wenn gl&auml;ubige Frauen als Auswanderer zu euch kommen, dann pr&uuml;ft sie. Gott wei&szlig; besser &uuml;ber ihren Glauben Bescheid. Wenn ihr feststellt, da&szlig; sie gl&auml;ubig sind, dann schickt sie nicht zu den Ungl&auml;ubigen zur&uuml;ck. Zur Ehe sind weder diese (Frauen) ihnen erlaubt, noch sind sie diesen (Frauen) erlaubt. Und la&szlig;t ihnen jedoch zukommen, was sie (seinerzeit f&uuml;r diese Frauen) ausgegeben haben. Es ist f&uuml;r euch kein Vergehen, sie zu heiraten, wenn ihr ihnen ihren Lohn zukommen la&szlig;t. Und haltet nicht am Eheband mit den ungl&auml;ubigen Frauen fest, und fordert, was ihr (bei der Eheschlie&szlig;ung) ausgegeben habt, zur&uuml;ck. Auch sie sollen zur&uuml;ckfordern, was sie ausgegeben haben. Das ist das Urteil Gottes; Er urteilt zwischen euch. Und Gott wei&szlig; Bescheid und ist weise.';
$t[11] = 'Und wenn euch etwas von euren Gattinnen an die Ungl&auml;ubigen abhanden kommt und ihr nach einer Strafaktion Beute macht, dann la&szlig;t denen, deren Gattinnen fortgegangen sind, soviel zukommen, wie sie ausgegeben haben. Und f&uuml;rchtet Gott, an den ihr glaubt.';
$t[12] = 'O Prophet, wenn gl&auml;ubige Frauen zu dir kommen, um dir Treue zu geloben, da&szlig; sie Gott nichts beigesellen, nicht stehlen, keinen Ehebruch begehen, ihre Kinder nicht t&ouml;ten, keine Verleumdung vorbringen, die sie vor ihren eigenen H&auml;nden und F&uuml;&szlig;en erdichten, und gegen dich nicht ungehorsam sind in dem, was recht ist, dann nimm ihr Treueversprechen an und bitte Gott f&uuml;r sie um Vergebung. Gott ist voller Vergebung und barmherzig.';
$t[13] = 'O ihr, die ihr glaubt, nehmt nicht Leute zu Freunden, auf die Gott zornig ist. Sie haben die Hoffnung auf das Jenseits aufgegeben, so wie die Ungl&auml;ubigen die Hoffnung aufgegeben haben in bezug auf die (Toten) in den Gr&auml;bern.';
?>