<?php
$t = array();
$t[1] = 'O Prophet, wenn ihr die Frauen entla&szlig;t, dann entla&szlig;t sie unter Beachtung ihrer Wartezeit, und berechnet die Wartezeit (sorgf&auml;ltig). Und f&uuml;rchtet Gott, euren Herrn. Weiset sie nicht aus ihren H&auml;usern aus. Sie sollen auch nicht selbst ausziehen, es sei denn, sie begehen eine offenkundige sch&auml;ndliche Tat. Das sind die Rechtsbestimmungen Gottes. Wer die Rechtsbestimmungen Gottes &uuml;bertritt, der tut sich selbst Unrecht. Du wei&szlig;t nicht, ob nicht Gott vielleicht danach eine neue Lage herbeif&uuml;hrt.';
$t[2] = 'Wenn sie das Ende ihrer Frist erreichen, dann behaltet sie in rechtlicher Weise oder trennt euch von ihnen in rechtlicher Weise. Und nehmt zwei gerechte Leute von euch zu Zeugen, und erhaltet das Zeugnis Gottes aufrecht. Damit wird derjenige ermahnt, der an Gott und den J&uuml;ngsten Tag glaubt. Und wer Gott f&uuml;rchtet, dem schafft Er einen Ausweg';
$t[3] = 'Und beschert Unterhalt, von wo er damit nicht rechnet. Und wer auf Gott vertraut, dem gen&uuml;gt Er. Gott erzielt sein Anliegen. Gott legt f&uuml;r jede Sache ein Ma&szlig; fest.';
$t[4] = 'Und f&uuml;r die von euren Frauen, die keine Menstruation mehr erwarten, falls ihr da Zweifel hegt, gilt eine Wartezeit von drei Monaten. Und ebenso f&uuml;r die, die keine Menstruation haben. F&uuml;r die, die schwanger sind, ist die Frist erreicht, wenn sie geb&auml;ren, was sie (in ihrem Leib) tragen. Und wer Gott f&uuml;rchtet, dem schafft Er Erleichterung in seiner Angelegenheit.';
$t[5] = 'Das ist die Anordnung Gottes, die Er zu euch herabgesandt hat. Und wer Gott f&uuml;rchtet, dem s&uuml;hnt Er seine Missetaten und dem verleiht Er einen gro&szlig;artigen Lohn.';
$t[6] = 'La&szlig;t sie dort wohnen, wo ihr selbst wohnt, euren M&ouml;glichkeiten entsprechend. Und f&uuml;gt ihnen keinen Schaden zu, um sie in Bedr&auml;ngnis zu bringen. Und wenn sie schwanger sind, dann &uuml;bernehmt f&uuml;r sie die n&ouml;tigen Aufwendungen, bis sie geb&auml;ren, was sie (in ihrem Leib) tragen. Wenn sie f&uuml;r euch das Kind stillen, dann la&szlig;t ihnen ihren Lohn zukommen, und beratet euch untereinander (dar&uuml;ber) in rechtlicher Weise. Und wenn ihr euch schwer einigen k&ouml;nnt, dann wird wohl eine andere (das Kind) f&uuml;r ihn stillen.';
$t[7] = 'Der Wohlhabende soll entsprechend seinem Verm&ouml;gen die Aufwendungen gestalten. Und wem der Unterhalt bemessen zugeteilt wurde, der soll von dem ausgeben, was Gott ihm hat zukommen lassen. Gott fordert von einem nur das, was Er ihm hat zukommen lassen. Gott wird nach der schwierigen Lage Erleichterung schaffen.';
$t[8] = 'Und wie manche Stadt rebellierte gegen den Befehl ihres Herrn und seiner Gesandten, worauf Wir sie einer harten Abrechnung unterzogen und mit einer entsetzlichen Pein peinigten.';
$t[9] = 'Da erlitt sie die schweren Folgen ihres Verhaltens. Und das Ende ihres Verhaltens war (nur) Verlust.';
$t[10] = 'Gott hat f&uuml;r sie eine harte Pein bereitet. So f&uuml;rchtet Gott, ihr Einsichtigen, die ihr glaubt. Gott hat zu euch eine Ermahnung herabgesandt,';
$t[11] = 'Einen Gesandten, der euch die Zeichen Gottes, die alles deutlich machen, verliest, um die, die glauben und die guten Werke tun, aus den Finsternissen ins Licht hinauszuf&uuml;hren. Und wer an Gott glaubt und Gutes tut, den wird Er in G&auml;rten eingehen lassen, unter denen B&auml;che flie&szlig;en; darin werden sie auf immer ewig weilen. Gott hat ihm (damit) einen sch&ouml;nen Unterhalt gew&auml;hrt.';
$t[12] = 'Gott ist es, der sieben Himmel erschaffen hat, und von der Erde gleich viel. Der Befehl (Gottes) kommt zwischen ihnen herab, damit ihr wi&szlig;t, da&szlig; Gott Macht hat zu allen Dingen und da&szlig; Gott alle Dinge mit seinem Wissen umfa&szlig;t.';
?>