<?php
$t = array();
$t[1] = 'O Prophet, warum erkl&auml;rst du f&uuml;r verboten, was Gott dir erlaubt hat, im Streben danach, deinen Gattinnen zu gefallen? Gott ist voller Vergebung und barmherzig.';
$t[2] = 'Gott hat f&uuml;r euch festgelegt, wie eure Eide zu l&ouml;sen sind. Und Gott ist euer Schutzherr, und Er ist der, der Bescheid wei&szlig; und weise ist.';
$t[3] = 'Als der Prophet einer seiner Gattinnen einige Worte im geheimen anvertraute. Als sie sie dann mitteilte und Gott ihm dar&uuml;ber Auskunft gab, gab er einen Teil davon bekannt und &uuml;berging einen anderen Teil. Als er es ihr nun mitteilte, sagte sie: &laquo;Wer hat dir das kundgetan?&raquo; Er sagte: &laquo;Kundgetan hat (es) mir der, der Bescheid wei&szlig; und Kenntnis (von allem) hat.';
$t[4] = 'Wenn ihr beide zu Gott umkehrt - eure Herzen waren ja dem Gerede zugeneigt -... Und wenn ihr einander gegen ihn Beistand leistet, so ist Gott sein Schutzherr, und Gabriel, die Rechtschaffenen von den Gl&auml;ubigen und au&szlig;erdem die Engel werden (ihm) Beistand leisten.';
$t[5] = 'M&ouml;ge sein Herr ihm, wenn er euch (alle) entl&auml;&szlig;t, zum Tausch andere Gattinnen geben, die besser sind als ihr: muslimische Frauen, die gl&auml;ubig und dem&uuml;tig ergeben sind, bereit zur Umkehr sind, (Gott) dienen und umherziehen, ob sie fr&uuml;her verheiratet waren oder Jungfrauen sind.';
$t[6] = 'O ihr, die ihr glaubt, h&uuml;tet euch selbst und eure Angeh&ouml;rigen vor einem Feuer, dessen Brennstoff Menschen und Steine sind und &uuml;ber das hartherzige und strenge Engel gesetzt sind, die gegen Gott nicht ungehorsam sind in dem, was Er ihnen befiehlt, sondern tun, was ihnen befohlen wird.';
$t[7] = 'O ihr, die ihr ungl&auml;ubig seid, entschuldigt euch heute nicht. Euch wird nur das vergolten, was ihr zu tun pflegtet.';
$t[8] = 'O ihr, die ihr glaubt, kehrt zu Gott um in aufrichtiger Umkehr. M&ouml;ge Gott euch eure Missetaten s&uuml;hnen und euch in G&auml;rten eingehen lassen, unter denen B&auml;che flie&szlig;en, am Tag, da Gott den Propheten und die, die mit ihm gl&auml;ubig sind, nicht zuschanden macht! Ihr Licht eilt vor ihnen und zu ihrer Rechten her. Sie sagen: &laquo;Unser Herr, vollende f&uuml;r uns unser Licht und vergib uns. Du hast Macht zu allen Dingen.&raquo;';
$t[9] = 'O Prophet, setze dich gegen die Ungl&auml;ubigen und die Heuchler ein und fasse sie hart an. Ihre Heimst&auml;tte ist die H&ouml;lle - welch schlimmes Ende!';
$t[10] = 'Gott hat f&uuml;r die, die ungl&auml;ubig sind, die Frau Noachs und die Frau Lots als Beispiel angef&uuml;hrt. Sie beide unterstanden zwei Dienern von unseren rechtschaffenen Dienern. Aber sie waren treulos zu ihnen, so konnten ihnen diese vor Gott nichts n&uuml;tzen. Und es wurde gesagt: &laquo;Geht ins Feuer ein mit denen, die hineingehen.&raquo;';
$t[11] = 'Und Gott hat f&uuml;r die, die glauben, die Frau des Pharao als Beispiel angef&uuml;hrt. Als sie sagte: &laquo;Mein Herr, baue mir ein Haus bei Dir im Paradies, und errette mich von Pharao und seinem Handeln, und errette mich von den Leuten, die Unrecht tun.&raquo;';
$t[12] = 'Und (auch) Maria, die Tochter, Imraans, die ihre Scham unter Schutz stellte, worauf Wir in sie von unserem Geist bliesen. Und sie hielt die Worte ihres Herrn und seine B&uuml;cher f&uuml;r wahr und geh&ouml;rte zu denen, die (Gott) dem&uuml;tig ergeben sind.';
?>