<?php
$t = array();
$t[1] = 'Y&atilde; ku waɗanda suka yi ĩm&atilde;ni! Kada ku gab&atilde;ta (da k&otilde;me) gaba ga Allah da ManzonSa. Kuma ku yi ɗ&atilde;\'&atilde; ga Allah da taƙawa. Lalle Allah Mai ji ne, Masani.';
$t[2] = 'Y&atilde; kũ waɗanda suka yi ĩmani! Kada ku ɗaukaka saututtukanku bisa sautin Annabi, kuma kada ku bayyana sauti gare shi a magana, kamar bayyan&atilde;war s&atilde;shenku ga s&atilde;she, d&otilde;min kada ayyukanku su ɓ&atilde;ci, alh&atilde;li kuwa kũ ba ku sani ba.';
$t[3] = 'Lalle waɗanda ke runtsẽwar saututtukansu a wurin Manzon Allah waɗannan ne waɗanda Allah Y&atilde;, jarrabi zuk&atilde;tansu ga taƙawa. Sun&atilde; da wata irin g&atilde;fara da ij&atilde;ra mai girma.';
$t[4] = 'Lalle waɗanda ke kiranka daga b&atilde;yan ɗakuna, mafi Yawansu b&atilde; su aiki da hankali.';
$t[5] = 'Kuma d&atilde; lalle sũ, sun yi haƙuri har ka fita zuwa gare su, haƙĩƙa, d&atilde; y&atilde; kasance mafi alhẽri gare su, kuma Allah Mai g&atilde;fara ne, Mai jin ƙai.';
$t[6] = 'Y&atilde; kũ waɗanda suka yi ĩm&atilde;ni! Idan f&atilde;siƙi Y&atilde; zo muku da wani babban l&atilde;b&atilde;ri, to, ku nẽmi bay&atilde;ni, d&otilde;min kada ku cũci waɗansu mut&atilde;ne a cikin j&atilde;hilci, sab&otilde;da haka ku w&atilde;yi gari a kan abin da kuka aikata kun&atilde; m&atilde;su nad&atilde;ma.';
$t[7] = 'Kuma ku sani (cẽwa) lalle ne, a cikinku akwai Manzon Allah. D&atilde; Yana bin ku ga (h&atilde;l&atilde;ye) m&atilde;su Yawa na al\'amarin, d&atilde; kun auku a cikin zunubi, kuma amma Allah Y&atilde; s&otilde;yar da ĩm&atilde;ni a gare ku, kuma Y&atilde; ƙaw&atilde;ta shi a cikin zuk&atilde;tanku kuma Y&atilde; ƙy&atilde;mantar da k&atilde;firci da f&atilde;sicci da s&atilde;ɓo zuwa gare ku. Waɗannan (da suka lazimci sif&otilde;fin nan) su ne shiryayyu.';
$t[8] = 'Bisa ga falala daga Allah da ni\'ima. Kuma Allah Masani ne, Mai hikima.';
$t[9] = 'Kuma idan jama\'a biyu ta mũminai suka yi y&atilde;ki, to, kuyi sulhu, a tsak&atilde;ninsu. Sai idan ɗayansu ta yi z&atilde;lunci a kan gudar, to, sai ku y&atilde;ƙi wadda ke yin z&atilde;lunci har ta k&otilde;ma, zuwa ga umurnin Allah. To, idan ta k&otilde;ma, sai ku yi sulhu a tsak&atilde;ninsu da &atilde;dalci kuma ku daidaita. Lalle Allah na son m&atilde;su daidait&atilde;wa.';
$t[10] = 'Mũminai \'yan\'uwan jũna kawai ne, sab&otilde;da haka ku yi sulhu a tsak&atilde;nin \'yan\'uwanku biyu, kuma ku bi Allah da taƙawa tsamm&atilde;ninku, a yi muku rahama.';
$t[11] = '&quot;Y&atilde; ku waɗanda suka yi ĩm&atilde;ni! Kada waɗansu mut&atilde;ne su yi izgili game da waɗansu mut&atilde;ne, mai yiwuwa ne (abin yi wa izgilin) su kasance mafifita daga gare su (m&atilde;su izgilin), kuma waɗansu m&atilde;t&atilde; kada su yi izgili game da waɗansu m&atilde;t&atilde; mai yiwuwa ne su kasancc mafĩfĩta daga gare su. Kuma kada ku aibanta kanku, kuma kada ku jẽfi jũna da miy&atilde;gun sun&atilde;ye na laƙab&otilde;bĩ. Tir da sũna na f&atilde;sicci a b&atilde;y&atilde;n ĩm&atilde;ni. Kuma wanda bai tũba ba, to, waɗannan sũ ne azz&atilde;lumai.&quot;';
$t[12] = 'Y&atilde; kũ waɗanda suka yi ĩm&atilde;ni! Ku nĩsanci abu mai y&atilde;wa na zato. Lalle s&atilde;shen zato laifi ne. Kuma kada ku yi rah&otilde;to, kuma kada s&atilde;shenku y&atilde; yi gulmar s&atilde;she. Shin, ɗayanku n&atilde; son y&atilde; ci naman ɗan\'uwansa yan&atilde; matacce? To, kun ƙĩ shi (cin n&atilde;man). Kuma ku bi Allah da taƙawa. Lalle Allah Mai karɓar tũba ne, Mai jin ƙai.';
$t[13] = 'Y&atilde; kũ mut&atilde;ne! Lalle ne Mũ, Mun halitta ku daga namiji da mace, kuma Muka sanya ku dang&otilde;gi da kabĩl&otilde;li, d&otilde;min ku san jũna. Lalle mafĩfĩcinku daraja a wurin Allah, (shĩ ne) wanda yake mafĩfĩcinku a taƙawa. Lalle nẽ Allah Masani ne, Mai ƙididdigẽwa.';
$t[14] = '&iexcl;auy&atilde;wa suka ce: &quot;Mun yi ĩm&atilde;ni.&quot; Ka ce: &quot;Ba ku yi ĩm&atilde;ni ba, amma dai ku ce, \'Mun mĩƙawuya, ĩmani bai gama shiga a cikinzuk&atilde;tanku ba. Kuma idan kun yi ɗ&atilde;\'a ga Allah da ManzonSa, to, b&atilde; zai rage muku k&otilde;me daga ayyukanku ba. Lalle Allah Mai g&atilde;fara ne, Mai jin ƙai.&quot;';
$t[15] = 'Mũminan gaskiya kawai, sũ ne waɗanda suka yi ĩm&atilde;ni da Allah da ManzonSa, sa\'an nan ba su yi shakka ba, kuma suka yi jih&atilde;di da dũkiyarsu da kuma r&atilde;yukansu, cikin tafarkin Allah. Waɗannan sũ ne m&atilde;su gaskiya.';
$t[16] = 'Ka ce: &quot;Kuna sanar da Allah ne game da addininku, alh&atilde;li kuwa Allah Y&atilde; san abin da ke cikin sammai da abin da ke cikin ƙasa, kuma Allah Masani ne ga dukan k&otilde;me?&quot;';
$t[17] = 'Suna yin g&otilde;ri a kanka wai sun musulunta. Ka ce: &quot;Kada ku yi g&otilde;rin kun musulunta a kaina. &Atilde;\'a, Allah ne ke yi muku g&otilde;ri d&otilde;min Ya shiryar da ku ga ĩm&atilde;ni, idan kun kasance m&atilde;su gaskiya.&quot;';
$t[18] = '&quot;Lalle Allah yan&atilde; sanin gaibin sammai da &iexcl;asa, kuma Allah Mai gani ne ga abin da kuke aikat&atilde;wa.&quot;';
?>