<?php
$t = array();
$t[1] = 'Lalle Alla Ya ji maganar wadda ke yi maka j&atilde;yayya game da mijinta, tan&atilde; kai ƙ&atilde;ra ga Allah, kuma Allah n&atilde; jin muhawararku. Lalle Allah Mai ji ne, Mai gani.';
$t[2] = 'Waɗanda ke yin zih&atilde;ri daga cikinku game da m&atilde;tansu, sũm&atilde;tan nan b&atilde; uw&atilde;yensu ba ne, b&atilde;bu uwayensu f&atilde;ce waɗanda suka haife su. Lalle sũ, sun&atilde; faɗar abin ƙy&atilde;m&atilde; na magana da ƙarya, kuma lalle Allah haƙĩƙa Mai y&atilde;fẽwa ne, Mai g&atilde;fara.';
$t[3] = 'Waɗanda ke yin zih&atilde;ri game da m&atilde;tansu, sa\'an nan su k&otilde;ma wa abin da suka faɗa, to, akwai \'yanta wuya a gab&atilde;nin su sh&atilde;fi jũna. Wannan an&atilde; yi muku wa\'azi da shi. Kuma Allah Mai ƙididdigewa ne ga abin da kuke aikat&atilde;wa.';
$t[4] = 'To, wanda bai s&atilde;mu ba, sai azumin wata biyu jẽre a gab&atilde;nin su sh&atilde;fi jũna, sa\'an nan wanda bai s&atilde;mi ĩkon yi ba, to, sai ciyar da miskĩnai sittin. Wannan d&otilde;min ku yĩ ĩm&atilde;ni da Allah da Manzonsa. Kuma waɗannan hukunce-hukunce hadd&otilde;din Allah ne. Kuma k&atilde;firai, sun&atilde; da az&atilde;ba mai raɗadi.';
$t[5] = 'Lalle waɗanda ke s&atilde;ɓ&atilde; wa Allah da ManzonSa, an wul&atilde;kanta su kamar yadda aka wul&atilde;kantar da waɗanda ke a gab&atilde;ninsu, kuma lalle Mun saukar da &atilde;y&otilde;yi bayyanannu, kuma k&atilde;firai n&atilde; da az&atilde;ba mai wul&atilde;kant&atilde;wa.';
$t[6] = 'R&atilde;nar da Allah zai t&atilde;yar da su gab&atilde; ɗaya, sa\'an nan Ya b&atilde; su l&atilde;b&atilde;ri game da abin da suka aikata, Allah Y&atilde; lissafa shi, alh&atilde;li kuwa sũ, sun manta da shi, kuma a kan k&otilde;me Allah Halartacce ne.';
$t[7] = 'Ashe, ba ka ga cẽwa lalle Allah Yan&atilde; sane da abin da yake a cikin sammai da abin da ke cikin ƙasa ba? Wata g&atilde;n&atilde;wa ta mutum uku b&atilde; z&atilde; ta kasance ba f&atilde;ce Allah Shĩ ne na huɗu ɗinta, kuma b&atilde;bu ta mutum biyar f&atilde;ce Shĩ ne na shida ɗinta, kuma babu abin da ya k&atilde;sa wannan kuma babu abin da yake mafi yawa f&atilde;ce Shĩ Yan&atilde; t&atilde;re da su duk inda suka kasance, sa\'an nan Ya b&atilde; su l&atilde;b&atilde;ri game da abin da suka aikata a R&atilde;nar &iexcl;iy&atilde;ma. Lalle Allah Masani ne ga dukkan k&otilde;me.';
$t[8] = 'Ashe, ba ka ga waɗanda aka hane su ba daga gan&atilde;war, sa\'an nan sun&atilde; k&otilde;m&atilde; wa abin da aka hane su daga gare shi, kuma sun&atilde; g&atilde;n&atilde;wa game da zunubi da z&atilde;lunci da s&atilde;ɓ&atilde; wa Manzon Allah, kuma idan sun zo maka sai su gasihe ka da abin da Allah bai gaishe ka da shi ba, kuma sun&atilde; cẽwa a cikin zukatansu: &quot;Don me Allah ba Ya yi mana az&atilde;ba sab&otilde;da abin da muke faɗi?&quot; Jahannama ita ce mai isarsu, z&atilde; su shigeta. Sab&otilde;da haka mak&otilde;marsu ta mũnana.';
$t[9] = 'Y&atilde; kũ waɗanda suka yi ĩm&atilde;ni! Idan za ku yi g&atilde;n&atilde;wa, to, kada ku g&atilde;na game da zunubi da z&atilde;lunci da s&atilde;ɓ&atilde; wa Manzon Allah, kuma ku yi g&atilde;n&atilde;wa game da alhẽri da taƙawa. Ku bi Allah da taƙawa wanda z&atilde; a tattara ku zuwa gare, shi.';
$t[10] = 'G&atilde;n&atilde;war daga Shaiɗan take kawai d&otilde;min ya mũnan&atilde; wa waɗanda suka yi ĩm&atilde;ni, alh&atilde;li kuwa b&atilde; zai iya cũtar su da k&otilde;me ba f&atilde;ce da iznin Allah. Kuma sai mũminai su dogara ga Allah.';
$t[11] = 'Y&atilde; kũ waɗanda suka yi ĩm&atilde;ni! Idan an ce muka, &quot;Ku yalwat&atilde; a cikin majalisai,&quot; to, ku yalwat&atilde;, sai Allah Ya yalwat&atilde; muku, kuma idan an ce muku, &quot;Ku t&atilde;shi&quot; to, ku t&atilde;shi. Allah n&atilde; ɗaukaka waɗanda suka yi ĩm&atilde;ni daga cikinku da waɗanda aka bai wa ilim wasu daraj&otilde;ji m&atilde;su yawa, kuma, Allah Mai ƙididdigewa ne ga dukan k&otilde;me.';
$t[12] = 'Y&atilde; kũ waɗanda suka yi ĩm&atilde;ni! Idan z&atilde; ku g&atilde;n&atilde;wa da Manzon Allah, to, ku gab&atilde;tar da \'yar sadaka a gab&atilde;nin g&atilde;n&atilde;warku, wannan ne mafi alhẽri a gare ku, kuma mafi tsarki. Sai idan ba ku s&atilde;mi (abin sadakar ba), to, lalle, Allah, Mai g&atilde;fara ne, Mai jin ƙai.';
$t[13] = 'Ashe, kun ji ts&otilde;ron ku gab&atilde;tar da sadak&otilde;ki a gab&atilde;nin g&atilde;n&atilde;warku? To, idan ba ku aikata ba, kuma Allah Ya k&otilde;mo da ku zuwa ga sauƙi, sai ku tsai da salla, kuma ku b&atilde;yar da zakka, kuma ku yi ɗ&atilde;\'&atilde; ga Allah da ManzonSa. Kuma Allah ne Mai ƙididdigewa ga abin da kuke aikat&atilde;wa.';
$t[14] = 'Ashe, baka ga waɗanda suka jiɓinci waɗansu mut&atilde;ne da Allah Ya yi hushi a kansu ba, b&atilde; su cikinku, kuma b&atilde; su a cikinsu kuma sun&atilde; rantsuwa a kan ƙarya, alh&atilde;li kuwa sun&atilde; sane?';
$t[15] = 'Allah Ya yi musu tattalin az&atilde;ba mai tsanani. Lalle sũ abin da suka kasance sun&atilde; aikat&atilde;wa ya mũnana.';
$t[16] = 'Sun riƙi rantsuw&otilde;winsu garkuwa, sab&otilde;da haka suka kange (mũminai) daga jih&atilde;din ɗaukaka tafarkin Allah. To, sun&atilde; da az&atilde;ba mai wul&atilde;kant&atilde;wa.';
$t[17] = 'Dũkiy&otilde;yinsu ba su wad&atilde;tar musu k&otilde;me ba daga Allah, haka kuma ɗiyansu. Waɗannan \'yan wut&atilde; ne. Sũ, m&atilde;su dawwama ne a cikinta.';
$t[18] = 'R&atilde;nar da Allah ke t&atilde;yar da su gab&atilde; ɗaya, sai su yi Masa rantsuwa kamar yadda suke yi muku rantsuwa (a nan dũniya) kuma sun&atilde; zaton cẽwa sũ a kan wani abu suke! To, lalle sũ, sũ ne maƙaryata.';
$t[19] = 'Shaiɗan ya rinjaya a kansu, sai ya mantar da su ambaton Allah, waɗannan ƙungiyar Shaiɗan ne. To, lalle ƙungiyar Shaiɗan, sũ ne m&atilde;su has&atilde;ra.';
$t[20] = 'Lalle, waɗanda ke s&atilde;ɓ&atilde; wa Allah da ManzonSa waɗannan sun&atilde; a cikin (mut&atilde;ne) mafi ƙasƙanci.';
$t[21] = 'Allah Ya rubũta cẽwa,&quot; Lalle zan rinj&atilde;ya, Nĩ da ManzanniNa.&quot; Lalle Allah Mai ƙarfi ne, Mabuw&atilde;yi.';
$t[22] = 'B&atilde; z&atilde; ka s&atilde;mi mut&atilde;ne m&atilde;su yin ĩm&atilde;ni da Allah da R&atilde;narL&atilde;hira sun&atilde; s&otilde;yayya da wanda ya s&atilde;ɓ&atilde; wa Allah da ManzonSa ba, k&otilde; d&atilde; sun kasance ubanninsu ne, k&otilde; ɗiyansu k&otilde; \'yan\'uwansu, ko danginsu. waɗannan Allah Y&atilde; rubuta ĩm&atilde;ni a cikin zuk&atilde;tansu, kuma Y&atilde; ƙarfafa su da wani rũhi daga gare Shi, kuma zai shigar da su a gid&atilde;jen Aljanna, ƙoramu na gud&atilde;na ƙarƙashinsu sun&atilde; m&atilde;su dawwama a cikinsu. Allah Y&atilde; yarda da su, kuma sun yarda da Shi. Waɗannan ƙungiyar Allah ne. To, lalle ƙungiyar Allah sũ ne m&atilde;su babban rabo.';
?>