<?php
$t = array();
$t[1] = 'Abin da ke cikin sammai da abin da ke cikin ƙas&atilde; ya yi tasbihi ga Allah, alh&atilde;li kuwa, Shĩ ne Mabuw&atilde;yi, Mai hikima.';
$t[2] = 'Shĩ ne wanda Ya fitar da waɗanda suka k&atilde;firta daga Maz&otilde;wa Litt&atilde;fi, daga gid&atilde;jẽnsu da k&otilde;ra ta farko. Ba ku yi zaton sun&atilde; fita ba, kuma sun tabbata cẽwa g&atilde;nuw&otilde;winsu m&atilde;su tsare su ne daga Allah, sai Allah Ya jẽ musu daga wajen da ba su yi zato ba, kuma Ya jẽfa ts&otilde;ro a cikin zuk&atilde;tansu, sun&atilde; rushe gid&atilde;jensu da hann&atilde;yensu da kuma hann&atilde;yen mũminai. To, ku lũra fa, ya m&atilde;su basĩr&otilde;ri.';
$t[3] = 'Kuma ba d&otilde;min Allah Ya rubuta musu k&otilde;rar ba, d&atilde; Ya azabta su a cikin dũniya, kuma a L&atilde;hira sun&atilde; da az&atilde;bar wut&atilde;.';
$t[4] = 'Wannan d&otilde;min lalle su, sun s&atilde;ɓa wa Allah, da ManzonSa alh&atilde;li kuwa wanda ya s&atilde;ɓa wa Allah, to, lalle Allah, Mai tsananin uƙũba ne.';
$t[5] = 'Abin da kuka s&atilde;re na dabĩniya, k&otilde; kuka bar ta tsaye a kan asallanta, to da iznin Allah ne, kuma d&otilde;min Ya wul&atilde;kanta fasiƙai,';
$t[6] = 'Kuma abin da Allah Ya sanya ya zama ganĩma ga ManzonSa, daga gare su, to, ba ku yi hari a kansa da daw&atilde;ki ko r&atilde;ƙuma ba amma Allah ne Ya rinj&atilde;yar da ManzanninSa a kan wanda Yake so, kuma Allah Mai ĩkon yi ne a kan k&otilde;me.';
$t[7] = 'Abin da Allah Ya sanya shi ganĩma ga ManzonSa dagamut&atilde;nen ƙauyukan nan, to, na Allah ne, kuma na ManzonSa ne kuma na m&atilde;su dangantaka da m&atilde;rayu da miskĩnai da ɗan hanya (matafiyi) ne d&otilde;min kada ya kasance abin sh&atilde;w&atilde;gi a tsak&atilde;nin mawad&atilde;ta daga cikinku kuma abin da Manzo ya b&atilde; ku, to, ku kama shi, kuma abin da ya hane ku, to, ku bar shi. Kuma ku bi Allah da taƙawa. Lalle, Allah, Mai tsananin uƙũba ne.';
$t[8] = '(Ku yi m&atilde;m&atilde;ki) Ga matalauta m&atilde;su hijira waɗanda aka fitar daga gid&atilde;jẽnsu da dũkiy&otilde;yinsu, sun&atilde; nẽman falala daga Allah da kuma yarda, kuma sun&atilde; taimakon Allah da ManzonSa! Waɗannan sũ ne m&atilde;su gaskiya.';
$t[9] = 'Da waɗanda suka zaunar da gid&atilde;jensu (ga Musulunci) kuma (suka z&atilde;ɓi) ĩm&atilde;ni, a gab&atilde;nin zuwansu, sun&atilde; son wanda ya yi hijira zuwa gare su, kuma b&atilde; su tun&atilde;nin wata buk&atilde;ta a cikin ƙir&atilde;zansu daga abin da aka bai wa muh&atilde;jirĩna, kuma sun&atilde; fĩfĩta waɗansu a kan k&atilde;wunansu, kuma ko d&atilde; sun&atilde; da wata larũra. Wanda ya s&atilde;ɓ&atilde; wa r&otilde;war ransa, to, waɗannan sũ ne m&atilde;su babban rabo.';
$t[10] = 'Kuma waɗanda suka z&otilde; daga b&atilde;yansu, sun&atilde; cẽwa, &quot;Y&atilde; Ubangijinmu! Ka yi g&atilde;fara a gare mu, kuma ga \'yan\'uwanmu, waɗanda da suka riga mu yin ĩm&atilde;ni, kada Ka sanya wani ƙulli a cikin zuk&atilde;tanmu ga waɗanda suka yi ĩm&atilde;ni. Y&atilde; Ubangijinmu! Lalle Kai ne Mai tausayi, Mai jin ƙai.';
$t[11] = 'Ashe, ba ka ga waɗanda suka yi mun&atilde;finci ba, sun&atilde; cẽwa ga \'yan\'uwansu, waɗanda suka k&atilde;firta daga Maz&otilde;wa Littafi, &quot;Lalle idan an fitar da ku, lalle z&atilde; mu fita t&atilde;re da ku, kuma b&atilde; z&atilde; mu yi ɗ&atilde;\'a ga k&otilde;wa ba game da ku, har abada, kuma lalle idan an y&atilde;ƙe ku, lalle z&atilde; mu taimake ku haƙĩƙatan?&quot; Alh&atilde;li kuwa Allah na shaidar cẽwa lalle sũ tabbas, maƙaryata ne.';
$t[12] = 'Lalle idan an fitar da su, b&atilde; z&atilde; su fita t&atilde;re da su ba kuma lalle idan an y&atilde;ƙe su b&atilde; z&atilde; su taimake su ba, kuma lalle idan sun taimake su lalle ne, haƙĩƙatan, z&atilde; su jũyar da b&atilde;yansu d&otilde;min gudu, sa\'an nan kuma b&atilde; z&atilde; a taimake su ba.';
$t[13] = 'Lalle kũ ne kuka fi b&atilde;yar da firgita a cikin zuk&atilde;tansu bisa ga Allah, wannan kuwa d&otilde;min sũ lalle waɗansu irin mut&atilde;ne ne da b&atilde; su g&atilde;nẽwa.';
$t[14] = 'B&atilde; su iya y&atilde;ƙar ku gab&atilde; ɗaya, f&atilde;ce a cikin garũruwa m&atilde;su g&atilde;nuwa da g&atilde;runa, k&otilde; kuma daga b&atilde;yan katangu. Y&atilde;kinsu a ts&atilde;kaninsu mai tsanani ne, kan&atilde; zaton su a haɗe, alh&atilde;li kuwa zuk&atilde;tansu dabam- dabam suke. Wannan kuwa d&otilde;min sũ, lalle wasu irin mutane ne da b&atilde; su hankalta.';
$t[15] = 'Kamar mis&atilde;lin waɗanda ke a gab&atilde;ninsu, b&atilde; da daɗẽwa ba, sun ɗanɗani kũɗar al\'amarinsu, kuma sun&atilde; da wata az&atilde;ba mai raRaɗi.';
$t[16] = 'Kamar mis&atilde;lin Shaiɗan a l&otilde;kacin da yake cẽ wa mutum, &quot;Ka k&atilde;firta,&quot; To, a l&otilde;kacin da ya k&atilde;firta ɗin, ya ce (masa): &quot;Lalle b&atilde;bu ruw&atilde;na da kai. Lalle ni in&atilde; ts&otilde;ron Allah Ubangijin halitta!&quot;';
$t[17] = 'Sai &atilde;ƙibarsu ta kasance cẽwa su biyun duka sun&atilde; a cikin wut&atilde;, sun&atilde; m&atilde;su dawwama a cikinta. &quot;Kuma wannan shĩ ne sakamakon m&atilde;su z&atilde;lunci.&quot;';
$t[18] = 'Y&atilde; kũ waɗanda suka yi ĩm&atilde;ni! Ku bi Allah da taƙawa kuma rai ya dũbi abin da ya gab&atilde;tar d&otilde;min g&otilde;be, kuma ku bi Allah da taƙawa. lalle Allah, Mai ƙididdigewa ne ga abin da kuke aikat&atilde;wa.';
$t[19] = 'Kuma kada ku kasance kamar waɗanda suka manta Allah shi kuma Ya mantar da su r&atilde;yu, kansu. Waɗannan sũ ne f&atilde;siƙai.';
$t[20] = '\'Yan Wut&atilde; da \'yan Aljanna b&atilde; su daidaita. \'Yan Aljanna, sũ ne m&atilde;su babban rabo.';
$t[21] = 'D&atilde; Mun saukar da wannan Alƙur\'ani a kan dũtse, d&atilde; lalle k&atilde; ga dũtsen yan&atilde; mai taw&atilde;li\'u, mai tsatts&atilde;gẽwa sab&otilde;da ts&otilde;ron Allah, kuma waɗancan mis&atilde;lai Mun&atilde; bayyana su ne ga mut&atilde;ne, da fatan za su yi tun&atilde;ni.';
$t[22] = '(Wanda Ya saukar da Alƙur\'ani) Shi ne Allah, wanda b&atilde;bu wani abin baut&atilde;wa f&atilde;ce Shi Masanin fake da bayyane, Shĩ ne Mai rahama, Mai jin ƙai.';
$t[23] = 'Shĩ ne Allah, wanda b&atilde;bu abin baut&atilde;wa f&atilde;ce shi, Mai mulki, Mai tsarki, Aminci, Mai amintarwa, Mai Tsarẽwa, Mabuw&atilde;yi, Mai t஛ast&atilde;wa Mai nuna isa, tsarki ya tabbata a gare Shi daga abin da suke yi na shirki da Shi.';
$t[24] = 'Shĩ ne Allah, Mai halitta, Mai gin&atilde;wa, Mai sũrant&atilde;wa. Yan&atilde; da sũn&atilde;ye m&atilde;su kyau, abin da ke a cikin sammai da ƙasa sun&atilde; tsarkake Shi, kuma Shĩ ne Mabuw&atilde;yi, Mai hikima.';
?>