<?php
$t = array();
$t[1] = 'Ya kũ waɗanda suka yi ĩmani! Kada ku riƙi maƙiyĩNa kuma maƙiyinku mas&otilde;yi, 845. Kuna jẽfa s&otilde;yayya zuwa gare su, alh&atilde;li kuwa haƙĩƙa sun k&atilde;firta da abin da ya zo muku, na gaskiya, sun&atilde; fitar da Manzon Allah t&atilde;re da ku (daga gid&atilde;jenku) d&otilde;min kun yi ĩm&atilde;ni da Allah, Ubangijinku, idan kun fito d&otilde;min jih&atilde;di sab&otilde;da ɗaukaka kalmaTa da nẽman yardaTa, kun&atilde; asirta s&otilde;yayya zuwa gare su alh&atilde;li kuwa Nĩ ne Mafi sani ga abin da kuka ɓ&otilde;ye da abin da kuka bayyana, kuma duk wanda ya aikata shi daga cikinku, to, lalle ya ɓace daga tsakar hanya.';
$t[2] = 'Idan sun k&atilde;ma ku, z&atilde; su kasance maƙiya a gare ku, kuma su shimfiɗa hannuwansu da harsunan gũrin ku k&atilde;firta.';
$t[3] = 'Zumuntarku b&atilde; z&atilde; ta amf&atilde;ne ku ba, haka kuma ɗiyanku, a R&atilde;nar Kiy&atilde;ma. (Allah) zai rarrabe tsak&atilde;ninku, kuma Allah Mai gani ne ga abin da kuke aikat&atilde;wa.';
$t[4] = 'Lalle abin k&otilde;yi mai kyau ya kasance a gare ku game da Ibr&atilde;hĩm da waɗanda ke t&atilde;re da shi a l&otilde;kacin da suka ce wa mutnensu, &quot;Lalle mũ b&atilde;bu ruwanmu daku, kuma da abin da kuke baut&atilde;wa, baicin Allah, mun fita batunku, kuma ƙiyayya da jiyẽwa jũna sun bayyana a tsak&atilde;ninmu, sai kun yi ĩm&atilde;ni da Allah Shi kaɗai.&quot; F&atilde;ce maganar Ibr&atilde;hĩm ga ubansa (da yace), &quot;Lalle za ni nẽma maka g&atilde;fara kuma ban mallaki k&otilde;me ba daga Allah sab&otilde;da kai.&quot; &quot;Y&atilde; Ubangijinmu! A gare Ka muka d&otilde;gara, kuma gare Ka muka mayar da al\' amuranmu, kuma zuwa gare Ka mak&otilde;ma take.&quot;';
$t[5] = '&quot;Y&atilde; Ubangijinmu! Kada Ka sanya mu fitina ga waɗanda suka k&atilde;firta, kuma Ka yi g&atilde;fara gare Mu. Ya Ubangijinmu! Kai ne Mabuw&atilde;yi, Mai hikima!';
$t[6] = 'Lalle, haƙĩƙa, abin k&otilde;yi mai kyau ya kasance a gare ku daga cikinsu, ga wanda ya kasance yan&atilde; f&atilde;tan (rahamar) Allah da R&atilde;nar L&atilde;hira, kuma wanda ya jũya b&atilde;ya, to, lalle Allah, Shĩ ne wad&atilde;tacce, G&otilde;dadde.';
$t[7] = 'An&atilde; tsamm&atilde;nin Allah Ya sanya, a tsak&atilde;ninku da tsak&atilde;nin waɗanda kuka yi ƙiyayya da su, wata s&otilde;yaya daga gare su, kuma Allah Mai ĩkon yi ne, kuma Allah Mai g&atilde;fara ne, Mai jin ƙai.';
$t[8] = 'Allah b&atilde; Ya hana ku, daga waɗanda ba su y&atilde;ƙe ku ba sab&otilde;da addini kuma ba su fitar da ku ba daga gid&atilde;jenku, ga ku kyautata musu kuma ku yi musu &atilde;dalci. Lalle Allah Yan&atilde; son m&atilde;su &atilde;dalci.';
$t[9] = 'Allah Yan&atilde; hana ku kawai daga waɗanda suka y&atilde;ke ku sab&otilde;da addini kuma suka fitar da ku daga gid&atilde;jenku, kuma suka taimaki jũna ga fitar da ku, karku jiɓince su, kuma wanda ya jiɓince su, to waɗannan sũ ne azz&atilde;lumai.';
$t[10] = 'Y&atilde; kũ waɗanda suka yi ĩm&atilde;ni! Idan m&atilde;t&atilde; mũminai suka zo muku, sun&atilde; m&atilde;su hijira, to, ku jarraba su. Allah Shĩ ne mafi sani ga ĩm&atilde;ninsu. To, idan kun san sũ mũminai ne, kada ku mayar da su zuwa ga k&atilde;firai. Sũ m&atilde;tan b&atilde; su halatta ga aurensu, sũ kuma k&atilde;firan b&atilde; su halatta ga auren m&atilde;tan. Ku b&atilde; su abin da suka ɓatar na dũkiya. Kuma b&atilde;bu laifi a kanku ga ku aure su idan kun b&atilde; su sad&atilde;k&otilde;kinsu. Kuma kada ku riƙe auren m&atilde;t&atilde; k&atilde;firai, kuma ku tambayi abin da kuka ɓatar daga dũkiya, su kuma k&atilde;firai su tambayi abin da suka ɓatar na dũkiya. Wannan hukuncin Allah ne Yan&atilde; hukunci a tsak&atilde;ninku. kuma Allah, Masani ne, Mai hikima';
$t[11] = 'Kuma idan wani abu ya kuɓuce muku daga m&atilde;tanku zuwa ga k&atilde;firai sa\'an nan kuma kuka ɗauki fansa, to, sai ku bai wa waɗanda matansu suka tafi kwatankwacin abin da suka ɓatar na dũkiya. Kuma ku yi biyayya da taƙawa ga Allah wanda kuke m&atilde;su ĩm&atilde;ni da Shi, Shi Kaɗai.';
$t[12] = 'Y&atilde; kai Annabi! Idan m&atilde;t&atilde; mũminai suka zo maka sun&atilde; yi maka mub&atilde;ya\'a a kan b&atilde; z&atilde; su yi shirki da Allah ba ga k&otilde;me, kuma b&atilde; su yin s&atilde;t&atilde;, kuma b&atilde; su yin zina, kuma b&atilde; su kashe, ya\'yansu, kuma b&atilde; su zuwa da ƙarya da suke ƙirƙir&atilde;wa a ts&atilde;kanin hannuwansu da ƙaf&atilde;funsu kuma b&atilde; su s&atilde;ɓa maka ga wani abu da aka sani na sharĩ\'a, to, ka karɓi mub&atilde;ya\'arsu, kuma ka nẽmi Allah Ya g&atilde;farta musu. Lalle Allah Mai g&atilde;fara ne, Mai jin ƙai.';
$t[13] = 'Y&atilde; kũ waɗanda suka yi ĩm&atilde;ni! Kada ku jiɓinci waɗansu mut&atilde;ne da Allah Ya yi hushi a kansu. Lalle sun yanke tsamm&atilde;ni daga (rahamar) L&atilde;hira, kamar yadda k&atilde;firai suka yanke tsamm&atilde;ni daga maz&otilde;wa kaburbura.';
?>