<?php
$t = array();
$t[1] = 'Ya kai Annabi! Idan kun saki m&atilde;t&atilde;, sai ku sake su ga iddarsu, kuma ku ƙididdige iddar. Kuma ku bi Allah Ubangijinku da taƙawa. Kada ku fitar da su daga gid&atilde;jensu, kuma kada su fita f&atilde;ce idan sun&atilde; zuwa da wata alf&atilde;sh&atilde; bayyananna. Kuma waɗancan iyak&otilde;kin Allah ne. Kuma wanda ya ƙẽtare iy&atilde;k&otilde;kin Allah, to, lalle ya z&atilde;lunci kansa. Ba ka sani ba ɗamm&atilde;nin Allah zai fitar da wani al\'amari a b&atilde;yan haka.';
$t[2] = 'Sa\'an nan idan sun isa ga ajalinsu (na idda) sai ku riƙe su da abin da aka sani k&otilde; ku rabu da su da abin da aka sani kuma ku shaidar da m&atilde;su adalci biyu daga gare ku. Kuma ku tsayar da shaidar d&otilde;min Allah. Wancan ɗinku an&atilde; yin wa\'azi da shi ga wanda ya kasance yan&atilde; yin ĩm&atilde;ni da Allah da R&atilde;nar L&atilde;hira. Kuma wanda ya bi Allah da taƙawa, Allah zai sanya masa mafita.';
$t[3] = 'Kuma Ya arzũta shi daga inda b&atilde; ya zato. Kuma wanda ya d&otilde;gara ga Allah, to, Allah ne Ma\'ishinsa. Lalle Allah Mai iyar da umurninSa ne. Haƙĩƙa Allah Ya sanyama\'auni ga dukan k&otilde;me.';
$t[4] = 'Kuma waɗanda suka yanke ɗamm&atilde;ni daga haila daga m&atilde;tanku, idan kun yi shakka, to, iddarsu wat&atilde; uku ce da waɗanda ba su yi haila ba. Kuma ma\'abũta cikinna ajalinsu, (shi ne) cewa su haifi cikinnansu. Kuma wanda ya bi Allah da taƙawa, (Allah) zai sanya masa wani sauƙi daga al\'amarinsa.';
$t[5] = 'Wancan umurnin Allah ne, Ya saukar da shi zuwa gare ku. Kuma wanda ya bi Allah da taƙawa, Allah zai kankare masa mũn&atilde;nan ayyukansa, kuma Ya girmama masa s&atilde;kamako.';
$t[6] = 'Ku zaunar da su daga inda kuka zaunar daga gwargwadon s&atilde;munku. Kuma kada ku cũce su d&otilde;min ku ƙuntata a kansu. Kuma idan sun kasance ma\'abũta ciki, sai ku ciyar da su har su haifi cikinsu. Sa\'an nan idan sun sh&atilde;yar da m&atilde;ma sab&otilde;da ku, sai ku b&atilde; su ts&atilde;d&otilde;dinsu. Kuma ku yi sh&atilde;wara a tsak&atilde;ninku bisa abin da aka sani. Kuma idan kun nũna talauci to wata mace z&atilde; ta sh&atilde;yar da m&atilde;ma sab&otilde;da shi (mijin).';
$t[7] = 'Sai mawad&atilde;ci ya ciyar daga wad&atilde;tarsa kuma wanda aka ƙuntata masa arzikinsa, to, sai ya ciyar daga abin da Allah Ya b&atilde; shi. Allah b&atilde; Ya kallafa wa wani rai f&atilde;ce abin da Ya b&atilde; shi. Allah zai sanya sauƙi a b&atilde;yan tsanani.';
$t[8] = 'Kuma da yawa daga alƙarya wadda ta yi tsaurin kai daga barin umurnin Ubangijinta da ManzanninSa, sai Muka yi mata his&atilde;bi, his&atilde;bi mai tsanani, kuma Muka, azabtar da ita az&atilde;ba abar ƙy&atilde;ma.';
$t[9] = 'Sa\'an nan ta ɗanɗana masĩfar al\'amarinta. kuma ƙarshen al\'amarinta ya kasance has&atilde;ra,';
$t[10] = 'Allah Ya yi musu tattalin wata az&atilde;ba mai tsanani. Sab&otilde;da haka ku bi Allah da taƙawa, y&atilde; ma\'abũta hankula, waɗanda suka yi ĩm&atilde;ni! Haƙĩƙa Allah Ya saukar da wata tun&atilde;tarwa zuwa gare ku.';
$t[11] = 'Manzo, yan&atilde; kar&atilde;tun &atilde;y&otilde;yin Allah bayyananu a kanku d&otilde;min Ya fitar da waɗanda suka yi ĩm&atilde;ni kuma suka aikata ayyukan ƙwarai daga duffai zuwa ga haske. Kuma wanda ya yi ĩm&atilde;ni da Allah ya aikata aikin ƙwarai Allah zai shigar da shi gid&atilde;jen Aljanna ƙoramu n&atilde; gud&atilde;na daga ƙarƙashnsu sun&atilde; m&atilde;su dawwama a cikinsu har abada. Haƙĩƙa Allah Y&atilde; kyautata masa arziki.';
$t[12] = 'Allah, wanda Ya halitta bakwai ɗin sammai kuma daga ƙas&atilde; kwatankwacinsu, umuruinSa yan&atilde; ta sauka a tsakaninsu d&otilde;min ku san lalle Allah Mai ĩkon yi ne akan dukan k&otilde;me, kuma lalle Allah, haƙĩƙa Ya kẽwaye ga dukan k&otilde;me da sani.';
?>