<?php
$t = array();
$t[1] = 'Y&atilde; kai Annabi! Don me kake haramta abin da Allah Ya halatta maka, kan&atilde; nẽman yardar m&atilde;tanka, alh&atilde;li kuwa Allah Mai g&atilde;fara ne, Mai jin ƙai.';
$t[2] = 'Haƙĩƙa Allah ya faralta muku warware rantsuw&otilde;yinku, kuma Allah ne Mataimakinku kuma shĩ ne Masani, Mai hikima.';
$t[3] = 'Kuma a s&atilde;\'ilin da Annabi ya asirta wani l&atilde;b&atilde;ri zuwa ga s&atilde;shen m&atilde;tansa, to, a l&otilde;kacin da ta b&atilde; da l&atilde;bari da shi. Kuma Allah Ya bayyana shi a gare shi, ya sanar da s&atilde;shensa kuma ya kau da kai daga wani s&atilde;she. To, a l&otilde;kacin da ya b&atilde; ta l&atilde;b&atilde;ri da shi, ta ce: &quot;W&atilde;ne ne ya gaya maka wannan?&quot; Ya ce: &quot;Masani, Mai labart&atilde;wa, Ya gaya mini.&quot;';
$t[4] = 'Idan kũ biyu kuka tũba zuwa ga Allah, to, haƙĩƙa zuk&atilde;tanku sun karkata. Kuma idan kun taimaki jũna a kansa to, lalle Allah Shĩ ne Mataimakinsa, da Jibrĩlu da s&atilde;lihan mũminai. Kuma mal&atilde;\'iku a b&atilde;yan wancan, mataimaka ne.';
$t[5] = 'Mai yiwuwa ne Ubangijinsa, idan ya sake ku, Ya musanya masa waɗansu m&atilde;tan aure mafiya alhẽri daga gare ku, Musulmai mũminai m&atilde;su taw&atilde;li\'u, m&atilde;su tũba, m&atilde;su ib&atilde;da, m&atilde;su, azumi, zawar&otilde;ri da \'yamm&atilde;ta.';
$t[6] = 'Y&atilde; kũ waɗanda suka yi ĩm&atilde;ni! Ku k&atilde;re wa kanku (da iy&atilde;linku wata wuta mak&atilde;mashinta mut&atilde;ne da duw&atilde;tsu ne. A kanta akwai waɗansu mal&atilde;\'iku m&atilde;su kauri, m&atilde;su ƙarfi. B&atilde; su s&atilde;ɓ&atilde; wa Allah ga abin da Ya umurce su, kuma sun&atilde; aikata abin da ake umunin su.';
$t[7] = 'Y&atilde; kũ waɗanda suka k&atilde;firta! Kada ku k&atilde;wo wani uzuri a yau. An&atilde; yi muku sakamakon abin da kuka kasance kun&atilde; aikat&atilde;wa kawai ne.';
$t[8] = 'Y&atilde; kũ waɗanda suka yi ĩm&atilde;ni! Ku k&otilde;ma zuwa ga Allah k&otilde;mawar gaskiya. Mai yiwuwa Ubangjinku Ya kankare muku miy&atilde;gun ayyukanku kuma Ya shigar da ku a gid&atilde;jen Aljanna, ƙoramu na gud&atilde;na daga ƙarƙashinsu a r&atilde;nar da Allah b&atilde; Ya kunyatar da Annabi da wadanda suka yi ĩm&atilde;ni t&atilde;re da shi. Haskensu yan&atilde; tafiya a gaba gare su da jih&otilde;hin d&atilde;mansu, sun&atilde; cẽwa, &quot;Y&atilde; Ubangijiumu! Ka cika mana haskenmu, kuma Ka yi mana g&atilde;fara. Lalle Kai, a kan dukkan k&otilde;me, Y&atilde; kai Mai ikon yi ne.&quot;';
$t[9] = 'Y&atilde; kai Annabi! Ka y&atilde;ki k&atilde;firai da mun&atilde;fwkai. Kuma ka tsananta a kansu. Kuma matattararsu Jahannama ce, kuma tir da makoma, ita.';
$t[10] = 'Allah Ya buga wani mis&atilde;li d&otilde;min waɗanda suka k&atilde;firta: m&atilde;tar Nũhu da m&atilde;tar Lũɗu, sun kasance a ƙarƙashin wasu b&atilde;yi biyu daga b&atilde;yinMu s&atilde;lihai, saisuka yaudare su, sab&otilde;da haka ba su wad&atilde;tar musu da k&otilde;me daga Allah ba. Kuma aka ce: &quot;Ku shiga, kũ biyu, wut&atilde; t&atilde;re da m&atilde;su shiga.&quot;';
$t[11] = 'Kuma Allah Ya buga wani mis&atilde;li d&otilde;min waɗanda suka yi ĩm&atilde;ni; matar Fir\'auna, sa\'ad da ta ce &quot;Ya Ubangiji! Ka gina mini wani gida a wurinKa a cikin Aljanna. Kuma Ka tsĩrar da ni daga Fir\'auna da aikinsa. Kuma Ka tsĩrar da ni daga mut&atilde;nen nan azz&atilde;lumai.&quot;';
$t[12] = 'Da Maryama ɗiyar Imr&atilde;na wadda ta tsare farjinta, sai Muka hũra a cikinsa daga rũhinMu. Kuma ta gaskata game da &atilde;y&otilde;yin Ubangijinta da LittattafanSa alh&atilde;li kuwa ta kasance daga m&atilde;su taw&atilde;li\'u.';
?>