<?php
$t = array();
$t[1] = '&ocirc; vous qui avez cru ! Ne devancez pas Allah et Son messager . Et craignez Allah. Allah est Audient et Omniscient.';
$t[2] = '&ocirc; vous qui avez cru ! N\'&eacute;levez pas vos voix au-dessus de la voix du Proph&egrave;te, et ne haussez pas le ton en lui parlant, comme vous le haussez les uns avec les autres, sinon vos oeuvres deviendraient vaines sans que vous vous en rendiez compte.';
$t[3] = 'Ceux qui aupr&egrave;s du Messager d\'Allah baissent leurs voix sont ceux dont Allah a &eacute;prouv&eacute; les coeurs pour la pi&eacute;t&eacute;. Ils auront un pardon et une &eacute;norme r&eacute;compense.';
$t[4] = 'Ceux qui t\'appellent &agrave; haute voix de derri&egrave;re les appartements, la plupart d\'entre eux ne raisonnent pas.';
$t[5] = 'Et s\'ils patientaient jusqu\'&agrave; ce que tu sortes &agrave; eux, ce serait certes mieux pour eux. Allah cependant, est Pardonneur et Mis&eacute;ricordieux.';
$t[6] = '&ocirc; vous qui avez cru ! Si un pervers vous apporte une nouvelle, voyez bien clair [de crainte] que par inadvertance vous ne portiez atteinte &agrave; des gens et que vous ne regrettiez par la suite ce que vous avez fait.';
$t[7] = 'Et sachez que le Messager d\'Allah est parmi vous. S\'il vous ob&eacute;issait dans maintes affaires, vous seriez en difficult&eacute;s. Mais Allah vous a fait aimer la foi et l\'a embellie dans vos coeurs et vous a fait d&eacute;tester la m&eacute;cr&eacute;ance, la perversit&eacute; et la d&eacute;sob&eacute;issance. Ceux-l&agrave; sont les bien dirig&eacute;s,';
$t[8] = 'c\'est l&agrave; en effet une gr&acirc;ce d\'Allah et une bienfait. Allah est Omniscient et Sage.';
$t[9] = 'Et si deux groupes de croyants se combattent, faites la conciliation entre eux. Si l\'un d\'eux se rebelle contre l\'autre, combattez le groupe qui se rebelle, jusqu\'&agrave; ce qu\'il se conforme &agrave; l\'ordre d\'Allah. Puis, s\'il s\'y conforme, r&eacute;conciliez-les avec justice et soyez &eacute;quitables car Allah aime les &eacute;quitables.';
$t[10] = 'Les croyants ne sont que des fr&egrave;res. &eacute;tablissez la concorde entre vos fr&egrave;res, et craignez Allah, afin qu\'on vous fasse mis&eacute;ricorde.';
$t[11] = '&ocirc; vous qui avez cru ! Qu\'un groupe ne se raille pas d\'un autre groupe : ceux-ci sont peut-&ecirc;tre meilleurs qu\'eux. Et que des femmes ne se raillent pas d\'autres femmes : celles-ci sont peut-&ecirc;tre meilleures qu\'elles. Ne vous d&eacute;nigrez pas et ne vous lancez pas mutuellement des sobriquets (injurieux). Quel vilain mot que &quot;perversion&quot; lorsqu\'on a d&eacute;j&agrave; la foi . Et quiconque ne se repent pas... Ceux-l&agrave; sont les injustes.';
$t[12] = '&ocirc; vous qui avez cru ! &eacute;vitez de trop conjecturer [sur autrui] car une partie des conjectures est p&eacute;ch&eacute;. Et n\'espionnez pas; et ne m&eacute;disez pas les uns des autres. L\'un de vous aimerait-il manger la chair de son fr&egrave;re mort ? (Non ! ) vous en aurez horreur. Et craignez Allah. Car Allah est Grand Accueillant au repentir, Tr&egrave;s Mis&eacute;ricordieux.';
$t[13] = '&ocirc; hommes ! Nous vous avons cr&eacute;&eacute;s d\'un m&acirc;le et d\'une femelle, et Nous avons fait de vous des nations et des tribus, pour que vous vous entreconnaissiez. Le plus noble d\'entre vous, aupr&egrave;s d\'Allah, est le plus pieux. Allah est certes Omniscient et Grand-Connaisseur.';
$t[14] = 'Les B&eacute;douins ont dit : &quot;Nous avons la foi&quot;. Dis : &quot;Vous n\'avez pas encore la foi. Dites plut&ocirc;t : Nous nous sommes simplement soumis, car la foi n\'a pas encore p&eacute;n&eacute;tr&eacute; dans vos coeurs. Et si vous ob&eacute;issez &agrave; Allah et &agrave; Son messager, Il ne vous fera rien perdre de vos oeuvres&quot;. Allah est Pardonneur et Mis&eacute;ricordieux.';
$t[15] = 'Les vrais croyants sont seulement ceux qui croient en Allah et en Son messager, qui par la suite ne doutent point et qui luttent avec leurs biens et leurs personnes dans le chemin d\'Allah. Ceux-l&agrave; sont les v&eacute;ridiques.';
$t[16] = 'Dis : &quot;Est-ce vous qui apprendrez &agrave; Allah votre religion, alors qu\'Allah sait tout ce qui est dans les cieux et sur la terre ? &quot; Et Allah est Omniscient.';
$t[17] = 'Ils te rappellent leur conversion &agrave; l\'Islam comme si c\'&eacute;tait une faveur de leur part. Dis : &quot; Ne me rappelez pas votre conversion &agrave; l\'Islam comme une faveur. C\'est tout au contraire une faveur dont Allah vous a combl&eacute;s en vous dirigeant vers la foi, si toutefois vous &ecirc;tes v&eacute;ridiques&quot;.';
$t[18] = 'Allah conna&icirc;t l\'Inconnaissable des cieux et de la terre et Allah est Clairvoyant sur ce que vous faites.';
?>