<?php
$t = array();
$t[1] = 'Allah a bien entendu la parole de celle qui discutait avec toi &agrave; propos de son &eacute;poux et se plaignait &agrave; Allah. Et Allah entendait votre conversation, car Allah est Audient et Clairvoyant.';
$t[2] = 'Ceux d\'entre vous qui r&eacute;pudient leurs femme, en d&eacute;clarant qu\'elles sont pour eux comme le dos de leur m&egrave;res... alors qu\'elles ne sont nullement leur m&egrave;res, car ils n\'ont pour m&egrave;res que celles qui les ont enfant&eacute;s. Ils prononcent certes une parole bl&acirc;mable et mensong&egrave;re. Allah cependant est Indulgent et Pardonneur.';
$t[3] = 'Ceux qui comparent leurs femmes au dos de leurs m&egrave;res, puis reviennent sur ce qu\'ils ont dit, doivent affranchir un esclave avant d\'avoir aucun contact [conjugal] avec leur femme. C\'est ce dont on vous exhorte. Et Allah est Parfaitement Connaisseur de ce que vous faites.';
$t[4] = 'Mais celui qui n\'en trouve pas les moyens doit je&ucirc;ner alors deux mois cons&eacute;cutifs avant d\'avoir aucun contact [conjugal] avec sa femme. Mais s\'il ne peut le faire non plus, alors qu\'il nourrisse soixante pauvres. Cela, pour que vous croyiez en Allah et en Son messager. Voil&agrave; les limites impos&eacute;es par Allah. Et les m&eacute;cr&eacute;ants auront un ch&acirc;timent douloureux.';
$t[5] = 'Ceux qui s\'opposent &agrave; Allah et &agrave; Son messager seront culbut&eacute;s comme furent culbut&eacute;s leurs devanciers. Nous avons d&eacute;j&agrave; fait descendre des preuves explicites, et les m&eacute;cr&eacute;ants auront un ch&acirc;timent avilissant,';
$t[6] = 'le jour o&ugrave; Allah les ressuscitera tous, puis les informera de ce qu\'ils ont fait. Allah l\'a d&eacute;nombr&eacute; et ils l\'auront oubli&eacute;. Allah est t&eacute;moin de toute chose.';
$t[7] = 'Ne vois-tu pas qu\'Allah sait ce qui est dans les cieux et sur la terre ? Pas de conversation secr&egrave;te entre trois sans qu\'Il ne soit leur quatri&egrave;me, ni entre cinq sans qu\'Il n\'y ne soit leur sixi&egrave;me, ni moins ni plus que cela sans qu\'Il ne soit avec eux, l&agrave; o&ugrave; ils se trouvent. Ensuite, Il les informera, au Jour de la R&eacute;surrection, de ce qu\'ils faisaient, car Allah est Omniscient.';
$t[8] = 'Ne vois-tu pas ceux &agrave; qui les conversations secr&egrave;tes ont &eacute;t&eacute; interdites ? Puis, ils retournent &agrave; ce qui leur a &eacute;t&eacute; interdit, et se concertent pour p&eacute;cher, transgresser et d&eacute;sob&eacute;ir au Messager. Et quand ils viennent &agrave; toi, ils te saluent d\'une fa&ccedil;on dont Allah ne t\'a pas salu&eacute;, et disent en eux-m&ecirc;mes : &quot;Pourquoi Allah ne nous ch&acirc;tie pas pour ce que nous disons ? &quot; L\'Enfer leur suffira, o&ugrave; ils br&ucirc;leront. Et quelle mauvaise destination !';
$t[9] = '&ocirc; vous qui avez cru ! Quand vous tenez des conversations secr&egrave;tes, ne vous concertez pas pour p&eacute;cher, transgresser et d&eacute;sob&eacute;ir au Messager, mais concertez-vous dans la bont&eacute; et la pi&eacute;t&eacute;. Et craignez Allah vers qui vous serez rassembl&eacute;s.';
$t[10] = 'La conversation secr&egrave;te n\'est que [l\'oeuvre] du Diable pour attrister ceux qui ont cru. Mais il ne peut leur nuire en rien sans la permission d\'Allah. Et c\'est en Allah que les croyants doivent placer leur confiance.';
$t[11] = '&ocirc; vous qui avez cru ! Quand on vous dit : &quot;Faites place [aux autres] dans les assembl&eacute;es&quot;, alors faites place. Allah vous m&eacute;nagera une place (au Paradis) Et quand on vous dit de vous lever, levez-vous. Allah &eacute;l&egrave;vera en degr&eacute;s ceux d\'entre vous qui auront cru et ceux qui auront re&ccedil;u le savoir. Allah est parfaitement Connaisseur de ce que vous faites.';
$t[12] = '&ocirc; vous qui avez cru ! Quand vous avez un entretien confidentiel avec le Messager, faites pr&eacute;c&eacute;der d\'une aum&ocirc;ne votre entretien : cela est meilleur pour vous et plus pur. Mais si vous n\'en trouvez pas les moyens alors Allah est Pardonneur et tr&egrave;s Mis&eacute;ricordieux !';
$t[13] = 'Appr&eacute;hendez-vous de faire pr&eacute;c&eacute;der d\'aum&ocirc;nes votre entretien ? Mais, si vous ne l\'avez pas fait et qu\'Allah a accueilli votre repentir, alors accomplissez la Salat, acquittez la Zakat, et ob&eacute;issez &agrave; Allah et &agrave; Son messager. Allah est Parfaitement Connaisseur de ce que vous faites.';
$t[14] = 'N\'as-tu pas vu ceux qui ont pris pour alli&eacute;es des gens contre qui Allah S\'est courrouc&eacute; ? Ils ne sont ni des v&ocirc;tres, ni des leurs; et ils jurent mensong&egrave;rement, alors qu\'ils savent .';
$t[15] = 'Allah leur a pr&eacute;par&eacute; un dur ch&acirc;timent. Ce qu\'ils faisaient alors &eacute;tait tr&egrave;s mauvais.';
$t[16] = 'Prenant leurs serments comme boucliers, ils obstruent le chemin d\'Allah. Ils auront donc un ch&acirc;timent avilissant.';
$t[17] = 'Ni leurs bien, ni leurs enfants ne leur seront d\'aucune utilit&eacute; contre la [punition] d\'Allah. Ce sont les gens du Feu o&ugrave; ils demeureront &eacute;ternellement.';
$t[18] = 'Le jour o&ugrave; Allah les ressuscitera tous, ils Lui jureront alors comme ils vous jurent &agrave; vous-m&ecirc;mes, pensant s\'appuyer sur quelque chose de solide. Mais ce sont eux les menteurs.';
$t[19] = 'Le Diable les a domin&eacute;s et leur a fait oublier le rappel d\'Allah. Ceux-l&agrave; sont le parti du Diable et c\'est le parti du Diable qui sont assur&eacute;ment les perdants.';
$t[20] = 'Ceux qui s\'opposent &agrave; Allah et &agrave; Son messager seront parmi les plus humili&eacute;s.';
$t[21] = 'Allah a prescrit : &quot;Assur&eacute;ment, Je triompherai, moi ainsi que Mes Messagers&quot;. En v&eacute;rit&eacute; Allah est Fort et Puissant.';
$t[22] = 'Tu n\'en trouveras pas, parmi les gens qui croient en Allah et au Jour dernier, qui prennent pour amis ceux qui s\'opposent &agrave; Allah et &agrave; Son Messager, fussent-ils leur p&egrave;res, leur fils, leurs fr&egrave;res ou les gens de leur tribu. Il a prescrit la foi dans leurs c&oelig;urs et Il les a aid&eacute;s de Son secours. Il les fera entrer dans des Jardins sous lesquels coulent les ruisseaux, o&ugrave; ils demeureront &eacute;ternellement. Allah les agr&eacute;e et ils L\'agr&eacute;ent. Ceux-l&agrave; sont le parti d\'Allah. Le parti d\'Allah est celui de ceux qui r&eacute;ussissent.';
?>