<?php
$t = array();
$t[1] = 'Ce qui est dans les cieux et ce qui est sur la terre glorifient Allah, et Il est le Puissant, le Sage.';
$t[2] = 'C\'est Lui qui a expuls&eacute; de leurs maisons, ceux parmi les gens du Livre qui ne croyaient pas, lors du premier exode . Vous ne pensiez pas qu\'ils partiraient, et ils pensaient qu\'en v&eacute;rit&eacute; leurs forteresses les d&eacute;fendraient contre Allah. Mais Allah est venu &agrave; eux par o&ugrave; ils ne s\'attendaient point, et a lanc&eacute; la terreur dans leurs c&oelig;urs. Ils d&eacute;molissaient leurs maisons de leurs propres mains, autant que des mains des croyants. Tirez-en une le&ccedil;on, &ocirc; vous &ecirc;tes dou&eacute;s de clairvoyance.';
$t[3] = 'Et si Allah n\'avait pas prescrit contre eux l\'expatriation, Il les aurait certainement ch&acirc;ti&eacute;s ici-bas; et dans l\'au-del&agrave; ils auront le ch&acirc;timent du Feu.';
$t[4] = 'Il en est ainsi parce qu\'ils se sont dress&eacute;s contre Allah et Son messager. Et quiconque se dresse contre Allah... alors, vraiment Allah est dur en punition.';
$t[5] = 'Tout palmier que vous avez coup&eacute; ou que vous avez laiss&eacute; debout sur ses racines, c\'est avec la permission d\'Allah et afin qu\'Il couvre ainsi d\'ignominie les pervers.';
$t[6] = 'Le butin provenant de leurs biens et qu\'Allah a accord&eacute; sans combat &agrave; Son Messager, vous n\'y aviez engag&eacute; ni chevaux, ni chameaux; mais Allah donne &agrave; Ses messagers la domination sur qui Il veut, et Allah est Omnipotent.';
$t[7] = 'Le butin provenant [des biens] des habitants des cit&eacute;s, qu\'Allah a accord&eacute; sans combat &agrave; Son Messager, appartient &agrave; Allah, au Messager, aux proches parents, aux orphelins, aux pauvres et au voyageur en d&eacute;tresse, afin que cela ne circule pas parmi les seuls riches d\'entre vous. Prenez ce que le Messager vous donne; et ce qu\'il vous interdit, abstenez-vous en; et craignez Allah car Allah est dur en punition.';
$t[8] = '[Il appartient aussi] aux &eacute;migr&eacute;s besogneux qui ont &eacute;t&eacute; expuls&eacute;s de leurs demeures et de leurs biens, tandis qu\'ils recherchaient une gr&acirc;ce et un agr&eacute;ment d\'Allah, et qu\'ils portaient secours &agrave; (la cause d\') Allah et &agrave; Son Messager. Ceux-l&agrave; sont les v&eacute;ridiques.';
$t[9] = 'Il [appartient &eacute;galement] &agrave; ceux qui, avant eux, se sont install&eacute;s dans le pays et dans la foi, qui aiment ceux qui &eacute;migrent vers eux, et ne ressentent dans leurs coeurs aucune envie pour ce que [ces immigr&eacute;s] ont re&ccedil;u, et qui [les] pr&eacute;f&egrave;rent &agrave; eux-m&ecirc;mes, m&ecirc;me s\'il y a p&eacute;nurie chez eux. Quiconque se pr&eacute;munit contre sa propre avarice, ceux-l&agrave; sont ceux qui r&eacute;ussissent.';
$t[10] = 'Et [il appartient &eacute;galement] &agrave; ceux qui sont venus apr&egrave;s eux en disant : &quot;Seigneur, pardonne-nous, ainsi qu\'&agrave; nos fr&egrave;res qui nous ont pr&eacute;c&eacute;d&eacute;s dans la foi; et ne mets dans nos coeurs aucune ranc&oelig;ur pour ceux qui ont cru. Seigneur, Tu es Compatissant et Tr&egrave;s Mis&eacute;ricordieux&quot;.';
$t[11] = 'N\'as-tu pas vu les hypocrites disant &agrave; leurs confr&egrave;res qui ont m&eacute;cru parmi les gens du Livre : &quot;Si vous &ecirc;tes chass&eacute;s, nous partirons certes avec vous et nous n\'ob&eacute;irons jamais &agrave; personne contre vous; et si vous &ecirc;tes attaqu&eacute;s, nous vous secourrons certes&quot;. Et Allah atteste qu\'en v&eacute;rit&eacute; ils sont des menteurs.';
$t[12] = 'S\'ils sont chass&eacute;s, ils ne partiront pas avec eux; et s\'ils sont attaqu&eacute;s, ils ne les secourront pas; et m&ecirc;me s\'ils allaient &agrave; leur secours, ils tourneraient s&ucirc;rement le dos; puis ils ne seront point secourus.';
$t[13] = 'Vous jetez dans leurs coeurs plus de terreur qu\'Allah. C\'est qu\'ils sont des gens qui ne comprennent pas.';
$t[14] = 'Tous ne vous combattront que retranch&eacute;s dans des cit&eacute;s fortifi&eacute;es ou de derni&egrave;re des murailles. Leurs dissensions internes sont extr&ecirc;mes. Tu les croirait unis, alors que leurs coeurs sont divis&eacute;s. C\'est qu\'ils sont des gens qui ne raisonnent pas.';
$t[15] = 'ils sont semblables &agrave; ceux qui, peu de temps avant eux, ont go&ucirc;t&eacute; la cons&eacute;quence de leur comportement et ils auront un ch&acirc;timent douloureux ;';
$t[16] = 'ils sont semblables au Diable quand il dit &agrave; l\'homme : &quot;Sois incr&eacute;dule&quot;. Puis quand il a m&eacute;cru, il dit : &quot;Je te d&eacute;savoue car redoute Allah, le Seigneur de l\'Univers&quot;.';
$t[17] = 'Ils eurent pour destin&eacute;e d\'&ecirc;tre tous deux dans le Feu pour y demeurer &eacute;ternellement. Telle est la r&eacute;tribution des injustes.';
$t[18] = '&ocirc; vous qui avez cru ! Craignez Allah. Que chaque &acirc;me voit bien ce qu\'elle a avanc&eacute; pour demain. Et craignez Allah, car Allah est Parfaitement Connaisseur de ce que vous faites.';
$t[19] = 'Et ne soyez pas comme ceux qui ont oubli&eacute; Allah; [Allah] leur a fait alors oublier leur propres personnes; ceux-l&agrave; sont les pervers.';
$t[20] = 'Ne seront pas &eacute;gaux les gens du Feu et les gens du Paradis. Les gens du Paradis sont eux les gagnants.';
$t[21] = 'Si Nous avions fait descendre ce Coran sur une montage, tu l\'aurais vu s\'humilier et se fendre par crainte d\'Allah. Et ces paraboles Nous les Nous les citons aux gens afin qu\'ils r&eacute;fl&eacute;chissent.';
$t[22] = 'C\'est Lui Allah. Nulle divinit&eacute; autre que Lui, le Connaisseur de l\'Invisible tout comme du visible. C\'est Lui, le Tout Mis&eacute;ricordieux, le Tr&egrave;s Mis&eacute;ricordieux.';
$t[23] = 'C\'est Lui, Allah. Nulle divinit&eacute; que Lui; Le Souverain, le Pur, L\'Apaisant, Le Rassurant, le Pr&eacute;dominant, Le Tout Puissant, Le Contraignant, L\'Orgueilleux. Gloire &agrave; Allah ! Il transcende ce qu\'ils Lui associent.';
$t[24] = 'C\'est Lui Allah, le Cr&eacute;ateur, Celui qui donne un commencement &agrave; toute chose, le Formateur. A Lui les plus beaux noms. Tout ce qui est dans les cieux et la terre Le glorifie. Et c\'est Lui le Puissant, le Sage.';
?>