<?php
$t = array();
$t[1] = '&ocirc; vous qui avez cru ! Ne prenez pas pour alli&eacute;s Mon ennemi et le v&ocirc;tre, leur offrant l\'amiti&eacute;, alors qu\'ils ont ni&eacute; ce qui vous est parvenu de la v&eacute;rit&eacute;. Ils expulsent le Messager et vous-m&ecirc;mes parce que vous croyez en Allah, votre Seigneur. Si vous &ecirc;tes sortis pour lutter dans Mon chemin et pour rechercher Mon agr&eacute;ment, leur t&eacute;moignerez-vous secr&egrave;tement de l\'amiti&eacute;, alors que Je connais parfaitement ce que vous cachez et ce que vous divulguez ? Et quiconque d\'entre vous le fait s\'&eacute;gare de la droiture du sentier.';
$t[2] = 'S\'ils vous dominent, ils seront des ennemis pour vous et &eacute;tendront en mal leurs mains et leurs langues vers vous; et ils aimeraient que vous deveniez m&eacute;cr&eacute;ants.';
$t[3] = 'Ni vos proches parents ni vos enfants ne vous seront d\'aucune utilit&eacute; le Jour de la R&eacute;surrection, Il [Allah] d&eacute;cidera entre vous, et Allah est Clairvoyant sur ce que vous faites.';
$t[4] = 'Certes, vous avez eu un bel exemple [&agrave; suivre] en Abraham et en ceux qui &eacute;taient avec lui, quand ils dirent &agrave; leur peuple : &quot;Nous vous d&eacute;savouons, vous et ce que vous adorez en dehors d\'Allah. Nous vous renions. Entre vous et nous, l\'inimiti&eacute; et la haine sont &agrave; jamais d&eacute;clar&eacute;es jusqu\'&agrave; ce que vous croyiez en Allah, seul&quot;. Exception faite de la parole d\'Abraham [adress&eacute;e] &agrave; son p&egrave;re : &quot;J\'implorerai certes, le pardon [d\'Allah] en ta faveur bien que je ne puisse rien pour toi aupr&egrave;s d\'Allah&quot;. &quot;Seigneur, c\'est en Toi que nous mettons notre confiance et &agrave; Toi nous revenons [repentants]. Et vers Toi est le Devenir.';
$t[5] = 'Seigneur, ne fais pas de nous [un sujet] de tentation pour ceux qui ont m&eacute;cru; et pardonne-nous, Seigneur, car c\'est Toi le Puissant, le Sage&quot;';
$t[6] = 'Vous avez certes eu en eux un bel exemple [&agrave; suivre], pour celui qui esp&egrave;re en Allah et en le Jour dernier : mais quiconque se d&eacute;tourne... alors Allah Se suffit &agrave; Lui-m&ecirc;me et est Digne de louange.';
$t[7] = 'Il se peut qu\'Allah &eacute;tablisse de l\'amiti&eacute; entre vous et ceux d\'entre eux dont vous avez &eacute;t&eacute; les ennemis. Et Allah est Omnipotent et Allah est Pardonneur et Tr&egrave;s Mis&eacute;ricordieux.';
$t[8] = 'Allah ne vous d&eacute;fend pas d\'&ecirc;tre bienfaisants et &eacute;quitables envers ceux qui ne vous ont pas combattus pour la religion et ne vous ont pas chass&eacute;s de vos demeures. Car Allah aime les &eacute;quitables.';
$t[9] = 'Allah vous d&eacute;fend seulement de prendre pour alli&eacute;s ceux qui vous ont combattus pour la religion, chass&eacute;s de vos demeures et ont aid&eacute; &agrave; votre expulsion. Et ceux qui les prennent pour alli&eacute;s sont les injustes.';
$t[10] = '&ocirc; vous qui avez cru ! Quand les croyantes viennent &agrave; vous en &eacute;migr&eacute;es, &eacute;prouvez-les; Allah conna&icirc;t mieux leur foi; si vous constatez qu\'elles sont croyantes, ne les renvoyez pas aux m&eacute;cr&eacute;ants. Elles ne sont pas licites [en tant qu\'&eacute;pouses] pour eux, et eux non plus ne sont pas licites [en tant qu\'&eacute;poux] pour elles. Et rendez-leur ce qu\'ils ont d&eacute;pens&eacute; (comme mahr). Il ne vous sera fait aucun grief en vous mariant avec elles quand vous leur aurez donn&eacute; leur mahr. Et ne gardez pas de liens conjugaux avec les m&eacute;cr&eacute;antes . R&eacute;clamez ce que vous avez d&eacute;pens&eacute; et que (les m&eacute;cr&eacute;ants) aussi r&eacute;clament ce qu\'ils ont d&eacute;pens&eacute;. Tel est le jugement d\'Allah par lequel Il juge entre vous, et Allah est Omniscient et Sage.';
$t[11] = 'Et si quelqu\'une de vos &eacute;pouses s\'&eacute;chappe vers les m&eacute;cr&eacute;ants, et que vous fassiez des repr&eacute;sailles , restituez &agrave; ceux dont les &eacute;pouses sont parties autant que ce qu\'ils avaient d&eacute;pens&eacute;. Craignez Allah en qui vous croyez.';
$t[12] = '&ocirc; Proph&egrave;te ! Quand les croyantes viennent te pr&ecirc;ter serment d\'all&eacute;geance, [et en jurent] qu\'elles n\'associeront rien &agrave; Allah, qu\'elles ne voleront pas, qu\'elles ne se livreront pas &agrave; l\'adult&egrave;re, qu\'elles ne tueront pas leurs propres enfants, qu\'elles ne commettront aucune infamie ni avec leurs mains ni avec leurs pieds et qu\'elles ne d&eacute;sob&eacute;iront pas en ce qui est convenable, alors re&ccedil;ois leur serment d\'all&eacute;geance, et implore d\'Allah le pardon pour elles. Allah est certes, Pardonneur et Tr&egrave;s Mis&eacute;ricordieux.';
$t[13] = '&ocirc; vous qui avez cru ! Ne prenez pas pour alli&eacute;s des gens contre lesquels Allah est courrouc&eacute; et qui d&eacute;sesp&egrave;rent de l\'au-del&agrave;, tout comme les m&eacute;cr&eacute;ants d&eacute;sesp&egrave;rent des gens des tombeaux.';
?>