<?php
$t = array();
$t[1] = '&ocirc; Proph&egrave;te ! Quand vous r&eacute;pudier les femmes, r&eacute;pudiez-les conform&eacute;ment &agrave; leur p&eacute;riode d\'attente prescrite; et comptez la p&eacute;riode; et craignez Allah votre Seigneur. Ne les fa&icirc;tes pas sortir de leurs maisons, et qu\'elles n\'en sortent pas, &agrave; moins qu\'elles n\'aient commis une turpitude prouv&eacute;e. Telles sont les lois d\'Allah. Quiconque cependant transgresse les lois d\'Allah, se fait du tort &agrave; lui-m&ecirc;me. Tu ne sais pas si d\'ici l&agrave; Allah ne suscitera pas quelque chose de nouveau !';
$t[2] = 'Puis quand elles atteignent le terme prescrit, retenez-les de fa&ccedil;on convenable, ou s&eacute;parez-vous d\'elles de fa&ccedil;on convenable; et prenez deux hommes int&egrave;gres parmi vous comme t&eacute;moins. Et acquittez-vous du t&eacute;moignage envers Allah. Voil&agrave; ce &agrave; quoi est exhort&eacute; celui qui croit en Allah et au Jour dernier. Et quiconque craint Allah, il lui donnera une issue favorable,';
$t[3] = 'et lui accordera Ses dons par [des moyens] sur lesquels il ne comptait pas. Et quiconque place sa confiance en Allah, Il [Allah] lui suffit. Allah atteint ce qu\'Il Se propose, et Allah a assign&eacute; une mesure &agrave; chaque chose.';
$t[4] = 'Si vous avez des doutes &agrave; propos (de la p&eacute;riode d\'attente) de vos femmes qui n\'esp&egrave;rent plus avoir de r&egrave;gles, leur d&eacute;lai est de trois mois. De m&ecirc;me pour celles qui n\'ont pas encore de r&egrave;gles. Et quant &agrave; celles qui sont enceintes, leur p&eacute;riode d\'attente se terminera &agrave; leur accouchement. Quiconque craint Allah cependant, Il lui facilite les choses .';
$t[5] = 'Tel est le commandement d\'Allah qu\'Il a fait descendre vers vous. Quiconque craint Allah cependant, il lui efface ses fautes et lui accorde une grosse r&eacute;compense.';
$t[6] = 'Et faites que ces femmes habitent o&ugrave; vous habitez, et suivant vos moyens. Et ne cherchez pas &agrave; leur nuire en les contraignant &agrave; vivre &agrave; l\'&eacute;troit. Et si elle sont enceintes, pourvoyez &agrave; leurs besoins jusqu\'&agrave; ce qu\'elles aient accouch&eacute;. Puis, si elles allaitent [l\'enfant n&eacute;] de vous, donnez-leur leurs salaires . Et concertez-vous [&agrave; ce sujet] de fa&ccedil;on convenable. Et si vous rencontrez des difficult&eacute;s r&eacute;ciproques, alors, une autre allaitera pour lui.';
$t[7] = 'Que celui qui est ais&eacute; d&eacute;pense de sa fortune; et que celui dont les biens sont restreints d&eacute;pense selon ce qu\'Allah lui a accord&eacute;. Allah n\'impose &agrave; personne que selon ce qu\'Il lui a donn&eacute;, et Allah fera succ&eacute;der l\'aisance &agrave; la g&ecirc;ne.';
$t[8] = 'Que de cit&eacute;s ont refus&eacute; avec insolence le commandement de leur Seigneur et de Ses messagers ! Nous leur en demand&acirc;mes compte avec s&eacute;v&eacute;rit&eacute;, et les ch&acirc;ti&acirc;mes d\'un ch&acirc;timent inou&iuml;.';
$t[9] = 'Elles go&ucirc;t&egrave;rent donc la cons&eacute;quence de leur comportement. Et le r&eacute;sultat final de leurs actions fut [leur] perdition.';
$t[10] = 'Allah a pr&eacute;par&eacute; pour eux un dur ch&acirc;timent. Craignez Allah donc, &ocirc; vous qui &ecirc;tes dou&eacute;s d\'intelligence, vous qui avez la foi. certes, Allah a fait descendre vers vous un rappel,';
$t[11] = 'un Messager qui vous r&eacute;cite les versets d\'Allah comme preuves claires, afin de faire sortir ceux qui croient et accomplissent les bonnes oeuvres des t&eacute;n&egrave;bres &agrave; la lumi&egrave;re. Et quiconque croit en Allah et fait le bien, Il le fait entrer aux Jardins sous lesquels coulent les ruisseaux, pour y demeurer &eacute;ternellement. Allah lui a fait une belle attribution.';
$t[12] = 'Allah qui a cr&eacute;&eacute; sept cieux et autant de terres. Entre eux [Son] commandement descend, afin que vous sachiez qu\'Allah est en v&eacute;rit&eacute; Omnipotent et qu\'Allah a embrass&eacute; toute chose de [Son] savoir.';
?>