<?php
$t = array();
$t[1] = '&ocirc; Proph&egrave;te ! Pourquoi, en recherchant l\'agr&eacute;ment de tes femmes, t\'interdis-tu ce qu\'Allah t\'a rendu licite ? Et Allah est Pardonneur, Tr&egrave;s Mis&eacute;ricordieux.';
$t[2] = 'Allah vous a prescrit certes, de vous lib&eacute;rer de vos serments. Allah est votre Ma&icirc;tre; et c\'est Lui l\'Omniscient, le Sage .';
$t[3] = 'Lorsque le Proph&egrave;te confia un secret &agrave; l\'une de ses &eacute;pouses et qu\'elle l\'eut divulgu&eacute; et qu\'Allah l\'en eut inform&eacute;, celui-ci en fit conna&icirc;tre une partie et passa sur une partie. Puis, quand il l\'en eut inform&eacute;e elle dit : &quot;Qui t\'en a donn&eacute; nouvelle ? &quot; Il dit : &quot;C\'est l\'Omniscient, le Parfaitement Connaisseur qui m\'en a avis&eacute;&quot;.';
$t[4] = 'Si vous vous repentez &agrave; Allah c\'est que vos coeurs ont fl&eacute;chi. Mais si vous vous soutenez l\'une l\'autre contre le Proph&egrave;te, alors ses alli&eacute;s seront Allah, Gabriel et les vertueux d\'entre les croyants, et les Anges sont par surcro&icirc;t [son] soutien .';
$t[5] = 'S\'Ils vous r&eacute;pudie, il se peut que Seigneur lui donne en &eacute;change des &eacute;pouses meilleurs que vous, musulmanes, croyantes, ob&eacute;issantes, repentantes, adoratrices, je&ucirc;neuses, d&eacute;j&agrave; mari&eacute;es ou vierges .';
$t[6] = '&ocirc; vous qui avez cru ! Pr&eacute;servez vos personnes et vos familles, d\'un Feu dont le combustible sera les gens et les pierres, surveill&eacute; par des Anges rudes, durs, ne d&eacute;sob&eacute;issant jamais &agrave; Allah en ce qu\'Il leur commande, et faisant strictement ce qu\'on leur ordonne.';
$t[7] = '&ocirc; vous qui avez m&eacute;cru ! Ne vous excusez pas aujourd\'hui Vous ne serez r&eacute;tribu&eacute;s que selon ce que vous oeuvriez.';
$t[8] = '&ocirc; vous qui avez cru ! Repentez-vous &agrave; Allah d\'un repentir sinc&egrave;re. Il se peut que votre Seigneur vous efface vos fautes et qu\'Il vous fasse entrer dans des Jardins sous lesquels coulent les ruisseaux, le jour o&ugrave; Allah &eacute;pargnera l\'ignominie au Proph&egrave;te et &agrave; ceux qui croient avec lui. Leur lumi&egrave;re courra devant eux et &agrave; leur droite; ils diront : &quot;Seigneur, parfais-nous notre lumi&egrave;re et pardonne-nous. Car Tu es Omnipotent&quot;.';
$t[9] = '&ocirc; Proph&egrave;te ! M&egrave;ne la lutte contre les m&eacute;cr&eacute;ants et hypocrites et sois rude &agrave; leur &eacute;gard. leur refuge sera l\'Enfer, et quelle mauvaise destination !';
$t[10] = 'Allah a cit&eacute; en parabole pour ceux qui ont m&eacute;cru la femme de No&eacute; et la femme de Lot. Elles &eacute;taient sous l\'autorit&eacute; de deux vertueux de Nos serviteurs. Toutes deux les trahirent et ils ne furent d\'aucune aide pour [ces deux femmes] vis-&agrave;-vis d\'Allah. Et il [leur] fut dit : &quot;Entrez au Feu toutes les deux, avec ceux qui y entrent&quot;,';
$t[11] = 'et Allah a cit&eacute; en parabole pour ceux qui croient, la femme de Pharaon, quand elle dit &quot;Seigneur, construis-moi aupr&egrave;s de Toi une maison dans le Paradis, et sauve-moi de Pharaon et de son oeuvre; et sauve-moi des gens injustes&quot;.';
$t[12] = 'De m&ecirc;me, Marie, la fille d\'Imran qui avait pr&eacute;serv&eacute; sa virginit&eacute;; Nous y insuffl&acirc;mes alors de Notre Esprit. Elle avait d&eacute;clar&eacute; v&eacute;ridiques les paroles de son Seigneur ainsi que Ses Livres : elle fut parmi les d&eacute;vou&eacute;s.';
?>