<?php
$t = array();
$t[1] = 'Allah je čuo riječi one koja se s tobom o mužu svome raspravljala i Allahu se jadala &ndash; a Allah čuje razgovor va&scaron; međusobni, jer Allah, uistinu, sve čuje i sve vidi.';
$t[2] = 'Oni od vas koji ženama svojim reknu da im nisu vi&scaron;e dopu&scaron;tene, kao &scaron;to im nisu dopu&scaron;tene majke njihove &ndash; a one nisu majke njihove, majke njihove su samo one koje su ih rodile &ndash; oni, zaista, govore ružne riječi i neistinu &ndash; a Allah, sigurno, bri&scaron;e grijehe i pra&scaron;ta.';
$t[3] = 'Oni koji ženama svojim reknu da im nisu dopu&scaron;tene, kao &scaron;to im nisu dopu&scaron;tene majke njihove, a onda odluče da s njima nastave živjeti, dužni su, prije nego &scaron;to jedno drugo dodirnu, da jednog roba ropstva oslobode. To vam se naređuje &ndash; a Allah dobro zna ono &scaron;to vi radite.';
$t[4] = 'Onaj koji ne nađe, dužan je da dva mjeseca posti uzastopce prije nego jedno drugo dodirne. A onaj ko ne može, dužan je da &scaron;ezdeset siromaha nahrani, zato da biste potvrdili da u Allaha i Poslanika Njegova vjerujete &ndash; to su vam Allahovi propisi. A nevjernike čeka patnja nesnosna.';
$t[5] = 'Oni koji su neposlu&scaron;ni Allahu i Poslaniku Njegovu biće osramoćeni, kao &scaron;to su bili osramoćeni i oni prije njih. Mi objavljujemo jasne dokaze, a nevjernike čeka sramna patnja';
$t[6] = 'na Dan kada ih Allah sve oživi, pa ih obavijesti o onome &scaron;ta su radili; Allah je o tome račun sveo, a oni su to zaboravili &ndash; Allah je svemu svjedok.';
$t[7] = 'Zar ne zna&scaron; da Allah zna &scaron;to je na nebesima i &scaron;to je na Zemlji? Nema tajnih razgovora među trojicom, a da On nije četvrti, niti među petericom a da On nije &scaron;esti, ni kad ih je manje ni kad ih je vi&scaron;e, a da On nije s njima gdje god oni bili; On će ih na Sudnjem danu obavijestiti o onome &scaron;to su radili, jer Allah sve dobro zna.';
$t[8] = 'Zar ne vidi&scaron; one kojima je zabranjeno da se sa&scaron;aptavaju kako se vraćaju onome &scaron;to im je zabranjeno i sa&scaron;aptavaju se o grijehu i neprijateljstvu i neposlu&scaron;nosti prema Poslaniku. A kad ti dolaze, pozdravljaju te onako kako te Allah nikad nije pozdravio, i među sobom govore: &quot;Trebalo bi da nas Allah već jednom kazni za ono &scaron;to govorimo!&quot; &ndash; Dovoljan će im biti Džehennem! U njemu će gorjeti, a grozno je on prebivali&scaron;te!';
$t[9] = 'O vjernici, kada među sobom tajno razgovarate, ne razgovarajte o grijehu i neprijateljstvu i neposlu&scaron;nosti prema Poslaniku, već razgovarajte o dobročinstvu i čestitosti, i bojte se Allaha, pred kojim ćete sakupljeni biti.';
$t[10] = 'Sa&scaron;aptavanje je posao &scaron;ejtanski, da bi u brigu bacio vjernike, mada to ne može njima nimalo nauditi, osim ako to Allah dopusti. A vjernici neka se samo u Allaha pouzdaju!';
$t[11] = 'O vjernici, kad vam se kaže: &quot;Načinite mjesta drugima tamo gdje se sjedi&quot; &ndash; vi načinite, pa i vama će Allah mjesto načiniti; a kad vam se rekne: &quot;Dignite se&quot; &ndash; vi se dignite &ndash; Allah će na visoke stepene uzdignuti one među vama koji vjeruju i kojima je dato znanje. &ndash; A Allah dobro zna ono &scaron;to radite.';
$t[12] = 'O vjernici, kada hoćete da se s Poslanikom posavjetujete, prije savjetovanja milostinju udijelite. To je za vas bolje i čistije. A ako nemate &ndash; pa, Allah, zaista, pra&scaron;ta i samilostan je.';
$t[13] = 'Zar vas je strah da prije savjetovanja svoga milostinju udijelite? A ako ne udijelite i Allah vam oprosti, onda molitvu obavljajte i zekat dajite i Allaha i Poslanika Njegova slu&scaron;ajte! Allah dobro zna ono &scaron;to vi radite.';
$t[14] = 'Zar ne vidi&scaron; one koji prijateljuju s ljudima na koje se Allah rasrdio? Oni nisu ni va&scaron;i ni njihovi, a jo&scaron; se svjesno krivo zaklinju.';
$t[15] = 'Allah je njima pripremio te&scaron;ku patnju, jer je, zaista, ružno ono &scaron;to rade:';
$t[16] = 'zaklanjaju se iza zakletvi svojih, pa odvraćaju od Allahova puta; njih čeka sramna kazna.';
$t[17] = 'Ni bogatstva njihova ni djeca njihova im nimalo neće pomoći kod Allaha, oni će biti stanovnici u vatri, u njoj će vječno boraviti.';
$t[18] = 'Na Dan kada ih Allah sve oživi oni će se Njemu zaklinjati, kao &scaron;to se vama zaklinju, misleći da će im to ne&scaron;to koristiti. Oni su, doista, pravi lažljivci!';
$t[19] = 'Njima je ovladao &scaron;ejtan i učinio da zaborave na Allaha. Oni su na &scaron;ejtanovoj strani, a onī na &scaron;ejtanovoj strani će, sigurno, nastradati.';
$t[20] = 'Oni koji se suprotstavljaju Allahu i Poslaniku Njegovu biće, sigurno, najgore poniženi.';
$t[21] = 'Allah je zapisao: &quot;Ja i poslanici Moji sigurno ćemo pobijediti!&quot; &ndash; Allah je, zaista, moćan i silan.';
$t[22] = 'Ne treba da ljudi koji u Allaha i u onaj svijet vjeruju budu u ljubavi sa onima koji se Allahu i Poslaniku Njegovu suprotstavljaju, makar im oni bili očevi njihovi, ili sinovi njihovi, ili braća njihova, ili rođaci njihovi. Njima je On u srca njihova vjerovanje usadio i svjetlom Svojim ih osnažio, i On će ih uvesti u džennetske ba&scaron;če kroz koje će rijeke teći, da u njima vječno ostanu. Allah je njima zadovoljan, a i oni će biti zadovoljni Njime. Oni su na Allahovoj strani, a onī na Allahovoj strani će, sigurno, uspjeti.';
?>