<?php
$t = array();
$t[1] = 'O vjernici, ako ste po&scaron;li da se na putu Mome borite i da naklonost Moju steknete, s Mojim i svojim neprijateljima ne prijateljujte i ljubav im ne poklanjajte &ndash; oni poriču Istinu koja vam dolazi i izgone Poslanika i vas samo zato &scaron;to u Allaha, Gospodara va&scaron;eg, vjerujete. Vi im kri&scaron;om ljubav poklanjate, a Ja znam i ono &scaron;to tajite i ono &scaron;to javno činite. Onaj od vas koji to bude činio s Pravog puta je skrenuo.';
$t[2] = 'Ako vas se oni domognu, biće neprijatelji va&scaron;i i pružiće prema vama, u zloj namjeri, ruke svoje i jezičine svoje, i jedva će dočekati da postanete nevjernici.';
$t[3] = 'Ni rodbina va&scaron;a ni djeca va&scaron;a neće vam biti od koristi, na Sudnjem danu On će vas razdvojiti; &ndash; a Allah dobro vidi ono &scaron;to radite.';
$t[4] = 'Divan uzor za vas je Ibrahim i oni koji su uz njega bili kada su narodu svome rekli: &quot;Mi s vama nemamo ni&scaron;ta, a ni sa onima kojima se, umjesto Allahu, klanjate; mi vas se odričemo, i neprijateljstvo i mržnja će između nas ostati sve dok ne budete u Allaha, Njega jedinog, vjerovali!&quot; &ndash; ali nisu riječi Ibrahimove ocu svome: &quot;Ja ću se moliti da ti oprosti, ali te ne mogu od Allaha odbraniti.&quot; &ndash; Gospodaru na&scaron;, u Tebe se uzdamo i Tebi se obraćamo i Tebi ćemo se vratiti.';
$t[5] = 'Ne dopusti, Gospodaru na&scaron;, da nas nevjernicima stavi&scaron; u isku&scaron;enje i oprosti nam, Gospodaru na&scaron;! Ti si, zaista, Silni i Mudri.';
$t[6] = 'Oni su vama divan uzor &ndash; onima koji žele Allaha i onaj svijet. A onaj koji leđa okrene &ndash; pa, Allah, zaista, nije ni o kome ovisan i On je jedini hvale dostojan!';
$t[7] = 'Allah će sigurno uspostaviti ljubav između vas i onih s kojima ste u zavadi; Allah je svemoćan; Allah mnogo pra&scaron;ta i On je samilostan.';
$t[8] = 'Allah vam ne zabranjuje da činite dobro i da budete pravedni prema onima koji ne ratuju protiv vas zbog vjere i koji vas iz zavičaja va&scaron;eg ne izgone &ndash; Allah, zaista, voli one koji su pravični &ndash;';
$t[9] = 'ali vam zabranjuje da prijateljujete sa onima koji ratuju protiv vas zbog vjere i koji vas iz zavičaja va&scaron;eg izgone i koji pomažu da budete prognani. Oni koji s njima prijateljuju sami sebi čine nepravdu.';
$t[10] = 'O vjernici, kada vam vjernice kao muhadžirke dođu, ispitajte ih &ndash; a Allah dobro zna kakvo je vjerovanje njihovo &ndash; pa ako se uvjerite da su vjernice onda ih ne vraćajte nevjernicima: one njima nisu dopu&scaron;tene, niti su oni njima dopu&scaron;teni; a njima podajte ono &scaron;to su potro&scaron;ili. Nije vam grijeh da se njima ženite kad im vjenčane darove njihove date. U braku mnogobo&scaron;kinje ne zadržavajte! Tražite ono &scaron;to ste potro&scaron;ili, a neka i oni traže ono &scaron;to su potro&scaron;ili! To je Allahov sud, On sudi među vama &ndash; a Allah sve zna i mudar je.';
$t[11] = 'A ako neka od žena va&scaron;ih nevjernicima umakne, i ako vi poslije u borbu s njima stupite, onda onima čije su žene umakle &ndash; vjenčane darove koje su im dali namirite. I bojte se Allaha, u koga vjerujete!';
$t[12] = 'O Vjerovjesniče, kada ti dođu vjernice da ti polože prisegu: da neće Allahu nikoga ravnim smatrati, i da neće krasti, i da neće bludničiti, i da neće djecu svoju ubijati, i da neće muževima tuđu djecu podmetati i da neće ni u čemu &scaron;to je dobro poslu&scaron;nost odricati &ndash; ti prisegu njihovu prihvati i moli Allaha da im oprosti; Allah, zaista, mnogo pra&scaron;ta, i On je milostiv.';
$t[13] = 'O vjernici, ne prijateljujte s ljudima koji su protiv sebe Allahovu srdžbu izazvali; oni su izgubili nadu da će bilo kakvu nagradu na ovome svijetu imati, isto kao &scaron;to su izgubili nadu nevjernici da će se njihovi umrli živi vratiti.';
?>