<?php
$t = array();
$t[1] = 'Allah ha udito il discorso di colei che discuteva con te a proposito del suo sposo e si lamentava [davanti] ad Allah. Allah ascoltava il vostro colloquio. Allah &egrave; audiente e vede con chiarezza.';
$t[2] = 'Quanti fra voi che ripudiano le loro mogli dicendo: &ldquo;Sii per me come la schiena di mia madre&rdquo; [sappiano che] esse non sono affatto le loro madri. Le loro madri sono quelle che li hanno partoriti. In verit&agrave; proferiscono qualcosa di riprovevole e una menzogna. Tuttavia Allah &egrave; indulgente, perdonatore.';
$t[3] = 'Coloro che paragonano le loro mogli alla schiena delle loro madri e poi si pentono di quello che hanno detto, liberino uno schiavo prima di riprendere i rapporti coniugali. Siete esortati a far ci&ograve;. Allah &egrave; ben informato di quello che fate.';
$t[4] = 'E colui che non ne abbia i mezzi, digiuni [allora] per due mesi consecutivi prima di riprendere i rapporti coniugali. E chi non ne abbia la possibilit&agrave; nutra sessanta poveri. Ci&ograve; [vi &egrave; imposto] affinch&eacute; crediate in Allah e nel Suo Inviato. Questi sono i limiti di Allah. I miscredenti avranno un doloroso castigo.';
$t[5] = 'In verit&agrave; coloro che si oppongono ad Allah e al Suo Inviato, saranno sgominati come lo furono coloro che li precedettero. Gi&agrave; facemmo scendere prove inequivocabili. I miscredenti subiranno un avvilente castigo,';
$t[6] = 'nel Giorno in cui Allah tutti li resusciter&agrave; e li informer&agrave; delle loro opere. Allah le ha contate, mentre essi le hanno dimenticate. Allah &egrave; testimone di ogni cosa.';
$t[7] = 'Non vedi che Allah conosce quel che &egrave; nei cieli e sulla terra ? Non c\'&egrave; conciliabolo a tre in cui Egli non sia il quarto, n&eacute; a cinque in cui non sia il sesto; siano in pi&ugrave; o in meno, Egli &egrave; con loro ovunque si trovino. Poi, nel Giorno della Resurrezione, li porr&agrave; di fronte a quello che avranno fatto. In verit&agrave; Allah conosce ogni cosa.';
$t[8] = 'Non hai visto coloro ai quali sono stati vietati i conciliaboli? Hanno ricominciato [a fare] quel che era stato loro vietato e tengono conciliaboli peccaminosi, ostili e di disobbedienza nei confronti dell\'Inviato.';
$t[9] = 'O credenti, non siano peccaminosi, ostili e di disobbedienza nei confronti dell\'Inviato, i vostri colloqui privati, ma nel bene e nel timor di Allah. Temete Allah, davanti al Quale sarete radunati.';
$t[10] = 'Il conciliabolo non &egrave; altro che opera di Satana, per affliggere i credenti; ma in nulla pu&ograve; nuocer loro senza il permesso di Allah. Confidino dunque in Allah i credenti.';
$t[11] = 'O credenti, quando vi si dice: &ldquo;Fate spazio [agli altri] nelle assemblee&rdquo;, allora fatelo: Allah vi far&agrave; spazio [in Paradiso]. E quando vi si dice: &ldquo;Alzatevi&rdquo;, fatelo. Allah innalzer&agrave; il livello di coloro che credono e che hanno ricevuto la scienza. Allah &egrave; ben informato di quel che fate.';
$t[12] = 'O credenti! Quando desiderate un incontro privato con il Messaggero, fate precedere il vostro incontro da un\'elemosina: &egrave; meglio per voi e pi&ugrave; puro. Se per&ograve; non ne avete i mezzi, in verit&agrave; Allah &egrave; perdonatore, misericordioso.';
$t[13] = 'Forse temete [di cadere in miseria] se farete precedere un\'elemosina ai vostri incontri privati [con l\'Inviato]? Se non lo avrete fatto - e che Allah accolga il vostro pentimento - eseguite l\'orazione, versate la decima e obbedite ad Allah e al Suo Inviato. Allah &egrave; ben informato di quello che fate.';
$t[14] = 'Non hai visto coloro che si sono alleati con quelli con i quali Allah &egrave; adirato? Non sono n&eacute; dei vostri n&eacute; dei loro, e giurano il falso sapendo di farlo.';
$t[15] = 'Allah ha preparato per loro un severo castigo. &Egrave; malvagio quel che hanno commesso:';
$t[16] = 'facendosi scudo dei loro giuramenti, frappongono ostacoli sulla via di Allah. Avranno un avvilente castigo.';
$t[17] = 'I loro beni e la loro progenie non gioveranno loro in alcun modo contro Allah. Sono i compagni del Fuoco, in cui rimarranno in perpetuo.';
$t[18] = 'Il Giorno in cui Allah li resusciter&agrave; tutti, giureranno [davanti] a Lui come giuravano [davanti] a voi, credendo di basarsi su qualcosa [di vero]. Non sono forse loro i bugiardi?';
$t[19] = 'Satana si &egrave; impadronito di loro, al punto di far s&igrave; che dimenticassero il Ricordo di Allah. Sono il partito di Satana e il partito di Satana in verit&agrave; &egrave; perdente.';
$t[20] = 'In verit&agrave;, coloro che si oppongono ad Allah e al Suo Inviato saranno fra i pi&ugrave; umiliati.';
$t[21] = 'Allah ha scritto: &ldquo;Invero vincer&ograve;, Io e i Miei messaggeri&rdquo;. In verit&agrave; Allah &egrave; forte, eccelso.';
$t[22] = 'Non troverai alcuno, tra la gente che crede in Allah e nell\'Ultimo Giorno, che sia amico di coloro che si oppongono ad Allah e al Suo Inviato, fossero anche i loro padri, i loro figli, i loro fratelli o appartenessero al loro clan. Egli ha impresso la fede nei loro cuori e li ha rafforzati con uno spirito proveniente da Lui. Li far&agrave; entrare nei Giardini dove scorrono i ruscelli, in cui rimarranno in perpetuo. Allah si compiace di loro e loro si compiacciono di Lui. Essi sono il partito di Allah. Ebbene, il partito di Allah non &egrave; forse quello di coloro che trionferanno?';
?>