<?php
$t = array();
$t[1] = 'O credenti, non prendetevi per alleati il Mio nemico e il vostro, dimostrando loro amicizia, mentre essi non hanno creduto alla verit&agrave; che vi &egrave; giunta e hanno scacciato l\'Inviato e voi stessi, solo perch&eacute; credete in Allah vostro Signore. Se siete usciti in combattimento per la Mia causa, bramando il Mio compiacimento, pensate di poter mantenere segreta la vostra relazione con loro, mentre Io conosco meglio [di chiunque altro] quel che celate e quel che palesate? Chi di voi agisse in questo modo si allontanerebbe dalla retta via.';
$t[2] = 'Se vi incontrano in qualche luogo, saranno vostri nemici, vi aggrediranno con le loro mani e le loro lingue e si augureranno che diveniate miscredenti.';
$t[3] = 'I vostri parenti e i vostri figli non vi saranno utili e nel Giorno della Resurrezione [Allah] decider&agrave; tra di voi; Allah osserva quello che fate.';
$t[4] = 'Avete avuto un bell\'esempio in Abramo e in coloro che erano con lui, quando dissero alla loro gente: &ldquo;Noi ci dissociamo da voi e da quel che adorate all\'infuori di Allah: vi rinneghiamo. Tra noi e voi &egrave; sorta inimicizia e odio [che continueranno] ininterrotti, finch&eacute; non crederete in Allah, l\'Unico&rdquo;, eccezion fatta per quanto Abramo disse a suo padre : &ldquo;Implorer&ograve; perdono per te, anche se &egrave; certo che non ho alcun potere in tuo favore presso Allah!&rdquo;. - &ldquo;Signore a Te ci affidiamo, a Te ci volgiamo pentiti e verso di Te &egrave; il divenire.';
$t[5] = 'Signore, non fare di noi una tentazione per i miscredenti e perdonaci, o Signore! Tu sei l\'Eccelso, il Saggio.&rdquo;';
$t[6] = 'Invero avete avuto in loro un bell\'esempio, per chi spera in Allah e nell\'Ultimo Giorno. Quanto a chi invece volge le spalle, Allah basta a Se stesso ed &egrave; il Degno di lode.';
$t[7] = 'Forse Allah stabilir&agrave; amicizia tra voi e quanti fra di loro considerate nemici. Allah &egrave; onnipotente e Allah &egrave; perdonatore, misericordioso.';
$t[8] = 'Allah non vi proibisce di essere buoni e giusti nei confronti di coloro che non vi hanno combattuto per la vostra religione e che non vi hanno scacciato dalle vostre case, poich&eacute; Allah ama coloro che si comportano con equit&agrave;.';
$t[9] = 'Allah vi proibisce soltanto di essere alleati di coloro che vi hanno combattuto per la vostra religione, che vi hanno scacciato dalle vostre case, o che hanno contribuito alla vostra espulsione. Coloro che li prendono per alleati, sono essi gli ingiusti.';
$t[10] = 'O voi che credete, quando giungono a voi le credenti che sono emigrate, esaminatele ; Allah ben conosce la loro fede. Se le riconoscerete credenti, non rimandatele ai miscredenti - esse non sono lecite per loro n&eacute; essi sono loro leciti - e restituite loro ci&ograve; che avranno versato. Non vi sar&agrave; colpa alcuna se le sposerete versando loro il dono nuziale. Non mantenete legami coniugali con le miscredenti. Rivendicate quello che avete versato ed essi rivendichino quel che hanno versato. Questo &egrave; il giudizio di Allah, con il quale giudica fra voi, e Allah &egrave; sapiente, saggio.';
$t[11] = 'Se qualcuna delle vostre spose fugge verso i miscredenti, quando avete la meglio [su di loro] date a quelli le cui spose sono fuggite, quanto avevano versato. Temete Allah nel Quale credete.';
$t[12] = 'O Profeta, quando vengono a te le credenti a stringere il patto, [giurando] che non assoceranno ad Allah alcunch&eacute;, che non ruberanno, che non fornicheranno, che non uccideranno i loro figli, che non commetteranno infamie con le loro mani o con i loro piedi e che non ti disobbediranno in quel che &egrave; reputato conveniente, stringi il patto con loro e implora Allah di perdonarle. Allah &egrave; perdonatore, misericordioso.';
$t[13] = 'O credenti, non prendetevi per alleati gente contro la quale Allah &egrave; adirato e che non hanno la speranza dell\'altra vita, come i miscredenti che disperano [di rivedere] la gente delle tombe.';
?>