<?php
$t = array();
$t[1] = 'Je! Imekufikia khabari ya msiba wa kufudikiza?';
$t[2] = 'Siku hiyo nyuso zitainama,';
$t[3] = 'Zikifanya kazi, nazo taabani.';
$t[4] = 'Ziingie katika Moto unao waka -';
$t[5] = 'Zikinyweshwa kutoka chemchem inayo chemka.';
$t[6] = 'Hawatakuwa na chakula isipo kuwa kichungu chenye miba.';
$t[7] = 'Hakinenepeshi wala hakiondoi njaa.';
$t[8] = 'Siku hiyo nyuso nyengine zitakuwa kunjufu.';
$t[9] = 'Zitakuwa radhi kwa juhudi yao,';
$t[10] = 'Katika Bustani ya juu.';
$t[11] = 'Hawatasikia humo upuuzi.';
$t[12] = 'Humo imo chemchem inayo miminika.';
$t[13] = 'Humo vimo viti vilivyo nyanyuliwa,';
$t[14] = 'Na bilauri zilizo pangwa,';
$t[15] = 'Na matakia safu safu,';
$t[16] = 'Na mazulia yaliyo tandikwa.';
$t[17] = 'Je! Hawamtazami ngamia jinsi alivyo umbwa?';
$t[18] = 'Na mbingu jinsi ilivyo inuliwa?';
$t[19] = 'Na milima jinsi ilivyo thibitishwa?';
$t[20] = 'Na ardhi jinsi ilivyo tandazwa?';
$t[21] = 'Basi kumbusha! Hakika wewe ni Mkumbushaji.';
$t[22] = 'Wewe si mwenye kuwatawalia.';
$t[23] = 'Lakini anaye rudi nyuma na kukataa,';
$t[24] = 'Basi Mwenyezi Mungu atamuadhibu kwa adhabu iliyo kubwa kabisa!';
$t[25] = 'Hakika ni kwetu Sisi ndio marejeo yao.';
$t[26] = 'Kisha hakika ni juu yetu Sisi hisabu yao!';
?>