<?php
$t = array();
$t[1] = 'Dumnezeu a auzit vorbele celei care se certa cu tine despre soţul ei şi se pl&acirc;ngea lui Dumnezeu. Dumnezeu a auzit cearta voastră. El este Auzitorul, Văzătorul.';
$t[2] = 'Aceia dintre voi care &icirc;şi compară femeile cu spatele mamelor, să ştie că ele nu le sunt mame, căci mame le sunt doar acelea care i-au născut. Ei spun o vorbă nesăbuită şi ne&icirc;ntemeiată. Dumnezeu este Cel ce şterge păcatele, Iertătorul';
$t[3] = 'Cei care &icirc;şi compară femeile cu spatele mamelor lor şi repetă ceea ce au spus, va trebui să sloboade un rob &icirc;nainte de a se atinge din nou de ele. Aşa vă este predicat. Dumnezeu este Ştiutor a ceea ce făptuiţi.';
$t[4] = 'Cel care nu află aşa ceva, atunci să postească două luni necurmat &icirc;nainte de a se atinge unul de celălalt. Cel care nu poate, atunci să ospăteze şaizeci de sărmani. Aceasta pentru ca voi să credeţi &icirc;n Dumnezeu şi &icirc;n trimisul Său. Acestea sunt r&acirc;nduielile lui Dumnezeu, iar cei care le &icirc;ncalcă vor avea parte de o dureroasă os&acirc;ndă.';
$t[5] = 'Cei care se &icirc;mpotrivesc lui Dumnezeu şi trimisului Său vor fi răsturnaţi precum au fost şi cei dinaintea lor. Noi am pogor&acirc;t semne vădite. Tăgăduitorii vor avea o os&acirc;ndă umilitoare';
$t[6] = '&icirc;n Ziua c&acirc;nd Dumnezeu &icirc;i va scula şi le va da ştire de ceea ce-au săv&acirc;rşit. Dumnezeu le-a ţinut socoteala, &icirc;nsă ei au uitat. Dumnezeu este Martor asupra tuturor.';
$t[7] = 'Nu vezi oare că Dumnezeu ştie ceea ce este &icirc;n ceruri, precum şi pe păm&acirc;nt? Nu stau de vorbă trei, unde El să nu fie al patrulea, ori cinci şi El să nu fie al şaselea. Fie ei mai puţini ori mai mulţi, El este cu ei oriunde s-ar afla. &Icirc;n Ziua &Icirc;nvierii, El &icirc;i va &icirc;nştiinţa de ceea ce-au săv&acirc;rşit. Dumnezeu este Atotcunoscător!';
$t[8] = 'Nu i-ai văzut pe cei cărora li s-a oprit sfatul &icirc;n taină. Ei s-au apucat iarăşi de ceea ce le-a fost oprit. Ei ţin sfaturi &icirc;n taină cu păcat şi vrăjmăşie şi ned&acirc;ndu-i ascultare Trimisului. C&acirc;nd vin la tine te salută, cum nici Dumnezeu nu te-a salutat. Ei spun &icirc;n sinea lor: &ldquo;Să nu ne pedepsească Dumnezeu pentru ceea ce spunem!&rdquo; &Icirc;n Gheena vor fi aruncaţi! Ce rea devenire!';
$t[9] = 'O, voi cei ce credeţi! Atunci c&acirc;nd luaţi parte la sfaturi &icirc;n taină, feriţi-vă de păcat, de vrăjmăşie, de neascultarea Trimisului. Vorbiţi cu bunătate şi pioşenie. Temeţi-vă de Dumnezeu, căci veţi fi adunaţi &icirc;naintea Lui.';
$t[10] = 'Sfaturile &icirc;n taină vin de la Satan pentru a-i m&acirc;hni pe credincioşi. El nu le poate face &icirc;nsă nici un rău dec&acirc;t cu &icirc;ngăduinţa lui Dumnezeu. Credincioşii să se &icirc;ncredinţeze lui Dumnezeu!';
$t[11] = 'O, voi cei ce credeţi, c&acirc;nd vi se spune: &ldquo;Faceţi loc şi altora la sfaturile voastre!&rdquo; Atunci, faceţi loc, căci şi Dumnezeu vă va face loc. C&acirc;nd vi se spune: &ldquo;Sculaţi-vă!&rdquo; Atunci, sculaţi-vă. Dumnezeu &icirc;i va ridica pe trepte pe cei care cred şi au primit ştiinţa. Dumnezeu este Ştiutor a ceea ce făptuiţi.';
$t[12] = 'O, voi cei ce credeţi! C&acirc;nd aveţi un sfat de taină cu trimisul, daţi milostenie &icirc;nainte! Aşa este mai bine pentru voi şi mai curat. Dacă nu veţi găsi nimic (de dat), să ştiţi că Dumnezeu este Iertător, Milostiv!';
$t[13] = 'Vă temeţi ca &icirc;nainte de vorba voastră să daţi milostenie? C&acirc;nd nu o faceţi, iar Dumnezeu se &icirc;ntoarce către voi, atunci faceţi rugăciunea, daţi milostenie, daţi-i ascultare lui Dumnezeu şi trimisului Său. Dumnezeu este Ştiutor a ceea ce făptuiţi.';
$t[14] = 'Nu i-ai văzut pe cei care stau &icirc;n spatele unor oameni asupra cărora Dumnezeu s-a m&acirc;niat şi care nu sunt nici de-ai voştri şi nici de-ai lor? Ei jură str&acirc;mb, chiar dacă ştiu!';
$t[15] = 'Dumnezeu le-a pregătit o os&acirc;ndă aprigă, căci rău este ceea ce fac.';
$t[16] = 'Ei &icirc;şi iau jurămintele ca pavăză şi-i &icirc;mpiedică pe oameni de la calea lui Dumnezeu. Ei vor avea o os&acirc;ndă umilitoare.';
$t[17] = 'Nici averile şi nici copiii nu le vor fi de vreun folos &icirc;n faţa lui Dumnezeu. Ei sunt soţii Focului, unde vor veşnici.';
$t[18] = '&Icirc;n Ziua c&acirc;nd Dumnezeu &icirc;i va scula pe toţi, ei I se vor jura precum vi se jură şi vouă socotind că se sprijină pe ceva. Nu sunt ei oare mincinoşi?';
$t[19] = 'Satan a pus stăp&acirc;nire pe ei şi i-a făcut să uite amintirea lui Dumnezeu. Aceştia sunt iubitorii lui Satan. Iubitorii lui Satan nu sunt ei oare pierduţi?';
$t[20] = 'Cei care se &icirc;mpotrivesc lui Dumnezeu şi trimisului Său vor fi cei mai umiliţi.';
$t[21] = 'Dumnezeu a scris: &ldquo;Eu şi trimişii Mei vom birui &icirc;ntotdeauna. Dumnezeu este Brav, Puternic.';
$t[22] = 'Nu vei afla oameni ce cred &icirc;n Dumnezeu şi &icirc;n Ziua de Apoi care să le arate prietenie celor care se &icirc;mpotrivesc lui Dumnezeu şi trimisului Său, chiar de sunt taţii lor, fiii lor, fraţii lor ori obştea lor. Dumnezeu le-a scris &icirc;n inimi credinţa şi i-a &icirc;ntărit cu duhul Său. El &icirc;i va lăsa să intre &icirc;n Grădinile pe sub care curg r&acirc;uri, unde vor veşnici. Dumnezeu este mulţumit de ei, iar ei sunt mulţumiţi de El. Aceştia sunt iubitorii lui Dumnezeu. Iubitorii lui Dumnezeu nu sunt oare cei fericiţi?';
?>