<?php
$t = array();
$t[1] = 'O, voi cei ce credeţi! Nu-i luaţi de prieteni pe vrăjmaşii Mei şi pe vrăjmaşii voştri. Voi &icirc;i &icirc;nt&acirc;mpinaţi cu prietenie, &icirc;nsă ei tăgăduiesc Adevărul ce v-a venit şi &icirc;l prigonesc pe Trimis şi pe voi &icirc;nşivă fiindcă voi credeţi &icirc;n Dumnezeu, Domnul vostru. Dacă ieşiţi să vă luptaţi pe calea Mea caut&acirc;nd mulţumirea Mea, &icirc;nsă le mărturisiţi &icirc;n ascuns prietenie, Eu ştiu ceea ce voi tăinuiţi şi ceea ce destăinuiţi. Oricare dintre voi face astfel se rătăceşte de la Calea cea Dreaptă.';
$t[2] = 'Dacă vă vor avea ei &icirc;n m&acirc;nă, vă vor fi vrăjmaşi, vă vor ocăr&icirc; şi vă vor lovi şi s-ar bucura dacă aţi tăgădui.';
$t[3] = 'Nici rudele voastre, nici pruncii voştri nu vă vor fi de vreun folos &icirc;n Ziua &Icirc;nvierii c&acirc;nd El va judeca &icirc;ntre voi. El este Văzătorul a ceea ce făptuiţi.';
$t[4] = 'Aveţi o frumoasă pildă &icirc;n Abraham şi &icirc;n cei dimpreună cu el c&acirc;nd au spus poporului lor: &ldquo;Noi vă desfidem pe voi şi pe cei cărora vă &icirc;nchinaţi &icirc;n locul lui Dumnezeu. Ne lepădăm de voi! Vrăjmăşia şi ura să fie &icirc;ntotdeauna &icirc;ntre noi şi voi p&acirc;nă c&acirc;nd veţi crede &icirc;n Dumnezeu, Unul!&rdquo; Precum şi &icirc;n vorbele lui Abraham către tatăl său: &ldquo;Eu voi cere iertare pentru tine, chiar dacă nu pot face nimic pentru tine &icirc;naintea lui Dumnezeu.&rdquo; &ldquo;Domnul nostru! Ţie ne &icirc;ncredinţăm! La Tine ne &icirc;ntoarcem, căci &icirc;ntru Tine este devenirea!';
$t[5] = 'Domnul nostru! Nu ne face pe noi prada celor care tăgăduiesc! Domnul nostru! Iartă-ne nouă! Tu eşti Puternicul, &Icirc;nţeleptul.&rdquo;';
$t[6] = 'Aveţi &icirc;n ei o frumoasă pildă despre cei care &icirc;şi pun speranţa &icirc;n Dumnezeu şi &icirc;n Ziua de Apoi. Cel care &icirc;ntoarce spatele să ştie că Dumnezeu este Bogat, Lăudat.';
$t[7] = 'Dumnezeu ar putea pune prietenie &icirc;ntre voi şi unii dintre cei pe care &icirc;i socotiţi vrăjmaşi. Dumnezeu este Atotputernicul! El este Iertător, Milostiv';
$t[8] = 'Dumnezeu nu vă opreşte de la a fi buni şi drepţi cu cei care nu s-au războit cu voi pe credinţă şi nici nu v-au prigonit din casele voastre. Dumnezeu &icirc;i iubeşte pe cei nepărtinitori.';
$t[9] = 'Dumnezeu vă opreşte de la a vi-i face prieteni pe cei care s-au războit cu voi pentru credinţă şi v-au prigonit din casele voastre şi au fost părtaşi la prigonirea voastră. Cei care-i fac prieteni, sunt nedrepţi!';
$t[10] = 'O, voi cei ce credeţi! C&acirc;nd credincioasele care s-au pribegit, vin la voi, puneţi-le la &icirc;ncercare. Dumnezeu ştie prea bine credinţa lor. Dacă le aflaţi credincioase nu le &icirc;napoiaţi tăgăduitorilor &mdash; ele nu le mai sunt &icirc;ngăduite, ei nu le mai sunt &icirc;ngăduiţi. Daţi-le ceea ce au cheltuit pentru ele. Nu vi se va face nici o vină dacă vă &icirc;nsoţiţi cu ele după ce le-aţi dat dota. Nu le ţineţi, &icirc;nsoţindu-vă cu ele, pe cele necredincioase. Cereţi ce aţi cheltuit şi să vă ceară şi ei ce au cheltuit. Aceasta este judecata lui Dumnezeu cu care El vă judecă. Dumnezeu este Ştiutorul, &Icirc;nţeleptul';
$t[11] = 'Dacă vreuna dintre soţiile voastre fuge la tăgăduitori, iar voi &icirc;i veţi pedepsi pe aceştia, daţi despăgubire celor ale căror soţii au fugit pentru ceea ce au cheltuit. Temeţi-vă de Dumnezeu &icirc;n care credeţi!';
$t[12] = 'O, Profetule! C&acirc;nd credincioasele vin la tine şi-ţi fac jurăminte de credinţă că nu vor alătura pe nimeni lui Dumnezeu, nu vor fura, nu vor preacurvi, nu-şi vor ucide pruncii, nu vor veni cu nici o m&acirc;rşăvie născocită &icirc;ntre m&acirc;inile şi picioarele lor, nu se vor răzvrăti asupra ta &icirc;ntru cele de cuviinţă, primeşte atunci jurăm&acirc;ntul lor de credinţă. Cere iertare lui Dumnezeu pentru ele. Dumnezeu este Iertătorul, Milostivul';
$t[13] = 'O, voi cei ce credeţi! Nu vă faceţi prieteni dintr-un popor asupra căruia Dumnezeu s-a m&acirc;niat şi nu are nici o speranţă pentru Viaţa de Apoi, aşa cum tăgăduitorii n-au nici o nădejde pentru cei din morminte.';
?>