<?php
$t = array();
$t[1] = 'O, Profetule! Atunci c&acirc;nd vă lepădaţi de femeile voastre, faceţi-o după răstimpul de aşteptare. Socotiţi cu grijă răstimpul de aşteptare. Temeţi-vă de Dumnezeu, Domnul vostru! Nu le alungaţi din casele lor şi nici ele să nu iasă, doar dacă au săv&acirc;rşit o curvie vădită. Acestea sunt hotarele lui Dumnezeu, iar cel care le &icirc;ncalcă &icirc;şi face rău sieşi. Tu n-ai de unde să ştii, căci s-ar putea ca Dumnezeu să dea, după aceea, o altă poruncă.';
$t[2] = 'C&acirc;nd s-a &icirc;nt&acirc;mplinit sorocul hotăr&acirc;t, ţineţi-le cum se cuvine ori despărţiţi-vă de ele cum se cuvine. Chemaţi doi martori drepţi dintre voi şi depuneţi mărturie &icirc;naintea lui Dumnezeu. Aşa este &icirc;ndemnat cel care crede &icirc;n Dumnezeu şi &icirc;n Ziua de Apoi. Celui care se teme de Dumnezeu, Dumnezeu &icirc;i va asigura &icirc;ntotdeauna o ieşire';
$t[3] = 'şi &icirc;i va dărui ceea ce nici nu socoate. Dumnezeu este de ajuns celui care se &icirc;ncrede &icirc;n El. Dumnezeu duce la &icirc;mplinire porunca Sa. Dumnezeu a dat o soartă fiecărui lucru.';
$t[4] = 'Răstimpul de aşteptare va fi de trei luni, chiar şi pentru acelea dintre femeile voastre care nu mai nădăjduiesc la cele femeieşti &mdash; dacă aveţi vreo &icirc;ndoială &mdash; precum şi pentru cele care nu au &icirc;ncă cele femeieşti. Sorocul femeilor &icirc;nsărcinate se &icirc;mplineşte odată cu naşterea. Celui ce se teme de Dumnezeu, Dumnezeu &icirc;i uşurează povara.';
$t[5] = 'Aceasta este Porunca lui Dumnezeu pe care El a pogor&acirc;t-o asupra voastră. El &icirc;i şterge faptele rele celui ce se teme şi &icirc;i măreşte răsplata.';
$t[6] = 'Lăsaţi-le pe aceste femei să locuiască acolo unde locuiţi şi voi, după putinţa voastră. Nu le pricinuiţi suferinţe ca să le str&acirc;mtoraţi. Dacă sunt &icirc;nsărcinate aveţi grijă de ele p&acirc;nă c&acirc;nd nasc. Dacă alăptează copilul avut de la voi, daţi-le răsplata lor. &Icirc;nvoiţi-vă &icirc;ntre voi cum se cuvine, &icirc;nsă dacă vă faceţi greutăţi unul altuia, atunci să-l alăpteze alta.';
$t[7] = 'Cel care trăieşte &icirc;n &icirc;ndestulare, să plătească după puterea sa. Cel care nu are dec&acirc;t cu ce trăi, să plătească după cum i-a dat Dumnezeu. Dumnezeu nu &icirc;mpovărează pe nimeni dec&acirc;t pe măsura putinţei pe care i-a dat-o. Dumnezeu va face ca după greutate să vină uşurare.';
$t[8] = 'C&acirc;te cetăţi n-au dat ascultare Poruncilor Domnului lor şi ale trimişilor Săi! Noi le-am judecat cu asprime şi le-am os&acirc;ndit la o os&acirc;ndă fără seamăn.';
$t[9] = 'Ele au gustat urmarea faptelor lor, iar sf&acirc;rşitul faptelor lor a fost pierirea!';
$t[10] = 'Dumnezeu le-a pregătit os&acirc;ndă aspră. Temeţi-vă de Dumnezeu, voi cei dăruiţi cu minte şi care credeţi! Dumnezeu a pogor&acirc;t asupra voastră o amintire.';
$t[11] = 'Un trimis vă recită versetele desluşite ale lui Dumnezeu ca să vă scoată din &icirc;ntunecimi către lumină, pe voi, cei care credeţi şi făptuiţi binele. Dumnezeu &icirc;i va lăsa să intre &icirc;n Grădinile pe sub care curg r&acirc;uri, unde vor veşnici. Dumnezeu le face o frumoasă dăruire.';
$t[12] = 'Dumnezeu este Cel ce a creat şapte ceruri şi păm&acirc;ntul deopotrivă cu ele. Porunca pogoară &icirc;ntre ele ca să ştiţi că Dumnezeu are putere asupra tuturor şi asupra tuturor se &icirc;ntinde ştiinţa Sa.';
?>