<?php
$t = array();
$t[1] = 'A venit la tine spusa despre cea care &icirc;nvăluie?';
$t[2] = '&Icirc;n Ziua aceea, chipuri care se umilesc,';
$t[3] = 'care se trudesc şi se sleiesc,';
$t[4] = 'vor fi aruncate &icirc;ntr-un foc dogoritor.';
$t[5] = 'Se vor adăpa la un izvor clocotit';
$t[6] = 'şi vor avea drept ospăţ mărăcini';
$t[7] = 'care nici nu-i vor &icirc;ngrăşa, &icirc;nsă nici foamea nu le-o va ast&acirc;mpăra.';
$t[8] = '&Icirc;n Ziua aceea, chipuri voioase,';
$t[9] = 'de zelul lor mulţumite,';
$t[10] = 'vor fi &icirc;ntr-o Grădină &icirc;naltă';
$t[11] = 'unde nu vor auzi nici o vorbă deşartă.';
$t[12] = 'Acolo va fi un izvor curgător;';
$t[13] = 'paturi &icirc;nălţate,';
$t[14] = 'pocale aranjate,';
$t[15] = 'perne r&acirc;nduite,';
$t[16] = 'covoare aşternute.';
$t[17] = 'Oare ei nu privesc la cămile cum au fost create?';
$t[18] = 'Şi nici la cer cum a fost ridicat?';
$t[19] = 'Şi nici la munţi cum au fost &icirc;nălţaţi?';
$t[20] = 'Şi nici la păm&acirc;nt cum a fost &icirc;ntins?';
$t[21] = 'Adu-le aminte, căci asupra ta stă aducerea aminte,';
$t[22] = '&icirc;nsă asupra lor nu ai nici o putere.';
$t[23] = 'Celui care &icirc;ntoarce spatele şi tăgăduieşte,';
$t[24] = 'Dumnezeu &icirc;i va da os&acirc;nda cea mare.';
$t[25] = 'La Noi este &icirc;ntoarcerea lor,';
$t[26] = 'şi asupra Noastră stă judecata lor.';
?>