<?php
$t = array();
$t[1] = 'Kocasi hakkinda seninle tartisan ve Allah\'a sikayette bulunan kadinin s&ouml;z&uuml;n&uuml; Allah isitmistir. Allah, sizin konusmanizi isitir. &Ccedil;&uuml;nk&uuml; Allah, isitendir, bilendir.';
$t[2] = 'I&ccedil;inizde zih&acirc;r yapanlarin kadinlari, onlarin analari degildir. Onlarin analari ancak kendilerini doguran kadindir. S&uuml;phesiz onlar &ccedil;irkin ve yalan bir laf s&ouml;yl&uuml;yorlar. Kuskusuz Allah, affedici, bagislayicidir.';
$t[3] = 'Kadinlardan zih&acirc;r ile ayrilmak isteyip de sonra s&ouml;ylediklerinden d&ouml;nenlerin, karilariyla temas etmeden &ouml;nce bir k&ouml;leyi h&uuml;rriyete kavusturmalari gerekir. Size &ouml;g&uuml;tlenen budur. Allah, yaptiklarinizdan haberi olandir.';
$t[4] = 'Buna imkan bulamayan kimse, temas etmeden &ouml;nce araliksiz olarak iki ay oru&ccedil; tutmalidir. Buna da g&uuml;c&uuml; yetmeyen, altmis fakiri doyurur. Bu (hafifletme), Allah\'a ve Resul&uuml;ne inanmanizdan dolayidir. Bunlar Allah\'in h&uuml;k&uuml;mleridir. K&acirc;firler i&ccedil;in aci bir azap vardir.';
$t[5] = 'Allah\'a ve Resul&uuml;ne karsi gelenler, kendilerinden &ouml;ncekilerin al&ccedil;altildigi gibi al&ccedil;altilacaklardir. Biz apa&ccedil;ik &acirc;yetler indirmisizdir. K&acirc;firler i&ccedil;in k&uuml;&ccedil;&uuml;k d&uuml;s&uuml;r&uuml;c&uuml; bir azap vardir.';
$t[6] = 'O g&uuml;n Allah onlarin hepsini diriltecek ve yaptiklarini kendilerine haber verecektir. Allah onlari bir bir saymistir. Onlar ise unutmuslardir. Allah her seye sahiddir';
$t[7] = 'G&ouml;klerde ve yerde olanlari, Allah\'in bildigini g&ouml;rm&uuml;yor musunuz? &Uuml;&ccedil; kisinin gizli konustugu yerde d&ouml;rd&uuml;nc&uuml;s&uuml; mutlaka O\'dur. Bes kisinin gizli konustugu yerde altincisi mutlaka O\'dur. Bunlardan az veya &ccedil;ok olsunlar ve nerede bulunurlarsa bulunsunlar mutlak O, onlarla beraberdir. Sonra kiyamet g&uuml;n&uuml; onlara yaptiklarini haber verecektir. Dogrusu Allah, her seyi bilendir.';
$t[8] = 'Gizli konusmaktan menedildikten sonra yine o menedildikleri seyi yapmaya kalkisarak g&uuml;nah, d&uuml;smanlik ve Peygamber\'e karsi gelmek hususunda gizlice konusanlari g&ouml;rmedin mi? Onlar sana geldikleri zaman seni, Allah\'in selamlamadigi bir tarzda selamliyorlar. Kendi i&ccedil;lerinden de &quot;bu s&ouml;ylediklerimiz y&uuml;z&uuml;nden Allah\'in bize azap etmesi gerekmez miydi?&quot; derler. Cehennem onlara yeter. Oraya gireceklerdir, ne k&ouml;t&uuml; d&ouml;n&uuml;s yeridir orasi!';
$t[9] = 'Ey iman edenler! Aranizda gizli konusacaginiz zaman g&uuml;nahi d&uuml;smanligi ve Peygamber\'e karsi gelmeyi fisildamayin. Iyilik ve takvayi konusun. Huzuruna toplanacaginiz Allah\'tan korkun.';
$t[10] = 'Gizli konusmalar seytandandir. Bu iman edenleri &uuml;zmek i&ccedil;indir. Oysa seytan, Allah\'in izni olmadik&ccedil;a, m&uuml;minlere hi&ccedil;bir zarar veremez. M&uuml;minler Allah\'a dayanip g&uuml;vensinler.';
$t[11] = 'Ey iman edenler! Size: &quot;Meclislerde yer a&ccedil;in.&quot; denilince yer a&ccedil;in ki Allah da size genislik versin. Size &quot;Kalkin.&quot; denilince de kalkin ki Allah sizden inananlari ve kendilerine ilim verilenleri derecelerle y&uuml;kseltsin. Allah yaptiklarinizdan haberi olandir.';
$t[12] = 'Ey iman edenler! Peygamber ile gizli bir sey konusacaginiz zaman bu konusmanizdan &ouml;nce bir sadaka veriniz. Bu sizin i&ccedil;in daha hayirli ve daha temizdir. Sayet bir sey bulamazsaniz, artik Allah bagislayan ve merhamet edendir..';
$t[13] = 'Gizli (&ouml;zel) bir sey konusmanizdan &ouml;nce sadaka vermekten korktunuz da mi yerine getirmediniz? Fakat Allah da sizi affetti. Su halde namazi kilin, zekati verin, Allah\'a ve Resul&uuml;ne itaat edin. Allah, yaptiklarinizdan haberi olandir.';
$t[14] = 'Allah\'in kendilerine gazap ettigi bir toplulugu dost edinenleri g&ouml;rmedin mi? Onlar ne sizdendirler, ne de onlardan. Bilerek yalan yere yemin ediyorlar.';
$t[15] = 'Allah onlara &ccedil;etin bir azab hazirlamistir. Onlar ne k&ouml;t&uuml; isler yapiyorlar!';
$t[16] = 'Yeminlerini kalkan yapip Allah\'in yolundan &ccedil;evirdiler. Onlar i&ccedil;in k&uuml;&ccedil;&uuml;k d&uuml;s&uuml;r&uuml;c&uuml; bir azab vardir.';
$t[17] = 'Onlarin ne mallari, ne de evlatlari, kendilerinden, Allah\'dan hi&ccedil;bir sey savamaz. Onlar ates halkidir. Orada ebed&icirc; kalacaklardir.';
$t[18] = 'Allah onlarin hepsini tekrar dirilttigi g&uuml;n, d&uuml;nyada size yemin ettikleri gibi O\'na da yemin edecekler ve kendilerinin bir sey &uuml;zerinde bulunduklarini, sanacaklardir. Iyi bilin ki onlar yalancidirlar.';
$t[19] = 'Seytan onlari istil&acirc; etmis, onlara Allah\'i anmayi unutturmustur. Onlar, seytanin hizbi (partisi)dir. Iyi bilin ki seytanin partisi kaybedecektir.';
$t[20] = 'Allah\'a ve Resul&uuml;ne d&uuml;sman olanlar var ya, onlar en al&ccedil;aklar arasindadirlar.';
$t[21] = 'Allah: &quot;Elbette ben ve el&ccedil;ilerim galip gelecegiz.&quot; diye yazmistir. S&uuml;phesiz Allah g&uuml;&ccedil;l&uuml;d&uuml;r, galipdir.';
$t[22] = 'Allah\'a ve ahiret g&uuml;n&uuml;ne inanan bir milletin, babalari, ogullari, kardesleri, yahut akrabalari da olsa Allah\'a ve Resul&uuml;ne d&uuml;sman olanlarla dostluk ettigini g&ouml;rmezsiniz. Onlar o kimselerdir ki Allah kalblerine iman yazmis ve onlari kendinden bir ruh ile desteklemistir. Onlari, altlarindan irmaklar akan cennetlere sokacak, orada ebed&icirc; kalacaklardir. Allah onlardan razi olmus, onlar da O\'ndan razi olmuslardir. Iste onlar Allah\'in hizbi (dininin yardimcilari)dir. Iyi bil ki, kurtulusa ulasacak olanlar, Allah\'in hizbidir.';
?>