<?php
$t = array();
$t[1] = 'G&ouml;klerde ve yerde olanlarin hepsi Allah\'i tesbih etmektedir, O &uuml;st&uuml;nd&uuml;r, hikmet sahibidir.';
$t[2] = 'Ehl-i kitaptan inkar edenleri, ilk s&uuml;rg&uuml;nleri yurtlarindan &ccedil;ikaran O\'dur. Siz onlarin &ccedil;ikacaklarini sanmamistiniz. Onlar da kalelerinin, kendilerini Allah\'tan koruyacagini sanmislardi. Ama Allah\'in azabi, onlara beklemedikleri yerden geliverdi. O, y&uuml;reklerine korku d&uuml;s&uuml;rd&uuml;; &ouml;yle ki evlerini hem kendi elleriyle, hem de m&uuml;minlerin elleriyle harap ediyorlardi. Ey akil sahipleri! Ibret alin.';
$t[3] = 'Eger Allah onlara s&uuml;rg&uuml;n&uuml; yazmamis olsaydi, elbette, onlari d&uuml;nyada baska sekilde cezalandiracakti. Ahirette de onlar i&ccedil;in ates azabi vardir.';
$t[4] = 'Bunun sebebi sudur: Onlar Allah\'a ve Resul&uuml;ne karsi geldiler; Kim Allah\'a karsi gelirse Allah\'in azabi siddetlidir.';
$t[5] = 'Hurma aga&ccedil;larindan her hangi bir sey kesmeniz veya k&ouml;kleri &uuml;zerinde birakmaniz hep Allah\'in izniyle ve O\'nun, yoldan &ccedil;ikanlari cezalandirmasi i&ccedil;indir.';
$t[6] = 'Allah\'in, onlardan peygamberine verdigi ganimetlere gelince siz onun &uuml;zerine ne at, ne de deve s&uuml;rmediniz. Fakat Allah peygamberini, diledigi kimselerin &uuml;zerine salar. Allah her seye kadirdir.';
$t[7] = 'Allah\'in o kent halkindan, Resul&uuml;ne verdigi ganimetler, Allah\'a, Resul\'e, ona akrabaligi bulunanlara, yetimlere, yoksullara, yolcuya aittir. Ta ki i&ccedil;inizden yalniz zenginler arasinda dolasan bir sey olmasin. Peygamber size ne verdiyse onu alin. Size neyi yasakladiysa ondan sakinin ve Allah\'tan korkun. &Ccedil;&uuml;nk&uuml; Allah\'in azabi siddetlidir.';
$t[8] = 'Bir de g&ouml;&ccedil; eden fakirlere aittir ki yurtlarindan ve mallarindan &ccedil;ikarilmislardir, Allah\'in l&uuml;tuf ve rizasini ararlar; Allah\'a ve Resul&uuml;ne yardim ederler. Iste dogru olanlar onlardir.';
$t[9] = 'Ve onlardan &ouml;nce o yurda yerlesen imana sarilanlar kendilerine g&ouml;&ccedil; edip gelenleri severler ve onlara verilenlerden &ouml;t&uuml;r&uuml; g&ouml;g&uuml;slerinde bir ihtiya&ccedil; duymazlar. Kendilerinin ihtiya&ccedil;lari olsa dahi, onlari &ouml;z canlarina tercih ederler. Kim nefsinin cimriliginden korunursa, iste onlar umduklarina erenlerdir.';
$t[10] = 'Onlardan sonra gelenler derler ki: &quot;Rabbimiz, bizi ve bizden &ouml;nce inanan kardeslerimizi bagisla, kalplerimizde inananlara karsi bir kin birakma! Rabbimiz! Sen &ccedil;ok sefkatli, &ccedil;ok merhametlisin!&quot;';
$t[11] = 'M&uuml;nafiklarin, kitap ehlinden inkar eden dostlarina &quot;Eger siz yurdunuzdan &ccedil;ikarilirsaniz, mutlaka biz de sizinle beraber &ccedil;ikariz sizin aleyhinizde kimseye asla uymayiz. Eger savasa tutusursaniz, mutlaka yardim ederiz.&quot; dediklerini g&ouml;rmedin mi? Allah, onlarin yalanci olduklarina sahitlik eder.';
$t[12] = 'Andolsun eger onlar, &ccedil;ikarilirsalar, onlarla beraber &ccedil;ikmazlar; savasa tutusmus olsalar, onlara yardim etmezler; yardim etseler bile arkalarini d&ouml;n&uuml;p ka&ccedil;arlar, sonra kendilerine de yardim edilmez.';
$t[13] = 'Onlarin kalblerinde sizin korkunuz, Allah\'in korkusundan fazladir. B&ouml;yledir, &ccedil;&uuml;nk&uuml; onlar anlamayan bir topluluktur.';
$t[14] = 'Onlar toplu olarak sizinle savasamazlar, ancak, m&uuml;stahkem sehirlerde yahut duvarlarin ardindan (sizinle savasmak isterler). Kendi aralarindaki &ccedil;ekismeleri siddetlidir. Sen onlari toplu sanirsin, oysa onlarin kalbleri daginiktir. B&ouml;yledir, &ccedil;&uuml;nk&uuml; onlar aklini kullanmayan bir topluluktur.';
$t[15] = '(Bu yahudilerin durumu) kendilerinden az &ouml;nce, islerinin g&uuml;nahini tatmis olan, ahirette de kendileri i&ccedil;in aci bir azab bulunan kimselerin (Bedir\'de cezalarini bulan putperestlerin) durumu gibidir.';
$t[16] = '(Yahudileri kandiran m&uuml;nafiklarin durumu da) tipki seytanin durumuna benzer ki insana &quot;Ink&acirc;r et.&quot; dedi, (insan) inkar edince de: &quot;Ben senden uzagim, ben &acirc;lemlerin Rabb\'i Allah\'tan korkarim!&quot; dedi.';
$t[17] = 'Nihayet ikisinin sonu, ebedi olarak ateste oldu. Zalimlerin cezasi budur.';
$t[18] = 'Ey inananlar, Allah\'tan korkun ve kisi, yarin i&ccedil;in ne (yapip) g&ouml;nderdigine baksin. Allah\'tan korkun; &ccedil;&uuml;nk&uuml; Allah, yaptiklarinizdan haberdardir.';
$t[19] = 'Allah\'i unutup da Allah\'in da kendilerini unutturdugu kimseler gibi olmayin onlar, yoldan &ccedil;ikan kimselerdir.';
$t[20] = 'Cehennem ehli ile cennet ehli bir olmaz. Cennet ehli kurtularak isteklerine erisenlerdir.';
$t[21] = 'Biz bu Kur\'&acirc;n\'i bir daga indirseydik, Allah\'in korkusundan onu bas egmis, par&ccedil;a, par&ccedil;a olmus g&ouml;r&uuml;rd&uuml;n. Bu misalleri d&uuml;s&uuml;ns&uuml;nler diye insanlara veriyoruz.';
$t[22] = 'O, &ouml;yle Allah\'tir ki O\'ndan baska tanri yoktur. G&ouml;r&uuml;lmeyeni ve g&ouml;r&uuml;leni bilendir. O, esirgeyen bagislayandir.';
$t[23] = 'O, &ouml;yle bir Allah\'tir ki, kendisinden baska hi&ccedil;bir tanri yoktur. O, m&acirc;lik ve sahiptir, m&uuml;nezzehtir, sel&acirc;met verendir, emniyete kavusturandir, g&ouml;zetip koruyandir, &uuml;st&uuml;nd&uuml;r, istedigini zorla yaptiran, b&uuml;y&uuml;kl&uuml;kte esi olmayandir. Allah puta tapanlarin ortak kostuklari seylerden m&uuml;nezzehtir.';
$t[24] = 'O, yaratan, var eden, varliklara sekil veren Allah\'tir. En g&uuml;zel isimler O\'nundur. G&ouml;klerde ve yerde olanlar O\'nun s&acirc;nini y&uuml;celtmektedirler. O, g&acirc;lib olan, her seyi hikmeti uyarinca yapandir.';
?>