<?php
$t = array();
$t[1] = 'Ey inananlar! Benim de d&uuml;smanim, sizin de d&uuml;smaniniz olan kimseleri dost edinmeyin. Onlar size gelen ger&ccedil;egi inkar ettikleri, Rabbiniz Allah\'a inandiginizdan dolayi Resul&uuml; ve sizi (yurdunuzdan s&uuml;r&uuml;p) &ccedil;ikardiklari halde siz onlara sevgi ulastiriyorsunuz. Eger benim yolumda savasmak ve benim rizami kazanmak i&ccedil;in &ccedil;iktinizsa i&ccedil;inizde onlara sevgi mi gizliyorsunuz? Oysa ben sizin gizlediginiz ve a&ccedil;iga vurdugunuz her seyi bilirim. Sizden kim bunu yaparsa dogru yoldan sapmis olur.';
$t[2] = 'Sayet onlar sizi ele ge&ccedil;irirlerse, size d&uuml;sman kesilecekler, size ellerini ve dillerini k&ouml;t&uuml;l&uuml;kle uzatacaklardir. Zaten inkar edivermenizi istemektedirler.';
$t[3] = 'Kiyamet g&uuml;n&uuml; yakinlariniz ve &ccedil;ocuklariniz size fayda vermezler. &Ccedil;&uuml;nk&uuml; Allah aranizi ayirir. Allah yaptiklarinizi g&ouml;rendir.';
$t[4] = 'Ibrahim\'de ve onunla beraber bulunanlarda sizin i&ccedil;in g&uuml;zel bir misal vardir, onlar kavimlerine demislerdi ki: &quot;Biz sizden ve sizin Allah\'tan baska taptiklarinizdan uzagiz. Sizi tanimiyoruz. Siz bir tek Allah\'a inanincaya kadar sizinle bizim aramizda s&uuml;rekli bir d&uuml;smanlik ve nefret belirmistir.&quot; Yalniz Ibrahim\'in babasina: &quot;Senin i&ccedil;in magfiret dileyecegim, fakat senin i&ccedil;in Allah\'tan (gelecek) hi&ccedil;bir seyi (&ouml;nlemeye) g&uuml;c&uuml;m yetmez.&quot; demesi hari&ccedil;. Rabbimiz! Yalniz sana dayandik, sana y&ouml;neldik. D&ouml;n&uuml;s&uuml;m&uuml;z de ancak sanadir.';
$t[5] = '&quot;Rabbimiz! Bizi inkar edenler i&ccedil;in bir fitne kilma, (onlara maglub etme!) bizi bagisla! Ey Rabbimiz! Yegane g&acirc;lib ve hikmet sahibi ancak sensin.&quot;';
$t[6] = 'Andolsun, onlarda sizin i&ccedil;in, Allah\'i ve ahiret g&uuml;n&uuml;n&uuml; arzulayanlara g&uuml;zel bir &ouml;rnek vardir. Kim y&uuml;z &ccedil;evirirse s&uuml;phesiz Allah, zengindir, hamde layik olandir.';
$t[7] = 'Olur ki Allah sizinle d&uuml;smanlariniz arasinda yakinda bir dostluk meydana getirir. Allah g&uuml;c&uuml; yetendir. Allah &ccedil;ok bagislayan, &ccedil;ok merhamet edendir.';
$t[8] = 'Allah sizi, din hakkinda sizinle savasmayan ve sizi yurtlarinizdan &ccedil;ikarmayan kimselere iyilik etmekten, onlara adaletli davranmaktan men etmez. &Ccedil;&uuml;nk&uuml; Allah adalet yapanlari sever.';
$t[9] = 'Allah sizi, ancak sizinle din hakkinda savasan, sizi yurtlarinizdan &ccedil;ikaran ve &ccedil;ikarilmaniz i&ccedil;in yardim eden kimselere dost olmaktan men eder. Kim onlarla dost olursa iste zalimler onlardir.';
$t[10] = 'Ey iman edenler! M&uuml;min kadinlar hicret ederek size geldigi zaman, onlari imtihan edin. Allah onlarin imanlarini daha iyi bilir. Eger siz de onlarin inanmis kadinlar oldugunu &ouml;grenirseniz onlari k&acirc;firlere geri d&ouml;nd&uuml;rmeyin. Bunlar onlara helal degildir. Onlar da bunlara helal olmazlar. Onlarin (kocalarinin) sarfettiklerini (mehirleri) geri verin. Mehirlerini kendilerine verdiginiz zaman onlarla evlenmenizde size bir g&uuml;nah yoktur. K&acirc;fir kadinlari nik&acirc;hinizda tutmayin, sarfettiginizi isteyin. Onlar da sarfettiklerini istesinler. Allah\'in h&uuml;km&uuml; budur. Aranizda O, h&uuml;kmeder, Allah bilendir, hikmet sahibidir.';
$t[11] = 'Eger eslerinizden biri, sizden k&acirc;firlere ka&ccedil;ar da siz de savasta galip durumda olursaniz, esleri gitmis olanlara ganimetten, harcadiklari kadar verin. Inandiginiz Allah\'a karsi gelmekten sakinin.';
$t[12] = 'Ey Peygamber! Inanmis kadinlar sana gelip Allah\'a hi&ccedil;bir seyi ortak kosmamalari, hirsizlik etmemeleri, zina etmemeleri, &ccedil;ocuklarini &ouml;ld&uuml;rmemeleri, elleri ile ayaklari arasinda bir iftira uydurup getirmemeleri, iyi bir iste sana karsi gelmemeleri hususunda sana bey\'at ederlerse onlarin bey\'atlarini al ve onlar i&ccedil;in Allah\'tan magfiret dile. S&uuml;phesiz Allah, &ccedil;ok bagislayan, &ccedil;ok merhamet edendir.';
$t[13] = 'Ey inananlar, Allah\'in gazab ettigi kimselerle dostluk etmeyin. K&acirc;firler, mezarlik halkindan nasil &uuml;midi kesmisse, onlar da ahiretten &ouml;yle &uuml;midi kesmislerdi.';
?>