<?php
$t = array();
$t[1] = 'Ey Peygamber! Kadinlari bosamak istediginiz zaman onlari iddetleri i&ccedil;inde bosayin ve iddeti de sayin. Rabbiniz Allah\'tan korkun. Apa&ccedil;ik bir hayasizlik yapmalari hali bir yana, onlari evlerinden &ccedil;ikarmayin, kendileri de &ccedil;ikmasinlar. Bunlar Allah\'in sinirlaridir. Kim Allah\'in sinirlarini asarsa, s&uuml;phesiz kendine zulmetmis olur. Bilmezsin, olur ki Allah, bundan sonra bir durum ortaya &ccedil;ikariverir.';
$t[2] = 'S&uuml;relerinin sonuna vardiklarinda onlari g&uuml;zelce tutun, yahut g&uuml;zellikle onlardan ayrilin. I&ccedil;inizden adalet sahibi iki kisiyi sahit tutun. Sahidligi Allah i&ccedil;in yapin. Iste Allah\'a ve son g&uuml;ne inanan kimseye &ouml;g&uuml;tlenen budur. Kim Allah\'tan korkarsa Allah ona bir &ccedil;ikis yolu yaratir.';
$t[3] = 'Ve onu ummadigi yerden riziklandirir. Kim Allah\'a g&uuml;venirse O, ona yeter. Allah, emrini yerine getirendir. Allah her sey i&ccedil;in bir &ouml;l&ccedil;&uuml; koymustur.';
$t[4] = 'Kadinlariniz i&ccedil;inden &acirc;detten kesilmis olanlarla, hen&uuml;z &acirc;detini g&ouml;rmemis bulunanlardan eger s&uuml;phe ederseniz (iddetlerinin nasil olacaginda teredd&uuml;t ederseniz), onlarin bekleme s&uuml;resi &uuml;&ccedil; aydir. Gebe olanlarin bekleme s&uuml;resi ise, y&uuml;klerini birakmalari, dogum yapmalaridir. Kim Allah\'tan korkarsa, Allah ona isinde bir kolaylik verir.';
$t[5] = 'Bu, Allah\'in size indirdigi buyrugudur. Kim Allah\'tan korkarsa Allah onun k&ouml;t&uuml;l&uuml;klerini &ouml;rter ve onun m&uuml;kafatini b&uuml;y&uuml;t&uuml;r.';
$t[6] = 'O kadinlari, g&uuml;c&uuml;n&uuml;z &ouml;l&ccedil;&uuml;s&uuml;nde oturdugunuz yerin bir b&ouml;l&uuml;m&uuml;nde oturtun ve onlari sikistirmak i&ccedil;in kendilerine zarar vermeye kalkismayin. Sayet gebe iseler, y&uuml;klerini birakincaya kadar onlari besleyin. Sonra sizin i&ccedil;in emzirirlerse &uuml;cretlerini verin ve aranizda g&uuml;zellikle konusup danisin. G&uuml;&ccedil;l&uuml;k &ccedil;ekerseniz &ccedil;ocugu, baska bir kadin emzirecektir.';
$t[7] = 'Eli genis olan genisligine g&ouml;re nafaka versin. Rizki kisilmis bulunan da Allah\'in kendisine verdiginden versin. Allah bir kisiye ne vermisse ancak onu teklif eder. Allah bir g&uuml;&ccedil;l&uuml;kten sonra bir kolaylik yaratacaktir.';
$t[8] = 'Nice kent var ki Rablerinin ve O\'nun el&ccedil;ilerinin emrine baskaldirdi, biz de onlari &ccedil;etin bir hesaba &ccedil;ektik ve onlara g&ouml;r&uuml;lmemis sekilde azab ettik.';
$t[9] = 'Islerinin vebalini tattilar. Islerinin sonucu tam bir h&uuml;sran olmustur.';
$t[10] = 'Allah onlara siddetli bir azap hazirlamistir. O halde ey inanan akl-i selim sahipleri! Allah\'tan korkun, Allah size bir uyarici g&ouml;nderdi.';
$t[11] = 'Size Allah\'in a&ccedil;ik a&ccedil;ik &acirc;yetlerini okuyan bir el&ccedil;i (g&ouml;nderdi) ki inanip faydali isler yapanlari, karanliklardan aydinliga &ccedil;ikarsin. Kim Allah\'a inanir ve yararli is yaparsa (Allah) onu, altlarindan irmaklar akan, i&ccedil;inde ebedi kalacaklari cennetlere sokar. Allah ona ger&ccedil;ekten ne g&uuml;zel rizik vermistir.';
$t[12] = 'Allah O\'dur ki yedi g&ouml;g&uuml; ve yerden de onlar kadarini yaratti. Emir bunlar arasinda iner ki Allah\'in her seye k&acirc;dir oldugunu ve Allah\'in bilgisinin, her seyi kusattigini bilesiniz.';
?>