<?php
$t = array();
$t[1] = 'O besimtar&euml;, mos b&euml;ni asgj&euml; para (se t&euml; orientoheni n&euml; udh&euml;zimet e) Zotit dhe t&euml; d&euml;rguarit t&euml; Tij, keni kujdes All-llahun, se me t&euml; v&euml;rtet&euml; All-llahu i d&euml;gjon t&euml; gjitha dhe i di t&euml; gjitha.';
$t[2] = 'O ju q&euml; keni besuar, mos ngritni z&euml;rin tuaj mbi z&euml;rin e Pejgamberit dhe mos iu ng&euml;rmoni atij si i ng&euml;rmoheni nj&euml;ri-tjetrit, e t&euml; zhduken veprat tuaja duke mos ditur ju.';
$t[3] = 'Ata q&euml; ulin z&euml;rat e tyre paran&euml; t&euml; d&euml;rguarit t&euml; All-llahut. All-llahu zemrat e tyre i ka p&euml;rshtatur p&euml;r devotshm&euml;ri, ata kan&euml; falje m&euml;katesh dhe shp&euml;rblim t&euml; madh.';
$t[4] = 'Ata q&euml; th&euml;rrasin p&euml;rtej mureve, shumica e tyre jan&euml; q&euml; nuk kuptojn&euml;.';
$t[5] = 'E sikur ata t&euml; b&euml;nin durim derisa t&euml; kishe dal&euml; ti vet&euml;, do t&euml; ishte m&euml; edukative p&euml;r ta, po All-llahu &euml;sht&euml; m&euml;katfal&euml;s, m&euml;shirues.';
$t[6] = 'O ju q&euml; keni besuar, n&euml;se ndonj&euml; i pand&euml;rgjegjsh&euml;m u sjell ndonj&euml; lajm, ju shqyrtonie mir&euml;, ashtu q&euml; t&euml; mos e goditni ndonj&euml; popull pa e ditur realitetin, e pastaj t&euml; pendoheni p&euml;r at&euml; q&euml; keni b&euml;r&euml;.';
$t[7] = 'E, dijeni se n&euml; mesin tuaj e keni t&euml; d&euml;rguarin e All-llahut. sikur ai t&rsquo;ju d&euml;gjonte juve n&euml; shu, &euml; &ccedil;&euml;shtje, ju do t&euml; p&euml;sonit vuajtje, por All-llahu juve ua b&euml;ri t&euml; dashur besimin dhe ua zbukuroi at&euml; n&euml; zemrat tuaja, nd&euml;rsa mosbesimin, shfrenimin dhe kund&euml;rshtimin, ua b&euml;ri q&euml; t&rsquo;i uureni. T&euml; till&euml; jan&euml; ata q&euml; gjet&euml;n rrug&euml;n e drejt&euml;.';
$t[8] = 'Kjo &euml;sht&euml; dhurat&euml; dhe begati prej All-llahut, e All-llahu &euml;sht&euml; i dijsh&euml;mdhe i urt&euml;.';
$t[9] = 'N&euml;se dy grupe besimtar&euml;sh tentojn&euml; t&euml; luftojn&euml; nd&euml;rmjet vete, ju pajtoni ata, e n&euml; qoft&euml; se ndonj&euml;ri prej tyre e sulmon tjetrin, at&euml;her&euml; luftonie at&euml; grup q&euml; v&euml;rsulet me pa t&euml; drejt&euml;, derisa t&rsquo;i bindet udh&euml;zimit t&euml; All-llahut, e n&euml;se ktheheni, at&euml;her&euml; me drejt&euml;si b&euml;ni pajtimin nd&euml;rmjet tyre, mbanie drejt&euml;sin&euml;, se v&euml;rtet All-llahu i do t&euml; drejtit.';
$t[10] = 'S&rsquo;ka dyshim se besimtar&euml;t jan&euml; v&euml;llez&euml;r, pra b&euml;ni pajtim nd&euml;rmjet v&euml;llez&euml;rve tuaj dhe kinie frik&euml; All-llahun, q&euml; t&euml; jeni t&euml; m&euml;shiruar (na Zoti).';
$t[11] = 'O ju q&euml; besuat, nuk b&euml;n t&euml; tallet nj&euml; popull me nj&euml; popull tjet&euml;r, meq&euml; t&euml; p&euml;rqeshurit mund t&euml; jen&euml; m&euml; t&euml; mir&euml; nga ata t&euml; cil&euml;t p&euml;rqeshin dik&euml; tjet&euml;r, e as grat&euml; me grat&euml; e tjera, sepse mund t&euml; ndodh&euml; q&euml; grat&euml; e tjera t&euml; jen&euml; m&euml; t&euml; mira se ato q&euml; p&euml;rqeshin (duke n&euml;n&ccedil;muar nj&euml;ri-tjetrin) dhe mos etiketoni nj&euml;ri-tjetrin me llagape. Pas besimit &euml;sht&euml; keq t&euml; p&euml;rhapet llagapi i keq. E ata q&euml; nuk pendohen, jan&euml; mizor&euml;.';
$t[12] = 'O ju q&euml; keni besuar, largohuni prej dyshimeve t&euml; shumta, meq&euml; disa dyshime jan&euml; m&euml;kat dhe mos hulumtoni p&euml;r zbulimin e t&euml; metave t&euml; njeri tjetrit, dhe mos p&euml;rgjoni nj&euml;ri tjetrin; a mos ndonj&euml;ri prej jush d&euml;shiron t&euml; haj&euml; mishin e v&euml;llait t&euml; vet t&euml; vdekur? At&euml; pra e urreni! Kini frik&euml; nga nd&euml;shkimi i All-llahut, e All-llahu &euml;sht&euml; m&euml;shrues, Ai pranon shum&euml; pendimin.';
$t[13] = 'O ju njer&euml;z, v&euml;rtet&euml; Ne ju krijuam ju prej nj&euml; mashkulli dhe nj&euml; femre, ju b&euml;m&euml; popuj e fise q&euml; t&euml; njiheni nd&euml;rmjet vete, e s&rsquo;ka dyshim se te All-llahu m&euml; i ndershmi nd&euml;r ju &euml;sht&euml; ai q&euml; m&euml; tep&euml;r &euml;sht&euml; ruajtur (k&euml;qijat) e All-llahu &euml;sht&euml; i dijsh&euml;m dhe holl&euml;sisht i njohur p&euml;r &ccedil;do gj&euml;.';
$t[14] = 'Beduin&euml;t than&euml;: &ldquo;Ne kemi besuar!&rdquo; Thuaj: &ldquo;Ju nuk keni besuar ende, por thuani: ne jemi dor&euml;zuar, e ende nuk po hyn besimi n&euml; zemrat tuaja. E n&euml;se e respektoni All-llahun dhe t&euml; d&euml;rguarin e Tij, Ai nuk ju pak&euml;son asgj&euml; nga veprat tuaja, se All-llahu &euml;sht&euml; shum&euml; m&euml;katfal&euml;s, shum&euml; m&euml;shirues&rdquo;.';
$t[15] = 'Besimtar&euml; jan&euml; vet&euml;m ata q&euml; besuan All-llahut, t&euml; d&euml;rguarit t&euml; Tij, e mandej nuk dyshuan dhe p&euml;r hir&euml; t&euml; All-llahut luftuan me pasurin&euml; dhe me jet&euml;n e tyre. T&euml; till&euml; jan&euml; ata t&euml; v&euml;rtetit.';
$t[16] = 'Thuaj: &ldquo;A ju ia b&euml;ni me dije All-llahut fen&euml; tuaj (duke th&euml;n&euml;: ne besuam), kur All-llahu &euml;sht&euml; Ai q&euml; e di &ccedil;&rsquo;ka n&euml; qiej dhe &ccedil;&rsquo;ka n&euml; tok&euml; dhe All-llahu &euml;sht&euml; i dijsh&euml;m p&euml;r &ccedil;do send&rdquo;.';
$t[17] = 'Ata t&euml; shprehin ty mir&euml;njoh&euml;s (ta p&euml;rmendin) q&euml; u b&euml;n&euml; mysliman&euml;. Thuaj: &ldquo;Pranimin tuaj t&euml; fes&euml; islame mos ma njihni (mos ma p&euml;rmendni) mua, por n&euml;se jeni t&euml; sinqert&euml; All-llahu juve ju b&euml;ri mir&euml;, kur ju udh&euml;zoi p&euml;r besim&rdquo;.';
$t[18] = 'S&rsquo;ka dyshim se All-llahu e di fsheht&euml;sin&euml; e qiejve e t&euml; tok&euml;s, All-llahu sheh at&euml; q&euml; punoni ju.';
?>