<?php
$t = array();
$t[1] = 'V&euml;rtet, All-llahu d&euml;gjoi fjal&euml;t e asaj e cila bisedoi me ty lidhur m&euml; burrin e vet, q&euml; u ankua te All-llahu; prandaj All-llahu e d&euml;gjon bised&euml;n tuaj, All-llahu d&euml;gjon &ccedil;do bised&euml; dhe sheh &ccedil;do pun&euml;.';
$t[2] = 'Ata prej jush q&euml; b&euml;jn&euml; &ldquo;Dhihar&rdquo; (ep&euml;rsia ime ndaj teje &euml;sht&euml; haram si ep&euml;rsia ndaj n&euml;n&euml;s sime) ndaj grave t&euml; veta, n&euml; t&euml; v&euml;rtet&euml; ato nuk jan&euml; n&euml;nat e tyre, n&euml;nat e tyre jan&euml; vet&euml;m ato q&euml; i kan&euml; lindur ata, nd&euml;rsa ata jan&euml; jan&euml; duke th&euml;n&euml; fjal&euml; t&euml; irituara dhe g&euml;njeshtra, por All-llahu &euml;sht&euml; q&euml; l&euml; shum&euml; pa marr&euml; n&euml; p&euml;rgjegj&euml;si dhe shum&euml; fal&euml;.';
$t[3] = 'Ata q&euml; krahasojn&euml; (me n&euml;na) dhe largohen nga grat&euml; e veta, e pastaj zmbrapsen nga ajo q&euml; kan&euml; th&euml;n&euml;, jan&euml; t&euml; obliguar q&euml; para se t&euml; kontaktojn&euml; nd&euml;rmjet vete ta lirojn&euml; nj&euml; rob. Kjo &euml;sht&euml; dispozit&euml; me t&euml; cil&euml;n porositeni holl&euml;sisht me at&euml; q&euml; ju e punoni.';
$t[4] = 'E kush nuk gjen (rob p&euml;r lirim), at&euml;her&euml; le t&euml; agj&euml;roj&euml; dy muaj rresht para se t&euml; kontaktojn&euml;, e kush nuk mundet, at&euml;her&euml; le t&rsquo;i ushqej&euml; gjasht&euml;dhjet&euml; t&euml; varf&euml;r. Kjo (dispozit&euml; ju sh&euml;rben) p&euml;r t&euml; v&euml;rtet&euml;n ju se besoni All-llahun dhe t&euml; g&euml;rguarin e Tij (e jo zakonet injorante). K&euml;to, pra jan&euml; p&euml;rcaktimet e All-llahut. nd&euml;rkaq, mohuesit kan&euml; d&euml;nim t&euml; r&euml;nd&euml;.';
$t[5] = '&Euml;sht&euml; e v&euml;rtet&euml; se ata q&euml; i kund&euml;rvhen All-llahut dhe t&euml; d&euml;rguarit t&euml; Tij, jan&euml; t&euml; mposhtur, ashtu si&ccedil; u mposht&euml;n ata p&euml;rpara tyre. Mir&euml;po, Ne u kemi shpallur fakte t&euml; qarta, e p&euml;r mohuesit &euml;sht&euml; nj&euml; d&euml;nim i turpsh&euml;m.';
$t[6] = 'N&euml; dit&euml;n e kur All-llahu i ringjall ata t&euml; gjith&euml;, i njofton me at&euml; q&euml; kan&euml; punuar, pse All-llahu ka mbajtur ato sh&euml;nime, dhe pse ata i kan&euml; harruar. All-llahu &euml;sht&euml; Ai q&euml; &ccedil;do send esheh dhe e p&euml;rcjell.';
$t[7] = 'A nuk e di ti (o d&euml;gjues) se All-llahu di &ccedil;ka n&euml; qiej dhe &ccedil;ka n&euml; tok&euml;?! Nuk b&euml;het bised&euml; e fsheht&euml; mes tre vetave e t&euml; mos jet&euml; Ai i kat&euml;rti; e as mes pes&euml; vetave e t&euml; mos jet&euml; Ai i gjashti, e as mes pak vetave dhe as n&euml; shum&euml; vetave, e t&euml; mos jet&euml; Ai me ta, kudo q&euml; t&euml; jen&euml;. Pastaj, n&euml; dit&euml;n e kijametit i njofton ata me at&euml; q&euml; kan&euml; punuar. All-llahu ka p&euml;rshir&euml; &ccedil;do send n&euml; dijen e vet.';
$t[8] = 'A nuk i sheh ata q&euml; ishin t&euml; ndaluar t&euml; bisedojn&euml; fsheht&euml;, se si i kthehen p&euml;rs&euml;ri asaj na e cila ishin t&euml; ndaluar dhe p&euml;shp&euml;risin p&euml;r &ccedil;ka &euml;sht&euml; m&euml;kat, p&euml;r &ccedil;ka &euml;sht&euml; mizori &ccedil;ka &euml;sht&euml; n&euml; kund&euml;rshti t&euml; t&euml; d&euml;rguarit. Ata kur vjn&euml; t&euml; ti, t&euml; p&euml;rsh&euml;nesin me at&euml; q&euml; All-llahu nuk t&euml; p&euml;rsh&euml;ndet dhe vet&euml;mevete thon&euml;: &ldquo;P&euml;rse All-llahu nuk na d&euml;non p&euml;r k&euml;t q&euml; po e themi?&rdquo; Por, mjaft &euml;sht&euml; p&euml;r ta Xhehennemi n&euml; t&euml; cilin hidhen. Sa vend i sh&euml;mtuar &euml;sht&euml; ai.';
$t[9] = 'O ju q&euml; keni besuar, kur bisedoni mes vete fshehurazi, mos bisedoni p&euml;r &ccedil;ka &euml;sht&euml; m&euml;kat, armiq&euml;si dhe kund&euml;rshti ndaj pejgamberit, por bisedoni p&euml;r pun&euml; t&euml; ndershme e t&euml; matura dhe kinia frik&euml;n All-llahut, te i cili do t&euml; tuboheni!';
$t[10] = 'Bised&euml;n e fsheht&euml; e nxit vet&euml;m djalli p&euml;r t&rsquo;i shqet&euml;suar ata q&euml; besuan, ndon&euml;se ajo nuk mund t&rsquo;i d&euml;mtoj&euml; fare pa d&euml;shir&euml;n e All-llahut le t&rsquo;i mb&euml;shtet&euml;n besimtar&euml;t!';
$t[11] = 'O ju q&euml; besuat, kur t&rsquo;ju thuhet: zgjerohuni (b&euml;ni vend) n&euml; vend ndeje, ju zgj&euml;rohuni, se All-llahu b&euml;n zgj&euml;rim p&euml;r ju, e kur t&rsquo;ju thuhet: ngrituni! At&euml;her&euml; ju ngrihuni, All-llahu lart&euml;son ata q&euml; besuan prej jush, i lart&euml;son n&euml; shkall&euml; t&euml; lart&euml; ata t&euml; cil&euml;ve u &euml;sht&euml; dh&euml;n&euml; dituri. All-llahu &euml;sht&euml; i njohur mir&euml; me at&euml; q&euml; punoni.';
$t[12] = 'O ju q&euml; keni besuar, kur d&euml;shironi t&euml; bisedoni me t&euml; d&euml;rguarin, jepne nj&euml; sadaka para bised&euml;s suaj. Kjo &euml;sht&euml; p&euml;r ju m&euml; e past&euml;r; e n&euml;se nuk keni &ccedil;ka t&euml; jepni, All-llahu &euml;sht&euml; i njohur mir&euml; me at&euml; q&euml; punoni.';
$t[13] = 'A u frik&euml;suat (varf&euml;ris&euml;) t&euml; jepni l&euml;mosh&euml; n&euml; prag t&euml; bised&euml;s suaj? E kur ju nuk e b&euml;t&euml; dhe All-llahu ju fali, at&euml;her&euml; pra, falnie namazin, jepnie zeqatin, respekonie All-llahun dhe t&euml; d&euml;rguarin e Tij, All-llahu &euml;sht&euml; i njohur me pun&euml;n tuaj.';
$t[14] = 'A e dini p&euml;r at&euml; q&euml; kan&euml; miq&euml;suar nj&euml; popull q&euml; All-llahu ka shprehur mallkim kund&euml;r tyre? Ata nuk jan&euml; as prej jush as prej atyre dhe me vet&euml;dije betohen rrejsh&euml;m.';
$t[15] = 'All-llahu p&euml;r ta ka p&euml;rgatitur nj&euml; nd&euml;shkim t&euml; ashp&euml;r. V&euml;rtet, at&euml; q&euml; b&euml;jn&euml; &euml;sht&euml; shum&euml; e keqe.';
$t[16] = 'Ata betimin e tyre e kan&euml; marr&euml; si mbrojtje dhe kan&euml; penguar prej rrug&euml;s s&euml; All-llahut, andaj ata i pret nj&euml; d&euml;nim d&euml;nim poshtrues.';
$t[17] = 'Atyre nuk do t&rsquo;u b&euml;j&euml; kurrfar&euml; dobie pasuria e tyre as f&euml;mij&euml;t e tyre para All-llahut. Ata jan&euml; banor&euml; t&euml; zjarrit, aty jan&euml; p&euml;rgjithmon&euml;.';
$t[18] = 'Dit&euml;n kur All-llahu i ringjall t&euml; gjith&euml;, e ata i betohen Atij, sikurse u betoheshin juve, dhe mendojn&euml; (me at&euml; betim) t&euml; arrijn&euml; di&ccedil;ka. Pra ta dini, se ata jan&euml; me t&euml; v&euml;rtet&euml; rrenacak&euml;t.';
$t[19] = 'Ata i ka n&euml;nshtruar djalli dhe ua ka qitur n&euml; harres&euml; porosit&euml; e All-llahut. Ata jan&euml; shoq&euml;ri e djallit, e din&euml; se ithtar&euml;t e djallit jan&euml; m&euml; t&euml; d&euml;shpruarit.';
$t[20] = 'S&rsquo;ka dyshim se ata q&euml; e kund&euml;rshtojn&euml; All-llahun dhe t&euml; d&euml;rguarin e Tij, t&euml; till&euml;t jan&euml; nd&euml;r m&euml; t&euml; posht&euml;ruarit.';
$t[21] = 'All-llahu ka p&euml;rcaktuar (shkruar n&euml; Levhi Mahvudh): &ldquo;Un&euml; dhe t&euml; d&euml;rguarit e Mi, pa tjet&euml;r do t&euml; ngadhnjejm&euml;!&rdquo; All-llahu &euml;sht&euml; i fort&euml;, ngadhnjyes.';
$t[22] = 'Nuk gjen popull q&euml; e beson All-llahun dhe dit&euml;n e gjykimit, e ta doj&euml; at&euml; q&euml; e kund&euml;rshton All-llahun dhe t&euml; d&euml;rguarin e Tij, edhe sikur t&euml; jen&euml; ata (kund&euml;rshtar&euml;t) prind&euml;rit e tyre, ose f&euml;mij&euml;t e tyre, ose v&euml;llez&euml;rit e tyre, ose farefisi i tyre. Ata jan&euml; q&euml; n&euml; zemrat e tyre (Ai) ka skalitur besimin dhe ka forcuar me shpirt nga ana e Tij dhe ata do t&rsquo;i shpjer&euml; n&euml; Xhennete, n&euml;p&euml;r t&euml; cilin rrjedhin lumenj. Aty jan&euml; p&euml;rgjithmon&euml;. All-llahu ua ka p&euml;lqyer pun&euml;n e tyre dhe ata jan&euml; t&euml; k&euml;naqur me shp&euml;rblimin e Tij. T&euml; till&euml;t jan&euml; pal&euml; (grup, parti) e All-llahut ta dini pra, se ithtar&euml;t e All-llahut jan&euml; ata t&euml; shp&euml;tuarit.';
?>