<?php
$t = array();
$t[1] = 'All-llahun e madh&euml;ron me tesbih (duke i mohuar ato q&euml; nuk i takojn&euml; atij) gjith&ccedil;ka ka n&euml; tok&euml;, e Ai &euml;sht&euml; i fuqishmi, i urti.';
$t[2] = 'Ai &euml;sht&euml; q&euml; n&euml; d&euml;bimin e par&euml; i nxoru prej sht&euml;pive t&euml; tyre ata nga ithtar&euml;t e librit, t&euml; cil&euml;t nuk besuan. Ju nuk menduat se fortifikatat e tyre do t&rsquo;i mbronin prej nd&euml;shkimit t&euml; All-llahut, po All-llahu u erdhi atyre nga nuk e kishin menduar dhe n&euml; zemrat e tyre hodhi frik&euml;n ashu q&euml; me duart e veta dhe me duart t&euml; besimtar&euml;ve t&euml; rr&euml;zonin sht&euml;pit&euml; e veta; pra merrni p&euml;rvoj&euml; o ju t&euml; zot&euml;t e mendjes.';
$t[3] = 'Sikur All-llahu t&euml; mos u kishte caktuar atyre shp&euml;rnguljen, ata do t&rsquo;i nd&euml;shkonte n&euml; k&euml;t&euml; jet&euml;, kurse n&euml; jet&euml;n tjet&euml;r ata e kan&euml; d&euml;nimin e zjarrit.';
$t[4] = 'K&euml;t&euml; p&euml;r shkak se e kund&euml;rshtuan All-llahun dhe t&euml; d&euml;rguarin e Tij. Pra, kush e kund&euml;rshton All-llahun, s&rsquo;ka dyshim se All-llahu &euml;sht&euml; nd&euml;shkimfort&euml;.';
$t[5] = 'Ju nuk k&euml;put&euml;t asnj&euml; nga hurmat e buta (fidan&euml;t) ose at&euml; e keni l&euml;n&euml; t&euml; ngriur n&euml; rr&euml;nj&euml;t e tye, vet&euml;m se me lejen e All-llahut e p&euml;r t&rsquo;i shtypur kund&euml;rshtar&euml;t.';
$t[6] = 'E at&euml; (Pasuri) q&euml; prej tyre All-llahu ia ktheu t&euml; d&euml;rguarit t&euml; vet, ju p&euml;r t&euml; nuk i keni ngar&euml; as kuajt, as devet&euml;, por All-llahu i b&euml;n mbizot&euml;ruesit t&euml; d&euml;rguarit e vet kund&euml;r kujt t&euml; doj&euml;, All-llahu ka fuqi mbi &ccedil;do send.';
$t[7] = 'At&euml; q&euml; All-llahu nga banor&euml;t e vendeve (jobesimtare) ia dha pa luft&euml; t&euml; d&euml;rguarit t&euml; vet, ajo i takon All-llahut, t&euml; d&euml;rguarit, t&euml; af&euml;rmve, jetim&euml;ve, t&euml; varf&euml;rve, kurbet&ccedil;injve. (K&euml;shtu veprohet) Q&euml; ajo t&euml; mos ndahet nd&euml;rrmjet pasanik&euml;ve tuaj. &Ccedil;ka t&rsquo;ju jep i Pejgamberi, at&euml; merrmie e &ccedil;ka t&rsquo;ju ndaloj&euml;, p&euml;rmbanju dhe kinie frik&euml; All-llahun, se All-llahu &euml;sht&euml; nd&euml;shkues i ashp&euml;r.';
$t[8] = '(Ajo pron&euml;) U takon muhaxhir&euml;ve t&euml; varf&euml;r, t&euml; cil&euml;t u d&euml;buan prej sht&euml;pive t&euml; tyre dhe prej pasuris&euml; s&euml; tyre, duke k&euml;rkuar mirasin&euml; dhe k&euml;naq&euml;ain&euml; e All-llahut, dhe q&euml; ndihmojn&euml; All-llahun dhe t&euml; d&euml;rguarin e Tij, t&euml; till&euml;t jan&euml; ata t&euml; sinqertit.';
$t[9] = 'Edhe ata q&euml; p&euml;rgatit&euml;n vendin (Medin&euml;n) dhe besimin para tyre, i duan ata q&euml; shp&euml;rnguleshin te ata dhe nuk ndiejn&euml; n&euml; gjoksat e tyre ndonj&euml; nevoj&euml; (p&euml;r zili a tjet&euml;r) nga ajo q&euml; u jepej atyre (muhaxhir&euml;ve), madje edhe sikur t&euml; kishin vet&euml; nevoj&euml; p&euml;r t&euml;, ata u jepnin p&euml;rpar&euml;si atyre para vetvetes. Kush &euml;sht&euml; i ruajtur prej lakmis&euml; s&euml; vet, t&euml; till&euml;t jan&euml; t&euml; shp&euml;tuar.';
$t[10] = 'Edhe ata q&euml; kan&euml; ardhur pas tyre e thon&euml;: &ldquo;Zoti yn&euml;, falna ne dhe v&euml;llez&euml;rit tan&euml; q&euml; para nesh u pajis&euml;n me besim dhe mos lejo n&euml; zemrat far&euml; urrejtjeje ndaj atyre q&euml; besuan. Zoti yn&euml; Ti je i but&euml;, m&euml;shirues!&rdquo;';
$t[11] = 'A nuk e ke ditur se ata q&euml; u b&euml;n&euml; hipokrit&euml;, u thoshin v&euml;llez&euml;rve t&euml; vet nga ithtar&euml;t e librit q&euml; nuk kishin besuar: n&euml;se ju d&euml;boheni, edhe ne do t&euml; dalim me ju, p&euml;r &ccedil;&euml;shtjen tuaj, ne kurr&euml; nuk do t&rsquo;i bindemi askujt (t&rsquo;ju luftojm&euml; ose t&rsquo;ju n&euml;nshtrojm&euml;), e n&euml;se luftoheni prej dikujt, ne gjithqysh do t; u ndihmojm&euml;. All-llahu d&euml;shmon se ata jan&euml; rrenacak&euml;!';
$t[12] = 'Sikur t&euml; d&euml;bohen ata (ithtar&euml;t e librit), nuk do t&euml; dilnin me ta edhe sikur t&euml; luftoheshin, nuk do t&rsquo;u ndihmojn&euml; atyre, po edhe sikur t&rsquo;u ndihmonin atyre, ata do t&euml; iknin prapa, e ata do t&euml; mbesin pa ndihm&euml;n e tyre.';
$t[13] = 'Ju (besimtar&euml;t) n&euml; zemrat e tyre (ta munafik&euml;ve) jeni frik&euml; m&euml; e fort&euml; se All-llahu (frika nga All-llahu). Kjo p&euml;r shkak se ata jan&euml; popull q&euml; nuk kuptojn&euml;.';
$t[14] = 'Ata t&euml; gjith&euml; s&euml; bashku nuk kan&euml; guxim t&rsquo;ju luftojn&euml;, vet&euml;m kur gjenden n&euml; ndonj&euml; vend t&euml; fortifikuar ose kur jan&euml; pas ndonj&euml; muri. Armiq&euml;sia nd&euml;rmjet tyre &euml;sht&euml; e ashp&euml;r. Mund t&euml; mendohet p&euml;r ta se jan&euml; t&euml; bashkuar, e n&euml; reallitet zemrat e tyre jan&euml; t&euml; p&euml;r&ccedil;ara, sepse jan&euml; njer&euml;z q&euml; nuk logjikojn&euml;.';
$t[15] = 'Si shembull i atyre jo fort moti q&euml; p&euml;rjetuan t&euml; keqen e pun&euml;s s&euml; vet, edhe ata kan&euml; nj&euml; d&euml;nim t&euml; r&euml;nd&euml;.';
$t[16] = 'Ata (hipokrit&euml;t) jan&euml; shembull si djalli, kur i thot&euml; njeriut: &ldquo;Refuzo besimin!&rdquo;, e kur ai t&euml; ket&euml; refuzuar, ai (djalli) t&euml;rhiqet prej teje; un&euml; i frikohem All-llahut, Zotit t&euml; gjith&euml;sis&euml;!&rdquo;';
$t[17] = 'Dhe ashtu, ata t&euml; dy do t&euml; p&euml;rfundojn&euml; n&euml; zjarr p&euml;rgjithmon&euml;. Ai &euml;sht&euml; nd&euml;shkim i zullumqar&euml;ve.';
$t[18] = 'O ju q&euml; besuat, frik&euml;sojuni All-llahut dhe le t&euml; shikoj&euml; &ccedil;donj&euml;ri se &ccedil;ka ka b&euml;r&euml; p&euml;r nes&euml;r. Dhe frik&euml;sojuni All-llahut! S&rsquo;ka dyshim se All-llahu &euml;sht&euml; i Njohtuar (Habir) p&euml;r at&euml; q&euml; punoni!';
$t[19] = 'E mos u b&euml;ni si ata q&euml; harruan All-llahun, pra (All-llahu b&euml;ri q&euml; ata) harruan vetveten! T&euml; till&euml;t jan&euml; t&euml; Fasik&euml;t.';
$t[20] = 'Nuk jan&euml; t&euml; barabart&euml; banor&euml;t e Xhennetit dhe banor&euml;t e Xhehennemit. Banor&euml;t e Xhennetit jan&euml; t&euml; suksesshmit (jan&euml; ata q&euml; ia kan&euml; arritur q&euml;llimit).';
$t[21] = 'Sikur Ne ta zbritnim k&euml;t&euml; Kur&rsquo;an mbi ndonj&euml; kod&euml;r, do t&euml; shihje at&euml; t&euml; strukur e t&euml; &ccedil;ar&euml; prej frik&euml;s nga All-llahu. K&euml;ta jan&euml; shembuj q&euml; ua sjellim njer&euml;zve, q&euml; ata t&euml; mendojn&euml;.';
$t[22] = 'Ai &euml;sht&euml; All-llahu, nuk ka zot tjet&euml;r pos Tij. Dijetari i t&euml; fsheht&euml;s dhe t&euml; dukshmes, Ai &euml;sht&euml; M&euml;shiruesi, M&euml;shir&euml;b&euml;r&euml;si!';
$t[23] = 'Ai &euml;sht&euml; All-llahu, pos t&euml; Cilit nuk ka zot tjet&euml;r, Sunduesi, i Shenjti, i Past&euml;rti (prej t&euml; metave q&euml; i mvishen), Siguruesi, Mbik&euml;qyr&euml;si, i Plotfuqishmi, Mbizot&euml;ruesi, i Madh&euml;rishmi. I lart&euml;suar &euml;sht&euml; All-llahu nga ajo q&euml; ia shoq&euml;rojn&euml;!';
$t[24] = 'Ai &euml;sht&euml; All-llahu, Krijuesi, Shpik&euml;si, Form&euml;suesi. T&euml; tij jan&euml; emrat m&euml; t&euml; bukur. At&euml; e lart&euml;son &ccedil;ka ka n&euml; qiej e n&euml; tok&euml;. Dhe Ai &euml;sht&euml; i Fuqishmi, i Urti!';
?>