<?php
$t = array();
$t[1] = 'O ju q&euml; besuat, n&euml;se keni dal&euml; (prej vendlindjes) p&euml;r hir&euml; t&euml; luft&euml;s p&euml;r rrug&euml;n Time, duke k&euml;rkuar k&euml;naq&euml;sin&euml; Time ndaj jush, mos e zini mik armikun Tim dhe armikun tuaj, duke shprehur ndaj tyre dashuri, kur dihet se ata mohuan t&euml; v&euml;rtet&euml;n q&euml; u erdhi juve. Ata e d&euml;bojn&euml; t&euml; d&euml;rguarin dhe ju, sespe i besoni All-llahut, Zotit tuaj, e ju fshehurazi u ofroni miq&euml;si, po Un&euml; m&euml; s&euml; miri e di at&euml; q&euml; e keni fshehur dhe at&euml; q&euml; e keni publikuar. Ai q&euml; punon ashtu nga pala juaj, ia e ka humbur rrug&euml;n e drejt&euml;.';
$t[2] = 'N&euml;se ata ia dalin t&rsquo;ju mindin, ata do t&euml; jen&euml; armiq tuaj, do t&euml; zgjasin duart e veta dhe gjuh&euml;t e veta kund&euml;r jush, duke ju p&euml;rbuzur, sepse ata d&euml;shironin t&euml; mos besonit.';
$t[3] = 'N&euml; dit&euml;n e kijametit All-llahu gjykon mes jush, e nuk do t&rsquo;ju b&euml;jn&euml; dobi as t&euml; a&euml;rmit tuaj e as f&euml;mij&euml;t tuaj. All-llahu sheh at&euml; q&euml; punoni.';
$t[4] = 'Ju e keni shembullin m&euml; t&euml; mir&euml; te Ibrahimi dhe ata q&euml; ishin me t&euml;, kur i than&euml; popullit t&euml; vet: &ldquo;Ne t&euml;rhiqemi prej jush dhe prej asaj q&euml; adhuroni, pos All-llahut, nuk besojn&euml; tuaj&euml;n, randaj nd&euml;rmjet nesh e jush &euml;sht&euml; e hap&euml;t armiq&euml;sia e urrejtja derisa ta besoni vet&euml;m All-llahun Nj&euml;!&rdquo; (Nuk e kemi shembull) Me p&euml;rjashtim t&euml; fjal&euml;s s&euml; Ibrahimit th&euml;n&euml; babait t&euml; vet: &ldquo;Un&euml; do t&euml; k&euml;rkoj falje p&euml;r ty, po un&euml; nuk kam n&euml; dor&euml; asgj&euml; p&euml;r ty te All-llahu!&rdquo; Zoti yn&euml;, vet&euml;m Ty t&euml; jemi mb&euml;shtetur, vet&euml;m nga Ti jemi kthyer dhe vet&euml;m te Ti &euml;sht&euml; e ardhmja!';
$t[5] = 'Zoti yn&euml;, mos na b&euml;n sprov&euml; n&euml; duar t&euml; atyre q&euml; nuk besuan dhe falna, Zoti yn&euml;, Ti je ngadh&euml;njyesi, i urti.';
$t[6] = 'V&euml;rtet, p&euml;r at&euml; q&euml; ka shpres&euml; n&euml; All-llahun dhe n&euml; dit&euml;n e gjykimit, ju keni most&euml;r t&euml; mir&euml; (te Ibrahimi dhe besimtar&euml;t), e kush i bie prapa, le ta dij&euml; se All-llahu &euml;sht&euml; Ai i panevojshmi, i vetvetiu i lavd&euml;ruari.';
$t[7] = 'Pritet q&euml; All-llahu t&euml; ver&euml; miq&euml;si nd&euml;rmjet jush dhe atyre q&euml; kishit armiq&euml;si, All-llahu &euml;sht&euml; i fuqish&euml;m, All-llahu fal&euml; m&euml;katet, &euml;sht&euml; m&euml;shirues.';
$t[8] = 'All-llahu nuk ju ndalon t&euml; b&euml;ni mir&euml; dhe t&euml; mbani drejt&euml;si me ata q&euml; nuk ju luftuan p&euml;r shkak t&euml; fes&euml;, e as nuk ju d&euml;buan prej sht&euml;pive tuaja; All-llahu i do ata q&euml; mbajn&euml; drejt&euml;sin&euml;.';
$t[9] = 'All-llahu ju ndalon t&rsquo;u afroheni vet&euml;m atyre q&euml; ju luftuan p&euml;r shkak t&euml; fes&euml;, q&euml; ju nxor&euml;n prej sht&euml;pive tuaja dhe q&euml; ndihmuan d&euml;bimin tuaj; ju ndalon t miq&euml;soheni me ta. Kush miq&euml;sohet me ta, t&euml; till&euml;t jan&euml; d&euml;mtues t&euml; vetvet&euml;s.';
$t[10] = 'O ju q&euml; besuat, kur t&rsquo;ju vijn&euml; besimtaret e shp&euml;rngulura (prej Mekes), provoni besnik&euml;rin&euml; e tyre, ndon&euml;se All-llahu di m&euml; s&euml; miri p&euml;r besimin e tyre; n&euml;se v&euml;rtetoni se ato jan&euml; besimtare, at&euml;her&euml;, mos i ktheni ato te jobesimtar&euml;t, pse as ato nuk jan&euml; t&euml; lejuara p&euml;r ta e as ata nuk jan&euml; t&euml; lejuar p&euml;r to, e ju jepnu atyre (jobesimtar&euml;ve) at&euml; q&euml; kan&euml; shpenzuar p&euml;r to (n&euml; em&euml;r t&euml; koror&euml;zimit). Ju nuk keni penges&euml; t&euml; martoheni me to, pasi t&rsquo;ua jepni vler&euml;n e kuror&euml;s. Mos i mbani n&euml;n kuror&euml;, idhujtaret por k&euml;rkoni (prej idhujtar&euml;ve mekas) at&euml; q&euml; keni shpenzuar p&euml;r to, dhe ata le t&euml; k&euml;rkojn&euml; (prej jush besimtar&euml;) at&euml; q&euml; kan&euml; shpenzuar. K&euml;to jan&euml; dispozita t&euml; All-llahut me t&euml; cilat Ai gjykon nd&euml;rmjet jush; All-llahu &euml;sht&euml; m&euml; i dijshmi, m&euml; i informuari.';
$t[11] = 'N&euml; qoft&euml; se u humbet di&ccedil;ka (nga shpenzimi) i ndonj&euml; gruaje tuaj q&euml; ik&euml;n te idhujtar&euml;t, e juve u vjen rasti t&rsquo;i luftoni dhe t&euml; merrni pre t&euml; luft&euml;s, at&euml;her&euml; atyre q&euml; u kan&euml; shkuar grat&euml;, jepnu aq sa kan&euml; shpenzuar; e, kinie frik&euml; All-llahun, t&euml; cilin ju e besoni!';
$t[12] = 'O Pejgamber, kur t&euml; vijn&euml; besimtaret q&euml; t&euml; japin bes&euml;n se: nuk do t&rsquo;i shoq&euml;rojn&euml; asnj&euml; send All-llahut; se nuk do t&euml; vjedhin; se nuk do t&euml; b&euml;jn&euml; kurv&euml;ri; se nuk do t&rsquo;i mbysin f&euml;mij&euml;t e tyre; se nuk do t&euml; g&euml;njejn&euml; me ndonj&euml; shpifje p&euml;r (f&euml;mij&euml;n e huaj q&euml; kan&euml; marr&euml;) se &euml;sht&euml; i tyre; dhe se nuk do t&euml; t&euml; kund&euml;rshtojn&euml; n&euml; at&euml; q&euml; i urdh&euml;ron, at&euml;her&euml;, prano zotimin e tyre dhe lute All-llahun t&rsquo;i fal&euml; ato, se All-llahu &euml;sht&euml; m&euml;katfal&euml;s dhe m&euml;shirues.';
$t[13] = 'O ju q&euml; keni besuar, mos u miq&euml;soni me nj&euml; popull q&euml; All-llahu ka shprehur hidh&euml;rim kund&euml;r tij, popull q&euml; ka humbur shpres&euml;n ndaj bot&euml;s s&euml; ardhshme, ashtu si nuk kan&euml; shpres&euml; jobesimtar&euml;t prej t&euml; vdekurve (q&euml; do t&euml; ngjallen) n&euml; k&euml;t&euml; bot&euml;, ose n&euml; ringjallje (n&euml; bot&euml;n tjet&euml;r).';
?>