<?php
$t = array();
$t[1] = 'Kur t&euml; erdh&euml;n ty hipokrit&euml;t, t&euml; than&euml;: &ldquo;Ne d&euml;shmojm&euml; se v&euml;rtet ti je i d&euml;rguar i All-llahut!&rdquo; E, All-llahu e di se ti je i d&euml;rguar i Tij, por All-llahu d&euml;shmon se hipokrit&euml;t jan&euml; rrenacak&euml; (kur thon&euml; ashtu).';
$t[2] = 'Ata betimin e tyre e b&euml;jn&euml; p&euml;r t&rsquo;u mbrojtur, andaj ata penguan nga rruga e All-llahut. Veprimi q&euml; ata b&euml;n&euml; &euml;sht&euml; shum&euml; keq.';
$t[3] = 'Ngase ata besuan (me goj&euml;) e pastaj mohuan, andaj zemrat e tyre u mbyll&euml;n dhe ata nuk kuptojn&euml;.';
$t[4] = 'E kur t&rsquo;i shohish ata, trupat e tyre t&euml; mahnisin, e kur t&euml; flasin, fjal&euml;s s&euml; tyre i v&euml; veshin. Po ata jan&euml; si trungujt e zgavruar e t&euml; mb&euml;shtetur, e &ccedil;do z&euml; e mendojn&euml; se &euml;sht&euml; kund&euml;r tyre. Ata jan&euml; armiq, pra ruaju prej tyre! All-llahu i vraft&euml;, si shmangen nga e v&euml;rteta!';
$t[5] = 'E kur u thuhet: &ldquo;Ejani te i d&euml;rguari i All-llahut q&euml; ai t&euml; k&euml;rkoj&euml; prej Tij falje p&euml;r ju&rdquo;, ata tundin kokat e tyre dhe i sheh se si ta kthejn&euml; shpin&euml;n duke e mbajtur veten t&euml; madh.';
$t[6] = 'Sa u p&euml;rket atyre, &euml;sht&euml; krejt nj&euml;soj: si k&euml;rkove p&euml;r ta falje, si nuk k&euml;rkove p&euml;r ta falje (nga Zoti), sepse All-llahu kurrsesi nuk do t&rsquo;i fal&euml; dhe &euml;sht&euml; e sigurt se All-llahu nuk ia ofron udh&euml;zimin popullit arrogant.';
$t[7] = 'Ata jan&euml; q&euml; u thon&euml; (vendasve t&euml; Medin&euml;s): &ldquo;Mos u jepni atyre q&euml; jan&euml; me t&euml; d&euml;rguarin e All-llahut (muhaxhir&euml;ve), ashtu q&euml; t&euml; shp&euml;rndahen!. Po, te All-llahu jan&euml; pasurit&euml; (depot) e iqejve e t&euml; tok&euml;s, por hipokrit&euml;t nuk jan&euml; duke kuptuar&rdquo;.';
$t[8] = 'Ata thon&euml;: &ldquo;N&euml;se do t&euml; kthehemi (prej gjuh&euml;s me beni Mustalik&euml;t) n&euml; Medine, ai m&euml; i forti pa tjet&euml;r prej aty ka p&euml;r ta p&euml;rz&euml;n&euml; at&euml; m&euml; t&euml; dob&euml;tin!&rdquo; (ashtu than&euml;) Nd&euml;rsa e t&euml;r&euml; krenaria i takon All-llahut, t&euml; d&euml;rguarit t&euml; Tij dhe besimtar&euml;ve, por hipokrit&euml;t k&euml;t&euml; nuk e din&euml;.';
$t[9] = 'O ju q&euml; besuat, as pasuria juaj e as f&euml;mij&euml;t tuaj t&euml; mos u shmangin prej adhurimit t&euml; All-llahut, e kush b&euml;n ashtu t&euml; till&euml;t jan&euml; mu ata t&euml; humburit.';
$t[10] = 'Dhe jepni nga ajo q&euml; Ne u kemi dh&euml;n&euml; juve, para se ndonj&euml;rit prej jush t&rsquo;i vij&euml; vdekja, e at&euml;her&euml; t&euml; thot&euml;: &ldquo;O Zoti im, p&euml;rse nuk m&euml; shtyve edhe pak afatin (e vdekjes), q&euml; t&euml; jepja l&euml;mosh&euml; e t&euml; b&euml;hesha prej t&euml; mira!&rdquo;';
$t[11] = 'Po, All-llahu kurrsesi ask&euml; nuk e shtyn p&euml;r m&euml; von&euml;, kur atij t&rsquo;i vij&euml; afati i vet. All-llahu holl&euml;sisht &euml;sht&euml; i njohur me at&euml; q&euml; ju punoni.';
?>