<?php
$t = array();
$t[1] = 'Vet&euml;m All-llahut i shprehin madh&euml;rin&euml; e lart&euml;simin &ccedil;ka ka n&euml; qiej dhe &ccedil;ka n&euml; tok&euml;, dhe se vet&euml;m e Tij &euml;sht&euml; i t&euml;r&euml; pushteti dhe vet&euml;m Atij i takon fal&euml;nderimi, e Ai &euml;sht&euml; i gjithfuqish&euml;m p&euml;r &ccedil;do send.';
$t[2] = 'Ai &euml;sht&euml; q&euml; u krijoi juve, e nga ju ka mohues dhe ka besimtar&euml;. All-llahu e sheh shum&euml; mir&euml; at&euml; q&euml; e punoni.';
$t[3] = 'Ai krijoi qiejt dhe tok&euml;n me urt&euml;si t&euml; p&euml;rsosur dhe Ai juve u dha form&euml;n, e form&euml;n tuaj e b&euml;ri t&euml; bukur dhe vet&euml;m te Ai &euml;sht&euml; e ardhmja.';
$t[4] = 'Ai e di &ccedil;&rsquo;ka n&euml; qiej e n&euml; tok&euml;, e di at&euml; q&euml; e fshihni dhe at&euml; q&euml; e shfaqni haptazi, sepse All-llahu di edhe at&euml; q&euml; mbajn&euml; n&euml; zemrat.';
$t[5] = 'A nuk ju erdhi lajmi i atyre q&euml; ishin m&euml; par&euml; e nuk besuan, ndaj edhe p&euml;rjetuan barr&euml;n e r&euml;nd&euml; t&euml; pun&euml;s s&euml; vet dhe ata kan&euml; nj&euml; d&euml;nim t&euml; idh&euml;t.';
$t[6] = 'At&euml; (d&euml;nim e marrin) p&euml;r shkak se atyre u vinin t&euml; d&euml;rguarit e vet me argumente t&euml; qarta, e ata thoshin: &ldquo;A njeriu i thjesht&euml; do t&euml; na udh&euml;zoj&euml; neve?&rdquo; Dhe ashtu nuk besuan dhe u zmbraps&euml;n, po All-llahu nuk ka nevoj&euml; p&euml;r ta; All-llahu &euml;sht&euml; begatsh&euml;m, e i fal&euml;nderuar nga vetvetiu.';
$t[7] = 'Ata q&euml; nuk besuan, menduan se kurrsesi nuk do t&euml; ringjallen. Thuaj: &ldquo;Po, pasha Zotin tim, pa tjet&euml;r do t&euml; ringjalleni dhe do t&euml; njiheni me at&euml; q&euml; keni punuar, e ajo p&euml;r All-llahun &euml;sht&euml; leht&euml;!&rdquo;';
$t[8] = 'At&euml;her&euml; pra, pranonie All-llahun, t&euml; d&euml;rguarin e Tij dhe drit&euml;n q&euml; e zbrit&euml;m Ne. All-llahu &euml;sht&euml; i njohur p&euml;r at&euml; q&euml; veproni.';
$t[9] = 'Dit&euml;n e kijametit, kur Ai u tubon juve, ajo &euml;sht&euml; dit&euml; e mashtrimit (dit&euml;n e kijametit duket se kush &euml;sht&euml; mashtruar). kush beson All-llahun dhe b&euml;n vepra t&euml; mira. Ai ia shlyen t&euml; k&euml;qijat e tij dhe at&euml; e fut n&euml; Xhennete, n&euml;p&euml;r t&euml; cilat rrjedhin lumenj; aty do t&euml; jen&euml; p&euml;rgjthmon&euml;, e ai &euml;sht&euml; shp&euml;timi i madh.';
$t[10] = 'E ata q&euml; nuk besuan dhe p&euml;rg&euml;njeshtruan argumentet Tona, t&euml; till&euml;t jan&euml; banor&euml;t e zjarrit; aty do t&euml; jen&euml; p&euml;rgjithmon&euml;, e ai &euml;sht&euml; p&euml;rfundim i keq.';
$t[11] = '&ccedil;far&euml;do e keqe q&euml; ndodh (godet), nuk mund t&euml; jet&euml; ndryshe, vet&euml;m sipas caktimit t&euml; All-llahut, e kush i beson All-llahut, Ai ia udh&euml;zon zemr&euml;n e tij; All-llahu &euml;sht&euml; i gjithdijsh&euml;m p&euml;r &ccedil;do send.';
$t[12] = 'Pra, respektonie All-llahun dhe respektonie t&euml; d&euml;rguarin, po n&euml;se nuk e respektoni, at&euml;her&euml; detyr&euml; e t&euml; d&euml;rguarit ton&euml; &euml;sht&euml; vet&euml;m kumtimi i qart&euml;.';
$t[13] = 'All-llahu &euml;sht&euml; Ai q&euml; pos Tij nuk ka zot tjet&euml;r, prandaj vet&euml;m All-llahut le t&rsquo;i mb&euml;shteten besimtar&euml;t.';
$t[14] = 'O ju q&euml; besuat, v&euml;rtet, disa nga bashk&euml;shortet tuaja dhe nga f&euml;moj&euml;t tuaj jan&euml; armiq tuaj, andaj kini kujdes ndaj tyre, e n&euml;se nuk merrni masa, nuk ua vini veshin dhe i falni, ta dini se edhe All-llahu &euml;sht&euml; m&euml;katfal&euml;s, m&euml;shirues.';
$t[15] = 'S&rsquo;ka dyshim se pasuria juaj dhe f&euml;mij&euml;t tuaj jan&euml; sprov&euml;, nd&euml;rsa ajo q&euml; &euml;sht&euml; te All-llahu, &euml;sht&euml; shp&euml;rblim i madh.';
$t[16] = 'Andaj, sa t&euml; keni mund&euml;si ruanu prej d&euml;nimit t&euml; All-llahut, d&euml;gjoni, respektoni dhe jepni p&euml;r t&euml; mir&euml;n tuaj, e kush i ruhet lakmis&euml; s&euml; vetvetes, t&euml; till&euml;t jan&euml; t&euml; shp&euml;tuarit.';
$t[17] = 'N&euml;se All-llahut i huazoni di&ccedil;ka t&euml; mir&euml;, Ai juve ua shum&euml;fishon at&euml; dhe ju fal&euml;; All-llahu &euml;sht&euml; shum&euml; mir&euml;njoh&euml;s, i but&euml;.';
$t[18] = '&Euml;sht&euml; i gjithdijshmi i t&euml; fsheht&euml;s e i t&euml; dukshmes, &euml;sht&euml; ngadh&euml;njyesi, i urti.';
?>