<?php
$t = array();
$t[1] = 'O ti pejgamber, kur t&rsquo;i l&euml;shoni grat&euml;, l&euml;shoni ato n&euml; vigjilje t&euml; fillimit t&euml; pritjes s&euml; tyre (n&euml; koh&euml;n e past&euml;rtis&euml; s&euml; tyre) dhe koh&euml;n e pritjes mbanie mend mir&euml; e kini frik&euml; All-llahut, Zotit tuaj, dhe mos i nxirrni ato prej sht&euml;pive t&euml; tyre, e edhe ato t&euml; mos dalin ndryshe vet&euml;m n&euml;se b&euml;jn&euml; ndonj&euml; vep&euml;r t&euml; keqe t&euml; v&euml;rtetuar. K&euml;to jan&euml; dispozitat e All-llahut, e kush del jasht&euml; dispozitave t&euml; All-llahut, ai e ka d&euml;mtuar vetveten. Ti nuk e di, All-llahu pas asaj mund t&euml; t&euml; jap di&ccedil;ka rishtazi.';
$t[2] = 'E kur t&rsquo;i afrohen ato mbarimit ta afatit t&euml; tyre, at&euml;her&euml; ose mbani (i ktheni n&euml; jet&euml;n bashk&euml;shortore) si duhet, ose ndanu prej tyre si &euml;sht&euml; e udh&euml;s, e k&euml;t&euml; do ta d&euml;shmojn&euml; dy d&euml;shmitar&euml; t&euml; drejt&euml; nga mesi juaj dhe d&euml;shmit&euml; zbatojeni p&euml;r hir&euml; t&euml; All-llahut. K&euml;shtu k&euml;shillohet ai q&euml; i beson All-llahut dhe dit&euml;s s&euml; fundit, e kush iu p&euml;rmbahet dispozitave t&euml; All-llahut, atij Ai i hap rrug&euml;,';
$t[3] = 'dhe e furnizon at&euml; prej nga nuk kujton fare. K&euml;shtu i mb&euml;shtetet All-llahut, Ai i mjafton atij, All-llahu realizon d&euml;shir&euml;n e vet dhe All-llahu &ccedil;do gj&euml;je ia ka caktuar koh&euml;n (afatin).';
$t[4] = 'E ato nga grat&euml; tuaja t&euml; cilave u &euml;sht&euml; nd&euml;rprer&euml; cikli mujor (menstruacioni) n&euml;se nuk e keni ditur, koha e pritjes s&euml; tyre &euml;sht&euml; tre muaj, e ashtu edhe ato q&euml; ende nuk kan&euml; pasur menstruacion. Nd&euml;rkaq, p&euml;r shtatz&euml;nat afati i pritjes s&euml; tyre &euml;sht&euml; derisa t&euml; lindin. E kush i frik&euml;sohet All-llahut, Ai atij ia leht&euml;son pun&euml;n.';
$t[5] = 'Ky &euml;sht&euml; vendim i All-llahut q&euml; ua zbriti juve, e kush e ka frik&euml; All-llahun, Ai atij ia shlyen t&euml; k&euml;qijat dhe ia shton shp&euml;rblimin.';
$t[6] = 'Ato (grat&euml; e l&euml;shuara), sipas mund&euml;sis&euml; suaj i vendosni n&euml; ndonj&euml; vend ku banoni ju, e mos i ngushtoni ato p&euml;r t&rsquo;i detyruar (t&euml; dalin). N&euml; qoft&euml; se ato jan&euml; shtatz&euml;na, at&euml;her&euml; furnizoni ato derisa ta heqin barr&euml;n e tyre, e n&euml;se ato u japin gji f&euml;mij&euml;ve tuaj, at&euml;her&euml; jepnu atyre shp&euml;rblimin q&euml; u takon dhe kini mir&euml;kuptim n&euml; mes jush ashtu si duhet, e n&euml; qoft&euml; se hasni n&euml; v&euml;shtir&euml;si nd&euml;r vete, at&euml;her&euml; le t&euml; k&euml;rkojn&euml; p&euml;r t&euml; gjidh&euml;n&euml;se tjet&euml;r.';
$t[7] = 'Ai q&euml; &euml;sht&euml; i pasur, le t&euml; shpenzoj&euml; sipas mund&euml;sis&euml; s&euml; vet, e ai q&euml; &euml;sht&euml; ngusht nga pasuria, le t&euml; jap&euml; nga ajo q&euml; i ka dh&euml;n&euml; All-llahu, e All-llahu nuk ngarkon ask&euml;, vet&euml;m aq sa i ka dh&euml;n&euml;; mir&euml;po pas v&euml;shtir&euml;sis&euml; All-llahu sjell &ccedil;lirim (begati).';
$t[8] = 'Sa shum&euml; banor&euml; t&euml; fshatrave, q&euml; ishin kryene&ccedil;&euml; ndaj urdh&euml;rit t&euml; Zotit t&euml; vet dhe ndaj t&euml; d&euml;rguar&euml;ve t&euml; Tij, Ne i kemi shp&euml;rblyer me nj&euml; llogari t&euml; ashp&euml;r, i kemi nd&euml;shkuar me nj&euml; d&euml;nim t&euml; pap&euml;rshkruesh&euml;m.';
$t[9] = 'She ata e p&euml;rjetuan barr&euml;n e r&euml;nd&euml; t&euml; pun&euml;s s&euml; vet, k&euml;shtu q&euml; fundi i &ccedil;&euml;shtjes s&euml; tyre ishte d&euml;shtimi.';
$t[10] = 'All-llahu u ka p&euml;rgatitur d&euml;nim t&euml; r&euml;nd&euml;, atyre pra, kinie frik&euml; All-llahun o ju t&euml; zot&euml;t e mendjes. E ju q&euml; keni besuar, All-llahu u zbriti juve shpalljen (Kur&rsquo;anin).';
$t[11] = 'T&euml; d&euml;rguarit q&euml; ua lexon ajetet e qarta t&euml; All-llahut p&euml;r t&rsquo;i nxjerr&euml; ata q&euml; besuan dhe b&euml;n&euml; cepra t&euml; mira prej err&euml;sirave n&euml; drit&euml;. Kush i beson All-llahut dhe b&euml;n vepra t&euml; mira, Ai e shpie at&euml; n&euml; Xhennete n&euml;p&euml;r t&euml; cilat rrjedhin lumenj; aty do t&euml; jen&euml; p&euml;rgjthmon&euml; e kurr&euml; pak&euml;putur. All-llahu i ka dh&euml;n&euml; atij furnizim t&euml; mir&euml;...';
$t[12] = 'All-llahu &euml;sht&euml; Ai q&euml; krijoi shtat&euml; pal&euml; qiej dhe prej tok&euml;s aq sa ata; n&euml; to zbatohet vendimi i Tij p&euml;r ta ditur ju se All-llahu ka fuqi p&euml;r &ccedil;do send dhe q&euml; me t&euml; v&euml;rtet&euml; All-llahu ka p&euml;rfshir&euml; &ccedil;do send me dijen e vet.';
?>