<?php
$t = array();
$t[1] = 'O ti pejgamber (o ti, q&euml; &euml;sht&euml; sjell&euml; kumtesa nga qielli), pse ndalon vetes at&euml; q&euml; All-llahu ta lejoni? A k&euml;rkon me t&euml; pajtim e grave tuaja? All-llahu &euml;sht&euml; m&euml;katfal&euml;s, m&euml;shirues.';
$t[2] = 'All-llahu u ka p&euml;rcaktuar juve zgjidhjen e betimeve tuaj; All-llahu &euml;sht&euml; kujdestari juaj; Ai &euml;sht&euml; i gjithdjshmi, i urti.';
$t[3] = '(P&euml;rkujto) kur Pejgamberi ndonjer&euml;s prej grave t&euml; veta i kumtoi fshehurazi nj&euml; lajm, e kur ajo tregoi at&euml; (lajm), e All-llahu (Pejgamberit) i zbuloi atij p&euml;r t&euml; (kallzimin e lajmit nga ajo grua), ai ia b&euml;ri me (asaj) me dije nj&euml; pjes&euml; t&euml; trgimit, kurse p&euml;r pjes&euml;n tjet&euml;r heshti. E kur ai (pejgamberi) e njohtoi at&euml; (gruan) me at&euml; (q&euml; kishte treguar), ajo tha: &ldquo;E kush t&euml; tregoi ty k&euml;t&euml;?&rdquo; Ai tha: &ldquo;M&euml; tregoi i gjithdijshmi, njoh&euml;si i t&euml; fshehtave!&rdquo;';
$t[4] = 'N&euml;se ju t&euml; dyja pendoheni te All-llahu (&euml;sht&euml; m&euml; mir&euml; p&euml;r ju), sepse se zemrat tuaja tanim&euml; kan&euml; rr&euml;shqitur, e n&euml;se bashkveproni kund&euml;r tij, ta dini se All-llahu &euml;sht&euml; Ai mbrojt&euml;s i tij si dhe Xhibrili dhe besimtar&euml;t e ndersh&euml;m; e kur &euml;sht&euml; k&euml;shtu, edhe engj&euml;jt i dalin n&euml; ndihm&euml;.';
$t[5] = 'N&euml;se ai u ka l&euml;shuar juve, &euml;sht&euml; detyr&euml; e Zotit t&euml; tij t&rsquo;i b&euml;j&euml; z&euml;vendsim me gra edhe m&euml; t&euml; mira se ju; myslimane, besmtar&euml;, respektuese, penduese, adhuruese, emigruese q&euml; kan&euml; qen&euml; t&euml; martuara ose virgjiresha.';
$t[6] = 'O ju q&euml; besuat, ruane veten dhe familjen tuaj prej zjarrit, l&euml;nda djeg&euml;se e t&euml; cilit jan&euml; njer&euml;zit dhe gur&euml;t. At&euml; (zjarrin) e mbik&euml;qyrin engj&euml;jt t&euml; rrept&euml; e t&euml; ashp&euml;r q&euml; nuk e knd&euml;rshtojn&euml; All-llahun p&euml;r asgj&euml; q&euml; Ai i urdh&euml;ron dhe punojn&euml; at&euml; q&euml; jan&euml; t&euml; urdh&euml;ruara.';
$t[7] = 'O ju q&euml; mohuat, sot mos u arsyetoni; ju shp&euml;rbleni veten p&euml;r at&euml; q&euml; keni vepruar.';
$t[8] = 'O ju q&euml; keni besuar, pendohuni te All-llahu me nj&euml; pendim t&euml; sinqert&euml; n&euml; m&euml;nyr&euml; q&euml; Zoti juaj t&rsquo;i largoj&euml; prej jush t&euml; k&euml;qijat, t&rsquo;u shpie n&euml; Xhennete, n&euml;n t&euml; cilat rrjedhin lumenj dit&euml;n kur All-llahu nuk e turp&euml;ron Pejgamberin e s&euml; bashku me t&euml; as atta q&euml; kan&euml; besuar. Drita e tyre ndri&ccedil;on para tyre dhe n&euml; t&euml; djatht&euml; t&euml; t&euml; tyre, e ata thon&euml;: &ldquo;Zoti yn&euml;, vazhdona drit&euml;n ton&euml;, falna neve. V&euml;rtet, Ti je i plotfuqish&euml;m p&euml;r &ccedil;do send&rdquo;.';
$t[9] = 'O ti pejgamber, luftonju jobesimtar&euml;t e hipokrit&euml;t dhe q&euml;ndro ash&euml;p&euml;r kund&euml;r tyre; vendi i tyre &euml;sht&euml; Xhehennemi q&euml; &euml;sht&euml; nj&euml; vend i sh&euml;mtuar!';
$t[10] = 'Atyre q&euml; mohuan, All-llahu u sjell nj&euml; shembull gruan e Nuhut dhe gruan e Lutit. Ato t&euml; dyja ishin n&euml; kuror&euml; t&euml; dy rob&euml;rve t&euml; mir&euml; nga rob&euml;rit tan&euml;, por ato t&euml; dyja i tradhtuan (n&euml; fe) ata t&euml; dy dhe k&euml;ta t&euml; dy nuk mund t&rsquo;i mbrojn&euml; ato fare te All-llahu, e atyre dyjave u thuhet: &ldquo;Hyni n&euml; zjarr s&euml; bashku me ata q&euml; hyjn&euml;!&rdquo;';
$t[11] = 'E atyre q&euml; besuan, All-llahun u solli shembull gruan e faraonit kur ajo tha: &ldquo;Zoti im, m&euml; b&euml;n nj&euml; vend pran&euml; m&euml;shir&euml;s sate n&euml; Xhennet dhe m&euml; shp&euml;to prej faraonit e brutalitetit t&euml; tij dhe m&euml; shp&euml;to prej popullit mizor!&rdquo;';
$t[12] = 'Edhe Merjemen t&euml; bij&euml;n e Imranit, q&euml; e ruajti nderin e vet, e Ne prej an&euml;s son&euml; i frym&euml;zuam nj&euml; shpirt e ajo i besoi fjal&euml;t e Zotit t&euml; saj dhe librat e Tij dhe ishte e devotshme.';
?>