<?php
$t = array();
$t[1] = 'O wy, kt&oacute;rzy wierzycie! Nie wysuwajcie się naprz&oacute;d przed Bogiem i Jego Posłańcem i b&oacute;jcie się Boga! Zaprawdę, B&oacute;g jest słyszący, widzący!';
$t[2] = 'O wy, kt&oacute;rzy wierzycie! Nie podnoście waszych głos&oacute;w ponad głos Proroka! I nie zwracajcie się do niego głosem podniesionym - jak to czynicie między sobą - aby nie stały się daremne wasze uczynki, kiedy nie jesteście świadomi.';
$t[3] = 'Zaprawdę, ci, kt&oacute;rzy zniżają głos w obecności Posłańca Boga - to są ci, kt&oacute;rych serca doświadczył B&oacute;g dla bogobojności. Dla nich będzie przebaczenie i nagroda ogromna.';
$t[4] = 'Zaprawdę, ci, kt&oacute;rzy ciebie wzywają z tyłu komnat, przeważnie tego nie rozumieją.';
$t[5] = 'A jeśliby oni byli cierpliwi, aż ty do nich wyjdziesz, to byłoby lepiej dla nich. A B&oacute;g jest przebaczający, litościwy!';
$t[6] = 'O wy, kt&oacute;rzy wierzycie! Jeśli przyjdzie do was jakiś zły człowiek z wieścią, to starajcie się rozeznać, żebyście nie urazili ludzi nieświadomie i abyście potem nie żałowali tego, co uczyniliście.';
$t[7] = 'I wiedzcie, że Posłaniec Boga jest pośr&oacute;d was. Jeśliby on posłuchał was w wielu sprawach, to z pewnością ponieślibyście szkodę. Lecz B&oacute;g dał wam pokochać wiarę i On ozdobił ją w waszych sercach, a uczynił dla was nienawistną niewiarę, zepsucie i nieposłuszeństwo. Tacy - oni idą drogą prawości.';
$t[8] = 'To jest łaska Boga i dobrodziejstwo. B&oacute;g jest wszechwiedzący, mądry!';
$t[9] = 'Jeśli dwie partie spośr&oacute;d wiernych zwalczają się, to ustan&oacute;wcie między nimi pok&oacute;j. A jeśli jedna z nich będzie nadal występować przeciw drugiej, to zwalczajcie tę, kt&oacute;ra się buntuje, aż zwr&oacute;ci się ku rozkazowi Boga. A jeśli się podda, to ustan&oacute;wcie między nimi pok&oacute;j według sprawiedliwości i postępujcie bezstronnie! Zaprawdę, B&oacute;g miłuje ludzi, kt&oacute;rzy postępują według słuszności.';
$t[10] = 'Wierni są przecież braćmi! Ustanawiajcie więc pok&oacute;j między waszymi dwoma braćmi i b&oacute;jcie się Boga! Być może, wy dostąpicie miłosierdzia.';
$t[11] = 'O wy, kt&oacute;rzy wierzycie! Niech jedni ludzie nie szydzą z drugich; być może, tamci są lepsi od nich. Ani też kobiety - z kobiet; być może, tamte są lepsze od nich. I nie zniesławiajcie siebie samych; i nie obrzucajcie się wyzwiskami. Jakże złe jest słowo &quot;zepsucie&quot; - po przyjęciu wiary! A ten, kto się nie nawr&oacute;ci - to ci - oni są niesprawiedliwi.';
$t[12] = 'O wy, kt&oacute;rzy wierzycie! Unikajcie wielce podejrzeń. Zaprawdę, niekt&oacute;re podejrzenia są grzechem! Nie szpiegujcie się wzajemnie! Nie obmawiajcie jedni drugich w ich nieobecności! Czy chciałby kt&oacute;ryś z was jeść ciało swego brata, kiedy on umarł? Przecież czulibyście wstręt do tego. B&oacute;jcie się Boga! Zaprawdę, B&oacute;g jest przebaczający, litościwy!';
$t[13] = 'O ludzie! Oto stworzyliśmy was z mężczyzny i kobiety i uczyniliśmy was ludami i plemionami, abyście się wzajemnie znali. Zaprawdę, najbardziej szlachetny spośr&oacute;d was, w obliczu Boga, to najbardziej bogobojny spośr&oacute;d was! Zaprawdę, B&oacute;g jest wszechwiedzący, dobrze świadomy!';
$t[14] = 'Powiedzieli Beduini: &quot;My wierzymy!&quot; Powiedz: &quot;Wy nie wierzycie; lecz raczej powiedzcie: \'My poddaliśmy się całkowicie!\', - bo wiara nie weszła jeszcze w wasze serca.&quot; A jeśli wy będziecie posłuszni Bogu i Jego Posłańcowi, to On w niczym nie umniejszy waszych uczynk&oacute;w. Zaprawdę, B&oacute;g jest przebaczający, litościwy!';
$t[15] = 'Wiernymi są tylko ci, kt&oacute;rzy uwierzyli w Boga i Jego Posłańca - potem nie mieli wątpliwości - i walczyli swoimi majątkami i swoimi osobami na drodze Boga. Tacy - oni są prawdom&oacute;wni!';
$t[16] = 'Powiedz: &quot;Czyż będziecie pouczać Boga o waszej religii, skoro B&oacute;g wie, co jest w niebiosach i co jest na ziemi? I B&oacute;g o każdej rzeczy jest wszechwiedzący?!&quot;';
$t[17] = 'Oni przedstawiają jako łaskawość dla ciebie to, iż przyjęli islam. Powiedz: &quot;Nie przedstawiajcie waszego islamu jako łaskawości dla mnie. Przeciwnie, to B&oacute;g obdarzył was łaską, że poprowadził was drogą prostą ku wierze - jeśli wy jesteście prawdom&oacute;wni!&quot;';
$t[18] = 'Zaprawdę, B&oacute;g zna to, co skryte w niebiosach i na ziemi! I B&oacute;g widzi jasno to, co wy czynicie!';
?>