<?php
$t = array();
$t[1] = 'B&oacute;g usłyszał słowa tej, kt&oacute;ra dyskutowała z tobą w sprawie swego męża i kt&oacute;ra skarżyła się Bogu; a B&oacute;g słyszał waszą rozmowę. Zaprawdę, B&oacute;g jest słyszący, widzący!';
$t[2] = 'Ci spośr&oacute;d was, kt&oacute;rzy się rozwodzą ze swoimi żonami, m&oacute;wiąc: &quot;Bądź dla mnie jak plecy mojej matki!&quot; - one przecież nie są ich matkami, matki to te, kt&oacute;re ich urodziły - oni z pewnością m&oacute;wią słowa godne nagany i pełne fałszu. Zaprawdę, B&oacute;g jest. odpuszczający, przebaczający!';
$t[3] = 'Tych, kt&oacute;rzy odsyłają swoje żony, m&oacute;wiąc: &quot;Ty jesteś dla mnie jak plecy mojej matki!&quot;, i powtarzają to, co powiedzieli - obowiązuje wyzwolenie niewolnika, zanim będą mogli ponownie się zetknąć. Oto w ten spos&oacute;b jesteście napominani. A B&oacute;g jest w pełni świadom tego, co wy czynicie!';
$t[4] = 'A kto nie ma możliwości, powinien pościć przez dwa następujące po sobie miesiące, zanim ponownie się zetkną. A kto ma możliwości, powinien nakarmić sześćdziesięciu biedak&oacute;w. Tak jest nakazane, abyście wierzyli w Boga i Jego Posłańca. Takie są granice Boga. A dla niewiernych kara będzie bolesna!';
$t[5] = 'Ci, kt&oacute;rzy się sprzeciwiają Bogu i Jego Posłańcowi, zostaną przewr&oacute;ceni, tak jak przewr&oacute;ceni zostali ci, kt&oacute;rzy byli przed nimi. My zesłaliśmy jasne znaki. A dla niewiernych kara będzie poniżająca!';
$t[6] = 'W tym Dniu, kiedy B&oacute;g wskrzesi ich wszystkich, powiadomi ich o tym, co oni uczynili; obliczył to B&oacute;g, a oni zapomnieli. B&oacute;g jest świadkiem każdej rzeczy!';
$t[7] = 'Czyż ty nie widzisz, że B&oacute;g wie doskonale, co jest w niebiosach i co jest na ziemi? I nie ma tajnej narady trzech, żeby On nie był czwarty, ani też pięciu, żeby On nie był sz&oacute;sty; ani też mniej, ani więcej, żeby On nie był z nimi, gdziekolwiek oni by się znajdowali. Następnie, w Dniu Zmartwychwstania, On im oznajmi to, co czynili. Zaprawdę, B&oacute;g o każdej rzeczy jest wszechwiedzący!';
$t[8] = 'Czyż nie widziałeś tych, kt&oacute;rym zostało zakazane tajne zebranie, jak potem ponownie czynią, co im zostało zakazane, i naradzają się potajemnie, w grzechu i wrogości, jak i nieposłuszeństwie względem Posłańca? Kiedy oni przychodzą do ciebie i pozdrawiają ciebie nie tak, jak pozdrawia ciebie B&oacute;g, m&oacute;wią o swoich duszach: &quot;Dlaczegoż miałby nas ukarać B&oacute;g za to, co m&oacute;wimy?&quot; Wystarczy dla nich Gehenna; będą się w niej palić! Jakże nieszczęsne to miejsce ostatecznej wędr&oacute;wki!';
$t[9] = 'O wy, kt&oacute;rzy wierzycie! Kiedy się zbieracie na tajne narady, nie naradzajcie się dla grzechu i wrogości czy dla nieposłuszeństwa Posłańcowi; lecz naradzajcie się wzajemnie dla pobożności i bojaźni Bożej! B&oacute;jcie się Boga, przy kt&oacute;rym zostaniecie zebrani!';
$t[10] = 'Potajemna narada pochodzi od szatana, aby zasmucili się ci, kt&oacute;rzy wierzą. Lecz on nie może im wcale zaszkodzić, chyba za pozwoleniem Boga. Niech więc ufają Bogu wierzący!';
$t[11] = 'O wy, kt&oacute;rzy wierzycie! Kiedy wam m&oacute;wią: &quot;Zr&oacute;bcie miejsce na zebraniach! &quot;, to zr&oacute;bcie miejsce, a B&oacute;g dla was zrobi miejsce. A kiedy wam m&oacute;wią: &quot;Wstawajcie!&quot;, to podnoście się! Wywyższy B&oacute;g - na r&oacute;żne stopnie - tych spośr&oacute;d was, kt&oacute;rzy wierzą i kt&oacute;rzy otrzymali wiedzę. B&oacute;g jest w pełni świadomy tego, co czynicie!';
$t[12] = 'O wy, kt&oacute;rzy wierzycie! Kiedy się naradzacie tajemnie z Posłańcem, to poprzedźcie tę waszą tajną naradę jałmużną. Jest to dla was lepsze i bardziej czyste. Lecz jeśli nie macie możliwości, to, zaprawdę, B&oacute;g jest przebaczający, litościwy!';
$t[13] = 'Czy wy się lękacie dać naprz&oacute;d jałmużnę, przed waszą tajną naradą? Jeśli tego nie uczyniliście i B&oacute;g zwr&oacute;cił się ku Wam, to odprawiajcie modlitwę, dawajcie jałmużnę, słuchajcie Boga i Jego Posłańca! B&oacute;g jest w pełni świadomy tego, co czynicie!';
$t[14] = 'Czyż nie widziałeś tych, kt&oacute;rzy zaprzyjaźnili się z ludem, na kt&oacute;rego zagniewał się B&oacute;g? Oni nie są ani z was, ani z nich; oni przysięgają kłamliwie, a przecież wiedzą!';
$t[15] = 'Przygotował dla nich B&oacute;g karę straszną. Zaprawdę, złe jest to, co oni czynili!';
$t[16] = 'Oni wzięli swoje przysięgi jako okrycie i odsunęli się od drogi Boga. Dla nich więc kara będzie poniżająca!';
$t[17] = 'Ani ich majątki, ani ich dzieci nie pomogą im nic wobec Boga. Oni będą mieszkańcami ognia; będą tam przebywać na wieki!';
$t[18] = 'W tym Dniu, kiedy wskrzesi ich B&oacute;g, wszystkich razem, oni będą Mu przysięgać, tak jak wam przysięgają; i sądzą, iż na czymś się opierają. Czyż oni nie są kłamcami?';
$t[19] = 'Zawładnął nimi szatan i spowodował, iż zapomnieli wspominać Boga. Stanowią oni partię szatana. O; tak! Zaprawdę, partia szatana! Oni, zaprawdę, są tymi, kt&oacute;rzy ponieśli stratę!';
$t[20] = 'Zaprawdę, ci, kt&oacute;rzy się sprzeciwiają Bogu i Jego Posłańcowi, są wśr&oacute;d najbardziej poniżonych.';
$t[21] = 'Napisał B&oacute;g: &quot;Z pewnością zwyciężę Ja i Moi posłańcy!&quot; Zaprawdę, B&oacute;g jest mocny, potężny!';
$t[22] = 'Nie znajdziesz ludzi, kt&oacute;rzy wierzą w Boga i w Dzień Ostatni, żeby odnosili się przyjaźnie do tych, kt&oacute;rzy się sprzeciwiają Bogu i Jego Posłańcowi; nawet gdyby to byli ich ojcowie albo ich synowie, albo ich bracia, albo ich r&oacute;d. On wypisał w ich sercach wiarę i umocnił ich Duchem pochodzącym od Niego. On wprowadzi ich do Ogrod&oacute;w, gdzie w dole płyną strumyki; oni będą tam przebywać na wieki. B&oacute;g znalazł w nich upodobanie i oni mają upodobanie w Nim. Oni stanowią partię Boga. O, tak! Zaprawdę, partię Boga - oni są szczęśliwi!';
?>