<?php
$t = array();
$t[1] = 'O wy, kt&oacute;rzy wierzycie! Nie bierzcie sobie za przyjaci&oacute;ł Mojego wroga i waszego wroga! Wy zwracacie się do nich z przyjaźnią, oni zaś nie wierzą w prawdę, kt&oacute;ra przyszła do was. Wypędzają Posłańca i was samych, ponieważ wy wierzycie w Boga, waszego Pana. Skoro wyszliście walczyć na Mojej drodze i poszukiwać Mojego zadowolenia, to czy będziecie w skrytości okazywać im przyjaźń? Ja wiem najlepiej to, co ukrywacie i co czynicie jawnie. A ktokolwiek z was to czyni, ten już zbłądził z r&oacute;wnej drogi.';
$t[2] = 'Jeśli oni was spotkają, będą dla was wrogami; wyciągną do was swoje ręce i swoje języki - ze złem. Oni by chcieli, abyście byli niewiernymi.';
$t[3] = 'Nie pomogą wam ani wasi bliscy krewni, ani wasze dzieci w Dniu Zmartwychwstania. On rozstrzygnie między wami. A B&oacute;g widzi dobrze, co czynicie!';
$t[4] = 'Mieliście już piękny przykład w Abrahamie i tych, kt&oacute;rzy byli z nim, kiedy powiedzieli do swego ludu: &quot;Zaprawdę, my nie mamy nic z wami i z tym, co wy czcicie opr&oacute;cz Boga! Wyrzekamy się was! Pojawiła się między nami i wami wrogość i zawiść na zawsze, chyba że uwierzycie w Boga Jedynego!&quot; Wyjątek uczyniwszy dla sł&oacute;w, jakie powiedział Abraham do swojego ojca: &quot;Z pewnością będę prosił o przebaczenie dla ciebie, choć nie mam władzy niczego uczynić dla ciebie u Boga.&quot; &quot;Panie nasz! Zaufaliśmy Tobie i nawr&oacute;ciliśmy się do Ciebie! Do Ciebie zmierza ostateczna wędr&oacute;wka!';
$t[5] = 'Panie nasz! Nie wystawiaj nas na pokuszenie wobec tych, kt&oacute;rzy nie wierzą! Przebacz nam, Panie nasz! Zaprawdę, Ty jesteś Potężny, Mądry!&quot;';
$t[6] = 'Mieliście w nich piękny przykład dla tego, kto spodziewa się spotkać Boga i kto się spodziewa Dnia Ostatniego. A ten, kto się odwr&oacute;ci... zaprawdę, B&oacute;g jest Bogaty, Godny Chwały!';
$t[7] = 'Być może, B&oacute;g ustanowi między wami i tymi spośr&oacute;d was, dla kt&oacute;rych jesteście wrogami - przyjaźń. B&oacute;g jest wszechmocny! B&oacute;g jest przebaczający, litościwy!';
$t[8] = 'B&oacute;g nie zabrania wam, abyście byli dobrzy i sprawiedliwi względem tych, kt&oacute;rzy was nie zwalczali z powodu religii ani nie wypędzali was z waszych domostw. Zaprawdę, B&oacute;g miłuje ludzi sprawiedliwych!';
$t[9] = 'B&oacute;g zabrania wam tylko, abyście sobie brali za przyjaci&oacute;ł tych, kt&oacute;rzy was zwalczali z powodu religii i kt&oacute;rzy was wypędzali z waszych domostw, i kt&oacute;rzy pomagali przy wypędzaniu was. Ci, kt&oacute;rzy ich biorą za przyjaci&oacute;ł, są ludźmi niesprawiedliwymi.';
$t[10] = 'O wy, kt&oacute;rzy wierzycie! Kiedy przyjdą do was kobiety wierzące, kt&oacute;re razem wywędrowały, to wybadajcie je. - B&oacute;g zna najlepiej ich wiarę! - Jeśli uznacie je za wierzące, to nie odsyłajcie ich do niewiernych: one nie są już im dozwolone ani oni nie są dozwoleni dla nich. Dajcie im to, co oni wydali! Nie będziecie mieli grzechu, jeśli je poślubicie, kiedy dacie im ich wynagrodzenie. I nie zatrzymujcie przez węzły małżeńskie kobiet niewierzących! Żądajcie od nich tego, co wydaliście, i niech oni żądają, co wydali. Takie jest dla was postanowienie Boga! On rozsądza między wami. B&oacute;g jest wszechwiedzący, mądry!';
$t[11] = 'A jeśli kt&oacute;raś z waszych żon odeszła od was do niewiernych, a potem wy chcecie się odpłacić, to dajcie tym, od kt&oacute;rych żony odeszły, tyleż, ile oni wydali. I b&oacute;jcie się Boga, w kt&oacute;rego wierzycie!';
$t[12] = 'O proroku! A kiedy przyjdą do ciebie kobiety wierzące złożyć ci przysięgę wierności: iż nie będą dodawać Bogu żadnych wsp&oacute;łtowarzyszy, iż nie będą kraść, iż nie będą popełniać cudzoł&oacute;stwa, iż nie będą zabijać swoich dzieci, iż nie będą przychodzić z oszczerstwem, zmyślając je między swoimi rękami i nogami, ani też nie będą się buntowały przeciwko tobie w tym, co jest uznane - to przyjmij ich przysięgę i proś Boga o przebaczenie dla nich! Zaprawdę, B&oacute;g jest przebaczający, mądry!';
$t[13] = 'O wy, kt&oacute;rzy wierzycie! Nie bierzcie sobie za przyjaci&oacute;ł ludzi, na kt&oacute;rych B&oacute;g jest zagniewany. Oni zwątpili w życie ostateczne, tak jak niewierni zwątpili w mieszkańc&oacute;w mogił.';
?>