<?php
$t = array();
$t[1] = 'O Proroku! Kiedy odprawiacie swoje żony, to odprawiajcie je w właściwym dla nich terminie. Przestrzegajcie tego terminu i b&oacute;jcie się Boga, waszego Pana! Nie wypędzajcie ich z dom&oacute;w i niech wcale nie wychodzą, chyba że dopuściły się jawnej bezecności. Takie są granice Boga! A ten, kto przekracza granice Boga, ten czyni niesprawiedliwość sobie samemu. Ty nie wiesz: Być może, B&oacute;g spowoduje, że zajdzie coś nowego.';
$t[2] = 'A kiedy nadejdzie ich termin, to albo zatrzymajcie je w spos&oacute;b godny, albo rozstańcie się z nimi w spos&oacute;b godny. I wezwijcie świadk&oacute;w, dw&oacute;ch sprawiedliwych spośr&oacute;d was, i ustan&oacute;wcie świadectwo wobec Boga. Przez to napominany jest ten, kto wierzy w Boga i w Dzień Ostatni. A temu, kto się boi Boga, On przygotuje jakieś wyjście;';
$t[3] = 'I da mu zaopatrzenie stąd, skąd on się nawet nie spodziewa. A temu, kto ufa Bogu, On sam wystarczy! Oto B&oacute;g powoduje spełnienie swojego rozkazu! B&oacute;g ustanowił miarę dla każdej rzeczy.';
$t[4] = 'A te spośr&oacute;d waszych żon, kt&oacute;re już zwątpiły w okres miesięczny - jeśli macie wątpliwości - niech czekają trzy miesiące; podobnie te, kt&oacute;re jeszcze się nie rozwinęły. Kobiety brzemienne zaś niech czekają, aż złożą swoje brzemię. Temu, kto się boi Boga, On przyniesie ułatwienie.';
$t[5] = 'Taki jest rozkaz Boga, kt&oacute;ry wam zesłał. A kto się boi Boga, temu On odpuści złe uczynki i powiększy jego nagrodę.';
$t[6] = 'Dajcie im mieszkanie, tam gdzie wy mieszkacie, stosownie do waszych środk&oacute;w! Nie wyrządzajcie im przykrości i nie stawiajcie ich w trudnej sytuacji! A jeśli są brzemienne, to ł&oacute;żcie na ich utrzymanie, aż złożą swoje brzemię! A jeśli one karmią wasze dziecko, dawajcie im za to wynagrodzenie i porozumiewajcie się ze sobą godnie! A jeśli napotykacie jakieś trudności, to niech karmi je inna!';
$t[7] = 'Niech ten, kt&oacute;ry żyje w dostatku, wydaje według swojego dostatku! Niech ten, kt&oacute;remu zostało wymierzone, wydaje według tego, co dał mu B&oacute;g! B&oacute;g nie obciąża żadnej duszy niczym innym, niż tym, co jej dał. B&oacute;g da wam po przeciwnościach ukojenie.';
$t[8] = 'Ileż to miast zachowało się dumnie wobec rozkazu Boga i Jego posłańc&oacute;w! I My policzyliśmy się z nimi rachunkiem surowym; ukaraliśmy je karą straszną.';
$t[9] = 'I one zakosztowały złych skutk&oacute;w swego postępowania, a w ostatecznym wyniku ponieśli stratę.';
$t[10] = 'Przygotował dla nich B&oacute;g karę straszną. B&oacute;jcie się więc Boga, o wy, obdarzeni umysłem, kt&oacute;rzy uwierzyliście! B&oacute;g zesłał wam napomnienie,';
$t[11] = 'Posłańca, kt&oacute;ry recytuje wam jasne znaki Boga, aby wyprowadzić z ciemności do światła tych, kt&oacute;rzy wierzą, kt&oacute;rzy pełnią dobre dzieła. Kto wierzy w Boga i czyni dobro, tego On wprowadzi do Ogrod&oacute;w, gdzie w dole płyną strumyki; oni będą tam przebywać nieśmiertelni na zawsze. B&oacute;g dał jemu piękny udział.';
$t[12] = 'To jest B&oacute;g, kt&oacute;ry stworzył siedem niebios i ziemi tyleż. Jego rozkaz dociera do nich, abyście wiedzieli, że B&oacute;g jest nad każdą rzeczą wszechwładny i że obejmuje każdą rzecz Swoją wiedzą.';
?>