<?php
$t = array();
$t[1] = 'Hai orang-orang yang beriman, janganlah kamu mendahului Allah dan Rasulnya dan bertakwalah kepada Allah. Sesungguhnya Allah Maha Mendengar lagi Maha Mengetahui.';
$t[2] = 'Hai orang-orang yang beriman, janganlah kamu meninggikan suaramu melebihi suara Nabi, dan janganlah kamu berkata kepadanya dengan suara yang keras, sebagaimana kerasnya suara sebagian kamu terhadap sebagian yang lain, supaya tidak hapus (pahala) amalanmu, sedangkan kamu tidak menyadari.';
$t[3] = 'Sesungguhnya orang yang merendahkan suaranya di sisi Rasulullah mereka itulah orang-orang yang telah diuji hati mereka oleh Allah untuk bertakwa. Bagi mereka ampunan dan pahala yang besar.';
$t[4] = 'Sesungguhnya orang-orang yang memanggil kamu dari luar kamar(mu) kebanyakan mereka tidak mengerti.';
$t[5] = 'Dan kalau sekiranya mereka bersabar sampai kamu keluar menemui mereka sesungguhnya itu lebih baik bagi mereka, dan Allah Maha Pengampun lagi Maha Penyayang.';
$t[6] = 'Hai orang-orang yang beriman, jika datang kepadamu orang fasik membawa suatu berita, maka periksalah dengan teliti agar kamu tidak menimpakan suatu musibah kepada suatu kaum tanpa mengetahui keadaannya yang menyebabkan kamu menyesal atas perbuatanmu itu.';
$t[7] = 'Dan ketahuilah olehmu bahwa di kalanganmu ada Rasulullah. Kalau ia menuruti kemauanmu dalam beberapa urusan benar-benarlah kamu mendapat kesusahan, tetapi Allah menjadikan kamu &quot;cinta&quot; kepada keimanan dan menjadikan keimanan itu indah di dalam hatimu serta menjadikan kamu benci kepada kekafiran, kefasikan, dan kedurhakaan. Mereka itulah orang-orang yang mengikuti jalan yang lurus,';
$t[8] = 'sebagai karunia dan nikmat dari Allah. Dan Allah Maha Mengetahui lagi Maha Bijaksana.';
$t[9] = 'Dan kalau ada dua golongan dari mereka yang beriman itu berperang hendaklah kamu damaikan antara keduanya! Tapi kalau yang satu melanggar perjanjian terhadap yang lain, hendaklah yang melanggar perjanjian itu kamu perangi sampai surut kembali pada perintah Allah. Kalau dia telah surut, damaikanlah antara keduanya menurut keadilan, dan hendaklah kamu berlaku adil; sesungguhnya Allah mencintai orang-orang yang berlaku adil.';
$t[10] = 'Orang-orang beriman itu sesungguhnya bersaudara. Sebab itu damaikanlah (perbaikilah hubungan) antara kedua saudaramu itu dan takutlah terhadap Allah, supaya kamu mendapat rahmat.';
$t[11] = 'Hai orang-orang yang beriman, janganlah sekumpulan orang laki-laki merendahkan kumpulan yang lain, boleh jadi yang ditertawakan itu lebih baik dari mereka. Dan jangan pula sekumpulan perempuan merendahkan kumpulan lainnya, boleh jadi yang direndahkan itu lebih baik. Dan janganlah suka mencela dirimu sendiri dan jangan memanggil dengan gelaran yang mengandung ejekan. Seburuk-buruk panggilan adalah (panggilan) yang buruk sesudah iman dan barangsiapa yang tidak bertobat, maka mereka itulah orang-orang yang zalim.';
$t[12] = 'Hai orang-orang yang beriman, jauhilah kebanyakan purba-sangka (kecurigaan), karena sebagian dari purba-sangka itu dosa. Dan janganlah mencari-cari keburukan orang dan janganlah menggunjingkan satu sama lain. Adakah seorang diantara kamu yang suka memakan daging saudaranya yang sudah mati? Maka tentulah kamu merasa jijik kepadanya. Dan bertakwalah kepada Allah. Sesungguhnya Allah Maha Penerima Taubat lagi Maha Penyayang.';
$t[13] = 'Hai manusia, sesungguhnya Kami menciptakan kamu dari seorang laki-laki dan seorang perempuan dan menjadikan kamu berbangsa-bangsa dan bersuku-suku supaya kamu saling kenal-mengenal. Sesungguhnya orang yang paling mulia diantara kamu disisi Allah ialah orang yang paling takwa diantara kamu. Sesungguhnya Allah Maha Mengetahui lagi Maha Mengenal.';
$t[14] = 'Orang-orang Arab Badui itu berkata: &quot;Kami telah beriman&quot;. Katakanlah: &quot;Kamu belum beriman, tapi katakanlah \'kami telah tunduk\', karena iman itu belum masuk ke dalam hatimu; dan jika kamu taat kepada Allah dan Rasul-Nya, Dia tidak akan mengurangi sedikitpun pahala amalanmu; sesungguhnya Allah Maha Pengampun lagi Maha Penyayang&quot;.';
$t[15] = 'Sesungguhnya orang-orang yang beriman itu hanyalah orang-orang yang percaya (beriman) kepada Allah dan Rasul-Nya, kemudian mereka tidak ragu-ragu dan mereka berjuang (berjihad) dengan harta dan jiwa mereka pada jalan Allah. Mereka itulah orang-orang yang benar.';
$t[16] = 'Katakanlah: &quot;Apakah kamu akan memberitahukan kepada Allah tentang agamamu, padahal Allah mengetahui apa yang di langit dan apa yang di bumi dan Allah Maha Mengetahui segala sesuatu?&quot;';
$t[17] = 'Mereka merasa telah memberi nikmat kepadamu dengan keislaman mereka. Katakanlah: &quot;Janganlah kamu merasa telah memberi nikmat kepadaku dengan keislamanmu, sebenarnya Allah, Dialah yang melimpahkan nikmat kepadamu dengan menunjuki kamu kepada keimanan jika kamu adalah orang-orang yang benar&quot;.';
$t[18] = 'Sesungguhnya Allah mengetahui apa yang ghaib di langit dan bumi. Dan Allah Maha Melihat apa yang kamu kerjakan.';
?>